### ISSUE TITLE
Feature Request (Pro Version); Membership Levels

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#15]
See: http://www.websharks-inc.com/product/quick-cache/#comment-31

Ethan Piliavin writes:

> Jason,
> 
> I guess I didnt explain myself as clearly as I could have. What I meant was something much more simple. Lets look at the plugin options screen.
> 
> In the section "Logged-In Users" you currently have 3 options:
> 
> No Yes - Separate Cache For Each User Yes - Same cache for all users
> 
> I am suggesting a 4th option:
> 
> Yes - Separate Cache for Each Role
> 
> Many s2member users use the function current_user_is(str $role) to differentiate content on pages. I dont want to cache the pages with paid content for the free users, or the other way.
> 
> I also think its quite inefficient to cache everything separately for every user as I was careful not to include usernames or anything else specific in the page output for this reason, but I was never able to do it properly with this plugin... This option would make it easy and painless.

**Comment by raamdev** [comment]
I'm reviewing this feature request again after a long time and my feeling is that relying exclusively on cookies (which is what you'd need to do, given that the caching system is loaded before WordPress, which means there's no easy way to retrieve the current users role), isn't a good idea for a core feature of the plugin. Many people run browsers with cookies disabled, so there are all kinds of scenarios that would need to be considered. So, I agree with @jaswsinc and feel we should leave such functionality out of the core ZenCache plugin. 

However, I'd be happy to create a tutorial on ZenCache.com that documents how you might implement something like this using an Advanced Cache Plugin.

@ethanpil Are you currently using any working code that implements this functionality? If so, would you mind sharing that here?

I'm going to close this issue, but like I said, I'll be happy to create a Tutorial on ZenCache.com that documents how to go about achieving this, if we can get some working examples in place.

**Comment by ethanpil** [comment]
I haven't implemented any code on this yet, have just been caching per user for now....

**Comment by ethanpil** [comment]
@raamdev
> However, I'd be happy to create a tutorial on ZenCache.com that documents how you might implement something like this using an Advanced Cache Plugin.

Are you still willing to write up this tutorial? Our site has continued to grow and I would very much appreciate a way to cache by role instead of individual users.

@jaswrks as discussed above, would we be able to have s2member trigger a cookie update if it changes a user's role?

**Comment by raamdev** [comment]
@ethanpil I just spent some time reviewing this entire GitHub issue and thinking through how I might be able to write up some documentation for it, and I even got as far as testing out a few code examples on my local test site, but I discovered that it's actually a little trickier than I first thought. 

For caching to be enabled for Logged-In Users, you must enable Logged-In User caching, which tells Comet Cache to create a separate cache for each user. If we combine that with an MU-Plugin that makes sure a `user_roles` cookie is set for logged in users, and an AC-Plugin that checks for the presence of that cookie and generates a Dynamic Version Salt based on the cookie, what we end up with is a user-specific cache of each page with a version salt on the end that represents the roles. That defeats the purpose of what we're trying to do here, which is to create a role-specific cache, not a user-specific cache. 

So, we'd need to somehow tell Comet Cache to allow caching for logged in users, but then don't maintain a separate cache for each user. That would require modifying the way Comet Cache itself works and would be outside the scope of a tutorial. That would be getting into customizing Comet Cache core files.

At this point I'm just not seeing an easy way to do this that could be described in an article or a simple code snippet.

**Comment by ethanpil** [comment]
Why not use the setting "Yes - Same cache for all users" and then apply the Dynamic Version Salt?

**Comment by raamdev** [comment]
That option was removed (hidden) in v151114, over a year ago, and is no longer available unless you were previously using it:

> - **Enhancement:** In Logged-In User Caching, the "Yes, but DON'T maintain a separate cache for each user" option has been hidden because this particular option has the potential to create a security issue if not configured properly. If you were already using this option, it will not be hidden and it will continue to work. Otherwise, if you require this particular option you can now enable it using a filter (see [this comment](https://github.com/websharks/zencache/issues/497#issuecomment-146060440)). Props @renzms @jaswsinc. See Issue #497.

I have no doubt that what you're asking can be done. It's just something that's going to take some careful planning and working through to get right and that's beyond the scope of an article. It really requires hiring a developer to make the necessary adjustments.

**Comment by ethanpil** [comment]
Just to beat a dead horse...

Today I happened to come across this plugin:  https://wordpress.org/plugins/gator-cache/ which claims 

> Posts can be cached for logged-in WordPress users by role. You can cache pages for Subscribers, Customers or other roles while skipping the cache for Administrators

Might be worth taking a look at one day...
https://plugins.trac.wordpress.org/browser/gator-cache/trunk

**Comment by raamdev** [comment]
@ethanpil Thanks for the update. I haven't dug into the Gator Cache codebase, but I was just thinking a bit more about how this would work and the problem that I foresee with caching logged-in users by role would be that if, for example, the site displays the logged-in user's name somewhere, then the first person to generate the cache would have their name cached, and subsequent users with the same role would end up seeing the cached version of the page that shows the _other_ user's name. That wouldn't be good. 

The only way to make this work properly would be for the site owner to make sure that no personally-identifiable information shows up on the front-end of the site for logged-in users, which is something that Comet Cache would have no good way of checking.

**Comment by ethanpil** [comment]
Personally, I understand the risks, and I think anyone who enables caching for logged in users faces a similar risk. We are running S2 member on a site with several thousand members and cache-per-user is no longer sustainable for us. I cannot imagine that we are the only ones that would benefit from this option. In any case we will likely need to find an alternative soon if we cant make it work here. I was hoping my favorite and easiest to use plugin would work :)

**Comment by jaswrks** [comment]
I took a look at how Gator Cache attempts this.

```php
add_action('auth_cookie_valid', 'WpGatorCache::chkUser', 5, 2);
```

On this hook, they identify the user's Role and if it's set to be cached, the cache is served.

---

The problem? This [hook](https://developer.wordpress.org/reference/hooks/auth_cookie_valid/) in [wp_validate_auth_cookie](https://developer.wordpress.org/reference/functions/wp_validate_auth_cookie/) requires that nearly all of WordPress be loaded (including plugins). It also requires that a database connection be made, and it requires that a DB query be made to check the current user. Only then is the cache served. I'm not sure I'd even call that a cache hit.

**Comment by ethanpil** [comment]
Isn't there something we can do cookie-wise with S2 Member. As special feature for S2 Member Pro (or any other membership system that wants to set/manage the cookie) to have it manage the cookie placement for users after login or role change?

**Comment by jaswrks** [comment]
Yes. There's certainly ways to implement this for site-specific needs. The only reason I'm pushing back on this at the moment, is that I'm not seeing a pathway that would allow for this to work on a large number of sites, or even a way to do it that wouldn't require several KB articles to explain how it functions — a sign of feature creep. There's also a lot of potential for security issues with this.

---

Implementing this yourself or as a separate add-on for Comet Cache is still feasible though, assuming that you accept the risks, which you're already stated that you would.

## Instructions (Requires Comet Cache Pro) [Read Warning]

_**Warning:** For the sake of posterity. Mixing cached variations for various groups of users may or may not work on your site. Be advised that there is the potential (if not implemented properly) for this to create major security issues._

- Add the following to your `wp-config.php` file.

  ```php
  define('COMET_CACHE_WHEN_LOGGED_IN', '1'); // Must be string '1'.
  ```
  _This enables a global cache for logged-in users, instead of breaking things down by each individual user, which is what normally occurs. With this enabled, you can then apply your own salt._

- Now add the following constant (but read below first please).

  ```php
  define('COMET_CACHE_VERSION_SALT', @$_COOKIE['user_role']);
  ```

- Last step is to set the cookie in any way that you choose. Users who don't have the cookie fall into a generic default group called 'everyone'. Users who do have the cookie see a cached copy of the site that is for their specific group, based on the value of the cookie.

  So in order for your salt to work, you just need to determine how and when to set the `user_role` cookie. See also: [Introduction to Dynamic Version Salts](https://cometcache.com/kb-article/introduction-to-dynamic-version-salts/)

  Values for the cookie might include:

  - `subscriber`
  - `s2member_level1`
  - `contributor`
  - `author`

  It's also fine to use a different cookie altogether.
