### ISSUE TITLE
Expiration Time

### ISSUE THREAD

**Issue by bradenmikael** [wpsharks/comet-cache#420]
I have the expiration set to 7 days (the default), and for some odd reason, the cache is clearing on it's own in about 30 minutes; or at least I think it does.  I say this because it seems to generate a new cached page instead of serving up what should be in the cache already.  My site doesn't get updated all that often.   Other than this issue, QuickCache works pretty well.  What am I missing here?

**Comment by raamdev** [comment]
@bradenmikael How are you determining that it's clearing in about 30 minutes?

**Comment by bradenmikael** [comment]
Shouldn't that be set in the expiration time?

**Comment by bradenmikael** [comment]
I've given up, switched back to WP-SuperCache and it's working better.

**Comment by raamdev** [comment]
@bradenmikael I never heard back from you about how you're determining that the cache is clearing in 30 minutes and not 7 days as specified in your options. We have thoroughly tested this part of Quick Cache and it works as expected. We also have thousands of happy users running the plugin and have heard no other reports of such an issue.

I'm closing this issue, but if you have something additional to add here, I'd be happy to help.
