### ISSUE TITLE
Installing, activating, deactivating, and deleting a plugin does not wipe/clear the cache

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#424]
As of Quick Cache v150129, installing, activating, deactivating, and deleting a plugin _does not_ wipe/clear the cache. This is unexpected behavior; I would expect it to clear the cache upon any of those events, since plugins often make front-end changes.

As of v150129, we have auto-clear handlers for active plugin upgrades, but not for installing, activating, deactivating, deleting plugins.

Related to #308.

**Comment by raamdev** [comment]
Need to test if this issue is still applicable with the latest version of ZenCache Lite and ZenCache Pro.

**Comment by jaswrks** [comment]
Referencing:
- [`activated_plugin`](https://github.com/WordPress/WordPress/blob/77e365efbf2e499e2ed11d29c101ea466cf1ceed/wp-admin/includes/plugin.php#L599)
- [`deactivated_plugin`](https://github.com/WordPress/WordPress/blob/77e365efbf2e499e2ed11d29c101ea466cf1ceed/wp-admin/includes/plugin.php#L701)

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch in the `websharks/zencache-pro` repo.
- After [this line](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/classes/Plugin.php#L455) add the following:
  
  ``` php
  add_action('activated_plugin', array($this, 'autoClearOnPluginActivationDeactivation'));
  add_action('deactivated_plugin', array($this, 'autoClearOnPluginActivationDeactivation'));
  ```
- Create a new file in [this directory](https://github.com/websharks/zencache-pro/tree/151105-RC/src/includes/closures/Plugin) with the name: `WcpPluginUtils.php`
  
  ``` php
  <?php
  namespace WebSharks\ZenCache\Pro;
  
  /*
  * Automatically wipes/clears on plugin activation/deactivation.
  *
  * @since 15xxxx Adding auto-wipe|clear on plugin activations/deactivations.
  *
  * @attaches-to `activated_plugin` hook.
  * @attaches-to `deactivated_plugin` hook.
  *
  * @param string $plugin Plugin basename.
  * @param bool True if activating|deactivating network-wide.
  *
  * @return int Total files wiped|cleared by this routine (if any).
  */
  $self->autoClearOnPluginActivationDeactivation = function ($plugin, $network_wide) use ($self) {
      return $self->{($network_wide ? 'autoWipeCache' : 'autoClearCache')}();
  };
  ```
- Submit PR.

**Comment by jaswrks** [comment]
Assigning this to @renzms :-)

**Comment by renzms** [comment]
@jaswsinc PR submitted! :+1:

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: ZenCache now clears the cache whenever a WordPress plugin is activated or deactivated. Many WordPress plugins change content on the front-end of the site, so this enhancement ensures that an old cache file is never served to visitors. If you want to disable this automatic behavior, see [this article](http://zencache.com/kb-article/how-do-i-prevent-zencache-from-clearing-the-cache-upon-plugin-activation-or-deactivation/). Props @renzms. See [Issue #424](https://github.com/websharks/zencache/issues/424).

**Comment by raamdev** [comment]
**ZenCache Pro v151220** has been released and includes changes worked on as part of this GitHub Issue. See the [release announcement](http://zencache.com/zencache-pro-v151220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#424).
