### ISSUE TITLE
Call to undefined method quick_cache\\version_specific_upgrade::from_lt_v150129_1()

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#425]
It appears that Quick Cache and Quick Cache Pro v150129-1 includes a call to a nonexistent function after a last-minute change. It's just a minor oversight, but it is causing a fatal error when some users upgrade to the latest/final release of Quick Cache. See: https://github.com/websharks/quick-cache/commit/e18b060f05bc547438e2112eb6b22ce10400fc97

See also: https://github.com/websharks/quick-cache/blob/e18b060f05bc547438e2112eb6b22ce10400fc97/quick-cache/includes/version-specific-upgrade.php#L52

**Comment by jaswrks** [comment]
Referencing: https://websharks.zendesk.com/agent/tickets/5352

**Comment by jaswrks** [comment]
This was resolved in the release of v150129.2
https://wordpress.org/plugins/quick-cache/changelog/

**Comment by tlongren** [comment]
Happy to have helped @jaswsinc!

**Comment by jaswrks** [comment]
@tlongren Thanks for report! Saved a lot of users upgrading from that version. I would have given you props, but it was a rush to push it out and I forgot :-)

**Comment by tlongren** [comment]
No props needed. Just happy to help.
