### ISSUE TITLE
Static CDN Filters + HTML Compressor

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#429]
At present, the Static CDN Filters deal with URL filters and we also filter `the_content`. There is no integration with the HTML Compressor in ZenCache. For this reason, cache files generated by the HTML Compressor are left as `http://localdomain.com/wp-content/cache/zencache/htmlc/...`. These can (and it seems they should) be served from the CDN also—to increase speed even further.

Next steps:
- [x] Detect Static CDN Filters being enabled [here](https://github.com/websharks/zencache-pro/blob/000000-dev/zencache-pro/includes/advanced-cache.tpl.php#L1393).
- [x] Alter the public cache URL for the HTML Compressor so it uses the CDN host name instead. See: [this line of code in ZenCache Pro](https://github.com/websharks/zencache-pro/blob/000000-dev/zencache-pro/includes/advanced-cache.tpl.php#L1393)

**Comment by raamdev** [comment]
Next release changelog:
- **Enhancement** (Pro): Static CDN Filters now apply to minified and compressed CSS/JS files generated by the HTML Compressor; these files will now be cached by your CDN. [Issue #429](https://github.com/websharks/zencache/issues/429)

**Comment by raamdev** [comment]
This enhancement has been released with ZenCache v150409:
http://zencache.com/zencache-v150409-now-available/

If you need to follow-up with something related to this GitHub Issue, please open a new GitHub Issue.
