### ISSUE TITLE
Static CDN Filters + Text Widgets

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#430]
At present, the Static CDN Filters deal with URL filters and we also filter `the_content`. However, there is no integration with Text Widgets in ZenCache. Any static media in Text Widgets can (and it seems they should) be served from the CDN also—to increase speed even further.

Referencing this internal ticket: https://websharks.zendesk.com/agent/tickets/5421
## Next Steps
- [x] Add a new filter [here in this private repo file](https://github.com/websharks/zencache-pro/blob/000000-dev/zencache-pro/includes/cdn-filters.php#L222) that deals with `widget_text` in WordPress.

**Comment by raamdev** [comment]
Next release changelog:
- **Enhancement** (Pro): Static CDN Filters now also filter any static resources inside Text Widgets, so that those resources can be cached by your CDN. [Issue #430](https://github.com/websharks/zencache/issues/430)

**Comment by raamdev** [comment]
This enhancement has been released with ZenCache v150409:
http://zencache.com/zencache-v150409-now-available/

If you need to follow-up with something related to this GitHub Issue, please open a new GitHub Issue.
