### ISSUE TITLE
CDN Fatal error when blacklisting extensions.

### ISSUE THREAD

**Issue by skipthedrive** [wpsharks/comet-cache#431]
Hello -
I was trying to add blacklist file extensions into the CDN area because I realized that part of my javascript was not rendering correctly when the CDN was enabled. I added JS to the blacklist area, and received the following fatal error:

**PHP Fatal error:  Call to protected method zencache\cdn_filters::filter_url() from context '' in /home/content/22/10327722/html/wp-content/plugins/zencache-pro/includes/cdn-filters.php on line 284**

**Comment by jaswrks** [comment]
@skipthedrive Thanks for the report! :-) Please see: https://github.com/websharks/quick-cache/issues/426 where work on this is underway.

**Comment by skipthedrive** [comment]
@jaswsinc - Thanks for the update :)
Pete

**Comment by raamdev** [comment]
@skipthedrive Thank you for the report. I'm closing this issue in favor of #426. Please click the "Subscribe" button on that GitHub Issue if you'd like to receive updates when it is updated. :-)
