### ISSUE TITLE
Deleting QCP post-migration to ZCP disables caching

### ISSUE THREAD

**Issue by MarioKnight** [wpsharks/comet-cache#432]
(While unrelated, the links to a Zen Cache issue tracker all 404. I was able to find this one for QuickCache and will use here to report the issue.)

This week, I have migrated sites on my personal license and my employer's license to Zen Cache Pro.  Sparing all the details on how I was able to figure this out through this week, I learned that deleting the QuickCache Pro plugin disables caching.  What appears to happen that I have been able to reproduce multiple times now is as follows:
- Upload and activate Zen Cache Pro as per the instructions in the KB.
- Verify options carried over, and that site is caching with Zen Cache Pro.
- Delete now unused QuickCache Pro

It is at this point where even though the list of files being reported that will be deleted only contains files within the quick-cache-pro plugin folder, what also happens to which there is no warning is that the advanded-cache.php file in wp-content is written to be 0 bytes, effectively disabling everything Zen Cache Pro does.  Simply going back to the plugin options and clicking "Save All Changes" will recreate this file, and then all is well.

I don't expect that this can be "fixed" in any sense, however I did want to make sure that y'all were aware of this, and suggest that you consider posting this on the migration KB pages and maybe elsewhere for people to double-check their sites and ensure it is working.

Thank you for doing such great work with this plugin!  I've loved it since learning about it this past summer, and was able to convince my employer to get a license as well for all of the sites we manage.  I look forward to what the future has in store for it.

**Comment by raamdev** [comment]
@MarioKnight Thank you VERY much for reporting this important issue! I have just verified this "bug" and we'll start working on a fix for this.

> (While unrelated, the links to a Zen Cache issue tracker all 404. I was able to find this one for QuickCache and will use here to report the issue.)

Ah, yes, that should be fixed today as we finish up the migration from Quick Cache to ZenCache here on GitHub as well (this Quick Cache repo is being renamed to ZenCache).

**Comment by MarioKnight** [comment]
You're very welcome!  It's certainly been a headache through the week, and you can't imagine the relief I felt when I was finally able to confirm the exact metrics causing it a little earlier.  I am happy that this could be of help.

**Comment by raamdev** [comment]
Next release changelog: 
- **Bug Fix**: Fixed a zero-byte `advanced-cache.php` bug related to migrating from Quick Cache. When you deleted/uninstalled Quick Cache after upgrading to ZenCache, the Quick Cache uninstallation process would empty the `advanced-cache.php` file, resulting in the site no longer being cached, despite ZenCache being active. ZenCache now continuously checks to make sure that `advanced-cache.php` is installed properly. See [#432](https://github.com/websharks/zencache/issues/432).
