### ISSUE TITLE
Feature Request: Static CDN Filters for Sub-Domain Multisite Networks

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#439]
At present, to use the Static CDN Filters, a Multisite Network must be using sub-directories (e.g., `example.com/site1/`). ZenCache Pro running in a Multisite Network environment using sub-domains (e.g., `site1.example.com`) is currently NOT supported by the Static CDN Filters feature (see [source code notes](https://github.com/websharks/zencache-pro/blob/000000-dev/zencache-pro/includes/cdn-filters.php#L195)). It would be great to add support for sub-domains, if possible.

**Comment by isaumya** [comment]
You guys have to make sure that you add this feature, as this is a very basic feature which is even provided by the free plugins like WP Super Cache, W3TC etc. When people install WP MU mostly they use sub-domain based as this makes more sense than subdirectory based.
So, if zencache pro cannot provide this basic feature, the first question people will ask if a free plugin can do it why can't a paid one ? lol. This is basic user's mentality.
But you guys must need to take this request seriously and to act upon it so that it can be added into the next release or so.

**Comment by raamdev** [comment]
@isaumya Thanks for your feedback. Static CDN Filters are a recent addition to ZenCache (we added that feature when we changed the Quick Cache plugin to ZenCache), so we're working to improve this feature. Adding sub-domain support is high on the list of improvements to ZenCache Pro.

**Comment by isaumya** [comment]
So when is this feature coming up? I hope the latest release does not contain this update.

**Comment by raamdev** [comment]
@isaumya No, the latest release does not contain this feature. We'll be considering it once we begin triaiging issues for the next development cycle, which will happen once the next release has been published (currently in beta, see [v150403 Release Candidate](http://zencache.com/zencache-v150403-release-candidate/)).

**Comment by isaumya** [comment]
@raamdev I understand. This is something, I've been waiting for to do a through testing of Zencache Pro on a MU environment. :) Any eta on this? I mean like the end of this month, or the start of next month, something like this.

**Comment by raamdev** [comment]
> Any eta on this? I mean like the end of this month, or the start of next month, something like this.

@isaumya We don't currently have an ETA. We try to avoid giving ETA's for things that we don't actually have an ETA for, to prevent unreasonable expectations. :-) We always prioritize fixing bugs before adding new features. We decide which features and bugs we're going to work on at the start of each new development cycle. We're currently at the end of a development cycle, so after we do the next public release (within the next day or so), we'll triage the issues and figure out what we're going to put our focus on.

**Comment by isaumya** [comment]
Glad to know., Please let me know your decision on this after this upcoming release. This is a seriously needed feature for wp multisite ;-) and frankly after start testing this plugin I'm so happy with its code quality that I really don't want anyone to complain about your plugin just for this simple minor feature. Looking forward to it :)

**Comment by isaumya** [comment]
Hi @raamdev Static CDN Filters on subdomain based multi site networks, not only work in subdomains, `i.e site1.example.com` but also not work for the primary site `i.e. www.example.com`. In short Static CDN filter does not work in Subdomain based multisite networks at all. Whether HTML Compressor is activated or not, that doesn't matter. I've been reviewing the cdn feature for a week now and after thorough testing I see that the CDN it self dont on subdomain based wp mu. Here are some proof.

## Static CDN Config

![Static CDN Filter Config](https://cloud.githubusercontent.com/assets/2124755/7157763/618ab11c-e390-11e4-9237-0654b5d56727.jpg)

## Frontend Source Code

![Frontend Source Code - HTML Compressor DISABLED](https://cloud.githubusercontent.com/assets/2124755/7157804/c213f61a-e390-11e4-94e6-31a10b3c55ce.jpg)
*\* Frontend Source Code - HTML Compressor DISABLED **

![Frontend Source Code - HTML Compressor ENABLED](https://cloud.githubusercontent.com/assets/2124755/7157830/24d8c5c8-e391-11e4-8ff0-fd073655f8d6.jpg)
*\* Frontend Source Code - HTML Compressor ENABLED **

Hope these above insights will help you to address the problem properly.

**Comment by isaumya** [comment]
@raamdev please let me know if you are going to fix this issue in the next upcoming update of zencahe pro, otherwise I have to remove it from my production live site and have to wait for this issue to be fixed as you did not provided any eta on this yet.

**Comment by raamdev** [comment]
@isaumya Thank you for reporting that bug. This has been fixed in the latest development branch and the fix will go out with the next release.

**Comment by isaumya** [comment]
Anyways guys when you are actually going to support subdomain based multi site officially. Almost all webmasters I know who are using WP MU, uses the subdomain based architecture, but the sub-directory based.

**Comment by isaumya** [comment]
So, in the upcoming updates Zencache is going to support subdomain properly? Like cache + cdn? If it is a yes, then its an amazing news.

**Comment by lkraav** [comment]
Aha, so this is why ZCP isn't doing any CDN rewriting on the subsite domain. Looking forward to the next release.

**Comment by raamdev** [comment]
@isaumya @lkraav This feature has been added and ZenCache Pro Static CDN Filters now support sub-domains in WordPress Multisite Network. This feature will go out with the next release.

**Comment by raamdev** [comment]
Next release changelog:
- **Enhancement** (Pro): Static CDN Filters now support sub-domains when ZenCache is running inside a WordPress Multisite Network. Props @jaswsinc. See [Issue #439](https://github.com/websharks/zencache/issues/439).

**Comment by isaumya** [comment]
Hi @raamdev I'm quite glad to see this feature at last. Can't wait to test it :)

**Comment by raamdev** [comment]
[ZenCache v150605 (Release Candidate)](http://zencache.com/zencache-v150605-release-candidate/) is now available. This release candidate includes the enhanced Static CDN Filters that now work with sub-domains in a WordPress Multisite Network.

If you'd like to help with testing this release candidate of ZenCache before the public version is released, please see the link above. If you want to be notified of future release candidate announcements, please sign-up [here](http://zencache.com/r/zencache-beta-testers-list/).
