### ISSUE TITLE
Use cURL as a fallback for the Auto-Cache Engine when allow_fopen_url is disabled

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#440]
Some web hosts disable `allow_url_fopen` in the PHP configuration on the server, which means the ZenCache Auto-Cache Engine will be unable to access the URL to the XML Sitemap (which it uses to figure out which pages it on the site it should generate a cache file for).

As a result, you may see an error like the following in your error log whenever the Auto-Cache Engine runs:

```
[Wed Mar 04 23:09:25 2015] [warn] [client 185.114.224.0] mod_fcgid: stderr: PHP Warning: XMLReader::open(http://example.com//sitemap_index.xml) [<a href='xmlreader.open'>xmlreader.open</a>]: failed to open stream: no suitable wrapper could be found in /home/example/www/wp-content/plugins/zencache-pro/includes/auto-cache.php on line 233
```

It should be possible to fetch a URL using cURL (which is more reliable than requiring `allow_fopen_url`, which _many_ web hosts disable for security reasons) and then load the result into `XMLReader()`. 

@jaswsinc writes...

> The XMLReader class reads the input XML from a stream, one node at a time. Making it possible for ZC to deal with extremely large (even multi-GB sitemaps). However, I don't see any reason why we couldn't have it open a stream from a local resource that we download via cURL. I'm not certain that will work, but definitely worth taking a look at, I agree.
> 
> Referencing: http://php.net/manual/en/xmlreader.open.php
> See also: http://php.net/manual/en/xmlreader.read.php

**Comment by raamdev** [comment]
Referencing https://github.com/websharks/zencache/issues/644

**Comment by Ed-AITpro** [comment]
allow_url_fopen is unfortunately is a common attack vector used by hackers so it should be disabled/turned off in a php.ini file for security reasons.  I just purchased the Pro unlimited version and will unfortunately have to request a refund for now since I am not willing to open up this attack vector and allow allow_url_fopen on any of my websites.  I will repurchase Comet Cache Pro again at a later time if you do provide a cURL or other safe method alternative to using allow_url_fopen.  I'm bummed out about this, but security takes priority so that leaves me no choice here. I will continue to use your free Comet Cache version since it is awesome, but so wanted the Pro version. bummer.

**Comment by raamdev** [comment]
The work on this issue includes a new filter that allows you to force the use of the fallback when fetching the XML Sitemap. The fallback uses the WP HTTP API to download the XML Sitemap and then parses it from the local file. The WP HTTP API includes a fallback to cURL, so if `allow_fopen_url` is disabled, it will use cURL instead. 

If `allow_fopen_url` is enabled and you want to force the use of the fallback anyway, you can create an [MU-Plugin](http://codex.wordpress.org/Must_Use_Plugins) and add the following override:

``` php
add_filter('comet_cache_auto_cache_sitemap_force_wp_http_api', function() { return true; });
```

**Comment by raamdev** [comment]
Next Release Changelog:
- **Enhancement** (Pro): The Auto-Cache Engine now supports a fallback to cURL using the WP HTTP API. If your PHP configuration has `allow_fopen_url=0`, the Auto-Cache Engine will use the fallback to download the XML Sitemap and parse it from a temporary file. If you want to force the use of this fallback even when `allow_fopen_url=1`, you can use [a filter](https://github.com/websharks/comet-cache/issues/440#issuecomment-228338371). See [Issue #440](https://github.com/websharks/comet-cache/issues/440).

**Comment by Ed-AITpro** [comment]
Awesome!  Very impressed with how quickly you created the additional options/features to get the cURL alternative caching method implemented. Woo Hoo!!!

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#440).
