### ISSUE TITLE
`flock()` Requires PHP v5.3.2+

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#444]
Referencing: http://php.net/manual/en/function.flock.php

> 5.3.2 The automatic unlocking when the file's resource handle is closed was removed. Unlocking now always has to be done manually.

What needs to happen?
- [x] Update our integration with `wp-php-rv` to require PHP v5.3.2+ instead of PHP v5.3+.

**Comment by raamdev** [comment]
Thanks @jaswsinc. I'm labeling this a bug, because we currently advertise ZenCache as requiring only PHP 5.3+ and <=5.3.2 could result in buggy behavior.

**Comment by raamdev** [comment]
Next release changelog:
- **Minimum Required PHP Version Bumped to PHP v5.3.2+:** The minimum PHP version required for ZenCache has been bumped up to PHP v5.3.2+ (from PHP v5.3+). The ZenCache cache locking mechanism, specifically the use of `flock()`, requires behavior introduced in PHP v5.3.2. [Issue #444](https://github.com/websharks/zencache/issues/444).

**Comment by raamdev** [comment]
This fix has been released with ZenCache v150409:
http://zencache.com/zencache-v150409-now-available/

If you need to follow-up with something related to this GitHub Issue, please open a new GitHub Issue and provide a link back to this Issue.
