### ISSUE TITLE
HTML Compression breaks the "Responsive WordPress Slider -- Soliloquy Lite" plugin in Chrome

### ISSUE THREAD

**Issue by KTS915** [wpsharks/comet-cache#445]
The option, "Yes, combine JS footer scripts into fewer files," causes the Responsive WordPress Slider -- Soliloquy Lite to fail to load when using Chrome.

Steps to reproduce:
1. Install Responsive WordPress Slider -- Soliloquy Lite from wordpress.org and upload an image to be used in a slider. Save the slider.
2. Use the Template Tag option to add the slider to the Theme's header.php file.
3. Attempt to access a page that calls the header with that slider.
4. In Chrome, the slider appears to try to load, but is then replaced by the standard "loading" GIF image.
5. In Firefox, this works as expected.

**Comment by jaswrks** [comment]
Thank you for the detailed report! :-)

**Comment by raamdev** [comment]
@KTS915 Thank you for the detailed report. I've updated the title of this issue and labeled it as something that needs testing. I'll come back here and update this issue once I get a chance to test this further. 

In the meantime, you might want to figure out what JavaScript files the plugin uses (you should be able to find this by doing "View Source" on the page and then looking for references to the plugin inside `wp-content/plugins/`) and exclude those JavaScript files from HTML Compression in `ZenCache → Plugin Options → HTML Compression → JavaScript Exclusion Patterns?`.

**Comment by KTS915** [comment]
Thanks for the tip, @raamdev. It works a treat!

In case it helps you to debug, the offending js file seems to be `~/wp-content/plugins/soliloquy-lite/assets/js/soliloquy.js?ver=2.2.4`.

**Comment by KTS915** [comment]
With the latest versions of both these plugins, this issue appears resolved, so am closing.

**Comment by raamdev** [comment]
@KTS915 Great! Thanks so much for following up. :smile:
