### ISSUE TITLE
Problem with combining CSS from <head> and <body> into fewer files

### ISSUE THREAD

**Issue by skipthedrive** [wpsharks/comet-cache#446]
Hello -
My styling pretty much went away when I had this option enabled. I'm able to have all of the other HTML compression options enabled except for this one. If you want to take a look at my home page, it's http://www.skipthedrive.com. As of now, I'm keeping this option disabled.
Thanks,
Pete

**Comment by raamdev** [comment]
@skipthedrive Thanks for the heads up, Pete!

@jaswsinc Any chance you might take a look at this?

**Comment by jaswrks** [comment]
Yes, will do. Thanks. I'm making a note of this here: https://github.com/websharks/html-compressor/issues/53

**Comment by skipthedrive** [comment]
No problem @raamdev ! I also noticed a PHP warning and exception, but am not sure if it's related to this issue or not. Here it is:

 [16-Mar-2015 22:55:01 UTC] PHP Warning:  file_put_contents(/.../wp-content/cache/zencache/htmlc/public/www-skipthedrive-com/f/3/0/a/c/b5f3acbd767fdca3e9fd606fa8d5c311-compressor-part.js.55075f45b576c4.83502659.tmp): failed to open stream: No such file or directory in /.../wp-content/plugins/zencache-pro/submodules/html-compressor/html-compressor/includes/core.php on line 1255
[16-Mar-2015 22:55:01 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to cache JS code file: `/.../wp-content/cache/zencache/htmlc/public/www-skipthedrive-com/f/3/0/a/c/b5f3acbd767fdca3e9fd606fa8d5c311-compressor-part.js`.' in /.../wp-content/plugins/zencache-pro/submodules/html-compressor/html-compressor/includes/core.php:1256
Stack trace:
#0 /.../wp-content/plugins/zencache-pro/submodules/html-compressor/html-compressor/includes/core.php(1063): websharks\html_compressor\core->compile_js_tag_frags_into_parts(Array)
#1 /.../wp-content/plugins/zencache-pro/submodules/html-compressor/html-compressor/includes/core.php(318): websharks\html_compressor\core->maybe_compress_combine_head_js('<!doctype html>...')
#2 /.../wp-content/advanced-cache.php(1406): websharks\html_compressor\core->compress('<!doctype html>...')
#3 /.../wp-content/advanced-cache.php(1320): zencache\advanced_c in /.../wp-content/plugins/zencache-pro/submodules/html-compressor/html-compressor/includes/core.php on line 1256

**Comment by jaswrks** [comment]
@skipthedrive writes...

> I also noticed a PHP warning and exception, but am not sure if it's related to this issue or not.

Thank you very much for those additional details :-)

**Comment by skipthedrive** [comment]
Sure thing!

**Comment by renzms** [comment]
@raamdev 

### Unable to reproduce issue

WordPress Version: 4.7
Current WordPress Theme: Illdy version 1.0.35.2
Theme Author: Colorlib - http://colorlib.com
Theme URI: http://colorlib.com/wp/themes/illdy/
Active Plugins: Comet Cache Pro v161227
PHP Version: 7.0.10-2+deb.sury.org~xenial+1
MySQL Version: 10.0.28-MariaDB-0ubuntu0.16.04.1

**HTML Compressor enabled** 

![screen shot 2016-12-30 at 12 01 02 am](https://cloud.githubusercontent.com/assets/13220018/21547769/1d800484-ce23-11e6-84ab-ecc74a560baf.png)

**Front end with Theme + Stylings**

![screen 12-29_23-45-21](https://cloud.githubusercontent.com/assets/13220018/21547842/83cb85c4-ce23-11e6-8382-adf11daf0653.png)

**Comment by skipthedrive** [comment]
Yep, seems to be working fine now. Thanks!

**Comment by raamdev** [comment]
@renzms @skipthedrive Thanks for the confirmation! :-) I'll go ahead and close this.
