### ISSUE TITLE
Uninstalling Quick Cache after migrating to ZenCache results in missing `define('WP_CACHE', TRUE)`

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#450]
In [v150314](https://github.com/websharks/zencache/releases/tag/150314) we fixed a zero-byte `advanced-cache.php` bug related to uninstalling Quick Cache after migrating over to ZenCache (see https://github.com/websharks/zencache/issues/432). However, it seems that uninstalling Quick Cache is also removing the `define('WP_CACHE', TRUE);` from the `wp-config.php` file. 

So, even though ZenCache is now ensuring that `advanced-cache.php` is populated and correct, the cache is not being used because `define('WP_CACHE', TRUE);` is missing from `wp-config.php`.

It looks like we just need to add a call to [`add_wp_cache_to_wp_config()`](https://github.com/websharks/zencache/blob/000000-dev/zencache/zencache.inc.php#L1948) inside `check_advanced_cache()` [right here](https://github.com/websharks/zencache/blob/000000-dev/zencache/zencache.inc.php#L2061), so that whenever the `advanced-cache.php` file is missing or empty we also check to make sure `define('WP_CACHE', TRUE);` is set in the `wp-config.php` file.

@jaswsinc Does that sound right to you?

**Comment by jaswrks** [comment]
@raamdev writes...

> Does that sound right to you?

Good catch! Sounds good to me.

**Comment by raamdev** [comment]
Next release changelog:
- **Bug Fix**: Fixed a bug related to the Quick Cache migration that resulted in caching being disabled despite ZenCache being enabled. Uninstalling Quick Cache was removing `define('WP_CACHE', TRUE);` from the `wp-config.php` file. ZenCache now makes sure that caching remains enabled after uninstalling Quick Cache during the ZenCache migration process. [Issue #450](https://github.com/websharks/zencache/issues/450).

**Comment by raamdev** [comment]
This fix has been released with ZenCache v150409:
http://zencache.com/zencache-v150409-now-available/

If you need to follow-up with something related to this GitHub Issue, please open a new GitHub Issue.
