### ISSUE TITLE
Fatal error: require_once()

### ISSUE THREAD

**Issue by marieneig** [wpsharks/comet-cache#452]
Running multisite, 4.1, site is currently not accessible

����������������������� all the way

even after I deleted the zencache folder and the advanced-cache.php file I get this error:

Warning: require_once(/home/nameyourd/public_html/wp-content/plugins/zencache/includes/share.php): failed to open stream: No such file or directory in /home/nameyourd/public_html/wp-content/advanced-cache.php on line 140

Fatal error: require_once(): Failed opening required '/home/nameyourd/public_html/wp-content/plugins/zencache/includes/share.php' (include_path='.:/opt/alt/php54/usr/share/pear:/opt/alt/php54/usr/share/php') in /home/nameyourd/public_html/wp-content/advanced-cache.php on line 140

Delete this file: /wp-content/advanced-cache.php = done
Delete this directory: /wp-content/plugins/zencache/ = done
Remove this line from your /wp-config.php file: define('WP_CACHE', TRUE); = there wasn't any but I put define('WP_CACHE', FALSE);
removed gzip compression lines form htaccess. I don't know what to remove anymore

there must be cache files somewhere, where can I flush them?

and if I reput your folder I get again the 1 error:
����������������������� all the way

**Comment by raamdev** [comment]
@marieneig This does not look like a ZenCache Error to me:

> ����������������������� all the way

I've never seen that before.

If you delete the ZenCache plugin folder from `wp-content/plugins/` and then delete `wp-content/advanced-cache.php` and also remove the line that says `define('WP_CACHE', TRUE);` from your `wp-config.php` file, that will _completely uninstall ZenCache_.

After following those steps, there's no way for ZenCache to continue affecting your site, even if there were cache files still hanging around (they would be in the `wp-content/cache/` directory, which you can also safely delete).

If you're still seeing errors like these after uninstalling ZenCache, then I suggest contacting your web hosting company and working with them to resolve this issue.
