### ISSUE TITLE
SVG Icon Color; Flash of Black

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#453]
A fork of https://github.com/websharks/wp-kb-articles/issues/95; this issue exists in ZenCache also.

**Comment by raamdev** [comment]
Closed by #454.

**Comment by raamdev** [comment]
Next release changelog:
- **Bug Fix**: Fixed a minor UI issue where the ZenCache Dashboard icon would occasionally flash to a black color when refreshing the Dashboard. [Issue #453](https://github.com/websharks/zencache/issues/453).

**Comment by raamdev** [comment]
This fix has been released with ZenCache v150409:
http://zencache.com/zencache-v150409-now-available/

If you need to follow-up with something related to this GitHub Issue, please open a new GitHub Issue.
