### ISSUE TITLE
Warning: is_dir() [function.is-dir]: open_basedir restriction in effect?

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#456]
Referencing: https://github.com/websharks/zencache/blob/000000-dev/zencache/includes/share.php#L1445

Whenever ZenCache is running on an installation of PHP with `open_basedir` restrictions applied, a call to `is_dir()` triggers a PHP Warning whenever ZenCache is looking for a writable temporary directory.
## Next Actions
- [x] Use `@` error suppression in [these calls to `is_dir()` and `is_writable()`](https://github.com/websharks/zencache/blob/000000-dev/zencache/includes/share.php#L1445)

**Comment by jaswrks** [comment]
Referencing this private bug report.
https://websharks.zendesk.com/agent/tickets/5721

**Comment by raamdev** [comment]
@jaswsinc Thanks for the bug report! Working on this now.

**Comment by raamdev** [comment]
@jaswsinc Wouldn't the `@` suppression need to be added to _all_ calls to `is_dir()` and `is_writeable()` throughout the codebase to fix this bug?

**Comment by raamdev** [comment]
@jaswsinc Ah, I see this is related specifically to opening the temp directory:

> File(/var/tmp/) is not within the allowed path(s)

So in that case, only modifying the lines you referenced above should be necessary.

**Comment by raamdev** [comment]
Next release changelog: 
- **Bug Fix**: When ZenCache was running on an installation of PHP with `open_basedir` restrictions applied, calls to `is_dir()` were triggering a PHP Warning while looking for a writable temporary directory. This bug has been fixed. [Issue #456](https://github.com/websharks/zencache/issues/456).

**Comment by raamdev** [comment]
This fix has been released with ZenCache v150409:
http://zencache.com/zencache-v150409-now-available/

If you need to follow-up with something related to this GitHub Issue, please open a new GitHub Issue.
