### ISSUE TITLE
Feature Request: Serve images referenced in CSS via Static CDN Filters

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#461]
The Static CDN Filters do not currently (as of v150314) filter images referenced in CSS to have those images served via the configured CDN. It would be good if there was an option to do this.

@jaswsinc writes...

> The HTML Compressor does rewrite these, in order to resolve relative paths that would break once CSS files are combined. We recently added support for Static CDN Filters in the HTML Compressor, so taking that a step further and applying it to CSS resources would not be _that_ difficult.

Since the HTML Compressor already rewrites these paths during compression, we can simply add an option to the Static CDN Filters called "Rewrite Static Resource URLs in CSS Files?" (`cdn_rewrite_css_urls`) that would then be passed to the HTML Compressor, along with `cdn_host`, to be used for determining whether or not paths inside CSS files should be replaced with the CDN host URL. 

If `cdn_rewrite_css_urls` is enabled, then during the processing of CSS compression, all paths would be replaced with paths to the CDN.

---
## Next Actions
- [ ] Update to the latest version of HTML Compressor (one that includes changes from https://github.com/websharks/html-compressor/issues/58).

**Comment by isaumya** [comment]
It's great that you have added my request as a feature request. Looking forward to see the improvements. :)

**Comment by raamdev** [comment]
@jaswsinc Can you confirm that https://github.com/websharks/html-compressor/issues/58 closes this issue (that is once ZenCache has been updated to the latest version of HTML Compressor)?

**Comment by jaswrks** [comment]
Correctamundo :-) :+1:

**Comment by raamdev** [comment]
Next release changelog:
- **Enhancement**: Static CDN Filters now also apply to any static files that are referenced inside CSS files. Props @jaswsinc. See [Issue #461](https://github.com/websharks/zencache/issues/461).
