### ISSUE TITLE
CDN issue with HTML Compressor

### ISSUE THREAD

**Issue by isaumya** [wpsharks/comet-cache#462]
I've start testing the Zencache Pro and find a wired issue with CDN and HTML Compressor. When both cdn and html compressor is enabled, the html compressor seems working fine, but all static file is using the site url not the cdn url.

**Testing Infrastructure:**
The testing has been done over a nginx server with single installation of wordpress (not multisite).

**Process to replicate the issue:**
1. Enable zencache pro (zencache light or quick cache was never installed on this site before)
2. Enable HTML compressor with all the default settings
3. Enable static cdn (used maxcdn)
4. Set yes to server static resource over https using cdn (as my testing site was on ssl)
5. Save and check the site on incognito window. Check the source code of the site.

Please let me know if you need any more informations about this issue.

**Comment by raamdev** [comment]
@isaumya This feature is coming in the next release of ZenCache (currently in beta):
- **Enhancement** (Pro): Static CDN Filters now apply to minified and compressed CSS/JS files generated by the HTML Compressor; these files will now be cached by your CDN. Props @jaswsinc. [Issue #429](https://github.com/websharks/zencache/issues/429)

You can see the full changelog for the next release [here](http://zencache.com/zencache-v150403-release-candidate/). The next release has been in the beta phase since April 4th and we'll be doing a public release within the next day or so.

**Comment by isaumya** [comment]
Thank you for conforming. I'm really sorry for the duplicate I didn't see that before posting.

**Comment by isaumya** [comment]
Hi @raamdev I got your email and start testing zencache pro on my own website. It seems this issue is still retain there. You can check the source code of my site. Its not taking the cdn url. It would be great if you take a deep look into it.

**Comment by raamdev** [comment]
@isaumya I'm not seeing any problem. I'm running the latest version of ZenCache Pro (v150409) on my personal site, http://raam.org, along with Static CDN Filters and the HTML Compression and you can see in the screenshot below (or by looking at the source when you visit my site) that HTML Compressor minified/compressed files are being served by the CDN:

![2015-04-10_09-28-20](https://cloud.githubusercontent.com/assets/53005/7088712/1df5cba6-df64-11e4-83d0-09a82659ca91.png)

**Comment by isaumya** [comment]
Yes. I think this is some issue with WP Multisite. I've seen few more wired thing. You see if you visit my other site (i.e. photography.isaumya.com) and see the source code, you will see that Zencache don't even running there in that subsite. But I've network activated it. Is you personal site is also running on WP Multisite or normal WP Installation?

I think this cdn feature with html compressor will only work with normal wp install and not multisite. I will suggest you to test it on a multisite network (if possible subdomain based) and check if the cdn is still working with HTML Compressor.

**Comment by raamdev** [comment]
> I think this cdn feature with html compressor will only work with normal wp install and not multisite.

Yes, that is correct. This is a known current limitation of the Static CDN Filters (I mentioned this before) and we're currently working to support Static CDN Filters for sub-domains on WordPress Multisite. See https://github.com/websharks/zencache/issues/439

**Comment by isaumya** [comment]
Hmm. I seems I have to wait more. Anyways. As per my current testing, the way your plugin is performing (even without the cdn) is really amazing. Well coded. I'm seriously looking forward to the cdn support.
Anyways very soon, I'm going move to a new server which has a dedicated radis cache system built in. (Know more: https://wphostingspot.com/) Then I'm gonna test how better it performs compared to the dedicated radis cache server.
BTW, Here is my current page load time, after proper configuration of zencache pro: http://tools.pingdom.com/fpt/#!/cUBqwN/https://www.isaumya.com

P.S: Please do a little hurry on the static cdn support on sub domain based multi sites. Otherwise my site gonna run without cdn and make it slow to the people who live in a distant place from my server.
