### ISSUE TITLE
Installing and Activating via WP-CLI

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#464]
[A user @ WordPress.org writes...](https://wordpress.org/support/topic/deploying-to-multiple-sites-at-once?replies=1#post-6771698)

> I am using wp-cli to deploy this plugin to over 200 sites at once, I have installed and activated it, but it seems that I have to enable it manually for ZenCache to start working. 

I'm not sure what's required to make this happen, but it would be great to make ZenCache fully compatible with [WP-CLI](http://wp-cli.org/) so that installs can be automated.

Marking this as `needs research`.

---

Related: https://github.com/websharks/zencache/issues/395 https://github.com/websharks/zencache/issues/394 https://github.com/websharks/zencache/issues/465 https://github.com/websharks/zencache/issues/289 https://github.com/websharks/zencache/issues/464 https://github.com/websharks/zencache/issues/352

**Comment by aghoshx** [comment]
Subscribing!

**Comment by jaswrks** [comment]
@raamdev Suggestion for how to get this working. Or, at least a place to start.

Above this line...
https://github.com/websharks/zencache/blob/150409/zencache/zencache.inc.php#L345

Add the following:

``` php
// Automatic activation when installed via CLI.
if(strcasecmp(PHP_SAPI, 'cli') === 0 // Activated from a CLI?
    if(!get_option(__METHOD__.'__options') // First-time activation?
        && (!is_multisite() || !get_site_option(__NAMESPACE__.'_options')))
     {
        $this->options['enable'] = '1';
        update_option(__NAMESPACE__.'_options', $this->options);
        if(is_multisite()) update_site_option(__NAMESPACE__.'_options', $this->options);
     }
```

**Comment by openbayou** [comment]
Would really like this as I manage a lot of WP sites as well.

**Comment by raamdev** [comment]
Next Release Changelog:
- **Compatibility: WP-CLI.** When installing Comet Cache via WP-CLI, Comet Cache is now automatically enabled. There's no need to manually enable Comet Cache from within the plugin options after installing. Props @jaswsinc. See [Issue #464](https://github.com/websharks/comet-cache/issues/464).

**Comment by aghoshx** [comment]
Thank you!

**Comment by raamdev** [comment]
**Comet Cache v160416** has been released and includes changes from this GitHub Issue. See the [v160416 announcement](https://cometcache.com/blog/comet-cache-v160416-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#464).
