### ISSUE TITLE
Add Pro Updater compatibility for ManageWP

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#465]
ManageWP allows site owners to manage multiple WordPress sites from a single Dashboard, which allows site owners to easily upgrade plugins on multiple sites at once. However, the ZenCache Pro Updater is not compatible with this, so site owners need to login to each site individually to perform the ZenCache Pro update.

There is a [ManageWP API](https://managewp.com/api), which is essentially just a set of three hooks that we'll need to attach appropriate routines to, that allows premium plugin developers to add support for updating premium plugins outside WordPress.org:
- `mwp_premium_update_notification`
- `mwp_premium_perform_update`
- `mwp_premium_update_check`

I reviewed the current ZenCache Pro updater functions and these will need some updating before we can just attach these hooks (i.e., the updater functions currently assume they're being run on the WordPress Dashboard and just output messages instead of returning specific values).

We can also [search GitHub for other plugins that have integrated with ManageWP](https://github.com/search?q=mwp_premium_update_notification&type=Code&utf8=%E2%9C%93) for more real-world examples.

---

Related: https://github.com/websharks/zencache/issues/395 https://github.com/websharks/zencache/issues/394 https://github.com/websharks/zencache/issues/465 https://github.com/websharks/zencache/issues/289 ~~https://github.com/websharks/zencache/issues/464~~ ~~https://github.com/websharks/zencache/issues/352~~

**Comment by patdumond** [comment]
+1 for this feature: referencing internal private ticket https://websharks.zendesk.com/agent/tickets/11122.

**Comment by raamdev** [comment]
+1 here (private ticket): https://websharks.zendesk.com/agent/tickets/12301

**Comment by raamdev** [comment]
Noting that the ManageWP API page has been updated to include the following notice:

> Important notice! This API is now deprecated and ManageWP now supports all premium plugins and themes that use standard WordPress update functionality to hook and display updates to in the WordPress admin out of the box. You do not need to do anything now, we are leaving this page for reference only.

So, since the ManageWP API is no longer supported, it looks like integrating with ManageWP will involve adapting our Pro Updater to work more closely with the WordPress update system. We already do this in some ways, but we could improve the integration so that any plugins, such as ManageWP, also work with our Pro Updater (and perhaps even with the [Jetpack Site Management](https://jetpack.com/support/site-management/) feature, which allows you to manage plugin updates for multiple self-hosted sites from a central WordPress.com account.

Right now the Comet Cache Pro Plugin Updater is used for both supplying the username/password _and_ running the update. What I propose we look into is using the Pro Plugin Updater page only for configuring (and validating) the username/password, but have the actual update be triggered by WordPress through the Plugin page, so that when an update is available it appears the same way as any other WordPress plugin.

**Comment by raamdev** [comment]
@jaswsinc Any opposition to what I suggested in the last paragraph above?

**Comment by jaswrks** [comment]
Nope. It sounds like a plan to me. I think all that really needs to happen is that [this filter](https://github.com/websharks/comet-cache-pro/blob/160521/src/includes/traits/Plugin/UpdateUtils.php#L112) needs to be capable of working without relying on request variables, the current user, or transients. That way CC details are given whenever WordPress itself looks for available upgrades.

I recently discovered that we can also hook into the underlying WordPress.org API calls, as seen by example in the WPSC RV handler [here](https://github.com/websharks/wp-sharks-core-rv/blob/000000-dev/src/includes/functions/filters.php#L24).

See also: [where the filter is established](https://github.com/websharks/wp-sharks-core-rv/blob/000000-dev/src/includes/check.php#L15).

**Comment by raamdev** [comment]
+1 here: https://github.com/websharks/comet-cache/issues/778

**Comment by bobo1** [comment]
Any progress on this? Getting to be a real pain to go to each supported website and update instead of using managewp and the standard WP upgrade tools.

**Comment by raamdev** [comment]
@bobo1 I've added this to the Next Release milestone. We'll try to get this into the next release.

**Comment by jaswrks** [comment]
I'm assigning this to myself and I'll begin work on it shortly so that Raam can review a PR.

**Comment by raamdev** [comment]
Coming in the next release, support for ManageWP:

![2016-09-01_00-34-50](https://cloud.githubusercontent.com/assets/53005/18155834/427c2e2c-6fdf-11e6-95fa-6cc7214943ef.png)

Comet Cache Pro updates now utilize the built-in WordPress Plugin Updater system:

![2016-09-02_17-03-06](https://cloud.githubusercontent.com/assets/53005/18218204/28267b62-712f-11e6-8d05-0d2b8275c3c3.png)

**Comment by raamdev** [comment]
Next Release Changelog:
- **ManageWP Compatibility** (Pro): Comet Cache Pro is now compatible with ManageWP, a service that allows remote management of multiple WordPress sites. Comet Cache Pro Plugin Updates will now appear in the ManageWP dashboard and, assuming you have saved valid license credentials in Dashboard → Comet Cache Pro → Plugin Options → Update Credentials, you will be able to upgrade Comet Cache Pro remotely from the ManageWP Dashboard. Props @jaswsinc. See [Issue #465](https://github.com/websharks/comet-cache/issues/465).
- **Rewritten Pro Plugin Updater**: The Comet Cache Pro Plugin Updater has been redesigned to use the built-in WordPress plugin updater system. When a Comet Cache Pro update is available, it now appears in the WordPress Updates section and in the Plugins list, like other WordPress plugins and can be updated normally like other WordPress plugins, as long as you have saved valid Comet Cache Pro license details in the new "Update Credentials" options panel. Props @jaswsinc. See [Issue #272](https://github.com/websharks/comet-cache-pro/issues/272).

**Comment by raamdev** [comment]
**Comet Cache v160917** has been released and includes changes from this GitHub Issue. See the [v160917 announcement](https://cometcache.com/blog/comet-cache-v160917-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#465).
