### ISSUE TITLE
Feature Request: JSON support for HTML Compression

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#469]
At this time (as of v150409), the ZenCache HTML Compression only supports compressing/minifying HTML, CSS, and JavaScript. It would be nice to also support JSON (which appears to only require removing whitespace).

If you want to enable [Google Sitelinks Search Box](https://developers.google.com/structured-data/slsb-overview) on your site, you need to add a snippet of JSON that uses `<script type="application/ld+json"></script>` (see https://github.com/websharks/zencache/issues/467 for a full example). It would be nice if the ZenCache HTML Compressor could also compress this.

---
## Next Actions
- [x] Add support for `application/ld+json`
- [x] Compress JSON by prepending the contents with `json =` and suffixing them with `;`. Then run the JavaScript compressor against the code; i.e., treat it as JavaScript.
- [x] Remove prefix and suffix after compression.
- [x] Prevent `application/ld+json` from ever being combined into another JavaScript file. This needs to stand alone it appears.

Referencing: https://developers.google.com/schemas/formats/json-ld

**Comment by jaswrks** [comment]
Adding a list of next actions above.

**Comment by jaswrks** [comment]
This has been implemented in the latest release of the HTML Compressor, and it's already a part of the newly restructured copy of ZenCache Pro.

**Comment by raamdev** [comment]
Woohoo! Awesome! Thanks. :-)

**Comment by raamdev** [comment]
Next release changelog:
- **Enhancement**: HTML Compression now supports compressing JSON (in addition to the already supported HTML, JavaScript, and CSS compression). Props @jaswsinc. See [Issue #469](https://github.com/websharks/zencache/issues/469).
