### ISSUE TITLE
Static CDN Filters do not work on primary site when SUBDOMAIN_INSTALL = true

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#470]
This was reported here: https://github.com/websharks/zencache/issues/439#issuecomment-93338773.

As seen on [this line](https://github.com/websharks/zencache-pro/blob/150409/zencache-pro/includes/cdn-filters.php#L204), ZenCache doesn't apply Static CDN Filters at all (even to the primary site) if `SUBDOMAIN_INSTALL` is defined:

``` php
if(is_multisite() && (defined('SUBDOMAIN_INSTALL') && SUBDOMAIN_INSTALL))
     return; // Not possible; requires a sub-directory install (for now).
```

There's nothing stopping the Static CDN Filters from working properly for the primary site in a WPMU environment, even if that site is using subdomains for the child sites.

**Comment by jaswrks** [comment]
I wonder if supporting sub-domain installs could be as easy as adding some new rewrite rules into `.htaccess`, and then routing all static resources though the CDN configured for the main site. Just a thought. A little off topic.

That's really what WordPress (when not running as a sub-domain install) does already.

**Comment by raamdev** [comment]
Next release changelog: 
- **Bug Fix** (Pro): Static CDN Filters were not being applied to the primary site on WP Multisite installations that used subdomains. (While subdomains are not currently supported by Static CDN Filters, the primary site can still use this feature.) Props to @isaumya for discovering this bug. See [Issue #470](https://github.com/websharks/zencache/issues/470).

**Comment by raamdev** [comment]
@jaswsinc I moved your comment here: https://github.com/websharks/zencache/issues/439#issuecomment-93834284

**Comment by isaumya** [comment]
Glad to help guys :)
