### ISSUE TITLE
`purge_cache` CRON Should Run Every Hour

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#472]
The `zencache\plugin::purge_cache()` method runs once daily (attached to WP Cron), in order to automatically cleanup expired/stale cache files. However, on a extrememly large site with a lower expiration time (to save disk space) it would be better if this routine ran hourly. That way an entire day has not gone by before ZenCache gets around to doing the cleanup; i.e., running hourly would make ZenCache smarter when configured in certain ways.

Referencing this internal ticket:
https://websharks.zendesk.com/agent/tickets/6002

**Comment by raamdev** [comment]
Great idea! I've marked this as `ready for work` and added it to the Next Release milestone.

**Comment by raamdev** [comment]
@jaswsinc Is there any reason we can't make this a configurable option? I.e., make the default 1 hour but allow a site owner to override that and specify an interval?

**Comment by jaswrks** [comment]
> Is there any reason we can't make this a configurable option? I.e., make the default 1 hour but allow a site owner to override that and specify an interval?

We can make it configurable, yes. I don't see any problem with that. However, it does need to be on a schedule that is either already registered with WP-Cron, or that we add via filters.

**Comment by jaswrks** [comment]
## Next Actions (Step 1 of 2)
- New feature branch in the `websharks/zencache-pro` repo.
- After [this line](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/classes/Plugin.php#L270) add the following:
  
  ``` php
  'cache_cleanup_schedule' => 'hourly', // `every15m`, `hourly`, `twicedaily`, `daily`
  ```
- Replace [this line](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/classes/Plugin.php#L524) with the following:
  
  ``` php
  wp_schedule_event(time() + 60, $this->options['cache_cleanup_schedule'], '_cron_'.__NAMESPACE__.'_cleanup');
  ```
- Replace [this line](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/classes/Plugin.php#L522) with the following:
  
  ``` php
  if ((integer) $this->options['crons_setup'] < 1447330252 || substr($this->options['crons_setup'], 10) !== '-'.__NAMESPACE__.'-'.$this->options['cache_cleanup_schedule']) {
  ```
- Submit PR.

**Comment by jaswrks** [comment]
## Next Actions (Step 2 of 2 — On Deck)
- New feature branch in the `websharks/zencache-pro` repo.
- Add UI option (as described above) that allows a site owner to control:
  - `cache_cleanup_schedule`
- Submit PR.

---

**Note:** The above instructions for Step 2 are rather vague. If you're able, attempt step 2 right away. Otherwise, once step 1 is complete hit me on Slack for a more complete set of Step 2 instructions.

**Comment by jaswrks** [comment]
Assigning this to @kristineds  :-)

**Comment by jaswrks** [comment]
Related issue (https://github.com/websharks/zencache/issues/408) that we could tackle once this is done.

**Comment by raamdev** [comment]
@jaswsinc @kristineds It appears the option for this got added to the Auto-Cache Engine section of the UI, however from what I can tell this is not related to the Auto-Cache Engine but rather to Cache Expiration and therefore belongs in **ZenCache → Plugin Options → Directory / Expiration Time**. 

The description for this option also needs to be updated to remove any mention of the Auto-Cache Engine.

**Comment by kristineds** [comment]
@raamdev @jaswsinc Submitted PRs for Steps 1 and 2 (updated version)
- [Step 1 of 2: Add hourly option on `purge_cache()` method ](https://github.com/websharks/zencache-pro/pull/174#issuecomment-157570692)
- [Step 2 of 2: Add UI option for cache cleanup schedule ](https://github.com/websharks/zencache-pro/pull/180)

**Comment by raamdev** [comment]
@kristineds @jaswsinc Also noting that the following text in Cache Expiration Time needs to be updated to reflect the new hourly schedule (it currently says "once daily", it should now say "once per hour"):

> In addition, a WP Cron job will automatically cleanup your cache directory (once daily); purging expired cache files periodically.

**Comment by kristineds** [comment]
@raamdev @jaswsinc That has been updated as part of the latest commit: https://github.com/websharks/zencache-pro/commit/d702eeb6858b8e209e94be68497c268fa4609711

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: The automatic Cache Cleanup schedule that cleans up (deletes) expired/stale cache files has been changed from once every day to once every hour. Running the cleanup hourly makes ZenCache smarter when configured in certain ways and saves disk space. Props @kristineds. See [Issue #472](https://github.com/websharks/zencache/issues/472).
- **New Feature!**: It's now possible to customize the Cache Cleanup Schedule and set your own schedule in _ZenCache → Plugin Options → Manual Cache Clearing → Cache Cleanup Schedule_. ZenCache uses [`wp_get_schedules()`](https://codex.wordpress.org/Function_Reference/wp_get_schedules) when generating the list of available schedules, which makes it possible to create your own custom cron schedule using a plugin like WP Crontrol and use that to define a custom Cache Cleanup Schedule. Props @kristineds. See [Issue #472](https://github.com/websharks/zencache/issues/472).

**Comment by raamdev** [comment]
**ZenCache Pro v151220** has been released and includes changes worked on as part of this GitHub Issue. See the [release announcement](http://zencache.com/zencache-pro-v151220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#472).
