### ISSUE TITLE
Feature Request: Inline Small CSS in Zencache Files

### ISSUE THREAD

**Issue by patdumond** [wpsharks/comet-cache#473]
A user requested that small CSS response bodies be inlined, per GTmetrix recommendations. This is the recommendation from GTmetrix:

Inline small CSS 
E (50) 

CSS High

The following external resources have small response bodies. Inlining the response in HTML can reduce blocking of page rendering.

https://www.urgentvertalen.nl/ should inline the following small resources:

https://www.urgentvertalen.nl/wp-content/cache/zencache/htmlc/public/www-urgentvertalen-nl/2/6/c/d/6/090a629776e2fd02a12c7b2b428dce02-compressor-part.css

**Comment by raamdev** [comment]
@patdumond Thank you for the feature request. 

> https://www.urgentvertalen.nl/ should inline the following small resources:
> 
> https://www.urgentvertalen.nl/wp-content/cache/zencache/htmlc/public/www-urgentvertalen-nl/2/6/c/d/6/090a629776e2fd02a12c7b2b428dce02-compressor-part.css

This actually makes no sense to do. The HTML Compressor combines all CSS into a single, compressed/minified CSS file (`090a629776e2fd02a12c7b2b428dce02-compressor-part.css` in this case) and loads that single file, as opposed to the browser requesting several different resources be loaded (which would slow things down).

The GTMetrix recommendation is a false-positive. It's recommending something that doesn't make sense, i.e., it's not aware that the site is already being cached and minified by a WordPress caching plugin so it's providing basic recommendations that it would provide to a non-cached/minified site.

There are many "metrics" that these page-testing services use that don't take into account WordPress sites or caching plugins that may be running on them. As a result, this can lead to many "false-positives" that make it sound like ZenCache isn't doing its job when in fact it is.

Here's a very common one that includes some further details about this issue with page-testing service results:
- [Why doesn’t ZenCache move CSS/JS scripts into the footer?](http://zencache.com/kb-article/why-doesnt-zencache-move-cssjs-into-the-footer/)
