### ISSUE TITLE
Feature Request: Per-Site CDN Configuration (Multisite)

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#475]
It would be great if the Static CDN Filters allowed for configuring a specific CDN pull zone for _each domain_ in a WordPress Multisite installation, thereby allowing per-site CDN configuration within a WordPress Multisite environment. 

Related: #439 #468

**Comment by isaumya** [comment]
I really don't think this is necessary at all. Because in case of WP Multisite a single cdn pull zone can be used for all the sites through out the network. So even if you have 50 sites in your netwrk, a single cdn package will be enough for all site when CDN is activated from the network admin and the plugin is network activated.

I don't think when someone can use a single cdn pull zone for all sites in the network will ever consider paying extra for each individual site.

P.S.: This is how W3TC multisite cdn works too.

**Comment by raamdev** [comment]
> I don't think when someone can use a single cdn pull zone for all sites in the network will ever consider paying extra for each individual site.

You're assuming that all of the sites in a multisite environment are owned by the same person. What if the sub-sites are part of a network where each individual site owner can choose if they want to pay the network admin for adding CDN caching via ZenCache? In that case, it would be desirable to configure a CDN Pull Zone on a per-site basis.

**Comment by isaumya** [comment]
Yes you are absolutely right. But in that case, you can give the ease to the general admin to change the cdn url only. Just the way wo super cache works. If you activate cdn in super cache from the network admin then by default it activates the cdn only for the primary site though its been network activated. Then for the sub site you have to go to that sub site dashboard and on that dashboard you have to go to the super cache settings and then you have to put your cdn url that you want to use. Now if you are the owner of all the sites then you can just use the same cdn url in that case you don't have to pay extra for that site's cdn or you can use a different cdn url.
Hope this idea helps.

**Comment by raamdev** [comment]
@isaumya Yes, that is how I was thinking this feature would work in ZenCache Pro.

**Comment by raamdev** [comment]
Support for configuring CDN hostname(s) on a per-site basis in a WordPress Multisite environment has been implemented and this feature will go out with the next release:

![2015-05-20_21-37-31](https://cloud.githubusercontent.com/assets/53005/7740002/9f4849ec-ff38-11e4-9ab2-f5b660897e26.png)

**Comment by raamdev** [comment]
Next release changelog:
- **Enhancement** (Pro): Static CDN Filters now supports the ability to configure separate CDN hostname(s) for each domain (or sub-domain) that you run in a WordPress Multisite Network. Props @jaswsinc. See [Issue #475](https://github.com/websharks/zencache/issues/475).
