### ISSUE TITLE
Feature Request (Pro): Prompt to configure Pro Updater after activation

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#477]
It would be nice if ZenCache Pro prompted the user to configure the Pro Updater after the plugin is activated.

![2015-05-02_20-37-48](https://cloud.githubusercontent.com/assets/53005/7443254/1c01a848-f10b-11e4-8fb4-ed302d70b9c4.png)

---

Related: https://github.com/websharks/zencache/issues/395 https://github.com/websharks/zencache/issues/394 https://github.com/websharks/zencache/issues/465 https://github.com/websharks/zencache/issues/289 https://github.com/websharks/zencache/issues/464 https://github.com/websharks/zencache/issues/352

**Comment by jaswrks** [comment]
:+1: Agree. Great idea.

**Comment by raamdev** [comment]
Noting that this would be extra-nice to have now that Pro Updates are hooked into the WordPress Plugin Update System (https://github.com/websharks/comet-cache/issues/289 and https://github.com/websharks/comet-cache/issues/465). We'll want to make sure the site owner configures the update credentials after installing Comet Cache Pro so that they can get updates.

**Comment by jaswrks** [comment]
Next Release Changelog:
- **UI Enhancement:** On pro version activation, display a notice that reminds site owners to configure their Pro Update Credentials so they'll be notified by WordPress about new versions of the pro software. See also: [issue #477](https://github.com/websharks/comet-cache/issues/477) if you'd like additional details.

**Comment by jaswrks** [comment]
![2016-11-08_10-57-19](https://cloud.githubusercontent.com/assets/1563559/20115178/c63f0d0c-a5a3-11e6-8c32-14f41d285d46.png)

**Comment by renzms** [comment]
@raamdev 

![screen shot 2016-11-13 at 6 33 13 pm](https://cloud.githubusercontent.com/assets/13220018/20244961/b1e1bab4-a9cf-11e6-950a-9ac1a0cca249.png)

Confirmed working!

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#477).
