### ISSUE TITLE
CDN Host Supports HTTPS Connections not working

### ISSUE THREAD

**Issue by tobias86aa** [wpsharks/comet-cache#478]
I have turn on that my cdn is configured for SSL certification but when i check my address for the cdn content the address still begins whit http and not https. My CDN provider is CDNsun. 

Can this be some sort of bug or something else?

**Comment by raamdev** [comment]
@tokar86a I believe you opened a support ticket related to this and that the issue has been solved now, is that correct?

**Comment by tobias86aa** [comment]
Yes i think it is.
