### ISSUE TITLE
Prevent server cache on urls

### ISSUE THREAD

**Issue by seozones** [wpsharks/comet-cache#483]
Hi there. On my site I need to prevent server cache on a couple of specific urls. Is that possible and if so, what do I do?

**Comment by raamdev** [comment]
@seozones We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [WordPress.org Support Forum](https://wordpress.org/support/plugin/zencache) (for ZenCache Lite) or open a [Trouble Ticket](https://www.websharks-inc.com/support/?product=zencache&request_type=trouble_ticket) (ZenCache Pro). Thank you! :)

**Comment by raamdev** [comment]
@seozones I should also mention that URI Exclusion Patterns are a feature of [ZenCache Pro](http://zencache.com/prices/), not currently available in ZenCache Lite.

**Comment by seozones** [comment]
Yes, I own the Pro version. So are you saying the answer to my question is under URI Exclusion Patterns?

**Comment by raamdev** [comment]
> So are you saying the answer to my question is under URI Exclusion Patterns?

Yes.
