### ISSUE TITLE
Cache doesn't work with logged in users

### ISSUE THREAD

**Issue by luisflo** [wpsharks/comet-cache#484]
I'm using zencache-pro with the option of maintaining a  separate cache for each user activated. When a user is logged and browsing the site, zencache creates a new id-html cache page for each page the user visits, BUT also remove the id-html page that created for the previous page the user visited. That implies there is only one page cached, the page you're visiting at that moment, but once you move to another one the cache generated get lost. Any help ?

**Comment by raamdev** [comment]
@luisflo Are you using WordPress Multisite?

**Comment by luisflo** [comment]
No. I'm not. It's working for one and only domain site. It's quite strange that it creates the cache page but although it exists in the disk the page do not speed if you reload. Also If i stay in the same page, just waiting, the cache page disapear after some seconds. I tried just to check changing the rights of the cache page not to write for apache or even chown them to root and even in that case they disapear. Any help ? Thanks.

**Comment by luisflo** [comment]
What kind of situation can force an id-cache file to disapear so fast ? or in anycase when the user moves to other page ?

**Comment by raamdev** [comment]
@luisflo It sounds like you either have another WordPress plugin that is conflicting with ZenCache and triggering a cache wipe when it should not be, or you have something on your server that is cleaning up cache files automatically (less likely).

I suggest trying to disable all other plugins and activating the default WordPress TwentyFifteen theme to see if you can then recreate the problem. If the problem goes away, you know it's related to your theme or one of your other plugins.

I have tested the Logged-In User Caching and the cache files do not get cleared immediately as you describe.

**Comment by luisflo** [comment]
Thanks for your answer, i will try. Does the logged in cache system work in disk or uses sometimes memory somehow ?

**Comment by raamdev** [comment]
> Does the logged in cache system work in disk or uses sometimes memory somehow ?

It works the same way as the rest of the cache, by storing cache files on disk. We have a feature request open for implementing other cache storage methods; see https://github.com/websharks/zencache/issues/47.
