### ISSUE TITLE
Static CDN Filters remain enabled for Logged-In Users even when Logged-In User caching is disabled

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#486]
## Steps to Reproduce This
1. Configure and enable Static CDN Filters (**ZenCache → Plugin Options → Static CDN Filters**)
2. Disable Logged-In User caching (**ZenCache → Plugin Options → Logged-In Users**)
3. Visit the front-end of the site as a logged-in user and inspect the source code (View Source)
## Expected Behavior

Since Logged-In User caching is disabled, I would expect all ZenCache features (including Static CDN Filters) to not apply when I visit the site as a logged-in user. 
## Observed Behavior

Upon inspecting the page source (View Source), I see that the Static CDN Filters _are_ being applied and static resource URLs are being rewritten, despite my visiting the site as a logged-in user.

---
## Update (converted from bug to enhancement)

As per the comments below, I've converted this GitHub Issue to an `enhancement` instead of a `bug`. While the current behavior is unexpected, it should still be possible to have Static CDN Filters enabled for Logged-In users when caching for Logged-In users is disabled.

---
## Next Steps
- [ ] Add new section to **ZenCache → Plugin Options → Logged-In Users** titled _Static CDN Filters Enabled for Logged-In Users & Comment Authors?_; this section will describe how Static CDN Filters for Logged-In users is disabled by default, but that can be changed to allow Static CDN Filters to apply to Logged-In users as well. A dropdown box will provide two options: `No, disabled (default)` and `Yes, enabled`.
- [ ] Update codebase to utilize this new option when determining if Static CDN Filters should be applied.

---

Related: https://github.com/websharks/zencache/issues/488

**Comment by lkraav** [comment]
Instead of elimination, I would actually prefer at least an opt-in to this behavior.

**Comment by raamdev** [comment]
@lkraav Thanks for the feedback! That's an even better idea. :-)

**Comment by lkraav** [comment]
Yes. The reasoning is that even when in development or the admin is working their site, there's plenty of motivation to still load a bunch of assets over CDN.

**Comment by isaumya** [comment]
I also agree with ikraav. I think its better to give an option to the user whether or not they want this to happen. If they don't then cdn won't show for logged in users or else it will.

**Comment by raamdev** [comment]
@isaumya Thanks for the feedback. :-)

---

@jaswsinc I added a list of next steps ↑. Can you review that when you get a chance and update the list if necessary?

**Comment by jaswrks** [comment]
@raamdev writes...

> Since Logged-In User caching is disabled, I would expect all ZenCache features (including Static CDN Filters) to not apply when I visit the site as a logged-in user.

I can certainly see where this particular scenario might lead to confusion.

However, at the same time I don't see how an option for this would be truly useful. If a CDN is configured, it is always serving "static" resources. So it doesn't matter if it's a logged-in user or not. If you have a CDN, you would always want static resources served from the CDN. Right? Or am I wrong?

I can see where providing an option _might_ help to avoid confusion though. No argument. I just can't see anyone actually turning it off for any valid reason.

**Comment by jaswrks** [comment]
> I added a list of next steps ↑. Can you review that when you get a chance and update the list if necessary?

Next actions look great to me.

**Comment by raamdev** [comment]
> If you have a CDN, you would always want static resources served from the CDN. Right? 

@jaswsinc No, _especially_ not when you're trying to verify that ZenCache is working properly, or when a static resource (that is hosted on the CDN) appears to be loading outdated content and you're trying to figure out if it's an issue with the CDN or an issue with your server not having the updated copy. 

For my own personal (single-user) sites, when I login to the WordPress Dashboard, I like to know that _nothing_ on my site is being cached in any way, because that gives me a sense of security knowing that what I'm seeing is exactly what's on my server (so long as I've ensured my browser isn't caching anything). That's why when I inspected the source code and noticed that my static resources were being loaded from the CDN, that caught me by surprise, as I intentionally left Logged-In User Caching disabled because I didn't want ZenCache touching anything when I was logged in and browsing the site.

**Comment by jaswrks** [comment]
> That's why when I inspected the source code and noticed that my static resources were being loaded from the CDN, that caught me by surprise, as I intentionally left Logged-In User Caching disabled because I didn't want ZenCache touching anything when I was logged in and browsing the site.

Roger that. I can understand that. Thanks for explaining.

**Comment by jaswrks** [comment]
## Next Actions (Step 1 of 2)
- New feature branch in the `websharks/zencache-pro` repo.
- After [this line](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/classes/Plugin.php#L230) add the following:
  
  ``` php
  'cdn_when_logged_in',
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/classes/Plugin.php#L355) add the following:
  
  ``` php
  'cdn_when_logged_in' => '0', // `0|1`; enable when logged in?
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/classes/CdnFilters.php#L52) add the following:
  
  ``` php
  /**
  * @since 15xxxx Adding logged-in check.
  *
  * @type bool CDN when logged in?
  */
  protected $cdn_when_logged_in;
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/classes/CdnFilters.php#L145) add the following:
  
  ``` php
  $this->cdn_when_logged_in = (boolean) $this->plugin->options['cdn_when_logged_in'];
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/classes/CdnFilters.php#L222) add the following:
  
  ``` php
  if (!$this->cdn_when_logged_in && $this->plugin->isLikeUserLoggedIn()) {
      return; // Disable in this case.
  }
  ```
- Submit PR.

**Comment by jaswrks** [comment]
## Next Actions (Step 2 of 2 — On Deck)
- New feature branch in the `websharks/zencache-pro` repo.
- Add UI option (as described above) that allows a site owner to control:
  - `cdn_when_logged_in`
- Submit PR.

---

**Note:** The above instructions for Step 2 are rather vague. If you're able, attempt step 2 right away. Otherwise, once step 1 is complete hit me on Slack for a more complete set of Step 2 instructions.

**Comment by jaswrks** [comment]
Assigning this to @kristineds :-)

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: Static CDN Filters are no longer applied by default for Logged-In Users. This was causing some confusion because Logged-In User caching is disabled by default. There is no harm in applying Static CDN Filters to all users (logged-in or not logged-in), in fact we recommend it, however we now disable this functionality by default to avoid confusion. A new option allows you to control this behavior and enable Static CDN Filters for Logged-In users; see _ZenCache → Logged-In Users → Static CDN Filters Enabled for Logged-In Users & Comment Authors?_ Props @kristineds, @lkraav, and @isaumya. See [Issue #486](https://github.com/websharks/zencache/issues/486).

**Comment by raamdev** [comment]
**ZenCache Pro v151220** has been released and includes changes worked on as part of this GitHub Issue. See the [release announcement](http://zencache.com/zencache-pro-v151220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#486).
