### ISSUE TITLE
Feature Request: Image Optimization

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#491]
It would be great if ZenCache had an option to auto-optimize all of the images on a site.

Related: https://github.com/websharks/zencache/issues/490

**Comment by lkraav** [comment]
Why take this burdain on? There's plenty of high-quality focused plugins to recommend.

**Comment by raamdev** [comment]
@lkraav Because image optimization is something that increases page loading time, which is a core goal of the ZenCache plugin: to speed up your site. 

Do you have any favorite Image Optimization plugins that you would recommend? Maybe we could work towards improving integration between ZenCache and existing Image Optimization plugins.

**Comment by lkraav** [comment]
You guys are experienced, so no point in going into "don't have to recode everything under the sun in-house". Here's hoping your precious effort will focus on things that are really weak elsewhere in the market - such as your great dependency minification effort to replace the stalled https://github.com/x-team/wp-dependency-minification/ project for an example.

For image optimization, integration with others sounds like the best incremental next step to learn about market response and determine further requirements.

https://wordpress.org/plugins/ewww-image-optimizer/
https://wordpress.org/plugins/kraken-image-optimizer/
https://premium.wpmudev.org/project/wp-smush-pro/ -> https://premium.wpmudev.org/blog/smush-kraken-ewww/ blog article that compares them all

**Comment by raamdev** [comment]
@lkraav Thanks so much for all the feedback! I will definitely research those plugins before determining how to proceed with this GitHub Issue. I'll update this GitHub issue later with any future thoughts.

**Comment by isaumya** [comment]
I agree with @lkraav on this. There are many great image optimization focused plugin out there in the wp repo, they are free and amazing. I always prefer https://wordpress.org/plugins/ewww-image-optimizer/ personally. If you add this feature into zencache it will nothing but an extra headache as people will prefer using focused image optimization plugin that using the zencache version, also it will make the zencache code/classes even more complex. I really do not think that there is any need for that. Trust me even if you spent your valuable manpower to get this feature, most people will disable the zencache optimization version and enable eww. 
This is my personal honest opinion on this. :-1: on this request. Sorry man!

**Comment by raamdev** [comment]
@isaumya Thanks for the feedback!

**Comment by KTS915** [comment]
I agree with @lkraav and @isaumya.

I don't see any reason to take this on when (a) it's very difficult to do well and (b) another plugin already does it well, i.e. https://wordpress.org/plugins/ewww-image-optimizer/ 

It would just be risking the usefulness and reputation of ZenCache for little or no gain.

**Comment by raamdev** [comment]
@KTS915 Thanks for the feedback. :-)

@jaswsinc I'm prepared to punt this feature in favor of improving support for (if necessary) and recommending [EWWW Image Optimizer](https://wordpress.org/plugins/ewww-image-optimizer/). Agreed?

**Comment by jaswrks** [comment]
Agree. I consider this to be a job for the browser itself, and I'd love to see improved support for this in Chrome/Firefox. Short of that, a highly specialized plugin that is focused entirely on this aspect would be a job of its own.

**Comment by raamdev** [comment]
@jaswsinc Thanks!

I'm closing this GitHub issue in favor of https://github.com/websharks/zencache/issues/556, which I will use to investigate and track EWWW Image Optimizer compatibility with ZenCache.

@lkraav @isaumya @KTS915 Thanks for all the feedback. :-)
