### ISSUE TITLE
Feature Request: Improve Matching Patterns

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#492]
> Quick Question: How can you exclude the home page from the cache? I tried using a URI Exclusion of `index`, `index.php`, `index.html`, _index.php {newline} *index.html`and`_index*`. None of it works`index.html` keeps reappearing in the cache.

Great question. I think this would make a good feature request. The home page is tricky (at present), because it is a match against the Request URI, not against the slug in WordPress. So things like `index`, `index.html`, `index.php` will usually not work here. The Request URI of the homepage (when you're running WP) is generally just a single `/` slash. Adding a `/` to the list of URI exclusions will simply exclude the entire site from the cache though.
## So how do you exclude _just_ the home page?

Add the following to your `/wp-config.php` file:

```
if($_SERVER['REQUEST_URI'] === '/')
    define('ZENCACHE_ALLOWED', false);
```

**Comment by raamdev** [comment]
@jaswsinc This is a duplicate of https://github.com/websharks/zencache/issues/191. Can you confirm and close this issue as `duplicate` if that's the case?

**Comment by jaswrks** [comment]
Confirmed. Thank you!
