### ISSUE TITLE
ZenCache RC 150605 Submodules

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#493]
@raamdev: I am just testing the latest RCs. Awesome!

I haven't started actual tests yet, but whenever I installed the updated copies I noticed there is a `zencache-pro` folder in the lite version that contains submodules.

I don't think there should be any submodules in the updated copy, since we now use Composer for dependencies in that plugin. Referencing: https://github.com/websharks/zencache/releases/download/150605-RC/zencache-v150605.rc.zip

This directories are empty, so no harm there. Just wanted to mention it.

![2015-06-05_11-12-27](https://cloud.githubusercontent.com/assets/1563559/8013204/f1918c4e-0b73-11e5-83dc-546b0b5c6362.png)

**Comment by raamdev** [comment]
@jaswsinc Thanks for the report! I'll adjust the build script to remove those empty directories.

**Comment by raamdev** [comment]
It appears this had nothing to do with the build script. I must've just had those empty directories in there from when I switched over to the refactored codebase.
