### ISSUE TITLE
ZenCache Pro RC 150605 Missing `src/vendor`

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#494]
![2015-06-05_11-20-30](https://cloud.githubusercontent.com/assets/1563559/8013344/00488322-0b75-11e5-8e04-b24a4b99fd1b.png)
## Steps to Reproduce
- Download: zencache-pro-v150605.rc.zip from the private pro repo.
- Attempt to activate in WordPress.
## Expected Behavior

Activation
## Observed Behavior

Fails due to a missing `src/vendor` directory with Composer dependencies in the zip.

**Comment by raamdev** [comment]
@jaswsinc I'm not able to reproduce this. I tested the `zencache-pro-v150605.rc.zip` zip file before publishing the release, and I just tested it again to make sure I wasn't crazy. I received no errors upon activation, ZenCache Pro activated successfully, and caches pages on my test site as expected:

![2015-06-06_10-27-47](https://cloud.githubusercontent.com/assets/53005/8020000/f01163da-0c36-11e5-9e13-ba93a0eb73d4.png)
![2015-06-06_10-28-13](https://cloud.githubusercontent.com/assets/53005/8020001/f1047bba-0c36-11e5-8ddd-5387ef47676a.png)
![2015-06-06_10-29-31](https://cloud.githubusercontent.com/assets/53005/8020002/f21d1c46-0c36-11e5-8fa9-bf28584e7789.png)

**Comment by jaswrks** [comment]
Thanks! I can't reproduce it now. I downloaded with the exact same link both times, but the first time I downloaded it (almost as soon as you released it) and it was missing the vendor directory. Maybe it was a strange GH propagation issue (or something), but it's all good now. Sorry for the alarm.

**Comment by raamdev** [comment]
@jaswsinc Copy that. No worries. Better to be safe than sorry. ;)
