### ISSUE TITLE
Cant uninstall your software

### ISSUE THREAD

**Issue by empaking** [wpsharks/comet-cache#496]
Hi,

I cant uninstall your software, zen cache. Please help me do this because i dont to use it when it dont work as it should like.

Login details:

_[removed login details--this is a public area, please don't post private information here]_

/Emil

**Comment by raamdev** [comment]
@empaking Please see: [How do I uninstall ZenCache?](http://zencache.com/kb-article/how-do-i-uninstall-zencache/)

**Comment by empaking** [comment]
Hi,

That It not possible, try ourself and see

Med vänlig hälsning
Emil Höglund
070 304 72 59
MinDatorSupport.sehttp://MinDatorSupport.se

Skickat från min iPhone

11 jun 2015 kl. 20:30 skrev Raam Dev <notifications@github.com<mailto:notifications@github.com>>:

@empakinghttps://github.com/empaking Please see: How do I uninstall ZenCache?http://zencache.com/kb-article/how-do-i-uninstall-zencache/

##

**Comment by raamdev** [comment]
@empaking If you need priority support and you're a Pro customer, please open a support ticket: http://zencache.com/support/
