### ISSUE TITLE
Show ZenCache version number in Plugin Options

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#502]
The installed ZenCache plugin version should be clearly visible from the ZenCache Plugin Options panel, somewhere at the top:

![2015-06-11_20-37-29](https://cloud.githubusercontent.com/assets/53005/8121443/c3e3bbae-1079-11e5-9d26-adad9ec9c99e.png)

**Comment by jaswrks** [comment]
## Next Actions (for Renz on Windows)

Create a directory on your computer (in your `$HOME` directory) to hold WebSharks-related projects. I suggest `~/projects/websharks`; where `~` is your `$HOME` directory.

## Open Git Bash and Create Directories

``` bash
$ mkdir -p ~/projects/websharks # Make these two directories.
```

---

## Clone the ZenCache Pro Repo

``` bash
$ cd ~/projects/websharks # Move into this directory.
$ git clone https://github.com/websharks/zencache-pro
```

---

## Satisfy Dependencies

``` bash
$ cd ~/projects/websharks/zencache-pro # Move into the ZenCache repo.
$ composer install # Run composer to install dependencies locally.
```

---

## Start a New Feature Branch

``` bash
$ cd ~/projects/websharks/zencache-pro # Move into the ZenCache repo.
$ git checkout 000000-dev # Always start from the dev branch.
$ git checkout -b feature/502 # A new feature branch for this issue; i.e., issue number 502
```

---

## Make Changes

Following the details outlined by @raamdev above, we need some new HTML markup in this file, somewhere inside of this div, as seen in the files listed below:
- See: https://github.com/websharks/zencache-pro/blob/150716/src/includes/classes/MenuPageOptions.php#L25
- Repeat here: https://github.com/websharks/zencache-pro/blob/150716/src/includes/classes/MenuPageProUpdater.php#L26

_Note: I am referencing these files as they exist on GitHub. However, the changes that you make should be in an editor of your choosing; i.e., you work from files in your local repo clone._

### Generating the Markup

The current plugin version is a PHP Constant named: `VERSION`

``` php
echo '<div class="plugin-menu-page-version">'.esc_html(VERSION).'</div>'."\n";
```

_That's just a basic example. You might need to dress things up a bit._

### Styling this div...

You can add styles in this file: https://github.com/websharks/zencache-pro/blob/150716/src/client-s/css/menu-pages.css

---

## Commit and Push Changes to GitHub

``` bash
$ cd ~/projects/websharks/zencache-pro # Move into the ZenCache repo.
$ git add --all && git commit -m 'Adding version to menu pages; see: websharks/zencache#502'
$ git push -u origin feature/502 # Push to GitHub
```

_If you get an error when doing the push, please contact @raamdev and ask for permission._

---

## Open a Pull Request @ GitHub
- Go here to find a list of all branches: https://github.com/websharks/zencache-pro/branches
- Find your branch in the list; i.e., `feature/502`
- Click "New Pull Request"
- Enter a title; e.g., "Adding Version to Menu Pages; see: websharks/zencache#502"
- Enter a body; e.g., "Closes websharks/zencache#502"
- Submit, then wait for a review from @raamdev :-)

**Comment by raamdev** [comment]
I just realized that it would be nice to show both the installed version number _and_ the 'latest' version number, if different. This could also show something like "Upgrade now" if there's a newer version.

**Comment by renzms** [comment]
Taking note of that Raam, and will adjust accordingly as I test and fix the parse error from: https://github.com/websharks/zencache-pro/pull/126

**Comment by renzms** [comment]
Tested on wordpress installation

![502 branch zencache](https://cloud.githubusercontent.com/assets/13220018/9104123/5465552a-3c3a-11e5-86a3-a054bebc312b.png)

**Comment by jaswrks** [comment]
@raamdev writes...

> I just realized that it would be nice to show both the installed version number and the 'latest' version number, if different. This could also show something like "Upgrade now" if there's a newer version.

Here is the endpoint URL to acquire the latest pro version:
http://zencache.com/?product_api[action]=latest_pro_version

``` json
{"pro_version":150716}
```

_A JSON object is returned by this API with the `pro_version` property._

**Comment by raamdev** [comment]
@renzms Cool! It's looking better. :-) Here's some feedback on design and how I feel the various states should affect the text:

_Note that I included the CSS style attributes in-line only for demonstration purposes; those styles should, of course, be moved to the appropriate place._

---

# ZenCache Pro (latest version)

![2015-08-07_14-20-47](https://cloud.githubusercontent.com/assets/53005/9142711/82e2cdbc-3d0f-11e5-90c2-434a2c73c709.png)

``` html
<div class="plugin-menu-page-version" style="
    float: right;
    clear: right;
    min-width: 350px;
    margin: 0.5em 0 0 0;
    text-align: center;
"><span>ZenCache™ Pro v150722 (<a href="https://zencache.com/changelog/">changelog</a>)</span></div>
```

# ZenCache Pro (update available)

![2015-08-07_14-22-58](https://cloud.githubusercontent.com/assets/53005/9142765/cddaa02e-3d0f-11e5-955b-2a62311a320e.png)

``` html
<div class="plugin-menu-page-version" style="
    float: right;
    clear: right;
    min-width: 350px;
    margin: 0.5em 0 0 0;
    text-align: center;
"><span>ZenCache™ Pro v150722 (<strong><a href="?page=zencache-pro-updater">update available!</a></strong>)</span></div>
```

# ZenCache Lite (latest version)

![2015-08-07_14-15-21](https://cloud.githubusercontent.com/assets/53005/9142600/c28aba5c-3d0e-11e5-925a-e26973df4204.png)

``` html
<div class="plugin-menu-page-version" style="
    float: right;
    clear: right;
    min-width: 350px;
    margin: 0.5em 0 0 0;
    text-align: center;
"><span>ZenCache™ Lite v150722 (<a href="http://zencache.com/changelog-lite/">changelog</a>)</span></div>
```

# ZenCache Lite (update available)

![2015-08-07_14-17-46](https://cloud.githubusercontent.com/assets/53005/9142640/17880190-3d0f-11e5-848a-bbd4cb82e16b.png)

``` html
<div class="plugin-menu-page-version" style="
    float: right;
    clear: right;
    min-width: 350px;
    margin: 0.5em 0 0 0;
    text-align: center;
"><span>ZenCache™ Lite v150722 (<strong><a href="https://wordpress.org/plugins/zencache/changelog/">update available!</a></strong>)</span></div>
```

**Comment by raamdev** [comment]
@renzms For the Pro version, when there's an update available, note that you should build the link to the Pro Updater page like this (see [this line](https://github.com/websharks/zencache-pro/blob/150716/src/includes/classes/MenuPageOptions.php#L48) from the Pro version):

``` php
esc_attr(add_query_arg(urlencode_deep(array('page' => GLOBAL_NS.'-pro-updater')), self_admin_url('/admin.php')))
```

**Comment by raamdev** [comment]
@renzms FYI, I just noticed that it looks like you accidentally committed something to the `000000-dev` branch (instead of to your feature branch) way back when you started this:

![2015-08-08_11-15-55](https://cloud.githubusercontent.com/assets/53005/9150951/0365f608-3dbf-11e5-948a-df9c4cb5ebc6.png)

I reverted the commit (https://github.com/websharks/zencache-pro/commit/a38fac0c79548a4a866491791ab6f1d97cdf7a33) and will merge changes from this PR instead when it's ready.

Please make sure that you're only committing work to your feature branch and not to `000000-dev`.

**Comment by renzms** [comment]
@raamdev Thanks for heads up, I apologize for that one, I think that one slipped in when I was first starting on it, and as you said, even with errors it could publish without warning to the 00000 Branch. Won't happen again, been using git status 3 times before I push anything, then I just check once more.

:+1:  Measure twice, cut once.

**Comment by renzms** [comment]
@raamdev 
![502 branch zencache2](https://cloud.githubusercontent.com/assets/13220018/9158879/ece4e2b6-3f50-11e5-8331-1bba89dc2114.png)

Both the changelog and the update seem to be showing, how do I make it either/or?

Also, is it redundant to have the Update Available Link show up on the Updater Page?

**Comment by renzms** [comment]
Also, after I polish up the pro - version changes, I'm assuming I will need to open a new branch for the lite version here - https://github.com/websharks/zencache/branches to commit the lite - version changes of #502?

**Comment by raamdev** [comment]
> Won't happen again,
> Measure twice, cut once.

Cool. No worries. :-) 

---

I noticed in the screenshot it says `V 150722`; it should say `v150722`.

---

> Also, is it redundant to have the Update Available Link show up on the Updater Page?

No, I think it's fine there. The "Update Available" link is more about indicating to a site owner that an update is, in fact, available, which you cannot tell by the Updater Page alone. So I'd say it's fine to leave that there, even on the Updater Page.

---

> Both the changelog and the update seem to be showing, how do I make it either/or?

Jason mentioned [earlier](https://github.com/websharks/zencache/issues/502#issuecomment-128766274) that the latest Pro version could be pulled like this:

> Here is the endpoint URL to acquire the latest pro version:
> http://zencache.com/?product_api[action]=latest_pro_version
> 
> ```
> {"pro_version":150716}
> ```
> 
> A JSON object is returned by this API with the `pro_version` property.

@jaswsinc Do you by any chance have any code examples for @renzms to look at where you're already using this endpoint?

@jaswsinc Regarding getting the latest Lite version number: Any thoughts on how to best do that? Maybe the answer to that question will depend on the work we still need to do in https://github.com/websharks/zencache.com/issues/61?

---

> Also, after I polish up the pro - version changes, I'm assuming I will need to open a new branch for the lite version here - https://github.com/websharks/zencache/branches to commit the lite - version changes of #502?

Correct. You'll follow the same procedure as you did for creating a `feature/502` branch for the ZenCache Pro repo; simply create the same branch for the ZenCache Lite (i.e., `websharks/zencache/`) repo, make your changes, push, then open a Pull Request for review.

_Keep in mind the ZenCache Lite codebase looks quite different from the ZenCache Pro codebase, which was recently restructured._

**Comment by raamdev** [comment]
@jaswsinc Ping ↑

**Comment by jaswrks** [comment]
> @jaswsinc Do you by any chance have any code examples for @renzms to look at where you're already using this endpoint?

I updated this routine recently, which already does a periodic check for the latest Pro version.

See: https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/closures/Plugin/UpdateUtils.php#L32-L34

So now that this is in place, you can simply print the latest pro version with:

``` php
echo $this->plugin->options['latest_pro_version'];
```

**Comment by jaswrks** [comment]
> @jaswsinc Regarding getting the latest Lite version number: Any thoughts on how to best do that? Maybe the answer to that question will depend on the work we still need to do in websharks/zencache.com#61?

Right. I suspect we can use this API. It's intended for stats, but it also gives us the version.
https://api.wordpress.org/stats/plugin/1.0/zencache

**Comment by jaswrks** [comment]
See also, full list of WordPress APIs:
https://codex.wordpress.org/WordPress.org_API

**Comment by renzms** [comment]
@jaswsinc 

Hi I tried using  `echo $this->plugin->options['latest_pro_version'];`  but it didn't seem to show up.

I noticed though in the update prompt that shows up on the notifications bar is an already working sample of what I want to happen:

![plugin options renz s test area wordpress](https://cloud.githubusercontent.com/assets/13220018/9432320/d98365e0-4a53-11e5-92c2-952ee513ee9a.jpg)

What is the code that is being used there in the prompt? I want to use that and edit it, as it only shows when an update is available, and shows the latest version number which is exactly what I need.

Thanks!

**Comment by jaswrks** [comment]
> Hi I tried using echo $this->plugin->options['latest_pro_version']; but it didn't seem to show up.

Have you done a pull recently, just to be sure that you're testing and working w/ the latest dev branch?

---

## Instructions

### Commit your changes thus far...

``` bash
$ cd ~/projects/websharks/zencache-pro
$ git checkout feature/502
$ git add --all && git commit -m 'Changes thus far. See: websharks/zencache-pro#502'
```

### Now... pull the latest changes to the dev branch.

``` bash
$ git checkout 000000-dev
$ git pull
```

### Merge the latest changes into your feature branch.

``` bash
$ git checkout feature/502
$ git merge 000000-dev
```

---

Now test `echo $this->plugin->options['latest_pro_version'];`

---

> What is the code that is being used there in the prompt?

https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/closures/Plugin/UpdateUtils.php#L32-L34

**Comment by renzms** [comment]
@jaswsinc 

Thanks, yeah I don't think I merged the latest update.

**Comment by renzms** [comment]
@jaswsinc 
![screen](https://cloud.githubusercontent.com/assets/13220018/9484222/0336b8fe-4bdc-11e5-915c-cbd9be13816a.png)

The merging failed, do I need to git pull `origin/feature/502' also? I was able to pull from`000000-dev'

Do I do the ff. next?

```
$ git checkout origin/feature/502
$ git pull

$ git checkout feature/502
$git merge 000000-dev
```

**Comment by jaswrks** [comment]
@renzms I see. So you had some merge conflicts there. Well, there have been quite a few changes since you began work on this, so that explains the merge conflicts. Nothing you did wrong, it's just that there has been a large chunk of time between when you began this, and where we are with the codebase right now. I could walk you through how to deal with merge conflicts, but that would be futile; because the CSS files in ZenCache have since been converted to SCSS files.

### Here's what I suggest...
- Save a backup of your current: `~/projects/websharks/zencache-pro` directory somewhere. Maybe call it `~/projects/websharks/old-zencache-pro`
- Start over by cloning a fresh copy of the repo.
  
  ``` bash
  $ git clone https://github.com/websharks/zencache-pro ~/projects/websharks/zencache-pro
  ```
- Instead of working w/ the `000000-dev` branch, which is outdated itself at the moment, because there are quite a few pending pull requests that Raam needs to review and merge. I suggest that you work from the most up-to-date branch that exists right now, which is `feature/347`.
  
  ``` bash
  $ cd ~/projects/websharks/zencache-pro
  $ git checkout feature/347 # You want to be on this branch whenever you run the next command. That way your feature branch is based on this branch.
  ```
- Now, start a few feature branch for this issue—for your second attempt.
  
  ``` bash
  $ git checkout -b feature/502-2nd-attempt
  ```
- Work to repeat your changes in this new attempt. Perhaps review `~/projects/websharks/old-zencache-pro` to reference those changes in your first attempt.
- Note that all of the ZenCache CSS files were converted to SCSS imports during recent improvements, so hit me on Slack and I'll walk you through how to work with these now. Referencing: https://github.com/websharks/zencache-pro/tree/feature/347/src/client-s/css
- When you're ready to submit your 2nd attempt for review.
  
  ``` bash
  $ cd ~/projects/websharks/zencache-pro
  $ git add --all && git commit -m 'My second attempt; see: websharks/zencache#502'
  $ git push -u origin feature/502-2nd-attempt
  ```

---

Noting that...
- Renz will need a walkthrough of the most recent SCSS file structure.
- Renz will need to install Sass command-line tools so he can compile the CSS files.

**Comment by jaswrks** [comment]
> Renz will need to install Sass command-line tools so he can compile the CSS files.

You can get a jump-start on this by installing Ruby.
See: http://rubyinstaller.org/

**Comment by renzms** [comment]
> You can get a jump-start on this by installing Ruby.
> See: http://rubyinstaller.org/

Ok, I've installed Ruby 2.1.6

**Comment by jaswrks** [comment]
> Ok, I've installed Ruby 2.1.6

Cool. Nice!

When you run the installer, be sure to check this box.

![2015-08-26_12-23-33](https://cloud.githubusercontent.com/assets/1563559/9505168/4e491da8-4bed-11e5-90e2-bace7ab163dd.png)

---

After Ruby is installed, open your command prompt; i.e., Git Bash and type:

```
$ gem install sass
```

**Comment by renzms** [comment]
> After Ruby is installed, open your command prompt; i.e., Git Bash and type:
> 
> $ gem install sass

Done installing sass, I've added the old changes to the cloned repo in: feature/502-2nd-attempt, except for the SCSS (menu-pages.scss) I'll await your next instructions/walkthrough regarding that one before I try anything with it.

**Comment by jaswrks** [comment]
Great! :-)

Now, you can add any custom CSS needed to display the version number in [this file](https://github.com/websharks/zencache-pro/blob/feature/347/src/client-s/css/menu-pages/_heading.scss).

## Recompiling the `menu-pages.min.css` file.
- From the command line, type:
  
  ``` bash
  $ cd ~/projects/websharks/zencache-pro/src/client-s/css
  $ sass --watch menu-pages.scss:menu-pages.min.css --style=compressed
  ```

This will do two things:
- It will immediately recompile `menu-pages.min.css` for you, so that you may test your changes.
- It "watches" the SCSS files associated with `menu-pages.scss` also. So that if you make any additional tweaks to the `*.scss` files (e.g., `_header.scss`), the `menu-pages.min.css` file is automatically recompiled whenever you save those changes.

When you're all done making changes, go back to the command line and type `Ctrl-C` to stop watching and terminate the Sass process.

**Comment by jaswrks** [comment]
Reference, if you'd like to learn more about Sass. We use the SCSS syntax:
http://sass-lang.com/

Note that SCSS supports regular CSS too, so you don't need to learn a new language. You can simply write CSS as you normally would do. The benefit is that SCSS supports many additional features that make it much more powerful and easier for us to stay organized.

**Comment by jaswrks** [comment]
> Start over by cloning a fresh copy of the repo.

I just realized that I left out the `$ composer install` step there. Be sure to run `composer install` in your newly cloned copy of the repo before you begin work on the CSS files, as the Composer installer resolves some other dependencies on your system.

You can reference my original instructions and use the the "Satisfy Dependencies" step to refresh yourself, just in case you forgot about this. See: https://github.com/websharks/zencache/issues/502#issuecomment-125992973

**Comment by renzms** [comment]
@jaswsinc: Hi Jason,  trying to test but I think the latest version installed on my test site is ZenCache v150821, so the files are still different especially regarding the CSS folder. It's not compiled yet. I tried overwriting with my cloned repo, but it just crashed.

Would I need to install `feature/347` files onto my test site? Or should I wait for a public release to test on? As a lot has changed since I started this and got back to it.

For MenuPageOptions.php I'm using:

```
    echo '<div class="plugin-menu-page-version">'.
            '  <small><span>'.sprintf(__('%1$s&trade; v'), esc_html(NAME)).'</span></small>'.
             ''.esc_html(VERSION).
            '   <a href="'.esc_attr('https://zencache.com/changelog/').'" target="_blank"> '.__('(changelog)').'</a>.'.
            ''   .$this->plugin->options['latest_pro_version'].
            '</div>'."\n";
```

But getting the following warnings:

```
Warning: Missing argument 2 for WebSharks\ZenCache\Pro\__(), called in /home4/wsksdev/public_html/renz/wp-content/plugins/zencache-pro/src/includes/classes/MenuPageOptions.php on line 58 and defined in /home4/wsksdev/public_html/renz/wp-content/plugins/zencache-pro/src/includes/functions/i18n-utils.php on line 14

Warning: Missing argument 2 for WebSharks\ZenCache\Pro\__(), called in /home4/wsksdev/public_html/renz/wp-content/plugins/zencache-pro/src/includes/classes/MenuPageOptions.php on line 60 and defined in /home4/wsksdev/public_html/renz/wp-content/plugins/zencache-pro/src/includes/functions/i18n-utils.php on line 14
```

![plugin options renz s test area wordpress 1](https://cloud.githubusercontent.com/assets/13220018/9523054/bf463c70-4d0a-11e5-9a95-76bcbe188b33.jpg)

**Comment by jaswrks** [comment]
> Would I need to install feature/347 files onto my test site?

Yeah. Just be sure that you remove the entire old plugin directory and replace it with the newly cloned repo that you have, which is based on `feature/347`.
- Delete: `/wp-content/plugins/zencache-pro`
- Upload: `~/projects/websharks/zencache-pro` to `/wp-content/plugins/zencache-pro`

> Missing argument 2 for WebSharks\ZenCache\Pro__(),

That error will continue though, even once you get up-to-date on your test site. For the second argument you can use `SLUG_TD`; e.g., `__('some text to translate', SLUG_TD)`

**Comment by renzms** [comment]
@jaswsinc Thanks Jason! Was trying to wrap my head around it ( I even thought my ftp upload of the code had failed) and then realized you guys must have really changed A LOT of code since then!

**Comment by renzms** [comment]
@jaswsinc  Hi Jason, it works now. Thanks for the assists. Is this ready for a push? Also, do I follow the same steps now for the Lite Version? And which branch do I start from for the Lite Version?

![plugin options renz s test area wordpress 2](https://cloud.githubusercontent.com/assets/13220018/9524104/babcc1d8-4d0f-11e5-8522-5f59f46e3700.jpg)

**Comment by jaswrks** [comment]
> Thanks for the assists. Is this ready for a push?

Cool. Definitely. Go ahead and do the push and then Raam and I can help by reviewing the code itself in your most recent work on this. Be sure that you are pushing `feature/502-2nd-attempt`.

``` bash
$ cd ~/projects/websharks/zencache-pro
$ git checkout feature/502-2nd-attempt # Make sure that you're on your branch.
$ git add --all && git commit -m 'My second attempt at websharks/zencache#502'
$ git push -u origin feature/502-2nd-attempt
```

**Comment by jaswrks** [comment]
> Also, do I follow the same steps now for the Lite Version?

The `websharks/zencache-pro` repo is actually the basis for the lite version; i.e., it is used to build the lite variation automatically. So we don't have the dual commits/PRs all the time like we have with Comment Mail and s2Member.

However, I'll let @raamdev  answer this, because there _is_ still an older copy of ZenCache Lite that we are maintaining over the short-term. I suspect this is not going to go into that older version though.

**Comment by raamdev** [comment]
> I suspect this is not going to go into that older version though.

@jaswsinc @renzms Correct. There's nothing to do for the Lite version in this case.

**Comment by renzms** [comment]
@raamdev @jaswsinc 

Hi, pushed for review: https://github.com/websharks/zencache-pro/tree/feature/502-2nd-attempt

Thanks!

**Comment by jaswrks** [comment]
Thanks! :-)

Some changes are needed in order to accomplish what [@raamdev wanted in this request](https://github.com/websharks/zencache/issues/502#issuecomment-128787903).
1. There needs to be logic that displays either `(changelog)` or `(update available)`, based on the current version they are running and the latest available version. See: https://github.com/websharks/zencache/issues/502#issuecomment-128787903
2. There needs to be logic that deals with either the pro version, or the lite version; depending upon which version of the plugin is being used. I think there is probably some confusion about this at the moment, because you asked us before about there being a lite version update needed here, and we said no. However, that was a little misleading. While there's no separate PR needed for the lite version, we _do_ need to consider the lite version here too, in order to accomplish what Raam wants.
   
   _Let's come back to this once we accomplish point 1 though. It's going to be easy :-)_

---

### On point 1 above. Instead of:

``` php
echo '<div class="plugin-menu-page-version">'.
             '  <small><span>'.sprintf(__('%1$s&trade; v', SLUG_TD), esc_html(NAME)).'</span></small>'.
             ''.esc_html(VERSION).
             '   <a href="'.esc_attr('https://zencache.com/changelog/').'" target="_blank"> '.__('(changelog)', SLUG_TD).'</a>.'.
             '  <a href="'.esc_attr(add_query_arg(urlencode_deep(array('page' => GLOBAL_NS.'-pro-updater')), self_admin_url('/admin.php'))).'" target="_blank"> '.__('Latest Pro v', SLUG_TD).'</a>'.
             ''  .$this->plugin->options['latest_pro_version'].
            '</div>'."\n";
```

#### You want something like this:

``` php
echo '<div class="plugin-menu-page-version">'."\n";
echo '  '.sprintf(__('%1$s&trade; v%2$s', SLUG_TD), esc_html(NAME), esc_html(VERSION))."\n";

if ($this->plugin->options['latest_pro_version'] && version_compare(VERSION, $this->plugin->options['latest_pro_version'], '<')) {
    echo '(<a href="'.esc_attr(add_query_arg(urlencode_deep(array('page' => GLOBAL_NS.'-pro-updater')), self_admin_url('/admin.php'))).'" style="font-weight:bold;">'.__('update available', SLUG_TD).'</a>)'."\n";
} else {
    echo '(<a href="'.esc_attr('https://zencache.com/changelog/').'" target="_blank">'.__('changelog', SLUG_TD).'</a>)'."\n";
}

echo '</div>'."\n";
```

#### In the above code, I made the following changes that @renzms can review:
- No need to separate `esc_html(VERSION)` from the translation string. You can use the `sprintf()` function to build the `ZenCache™ v[version]` string in one shot. See also: http://php.net/manual/en/function.sprintf.php
  
  ``` php
  echo '  '.sprintf(__('%1$s&trade; v%2$s', SLUG_TD), esc_html(NAME), esc_html(VERSION))."\n";
  ```
  - `%1$s` is replaced with `esc_html(NAME)`
  - `%2$s` is replaced with `esc_html(VERSION)`

---
- Instead of displaying both the current version and the latest version together at the same time, which may lead to confusion, I added some logic that accomplishes what Raam [noted here](https://github.com/websharks/zencache/issues/502#issuecomment-128787903).
  
  ``` php
  if ($this->plugin->options['latest_pro_version'] && version_compare(VERSION, $this->plugin->options['latest_pro_version'], '<')) {
      echo '(<a href="'.esc_attr(add_query_arg(urlencode_deep(array('page' => GLOBAL_NS.'-pro-updater')), self_admin_url('/admin.php'))).'" style="font-weight:bold;">'.__('update available', SLUG_TD).'</a>)'."\n";
  } else {
      echo '(<a href="'.esc_attr('https://zencache.com/changelog/').'" target="_blank">'.__('changelog', SLUG_TD).'</a>)'."\n";
  }
  ```
  - If their current version is less than the latest pro version available, display **(update available)**. See also: http://php.net/manual/en/function.version-compare.php
  - Otherwise, display (changelog)
  - _Note that Raam wants **(update available)** in bold, (changelog) with normal weight._

---

@renzms If you can update to the above snippet, review, and then push those changes, we can take another look at this. Just let me know if you have any questions.

_What comes next is that we need to deal with the lite version, because currently this is dealing only with the pro version. However, let's knock out the pro version logic first, and then we can come back to that later._

**Comment by jaswrks** [comment]
Note: you can push your changes to the same branch if you like.
- Make the changes noted above.
- Then run the following:
  
  ``` bash
  $ cd ~/projects/websharks/zencache-pro
  $ git checkout feature/502-2nd-attempt # Be sure that you're on your branch.
  $ git add --all && git commit -m 'Tweaks suggested by @jaswsinc. See: websharks/zencache#502'
  $ git push # No need for the `-u origin feature/502-2nd-attempt` this time, because you already did this. Now you can simply do a `git push`.
  ```

**Comment by renzms** [comment]
Hi @jaswsinc ,

Added your changes and those that you mentioned about nesting the CSS, I think it failed to push due to my Github configurations, please see Screenshot:

![warning](https://cloud.githubusercontent.com/assets/13220018/9547717/c80a0994-4dce-11e5-8b6a-075706555c7d.png)

**Comment by jaswrks** [comment]
Run `git config --global push.default simple` and then try this again.
What's happening is that Git is trying to push _both_ your feature branch and also the `000000-dev` branch at the same time, and the `000000-dev` branch that you have is just a teeny bit outdated at the moment. However, even if it were completely up-to-date, we want to avoid you pushing to the `000000-dev` or `master` branches. We can accomplish this by running `git config --global push.default simple`, so that only the current branch is pushed; exactly what you want.

_Note to self... always include `git config --global push.default simple` in my Git setup instructions in the future :-)_

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: The installed plugin version is now shown at the top of the ZenCache Options Panel. When a newer version of the plugin is available, an "update available" link appears. Props @renzms. See [Issue #502](https://github.com/websharks/zencache/issues/502).

**Comment by raamdev** [comment]
@renzms @jaswsinc I noticed the new version number is missing from the Stats/Charts page:

![2015-09-03_18-56-30](https://cloud.githubusercontent.com/assets/53005/9672987/98478652-526d-11e5-8db6-045b88332bd0.png)

**Comment by jaswrks** [comment]
## Next Actions
- New Feature Branch
  
  ``` bash
  $ cd ~/projects/websharks/zencache-pro
  $ git checkout 000000-dev # Start from the dev branch.
  $ git pull # Make sure you are working from the most up-to-date copy.
  # ↑ Note: if you get any warnings about there being merge conflicts, please contact Jason/Raam.
  $ git checkout -b feature/502-stats-page # New feature branch, based on dev branch.
  ```
- After [this line in `MenuPageStats.php`](https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/classes/MenuPageStats.php#L35), add the following:
  
  ``` php
  if (IS_PRO) {
      echo '<div class="plugin-menu-page-version">'."\n";
      echo '  '.sprintf(__('%1$s&trade; Pro v%2$s', SLUG_TD), esc_html(NAME), esc_html(VERSION))."\n";
  
      if ($this->plugin->options['latest_pro_version'] && version_compare(VERSION, $this->plugin->options['latest_pro_version'], '<')) {
          echo '(<a href="'.esc_attr(add_query_arg(urlencode_deep(array('page' => GLOBAL_NS.'-pro-updater')), self_admin_url('/admin.php'))).'" style="font-weight:bold;">'.__('update available', SLUG_TD).'</a>)'."\n";
      } else {
          echo '(<a href="'.esc_attr('https://zencache.com/changelog/').'" target="_blank">'.__('changelog', SLUG_TD).'</a>)'."\n";
      }
  
      echo '</div>'."\n";
  }
  ```
- Commit changes and push.
  
  ``` bash
  $ cd ~/projects/websharks/zencache-pro
  $ git add --all && git commit -m 'Show version on stats page. See: websharks/zencache#502'
  $ git push -u origin feature/502-stats-page
  ```
- Open a Pull Request from [this page at GitHub](https://github.com/websharks/zencache-pro/branches).

**Comment by raamdev** [comment]
During v150919-RC testing, I noticed that the version number on the option pages is misaligned on some of the pages. On Plugin Options it looks fine centered, but on Cache Stats and Plugin Updater it looks very odd centered and should instead be right-aligned.

## Plugin Options

![2015-09-18_20-54-05](https://cloud.githubusercontent.com/assets/53005/9973820/c6764654-5e47-11e5-84f5-5f2804cb835b.png)

## Cache Stats

![2015-09-18_20-54-19](https://cloud.githubusercontent.com/assets/53005/9973814/c4a1fd78-5e47-11e5-882c-06675f2d1c3b.png)

## Plugin Updater

![2015-09-18_20-54-30](https://cloud.githubusercontent.com/assets/53005/9973813/c2620b3e-5e47-11e5-825b-629cd657c649.png)

---

In fact, if we simply right-align it on all of the pages, that will work too. Here's what it looks like right-aligned on the Plugin Options page:

![2015-09-18_20-59-17](https://cloud.githubusercontent.com/assets/53005/9973836/26b363a8-5e48-11e5-8c3e-6ffe73490916.png)

---

The bit of CSS that needs to be changed is:

``` css
.plugin-menu-page-heading .plugin-menu-page-version { text-align: center; }
```

should be:

``` css
.plugin-menu-page-heading .plugin-menu-page-version { text-align: right; }
```

**Comment by renzms** [comment]
![plugin options renz s test area wordpress 3](https://cloud.githubusercontent.com/assets/13220018/10038621/b2334604-61fa-11e5-81d2-aab48a1f6194.jpg)

@raamdev  I used `$ git checkout 000000-dev` to get the updated copy

version showing is v150821, should I have used v150919-RC as the base?

Created new Branch:  [feature/502-styling-update](https://github.com/websharks/zencache-pro/tree/feature/502-styling-update)

Haven't submitted a pull request yet.

**Comment by raamdev** [comment]
@renzms I merged your `feature/502-styling-update` branch into the `release/150919` branch and the `000000-dev` branch. No need to submit a PR. Thanks! :-)

**Comment by renzms** [comment]
@raamdev Alright, cool! Thanks.

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [ZenCache Pro v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#502).

**Comment by raamdev** [comment]
@jaswsinc writes in https://github.com/websharks/zencache/issues/502#issuecomment-135763648...

> What comes next is that we need to deal with the lite version, because currently this is dealing only with the pro version. However, let's knock out the pro version logic first, and then we can come back to that later.

Reviewing this issue and the related PRs (https://github.com/websharks/zencache-pro/pull/144 and https://github.com/websharks/zencache-pro/pull/136) I see that the Lite version was never addressed, i.e., when we generate a Lite version from the Pro codebase, this enhancement (showing the version number and detecting when there's a new version available) will not be available.

The next Lite release (slated for early December) will be generated from the Pro codebase and I'd like to at least have the installed version showing in Options panel for the Lite version. I'm not so concerned about detecting when an update is available for the Lite version since WordPress already has its own built-in update notification system. I would, however, like to have the "changelog" link in there (linking to http://zencache.com/changelog-lite/ for the Lite version).

cc @renzms

**Comment by jaswrks** [comment]
@raamdev I added support for this. Please review: https://github.com/websharks/zencache-pro/pull/186
