### ISSUE TITLE
Access ZenCache settings from the Plugins List

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#503]
There should be a Settings link in the Plugins list to access the ZenCache Plugin Options.

![2015-06-11_21-35-20](https://cloud.githubusercontent.com/assets/53005/8122013/ec608ff0-1081-11e5-9144-78d2bedbb4d4.png)

This already exists in the Lite version of ZenCache (it's just missing from the Pro version):

![2015-06-11_21-36-48](https://cloud.githubusercontent.com/assets/53005/8122024/19707a14-1082-11e5-8e51-7379bf885ba3.png)

**Comment by jaswrks** [comment]
I was unable to reproduce this in the development branch. Seems like it might already be resolved.

![2015-06-17_14-02-13](https://cloud.githubusercontent.com/assets/1563559/8219862/91f32aec-14f9-11e5-9a25-5f7414144e10.png)

Referencing private code: https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/closures/Plugin/MenuPageUtils.php#L93

**Comment by raamdev** [comment]
@j

**Comment by raamdev** [comment]
@jaswsinc I have verified this across two separate WordPress installations, both running the latest ZenCache RC (v150605). Did you test the latest RC?

**Comment by jaswrks** [comment]
> Did you test the latest RC?

Yes. I was unable to reproduce. However, I see that if you upload the RC ZIP file straight into WordPress and let it unzip that way, the folder structure is unexpected, as you reported last week. This seems to break the `plugin->file` property and it results in the list of plugin links not working in that scenario.

In short, I was able to reproduce this, but only if the plugin directory name follows a ZIP file name.

**Comment by raamdev** [comment]
> the folder structure is unexpected

Ah, ha! That explains it. :-) Thanks for confirming that. I'll close this as invalid, as it's not really a bug but something related to the build process that we already have an open issue for (https://github.com/websharks/phings/issues/5).
