### ISSUE TITLE
Improve HTML Notes messaging when s2Member installed

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#504]
When s2Member is installed, pages that contain Pro-Forms set the `ZENCACHE_ALLOWED` constant to `FALSE`, thereby disabling caching for that particular page. 

![2015-06-11_21-43-21](https://cloud.githubusercontent.com/assets/53005/8122077/e64a7c88-1082-11e5-8f40-d6ab52270b34.png)

When it's s2Member disabling caching, we should do more to explain _why_ caching has been disabled on that particular page, i.e., because s2Member is loading some dynamic content.

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch: `feature/504` in the `websharks/zencache-pro` repo.
- Replace [these lines of code](https://github.com/websharks/zencache-pro/blob/151004/src/includes/closures/Ac/NcDebugUtils.php#L86-L88) with the following:
  
  ``` php
  case NC_DEBUG_ZENCACHE_ALLOWED_CONSTANT:
      if ($self->functionIsPossible('did_action') && did_action('ws_plugin__s2member_during_no_cache_constants')) {
          $reason = __('because the s2Member plugin set the PHP constant `ZENCACHE_ALLOWED` to a boolean-ish `FALSE` value at runtime. The s2Member plugin is serving content that must remain dynamic on this particular page, and therefore this page was intentionally not cached for a very good reason.', SLUG_TD);
      } else {
          $reason = __('because the PHP constant `ZENCACHE_ALLOWED` has been set to a boolean-ish `FALSE` value at runtime. Perhaps by WordPress itself, or by one of your themes/plugins. This usually means that you have a theme/plugin intentionally disabling the cache on this page; and it\'s usually for a very good reason.', SLUG_TD);
      }
      break; // Break switch handler.
  ```
- Submit PR.

**Comment by jaswrks** [comment]
@renzms While working on this issue you can learn more about the `did_action()` function in the WordPress core here: https://codex.wordpress.org/Function_Reference/did_action

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: Improved the HTML Notes generated by ZenCache when s2Member (a membership plugin for WordPress) is specifically disabling caching. s2Member automatically disables caching on certain pages that are required to remain dynamic. The HTML Notes generated by ZenCache now explain when this is happening. Props @renzms. See [Issue #504](https://github.com/websharks/zencache/issues/504).

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#504).
