### ISSUE TITLE
Refactor codebase with new method for determining hostname 

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#505]
@jaswsinc writes...

> There are actually a few places where we use `$_SERVER['HTTP_HOST']`. As of now, that needs to change I think, overall.
> https://github.com/websharks/zencache-pro/search?utf8=%E2%9C%93&q=%24_SERVER%5B%27HTTP_HOST%27%5D
> 
> It would be nice to have a new method that deals with working out what domain should be used.
> 
> I see us needing a new file in this folder called `HostUtils.php`
> https://github.com/websharks/zencache-pro/tree/6e6d2f7d8a4c992dd61a4ed59d3dc326cc829692/src/includes/closures/Shared
> 
> Inside `HostUtils.php`, we could create a new method that might be named something like:
> 
> ``` php
> $self->httpHost = function($consider_domain_mapping = true) use ($self) {
>     // That code snippet could go here, and we might need some additional logic and perhaps a function parameter or two. e.g., $consider_domain_mapping
> };
> ```
> 
> With that in place, we can start updating the rest of the codebase, replacing references to `$_SERVER['HTTP_HOST']` with calls to this method. 

Forked from https://github.com/websharks/zencache/issues/339#issuecomment-111577197

**Comment by jaswrks** [comment]
@raamdev Are you still planning to work on this or do you want me to take it?

**Comment by raamdev** [comment]
@jaswsinc You can take it if you'd like. Thanks!

**Comment by jaswrks** [comment]
Referencing: https://github.com/websharks/zencache/issues/339#issuecomment-111577197

**Comment by raamdev** [comment]
Closed by PR https://github.com/websharks/zencache-pro/pull/125. See related changelog entry: https://github.com/websharks/zencache/issues/339#issuecomment-130113419
