### ISSUE TITLE
Cache is not cleared when s2Member Pro is updated

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#508]
When the s2Member Pro module is updated, ZenCache does not catch this and trigger a clearing of the cache as it does with other WordPress plugin updates.

**Comment by raamdev** [comment]
This may actually be an s2Member Pro issue and not an issue with ZenCache. 

@jaswsinc any thoughts here?

**Comment by jaswrks** [comment]
I agree. It's an s2Member issue. I'm opening: https://github.com/websharks/s2member/issues/668

**Comment by raamdev** [comment]
@jaswsinc Copy that. Thanks! I'm closing this GitHub Issue since there's nothing to be done here for ZenCache.
