### ISSUE TITLE
Back Compat. Issues in RC Copy

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#510]
@raamdev I just received your note regarding a private ticket:
https://websharks.zendesk.com/agent/tickets/6844

In this ticket, a call to `$GLOBALS['zencache']->auto_clear_post_cache()` is being made by another plugin that expects this method to exist. This method does not exist in the restructed copy, so we should add back compat. for this (and some others) before a release is done.

Mentioned here: http://zencache.com/kb-article/clearing-the-cache-dynamically/
This article should be updated, but all of these methods need to exist in the restructed copy of ZenCache, because we have already stated they are OK to use.

---

**Idea:** In the future, we should try to avoid publishing details that call upon internal methods, and instead create API functions that we can maintain. See: https://github.com/websharks/zencache/blob/000000-dev/src/includes/classes/ApiBase.php

_These are the methods that we currently maintain for back compat. from one version to the next. We need to add a few new API calls in support of the methods used in the aforementioned KB article._

**Comment by raamdev** [comment]
@jaswsinc Thanks for catching this and opening a GitHub issue! I'm glad we caught this before the release, which I'm hoping to get out today.

If you have some time today to help me fix this, that would be great.

---

> Idea: In the future, we should try to avoid publishing details that call upon internal methods, and instead create API functions that we can maintain. See: https://github.com/websharks/zencache/blob/000000-dev/src/includes/classes/ApiBase.php

Agreed.

**Comment by jaswrks** [comment]
PR ready for review: https://github.com/websharks/zencache-pro/pull/117

**Comment by raamdev** [comment]
@jaswsinc Thanks so much for taking care of this! :-)
