### ISSUE TITLE
PHP Fatal error: Base lambda function for closure not found

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#511]
We've had several reports of ZenCache v160626 causing blank pages on sites, and some reporting the following error (this error is likely what's causing the 'blank pages', which occurs when a site does not have [`WP_DEBUG` enabled](https://codex.wordpress.org/Debugging_in_WordPress)):

> PHP Fatal error: Base lambda function for closure not found in /home/example/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php on line 15

This PHP Bug report appears to indicate known issues with using lambda functions on systems running APC Cache and it appears that as of today the issue still has not been fixed: https://bugs.php.net/bug.php?id=52144

---
## Steps to reproduce this bug
1. Install PHP v5.3.20 with APC Cache enabled
2. Install and Activate ZenCache v150626 (either Lite or Pro)
3. Visit the ZenCache plugin options (sometimes it takes one or two page changes before the error appears, but it's consistent within 1-2 page changes).
### Expected behavior

ZenCache activates.
### Observed behavior

Fatal Error:

> Fatal error: Base lambda function for closure not found in /Users/raam/Sites/zcpro.dev/wordpress/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheLockUtils.php on line 19

---
### Site Owners: If you're experiencing this issue:

We're still investigating this issue and will provide further updates below. While we're working on a fix issue, you can downgrade to the previous version of ZenCache ([Lite v150409](https://downloads.wordpress.org/plugin/zencache.150409.zip) | [Pro v150409](http://zencache.com/?s2member_file_download=ccaps%2Faccess-s2member-ccap-pro%2Fzencache-pro-v150409.zip)). Simply uninstall the current version of ZenCache and then you can install the previous version (see also: [How do I uninstall ZenCache?](http://zencache.com/kb-article/how-do-i-uninstall-zencache/)).

Or you can implement [this short-term workaround described below](https://github.com/websharks/zencache/issues/511#issuecomment-118181282).

---
#### Support threads referencing this issue
- https://websharks.zendesk.com/agent/tickets/6977
- https://websharks.zendesk.com/agent/tickets/6984
- https://websharks.zendesk.com/agent/tickets/6981
- https://websharks.zendesk.com/agent/tickets/6993
- https://websharks.zendesk.com/agent/tickets/6990
- https://websharks.zendesk.com/agent/tickets/7003
- https://wordpress.org/support/topic/white-background-10
- https://wordpress.org/support/topic/zencache-crashes-site
- https://wordpress.org/support/topic/can-we-get-an-update-on-v150626
- https://github.com/websharks/zencache/issues/515

**Comment by raamdev** [comment]
### <del>PHP v5.4.10 + APC Cache = Working</del>

<del>PHP v5.4.10 + APC Cache is working and does not produce the fatal error, so this would further confirm that what we're seeing is [PHP Bug #52144](https://bugs.php.net/bug.php?id=52144).</del>

**Edit:** This APC bug appears to affect multiple major versions of PHP. See [below](https://github.com/websharks/zencache/issues/511#issuecomment-118181282) for a temporary short-term workaround.

**Comment by raamdev** [comment]
### PHP v5.3.20 + APC Cache = Broken!

Installing ZenCache v150626 on a system running PHP v5.3.20 with the APC Cache extension enabled produces a Fatal Error, as the result of [PHP Bug #52144](https://bugs.php.net/bug.php?id=52144).

### Temporary Workarounds

See [short-term workaround below](https://github.com/websharks/zencache/issues/511#issuecomment-118181282).

**Comment by jaswrks** [comment]
@raamdev Nice work in reproducing this.

So far I have been unable to reproduce this on Ubuntu 12.04 64-bit running PHP v5.3.10 (or v5.3.20), and APC 3.1.7 Revision: 307215. Any other details you can provide about the specific OS and version of APC that you used to reproduce this? Did you build a Vagrant box to test this with? Once I can get it reproduced, debugging may shed light on a workaround for a specific PHP + APC version.

![](https://www.filepicker.io/api/file/5Z4trgGnTzy6BeTIZTFg#.png)

**Comment by raamdev** [comment]
## Workaround

If your server is running the APC Extension, you should disable it. The APC Extension is buggy and has been replaced by the newer Opcache extension (which is enabled by default in PHP 5.5+). The PHP community has stopped developing the APC extension and the last release was way back in 2012, so the best course of action if you're stuck running on PHP 5.3 or PHP 5.4 is to simply disable the extension altogether:
- Open your `/wp-config.php` file.
- At the top, right after `<?php`, on the next line add: `ini_set('apc.cache_by_default', false);`

This will disable APC at runtime and prevent the bug that's throwing the Fatal Error.

If you're unable to disable APC in this way, you'll need to contact your web hosting company to have them upgrade your server to a newer version of PHP (e.g., PHP 5.5+).

**Comment by raamdev** [comment]
## ZenCache Pro Changelog

Pro changelog that resolves this GitHub Issue:
- **Bug Fix**: Fixed a fatal error that was occurring on some sites after upgrading to v150629. We discovered the fatal error was related to PHP's outdated and buggy APC extension, which is often active on sites running PHP 5.3 and PHP 5.4. We now prevent activation of ZenCache on systems with the APC extension enabled and show a warning message instead. We've written [a KB Article that further explains the APC Extension Warning](http://zencache.com/kb-article/why-does-zencache-show-an-apc-extension-warning/) and offers advice to site owners who are currently running APC. See also [Issue #511](https://github.com/websharks/zencache/issues/511).

## ZenCache Lite Changelog

Lite changelog that resolves this GitHub Issue:
- **Bug Fix**: This update reverts the codebase restructure released in the previous version (v150626). That release received several reports of Fatal Errors, however those issues only affected a small subset of ZenCache users. After extensive research, we discovered that this issue was related to a bug in PHP's APC Extension (which is commonly used on systems running PHP 5.3 and PHP 5.4). The restructured codebase in the previous release utilized a newer PHP feature (Closures) and that increased the likelihood of exposing that existing PHP bug. Since we can't fix the PHP bug directly and we want to continue supporting PHP 5.3.2+ and PHP 5.4 for now, we're reverting the ZenCache Lite codebase restructure to the previous version (v150409). The new ZenCache Lite features that were included in the previous release are still available in this release--only the structure of the codebase itself has changed. To read more about the PHP APC bug, see [Issue #511](https://github.com/websharks/zencache/issues/511).

**Comment by raamdev** [comment]
This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#511).
