### ISSUE TITLE
Found detailed info on ac-plugin error in last version ...

### ISSUE THREAD

**Issue by Dams83** [wpsharks/comet-cache#513]
In fact it appears that the load_ac_plugins() function is not written in the advanced-cache.php file from the advanced-cache.tpl.php

In my case the advanced-cache.php file is approximatively 5 ko with the last version but 47 ko with the older version

You should certainly find why the process is blocked ... and why so many data are lost.

I actually re-use the older version because i need to use ac-plugin

**Comment by Dams83** [comment]
In fact it appears that the load_ac_plugins() function is not written in the advanced_cache file from the file advanced_cache_tpl

**Comment by raamdev** [comment]
@Dams83 Thanks so much for the report. We have verified this is a bug and we've patched the current release (v150626), so if you download it again you should get the patched copy.

Please see also this GitHub Issue with further details: https://github.com/websharks/zencache/issues/514
