### ISSUE TITLE
AC Plugin Back Compat. in 150626 Broken

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#514]
First reported here: https://wordpress.org/support/topic/zencache-ac-plugins-not-working-under-v150626?replies=5#post-7123044
## Steps to Reproduce
- Use the [old example AC plugin](https://github.com/websharks/zencache/blob/150409/zencache/includes/ac-plugin.example.php) from ZenCache v150409 to create a test AC plugin.
- Save the file to: `/wp-content/ac-plugins/test.php`
## Expected Behavior
- That the AC plugin test will return `other` as the version salt for non-mobile devices during testing, even though the AC plugin is using the old API calls.
## Observed Behavior
- The old example file has stopped working in the latest release, due to a glitch in the back compat. routines we added in v150626, which incorrectly references the old class name, instead of expecting the new class name.

_This is a tricky issue, because the old example file calls upon `get_class($ac)`. Our attempt to preserve back compat. failed, because we incorrectly preserved support for the old class name, when the old example does in fact reference the new class name when it calls upon `get_class($ac)`, where `$ac` is actually a reference to the new class. Somewhat deceiving at first glance._

---
## Suggested Short-Term Solution

Attach your AC plugin filter using the updated API calls.

``` php
$ac = $GLOBALS['zencache_advanced_cache']; // ZenCache instance.
$ac->addFilter('zencache_version_salt', 'my_ac_version_salt_shaker');
```

See also: [updated example for ZenCache v150626+](https://github.com/websharks/zencache/blob/master/src/includes/templates/ac-plugin.txt)
## Long-Term Solution

We need to fix the back compat. routine so that existing AC plugin files do not continue to break as more and more people upgrade to ZenCache 150626+.

**Comment by jaswrks** [comment]
@raamdev Pull request submitted to resolve the long-term solution suggested above.

**Comment by jaswrks** [comment]
A fix for this issue was pushed to the latest copy of ZenCache and ZenCache Pro v150626 as part of critical revision just now. We will merge this pull request in as a part of the next official release also, but for now the issue has been resolved.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed an issue with backwards compatibility that was preventing some AC Plugins from working properly. See [Issue #514](https://github.com/websharks/zencache/issues/514).

**Comment by raamdev** [comment]
This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#514).
