### ISSUE TITLE
Lite version 150626: Plugin failures after updating

### ISSUE THREAD

**Issue by eclerkin** [wpsharks/comet-cache#515]
I updated my website this morning with ZenCache 150626 and there have been multiple plugin failures with the new settings in ZenCache.  All In One WP Security and Firewall plugin was issuing an error with Google Sitemap and then causing a white page of death.  Here is the error:  Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/public_html/wp-content/plugins/all-in-one-wp-security-and-firewall/classes/wp-security-general-init-tasks.php:18) in /home/public_html/wp-content/plugins/google-sitemap-plugin/google-sitemap-plugin.php on line 49.  I am using PHP 5.4.

I deactivated All In One Security and Google Sitemap (it took awhile for Linux to release the plugins) then disabled the ZenCache option for clearing cache on sitemaps, activated Google Sitemap but it still caused up the white screen of death.  All In One Security is still deactivated. Suggestions?

**Comment by raamdev** [comment]
@eclerkin That's quite odd. It's hard to tell if ZenCache is actually causing those problems or if something else is going on.

Could you try adding the following to the top of your `wp-config.php` file (after the `<?php` line):

```
define('WP_DEBUG', true); //enable the reporting of notices during development - E_ALL
define('WP_DEBUG_LOG', true); //error logging to wp-content/debug.log
```

Then try deactivating and activating ZenCache, and doing whatever else you did the trigger the "white screen", and once you see the white screen check `wp-content/debug.log`. That file should contain any PHP errors that were logged. If you could post those in a [Pastebin](http://pastebin.com) and share the link here, that would be helpful.

**Comment by eclerkin** [comment]
Ok, will do soon.  I have 2 other websites using the same 3 plugins but those sites are on PHP 5.3 with the extension. I updated ZenCache on those 2 sites as well but they are not issuing any errors nor causing the white page of death.

UPDATE: I added debug settings to wp-config.php, left All In One Security deactivated then activated Google Sitemap (did not deactivate/activate ZenCache) and here is the debug log: http://pastebin.com/jEBb21q4  Google Sitemap is now activated but there was no white page of death. It did dump the session start errors on the front page above the theme. Once I removed the debug statements Google Sitemap appears to be playing well with other plugins now.  However, there are errors from Google Sitemap in the log.

**Comment by jaswrks** [comment]
@eclerkin writes...

> I added debug settings to wp-config.php
> did not deactivate/activate ZenCache

Thank you for the debug output. Nothing in there that pertains to any serious problems, as those are all `E_NOTICE` level messages. Also, nothing from ZenCache. I'm assuming, because you did not activate it.

I'd appreciate it if you could reactivate ZenCache and run another test. We need to see the debug log with ZenCache active, so that we help you review anything that is ZenCache-specific.

**Comment by eclerkin** [comment]
ZenCache is already active.  I activated Google Sitemap - where it failed before - to see what would happen and everything appears to be normal.  I still have not activated All In One Security and Firewall plugin since that appeared to have the most issues after I installed the ZenCache plugin update.  I can turn back on the debug mode and then activate All In One Security and Firewall plugin.

**Comment by jaswrks** [comment]
@eclerkin writes...

> I can turn back on the debug mode and then activate All In One Security and Firewall plugin.

Copy that. Thank you. Keep us posted. So far I'm not seeing anything ZenCache specific, but we are happy to monitor any additional information you can provide.

**Comment by eclerkin** [comment]
@jaswsinc Someone else just posted an issue with All In One Security and Firewall plugin on wordpress.org here: https://wordpress.org/support/topic/cnnot-send-session-cache-limiter-headers-already-sent?replies=2#post-7133936

He has actually deactivated all plugins (something I cannot do since I don't have a development Unix box/WP instance) and it's issuing the same error that I am experiencing. However, he didn't mention if he is using ZenCache. I posted my comments on there as well.

Meanwhile, I still plan on initiating debug mode and then activating All In One to see what happens next.  I will capture the log file and post here.

**Comment by raamdev** [comment]
@jaswsinc This issue may be related to #511. I just installed All In One Security on my local test install attempting to reproduce the issues reported with All In One Security and for the first time, I got the `Fatal error: Base lambda function for closure not found` error (see issue #511) while running **PHP 5.4.10** (previously I was only able to reproduce that APC bug with PHP 5.3.20 locally).

@eclerkin If you could enable debugging as mentioned earlier, and then try to activate ZenCache and let us know if you see any Fatal Errors that are referencing ZenCache files, that would be great. :-)

**Comment by eclerkin** [comment]
@jaswsinc UPDATE 1: First, I cleared all ZenCache, deactivated ZenCache, activated All In One Security and Firewall under PHP 5.4 - no issues navigating any of the pages within All In One.  I used to get the white page of death when clicking on Blacklist Manager but no issues at this point. Now, initiating debug and then I will attempt to activate ZenCache:
@jaswsinc UPDATE 2: I kept All In One & Google Sitemap plugins activated, initiated debug and then activated ZenCache http://pastebin.com/EQ5nsCs7 - see bottom of log showing ZenCache error. 
PHP Fatal error:  Base lambda function for closure not found in /home/slodssadmin1/public_html/wp-content/plugins/zencache/src/includes/closures/Shared/CacheDirUtils.php on line 15.  Now, I will attempt to navigate All In One Security.
@jaswsinc UPDATE 3: White page of death - cannot navigate anything in Admin panel now.  I will need to wait before I can get back in.
@jaswsinc UPDATE 4: ZenCache plugin was hanging up site so I had to disable (rename) ZenCache in cPanel File Manager so that WP would deactivate it when rendering the home page.  All In One is still enabled and working properly with ZenCache 150626 disabled.  I thought saw some instructions on installing the prior ZenCache version so I will head down that path for now.
@jaswsinc UPDATE 5: I un-installed ZenCache 150626 and installed the prior ZenCache version per instructions on Issue 511 - website using PHP 5.4 is now operating normally.  The other 2 sites are on PHP 5.3 + ext using ZenCache 150626 and not having a problem.  On those 2 sites, I did notice that ZenCache is requesting that I upgrade to PHP 5.4 but I will wait until there is a solution for this bug before upgrading sites.  The ZenCache settings link has been disabled until I upgrade.

**Comment by raamdev** [comment]
@eclerkin Thank you very much for all the feedback. This confirms my suspicion that the bug you're seeing is the bug described in Issue #511. I'm going to make a reference over there to this GitHub Issue so that we can use your feedback as part of our testing.

If possible, could get us a copy of `phpinfo()` on your PHP 5.4 site (or you can use the [WordPress phpinfo()](https://wordpress.org/plugins/wordpress-php-info/) plugin)? That will help us in diagnosing this important bug. (If you can copy the `phpinfo()` output to a new Pastbin and share it here, that would be very helpful.)

**Comment by eclerkin** [comment]
@raamdev Sure.  Since Pastebin is a shared public site, is there anything secure in PHPInfo that I should redact?

**Comment by raamdev** [comment]
@eclerkin No, there should be nothing in the output of `phpinfo()` that's private. It's just information about your PHP configuration (options, versions, etc.). I suggest leaving out any mention of the domain where that output came from, as that's the only time the information can be useful (i.e., if someone is specifically targeting your site, they would find that information useful, but if they have no idea which site the `phpinfo()` output came from, then the information is harmless).

**Comment by eclerkin** [comment]
@raamdev http://pastebin.com/912Zrfmh

**Comment by raamdev** [comment]
@eclerkin That output looks incomplete; there should be a lot more information, including the PHP version, APC Support info (and version), etc.

**Comment by eclerkin** [comment]
@raamdev Yep, you are correct - I used WP Phpinfo and it has page upon page of information.  I PDF'd it but it includes the domain information. Can I send the PDF to you via email?

**Comment by raamdev** [comment]
@eclerkin You can submit it privately here: http://wsharks.com/1U9vi3E Thanks!

**Comment by eclerkin** [comment]
@raamdev DONE! Go support ninjas!

**Comment by jaswrks** [comment]
Thanks for all of the work you're doing here to investigate this. I'm watching closely and analyzing the data provided as I debug this on my own also.

**Comment by jaswrks** [comment]
Data received. Your `phpinfo()` output shows PHP 5.4.37 + APC 3.1.13. That indicates that this bug was never fully corrected, because that's the latest/greatest version of APC. ~ Investigation continues.

**Comment by raamdev** [comment]
@eclerkin Thanks again for the PHP info. 

Since I have confirmed by the error message you got that this is the same bug described in #511, I'm going to close this GitHub Issue and reference it in #511, so that we can keep everything in one place. If you have any further details to add, please add them on #511. I also suggest commenting/subscribing to that GitHub Issue so that you receive updates when we post an update.
