### ISSUE TITLE
Shell Vulnerability?

### ISSUE THREAD

**Issue by fatalade** [wpsharks/comet-cache#517]
I'm using the latest Zencache plugin (pro version). Vaultpress tells me there is a serious web-based shell vulnerability in these plugin files. Is this a false positive? 

These are the infected files,
http://i.imgur.com/TrWzEmN.png

And this is the section of code in question,
http://i.imgur.com/waJjsWr.png

Thanks!

**Comment by jaswrks** [comment]
@fatalaid This was reported here already: https://github.com/websharks/zencache/issues/516

~ It's a false-positive. We are going to try to avoid the false-positive report, but in terms of this being a real issue—it's not. In other words, it is safe to ignore that warning from Vaultpress.
