### ISSUE TITLE
Fatal error with version 150626

### ISSUE THREAD

**Issue by NateCow** [wpsharks/comet-cache#518]
Hi, updating to the latest version (150626) causes a fatal error upon activation. Here's the full error text:

`Fatal error: Uncaught exception 'Exception' with message 'Undefined method/closure: `clearHtmlCCache`.' in /home/altenburgstudio/public_html/wp-content/plugins/zencache/src/includes/classes/AbsBaseAp.php on line 57`

`Exception: Undefined method/closure: 'clearHtmlCCache'. in /home/altenburgstudio/public_html/wp-content/plugins/zencache/src/includes/classes/AbsBaseAp.php on line 57`

Call Stack
Time    Memory  Function    Location
0.0013  385496           `{main}( ) ../plugins.php:0`
0.4488  22281328    `do_action( )   ../plugins.php:157`
0.4488  22282904    `call_user_func_array ( )   ../plugin.php:496`
0.4488  22283456    `WebSharks\ZenCache\AbsBaseAp->__call( )    ../plugin.php:0`
0.4488  22283648    `call_user_func_array ( )   ../AbsBaseAp.php:55`
0.4488  22283984    `WebSharks\ZenCache\Plugin->WebSharks\ZenCache\{closure}( ) ../AbsBaseAp.php:55`
0.4506  22374912    `autoClearCache ( ) ../InstallUtils.php:20`
0.4506  22375096    `WebSharks\ZenCache\AbsBaseAp->__call( )    ../InstallUtils.php:20`
0.4506  22375224    `call_user_func_array ( )   ../AbsBaseAp.php:55`
0.4506  22375392    `WebSharks\ZenCache\Plugin->WebSharks\ZenCache\{closure}( ) ../AbsBaseAp.php:55`
0.4507  22376152    `clearCache ( ) ../WcpUtils.php:181`
0.4507  22376336    `WebSharks\ZenCache\AbsBaseAp->__call( )    ../WcpUtils.php:181`
0.4507  22376464    `call_user_func_array ( )   ../AbsBaseAp.php:55`
0.4507  22376632    `WebSharks\ZenCache\Plugin->WebSharks\ZenCache\{closure}( ) ../AbsBaseAp.php:55`
0.4508  22377344    `clearHtmlCCache ( )    ../WcpUtils.php:69`
0.4508  22377696    `WebSharks\ZenCache\AbsBaseAp->__call( )    ../WcpUtils.php:69`

**Comment by raamdev** [comment]
@NateCow Can you tell me which version of PHP you're running?

**Comment by jaswrks** [comment]
Referencing the origin of this error:
https://github.com/websharks/zencache/blob/150626/src/includes/classes/AbsBaseAp.php#L57

I have been unable to reproduce this yet, but it does look like a bug.

**Comment by raamdev** [comment]
@NateCow Could you try deleting ZenCache and installing a fresh copy to see if you get this error again? We haven't been able to reproduce what you're seeing and it sounds like your ZenCache installation might be missing some files, which means the plugin may have become corrupted when you downloaded and installed it.

**Comment by NateCow** [comment]
Hey guys, thanks for the replies, and sorry for my slowness in getting back. The notifications got filed into a different tab in Gmail and I didn't notice them until after I had left work for the weekend.

PHP version is 5.4.21. I've tried deleting ZenCache and reinstalling, deactivated all other plugins, but still get the error. I'm having a hard time reliably recreating this as well. We setup WordPress installs as pre-packaged sites with a certain set of plugins, so the first thing I do with a new site is update WordPress and all the plugins. One of the plugins is QuickCache, so I download ZenCache from the dashboard and let it deactivate QC on its own.

At the moment, it seems like if I first deactivate all other plugins, I can download and activate ZenCache successfully, then re-activate the others just fine. But if I try to install ZenCache with other plugins activated, I'll get the fatal error. It also seems that once I've gotten the fatal error, no amount of removing and reinstalling plugins in any order will resolve it. Likewise, if I've managed to activate ZenCache without an issue, I can't for the life of me get it to break thereafter.

So having found that little work-around, this might be isolated to the two client sites I built last week.

**Comment by raamdev** [comment]
@NateCow Would it be possible to get a copy of the `phpinfo()` output from your server? I'm wondering if his issue may be related to one of the PHP extensions you're running, specifically APC or Opcache (see #511). You can post the `phpinfo()` output to pastebin.com and share the link here, or if you prefer to keep the details private you can submit them here (please mention this GitHub Issue): http://wsharks.com/1KPrem4

**Comment by raamdev** [comment]
@NateCow I believe this issue has been resolved in the latest version of ZenCache. I'm going to close this issue now, but if you discover that you're still having this issue with the latest version of ZenCache, please let me know by leaving a comment below.
