### ISSUE TITLE
Feature Request: Button and/or method to clear the Home Page cache

### ISSUE THREAD

**Issue by anthonyeden** [wpsharks/comet-cache#519]
Hi,

I want a way to clear the homepage cache from an externally accessible function? I'd love to clear the homepage cache whenever settings on our own custom admin screen are changed.

I can't see a way to do this via your exposed functions. Any clues?

Thanks,
Anthony Eden.

**Comment by raamdev** [comment]
@anthonyeden This is not currently possible, however I'll accept this as a feature request.

Note that while it's not currently possible to clear only the home page cache, you can clear the cache dynamically in many other ways:
- [Clearing the Cache Dynamically](http://zencache.com/kb-article/clearing-the-cache-dynamically/)

Also, note that it's also possible to [exclude the home page from being cached altogether](https://github.com/websharks/zencache/issues/191#issuecomment-46297679).

---

Related: #191

**Comment by raamdev** [comment]
@jaswsinc Now that https://github.com/websharks/zencache/issues/191 has been closed and we have a new API function (https://github.com/websharks/zencache/issues/590) to clear specific URLs, is it possible to clear the home page cache via `zencache::clearUrl($url);`?

**Comment by jaswrks** [comment]
Yep. Definitely possible to do that now with the new API function.

**Comment by raamdev** [comment]
@anthonyeden With the next release of ZenCache Pro it will be possible to clear the Home Page cache via `zencache::clearUrl()` by passing in a new [watered-down regex syntax](http://zencache.com/r/watered-down-regex-syntax/).

Regarding making a "button" for this (to clear the Home Page cache): I'm closing this issue in favor of https://github.com/websharks/zencache/issues/380. When https://github.com/websharks/zencache/issues/380 is closed, it should be possible to visit the home page as an admin and simply click a new "Clear Current Page" button (to be worked on as part of https://github.com/websharks/zencache/issues/380).

**Comment by raamdev** [comment]
@anthonyeden A new feature added in https://github.com/websharks/zencache/issues/596#issuecomment-152786080 that will be released with the next version of ZenCache Pro closes this issue. There's now a Clear Cache sub-menu in the Admin Bar that allows clearing the cache for the Home Page:

![2015-10-31_21-01-56](https://cloud.githubusercontent.com/assets/53005/10866843/4f66c152-801a-11e5-8da7-07eec956f85f.png)
