### ISSUE TITLE
Multisite subdomain creation breaks home page

### ISSUE THREAD

**Issue by BookClubs** [wpsharks/comet-cache#520]
I have a very strange issue happening. Every so often, a new site is added by a visitor that breaks the main site. A distorted version of the new subdomain site replaces the main site until I log in and clear the cache.

You can view this now on http://novelblogs.com

I am away from my computer at the moment and unable to fix this. 

To see the appropriate theme, please visit http://novelblogs.com/blogs/

**Comment by BookClubs** [comment]
Fixed this using reference #191 by adding code to wp-config to not cache index. This applies to all sites including sub domain.  Seems to work well so far. Curious to know what the problem is though

**Comment by raamdev** [comment]
@BookClubs I haven't seen this issue before, so it could have something to do with the theme you're using. I'm going to mark this as `needs testing` so that we can add this to our todo list and see if we can replicate the issue you're describing.

**Comment by raamdev** [comment]
@jaswsinc Any ideas what might cause the issue @BookClubs described above?

**Comment by BookClubs** [comment]
Have the names of any of the functions and variables change with the change of the program name?

For example:
`define('ZENCACHE_EXCLUDE_URIS',` '/^\/(index.php\/?)?(\?|$)/');``

Would this now be:
`define('COMETCACHE_EXCLUDE_URIS',`'/^\/(index.php\/?)?(\?|$)/');`

**Comment by raamdev** [comment]
@BookClubs Yes, it would be `COMET_CACHE_EXCLUDE_URIS` (there's an underscore between Comet and Cache).

**Comment by BookClubs** [comment]
I double checked my wp_config file and it turns out I was using the following code:

`if(preg_match('/^\/(index\.php\/?)?(\?|$)/', $_SERVER['REQUEST_URI']))
    define('ZENCACHE_ALLOWED', FALSE); // Don't cache home page.`

So, would this become:

`if(preg_match('/^\/(index\.php\/?)?(\?|$)/', $_SERVER['REQUEST_URI']))
    define('COMET_CACHE_ALLOWED', FALSE); // Don't cache home page.`

Thanks again!

**Comment by BookClubs** [comment]
Is the code above correct?

**Comment by raamdev** [comment]
@BookClubs Oh sorry, I didn't realize that you were asking a question.

Yes, that code looks correct to me.

**Comment by BookClubs** [comment]
No worries, I figured that after my reply.  Thanks for your quick responses.
