### ISSUE TITLE
Latest ZenCache breaks it

### ISSUE THREAD

**Issue by sous-studio** [wpsharks/comet-cache#527]
Hey Folks! :)

Long time no see, huh?

I think I have something similar to:
https://github.com/websharks/zencache/issues/523
Thought I can't investigate now (time), but latest update made ERR_INCOMPLETE_CHUNKED_ENCODING in Chrome and 502 errors at backend.

Now to tell the truth, I've updated my server security. I thought maybe it could be the problem. However, rolling back to previous ZenCache version solved it. I even more apuzzled by the fact that even when newest ZenCache is Disabled (plugin enabled, but in configuration of ZenCache it is turned off), the problem persists. That makes me think the problem is deeper, so inconsistency...

Anyway, if I have some time, I'll look up the logs.

A clue:
2015/07/16 01:58:52 [error] 22268#22268: *7268 recv() failed (104: Connection reset by peer) while reading response header $
2015/07/16 01:58:58 [error] 22268#22268: *7268 readv() failed (104: Connection reset by peer) while reading upstream, clien$
2015/07/16 01:59:01 [error] 22268#22268: *7257 readv() failed (104: Connection reset by peer) while reading upstream, clien$
2015/07/16 01:59:07 [error] 22267#22267: *7302 recv() failed (104: Connection reset by peer) while reading response header $
2015/07/16 01:59:08 [error] 22267#22267: *7300 recv() failed (104: Connection reset by peer) while reading response header $
2015/07/16 01:59:08 [error] 22267#22267: *7296 recv() failed 

That what happend on backend during latest ZenCache activation.

**Comment by raamdev** [comment]
@sous-studio It sounds to me like this might be related to Apache's ModSecurity, or some other security software on your server. I haven't been able to reproduce this at all and I haven't heard any other reports like this, which further indicates it's likely related to your server configuration.

I recommend inspecting the web server log files carefully for clues.
