### ISSUE TITLE
How to use jetpack mobile with Zencache ? 

### ISSUE THREAD

**Issue by tinteo** [wpsharks/comet-cache#531]
Hi, 
I use both jetpack mobile and Zencache. Unfortunately, zencache caches the mobile version of some pages and serve it to desktop users. I know I can prevent that by disallowing zencach for mobile useragents. 

Is there a way to have a cache version of the mobile site ?

**Comment by raamdev** [comment]
@tinteo Thanks for the question. There's a feature request open to add full Mobile Support to ZenCache. Please see: https://github.com/websharks/zencache/issues/471

I recommend leaving a comment there to show your vote for this feature. I'm going to close this issue in favor of #471.
