### ISSUE TITLE
HTML Compressor does not ignore <noscript> tags

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#533]
This issue is a placeholder for an HTML Compressor bug that affects ZenCache Pro. See https://github.com/websharks/html-compressor/issues/65#issuecomment-125794223

**Comment by jaswrks** [comment]
## Suggested Next Actions
- After [this line](https://github.com/websharks/html-compressor/blob/150512/src/includes/classes/Core.php#L345), tokenize `<noscript>...</noscript>` tags; i.e., remove those tags and their contents. Replace them with a numeric token like: `%%noscript-123%%`
- After [this line](https://github.com/websharks/html-compressor/blob/150512/src/includes/classes/Core.php#L348), restore `<noscript></noscript>` tags to their original state.

---

This will require two new methods:
- `tokenizeNoscriptTags($html)`
- `restoreNoscriptTags($html)`

**Comment by jaswrks** [comment]
Resolved by: https://github.com/websharks/html-compressor/issues/65
~ Coming in a future release of ZenCache.
