### ISSUE TITLE
Bug :: deleteFilesFromHostCacheDir () :: Multisite Compat. for Child Blogs

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#536]
## Overview

Clearing the cache on a multisite network fails for user-specific cache entries, or any other dotted sub-directory whenever the primary site has not yet been hit any user who is not logged in.
## Steps to Reproduce
- Setup multisite network w/ sub-directories.
- Create blogs for children: `example.com/child1`, `example.com/child2`
- Enable ZenCache.
- Enable User caching with a separate cache for each user.
- Wipe the cache.
- Hit the front page for `example.com/child1` as a logged-in user and let it cache you.
- Clear (not Wipe) the cache.
## Expected Behavior

That the cache for that user should be cleared along w/ anything else.
## Observed Behavior

In this particular scenario, a sub-directory is expected to exist for the child blog. However, instead we only have `zencache/cache/http/example-com/child1.u` (a user-specific cache only). This fails because of [this check](https://github.com/websharks/zencache-pro/blob/150716/src/includes/closures/Shared/CacheDirUtils.php#L299) that assumes it is a host-specific directory, when in fact it could be host _and_ child blog specific also.

**Comment by jaswrks** [comment]
This issue is actually a bit more complex than I first thought. It might take some refactoring to get this right in all circumstances.

**Comment by jaswrks** [comment]
Duplicate of: https://github.com/websharks/zencache/issues/409

**Comment by raamdev** [comment]
> Duplicate of: #409

Yep, this looks like a duplicate of #409. Can we close one of these two issues to avoid spreading info into to separate issues?

**Comment by raamdev** [comment]
@jaswsinc I've copied your comments from this issue to #409 and I'm closing this in favor of #409. Please reference #409 from now on. Thanks! :-)
