### ISSUE TITLE
Bug :: ACE :: PATH_CURRENT_SITE

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#537]
## Overview

The ACE (Auto-Cache Engine) fails to auto-cache child blogs in a multisite network whenever the network is being served from a sub-directory.
## Steps to Reproduce
- Setup a MS network w/ `PATH_CURRENT_SITE` that uses a nested sub-directory.
- Enable ZenCache and enable the ACE.
- Create a child blog.
- Run the ACE.
## Expected Behavior

That both the main site and all child blogs are cached.
## Observed Behavior

The main site is cached, but the child blog is not, and I see 404 errors in my server log files.
## Problem

[This line](https://github.com/websharks/zencache-pro/blob/150716/src/includes/classes/AutoCache.php#L81) is formulating a URL to each blog without considering `PATH_CURRENT_SITE`. This should make a call to `get_home_url($blog_id, '', 'http')` instead.

**Comment by jaswrks** [comment]
This has been fixed my dev branch.

**Comment by raamdev** [comment]
Ah, good catch!

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Multisite Bug Fix**: Fixed an issue where the Auto-Cache Engine would fail to auto-cache child blogs in a multisite network whenever the network was being served from a sub-directory. Props @jaswsinc. See [Issue #537](https://github.com/websharks/zencache/issues/537).

**Comment by raamdev** [comment]
**ZenCache Pro v150821** has been released and includes changes from this GitHub Issue.

See the [ZenCache Pro v150821 announcement](http://zencache.com/zencache-pro-v150821-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#537).
