### ISSUE TITLE
Feature Request :: Transition In/Out Effects on Cache Cleared Notifications

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#538]
See: https://daneden.github.io/animate.css/

![2015-07-30_17-39-15](https://cloud.githubusercontent.com/assets/1563559/8999091/ec84897e-36e1-11e5-8860-0c28a807a4f8.png)

**Comment by raamdev** [comment]
Cool idea! :+1:

**Comment by jaswrks** [comment]
This could be closed after the next release. I got this in there.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: New transition in/out effects on the Cache Cleared Dashboard notifications. Props @jaswsinc. See [Issue #538](https://github.com/websharks/zencache/issues/538).

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [ZenCache Pro v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#538).
