### ISSUE TITLE
Bug :: 404 Caching :: Multisite Compat.

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#539]
## Overview

[This line of code](https://github.com/websharks/zencache-pro/blob/150716/src/includes/closures/Ac/ObUtils.php#L151) that generates the file path for a centralized 404 error file does not currently consider that each child blog in a multisite network will have its own 404 error page.

**Comment by jaswrks** [comment]
Fixed in my branch. Referencing: https://github.com/websharks/zencache-pro/blob/feature/jaswsinc/src/includes/closures/Ac/ObUtils.php#L175

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Multisite Bug Fix**: Fixed a bug with 404 Request caching on Multisite Networks where ZenCache was not considering that each child blog in a multisite network will have its own 404 error page. Props @jaswsinc. See [Issue #539](https://github.com/websharks/zencache/issues/539).

**Comment by raamdev** [comment]
**ZenCache Pro v150821** has been released and includes changes from this GitHub Issue.

See the [ZenCache Pro v150821 announcement](http://zencache.com/zencache-pro-v150821-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#539).
