### ISSUE TITLE
Bug :: Multisite :: Cache Wipe

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#541]
## Overview

Wiping the cache on a multisite network results in the very next page view being cached incorrectly, because the `zencache/cache/zc-blog-paths` file is wiped also, and it's not rebuilt until after the next page view, and after the `AdvancedCache` class caches for the first time.

In that first page view (under the right conditions), this results in an invalid cache path being generated by `buildCachePath()`; i.e., it thinks the path is merely a sub-directory for the main blog instead of identifying it as a child blog token.

_Bug exists in the updated branch we are working on for the next release only: https://github.com/websharks/zencache-pro/pull/125, following improvements in the way cache paths are generated._
## Steps to Reproduce
- Setup MS network with sub-directory installation.
- Setup two child blogs: `child1` and `child2`.
- Wipe the cache.
- Without doing anything else, visit the front page of `child1` or `child2`.
- Check your `zencache/cache` directory.
## Expected Behavior

That the child blog path is interpreted correctly.
## Observed Behavior

The child blog is nested into the main site's directory incorrectly.

**Comment by jaswrks** [comment]
Wiping the cache now leaves behind the following files intentionally:
- `/zencache/cache/.htaccess`
- `/zencache/cache/zc-advanced-cache`
- `/zencache/cache/zc-blog-paths` (MS network only)
- `/zencache/cache/zc-auto-cache.log` (pro version only)
- `/zencache/cache/zc-auto-cache-archived-[DATE].log` (pro version only)
- _... anything else that is a regular file in the root of the `zencache/cache` directory._

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Multisite Bug Fix**: Fixed a bug where Wiping the cache on a multisite network resulted in the very next page view being cached incorrectly. Props @jaswsinc. See [Issue #541](https://github.com/websharks/zencache/issues/541).

**Comment by raamdev** [comment]
**ZenCache Pro v150821** has been released and includes changes from this GitHub Issue.

See the [ZenCache Pro v150821 announcement](http://zencache.com/zencache-pro-v150821-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#541).
