### ISSUE TITLE
Security breach, your attempt to access a secure form has be

### ISSUE THREAD

**Issue by fergusfish** [wpsharks/comet-cache#542]
I have been considering moving to the unlimites sites license but of late have been getting too many problems..
This morning I was locked out of my own site with this error "Security breach, your attempt to access a secure form has been denied!"
Unable to clear cache so left with no option but to go through cpanel and remove zencache - problem now solved. This site is about to go live and is a client membership site where I cannot have this happening.
If you can explain why then maybe I might use zencache but otherwise will have to look at other cache plugins

**Comment by raamdev** [comment]
@fergusfish That's not a ZenCache error message--nowhere in the ZenCache codebase does that error exist.

Also, ZenCache does not cache or do anything at all to the WordPress Login page, so if you were not able to login to your site, it sounds to my like you have an issue with something other than ZenCache and it was a coincidence that removing ZenCache "fixed" the problem.

If you can provide any more information about this issue, I would be happy to investigate further, but at this time I'm not seeing anything here related to ZenCache.
