### ISSUE TITLE
Bug :: Multisite :: ACE :: Option Storage

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#543]
## Overview

The ACE is supposed to run only from the Main Site. This strategy has actually changed a bit since the original creation of the ACE. Over time, we have improved the ACE, and now it really should _only_ be running from the Main Site in a network. It currently does not; i.e., BUG.
## Steps to Reproduce
- Enable ZenCache network wide in a MS installation.
- Enable the ACE & and setup an XML sitemap for at least one child blog.
- Visit each of the child blogs and run: `/?zencache_auto_cache_cron=1` from each of them.
## Expected Behavior

That the ACE would not run on the child blog.
## Observed Behavior

The ACE is currently allowed to run from the child blog. In fact, the `setup()` routine in ZenCache is currently configuring multiple CRON jobs; i.e., for each child blog. That's a bug. It also has the potential to create a process overlap which could lead to performance issues.

**Comment by jaswrks** [comment]
> The ACE is currently allowed to run from the child blog. In fact, the setup() routine in ZenCache is currently configuring multiple CRON jobs; i.e., for each child blog. That's a bug. It also has the potential to create a process overlap which could lead to performance issues.

This only happens in a specific scenario. It's not a widespread issue. However, it needs to be fixed nonetheless. My feeling is that data storage in ZenCache needs to use `*_site_option()` exclusively whenever work to correct this bug occurs.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Multisite Bug Fix**: Fixed a bug in the Auto-Cache Engine that was resulting in duplicate Cron Jobs being created for each Child Site. The Auto-Cache Engine now only runs from the Main Site in a network, as it should. When the Auto-Cache Engine runs on the Main Site, it will also run for each of the Child Blogs (see [this article](http://zencache.com/r/kb-article-how-does-the-auto-cache-engine-cache-child-blogs-in-a-multisite-network/) for more information). Props @jaswsinc. See [Issue #543](https://github.com/websharks/zencache/issues/543).

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [ZenCache Pro v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#543).
