### ISSUE TITLE
Minification Problem with CSS Pseudo-Classes

### ISSUE THREAD

**Issue by patdumond** [wpsharks/comet-cache#544]
Reference: https://webshark.zendesk.com/agent/tickets/7790

CSS pseudo-classes require a space between the class-name and pseudo-class-name. When minifying CSS with ZenCache, that space is removed, breaking the code.

For example:

`.test :first-child { color: green; }` would be changed to `.test:first-child{color:green;}`
## Work-Around to Avoid This Issue

To avoid this issue, choose "No, do not compress the code in any unified CSS files" from the panel at **WordPress Dashboard → ZenCache → Plugin Options → HTML Compression**. 

![zencache-screenshot](https://cloud.githubusercontent.com/assets/9320495/9215141/aec914f0-4074-11e5-90c6-e238064951c4.jpg)

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed an HTML Compressor bug related to CSS pseudo-classes where spaces between the class name and pseudo-class name were being removed when CSS was minified. Props @patdumond @jaswsinc. See [Issue #544](https://github.com/websharks/zencache/issues/544).

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [ZenCache Pro v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#544).
