### ISSUE TITLE
Remove Back Compat. `share.php` File

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#545]
Consider encoding this file to prevent inadvertent changes and to avoid having anything in this file turn up in search results while working on the codebase; e.g., running a search/replace.

https://github.com/websharks/zencache-pro/blob/150716/includes/share.php

**Comment by jaswrks** [comment]
@raamdev I'd like to suggest that we close this issue now, and instead we can just _be done_ with this file as a part of our upcoming work on 'you know what' (IC).

**Comment by raamdev** [comment]
@jaswsinc That sounds like a plan to me. But let's keep this issue open so that we remember to remove it.

I'm adding it to a new IC (Soft Launch) milestone.
