### ISSUE TITLE
Unit Testing `/tests`

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#546]
Consider building a set of unit tests in this directory to make release testing easier. Testing inside WordPress will likely still be required, but any automated unit tests in this directory could also catch problems for us; and these could be run during the build process.

https://github.com/websharks/zencache-pro/tree/150716/tests

**Comment by raamdev** [comment]
@jaswsinc I noticed we have a `tests/` directory in the Comet Cache Pro repo. Can you give me a status update on this GitHub issue?

**Comment by jaswrks** [comment]
@raamdev I think this can be closed now, because the testing framework was implemented a long while back. What we could use now is a new issue that tracks our progress on creating some wiki articles to document that framework and give everyone a refresher on how the framework functions, how to write tests using CasperJS, etc. In short, we just need to build the tests now.
