### ISSUE TITLE
3rd Party Plugin Compatibility: Autoptimize

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#547]
[Autoptimize](https://wordpress.org/plugins/autoptimize/) "speeds up your website and helps you save bandwidth by aggregating and minimizing JS, CSS and HTML." It basically does the same thing as the ZenCache HTML Compression, however with 90k+ active installs there are often users who install ZenCache on a site where Autoptimize is already running.

There has been [a report](https://wordpress.org/support/topic/autoptimize-and-zencahce-cdn-problem) of issues running Autoptimize + ZenCache Static CDN Filters. I'm opening this issue to investigate compatibility with Autoptimize.

**Comment by chandrautama** [comment]
The only problem I experienced using Autoptimize is the cache size will build up over time: http://blog.futtta.be/2014/03/19/how-to-keep-autoptimizes-cache-size-under-control-and-improve-visitor-experience/

Please note, I'm not using CDN. So this is maybe related or not.

**Comment by raamdev** [comment]
@chandrautama Thanks for the added information! It sounds like the issue is that Autoptimize does not include any automatic cache pruning, which can lead to a large Autoptimize cache size. That sounds like an Autoptimize problem; as far as I can tell, that issue would not affect ZenCache at all.

However, the issue that _would_ affect ZenCache is if you implemented a custom Autoptimize pruning mechanism (e.g., a Cron Job that ran a script every few days that automatically deleted Autoptimize cache files) because then the pages cached by ZenCache might be pointing to CSS/JS files created by Autoptimize that no longer exist, in which case when ZenCache loads the cache file the CSS/JS will be missing.

The only solution to that issue that I can think of is making sure that the pruning for Autoptimize is followed by a call to the [ZenCache API to clear the cache](http://zencache.com/kb-article/is-there-an-api-call-that-clears-the-cache/), so that you can make sure that all ZenCache cache files contain links to Autoptimize CSS/JS files that exist.

**Comment by raamdev** [comment]
@futtta Do you know if this is still a problem? This GitHub issue is quite old, so I'm wondering if you've seen any compatibility issues between Comet Cache and Autoptimize lately.

**Comment by futtta** [comment]
there's no AO+CC issues that I'm aware of @raamdev :-)

have a nice weekend!

**Comment by raamdev** [comment]
Thank you, @futtta! :-) Have a great weekend.
