### ISSUE TITLE
Feature Request: Option To Inject Async When Combining JS/CSS

### ISSUE THREAD

**Issue by kristineds** [wpsharks/comet-cache#548]
A customer writes:

> We are implementing best practices and using the HTML Compression Options for compressing JS. Currently ZenCache does not provide an option for setting a async attribute on the script tag it generates. Is this something that you can offer as an option?

From @jaswsinc: It's not a feature provided by ZenCache at this time. That's because changing and/or adding this attribute can break scripts. It's not something that an automated script can just flip the switch on, because there could be unintended consequences. It's best that a theme/plugin developer and/or site owner review their site carefully and make this change manually as needed. The HTML Compressor will preserve it if it's found, but it won't automatically generate this attribute for you. That's intentional.

---

Referencing: [Support Ticket](https://websharks.zendesk.com/agent/tickets/7777)

**Comment by raamdev** [comment]
@kristineds Thanks for the feature request.

@jaswsinc It sounds, based on your comment that Kristine quoted above, that this isn't something ZenCache should do, ever. Is that correct? If so, I'm not seeing a reason to keep this feature request open. Perhaps a better direction would be to write a KB Article that explains why ZenCache _does not_ offer the option to inject an async attribute.

**Comment by jaswrks** [comment]
> Is that correct? If so, I'm not seeing a reason to keep this feature request open.

Agreed. I wasn't sure at the time, but after giving it some thought I don't see this being possible.

**Comment by raamdev** [comment]
@jaswsinc Got it. Thanks. Closing this.
