### ISSUE TITLE
Fatal error: You have reached the browser stylesheet limit (31)

### ISSUE THREAD

**Issue by groubee** [wpsharks/comet-cache#551]
Hi

I use the latest version of 

s2member pro
BuddyPress
WordPress
Zencache

and my theme is: Razor - http://themeforest.net/item/razor-cutting-edge-wordpress-theme/3822067

I have a problem with to many stylesheets in Internet Explorer 11? I had hoped that Zencache could have helped this issue?

Fatal error: You have reached the browser stylesheet limit (31) - Internet Explorer 11, V. 11.0.10240.16384

best regards
Tonny

**Comment by raamdev** [comment]
@groubee If your WordPress theme and/or site has too many stylesheets being loaded, you can use the HTML Compressor feature to combine stylesheets into 1 or 2 stylesheets. The HTML Compressor feature is included with [ZenCache Pro](http://zencache.com/features/). 

Note that the "fatal error" you're experiencing is not related to ZenCache. You're running into what sounds like a browser limitation.
