### ISSUE TITLE
Detect when XML Sitemap URL does not exist for Auto-Cache Engine

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#555]
_Forked from https://github.com/websharks/zencache/issues/512#issuecomment-133451054_

@jaswsinc writes...

> So you were not running a plugin that generates a sitemap at all in this case. WordPress doesn't generate an XML sitemap automatically, so without a sitemap plugin this URL should in fact return a 404 error; i.e., that would be expected.
> 
> ```
> http://192.168.2.14/webby/sitemap.xml = 404 (expected in a default install)
> ```
> 
> It sounds like you enabled the ACE in ZenCache, and perhaps entered your own list of URLs instead of relying on the sitemap alone. Do I have that right?
> 
> If you leave the ACE configured with /sitemap.xml as a config. option (that's a default value), then it will still look for that sitemap location too, in addition to any other URLs that you enter manually.
> 
> ↑ That could trigger the 404 error, and I can see where that would lead to this confusion.

![2015-08-21_06-57-58](https://cloud.githubusercontent.com/assets/1563559/9411371/128c2ee6-47d2-11e5-8e9d-ac0bdda84d7a.png)

**Comment by raamdev** [comment]
@jaswsinc I think we can do better than a note: We should just check the XML Sitemap URL and see if it returns the appropriate status code. If it does not, we show a warning message indicating that the XML Sitemap could not be found and suggest installing the Google XML Sitemaps plugin, or clear the XML sitemap field and use the list of URLs instead. (Bonus points if we can also validate that a valid XML Sitemap exists at the URL when then URL returns an non-404.)

**Comment by jaswrks** [comment]
:+1:

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch: `feature/555` in the `websharks/zencache-pro` repo.
- Replace [these lines of code](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/AutoCache.php#L246-L263) with the following:
  
  ``` php
  if (is_wp_error($head = wp_remote_head($sitemap, array('redirection' => 5)))
        || empty($head['response']['code']) || (integer) $head['response']['code'] >= 400
        || empty($head['headers']['content-type']) || stripos($head['headers']['content-type'], 'xml') === false) {
  
          // Enqueue a dashboard notice if this is a primary Sitemap location.
          if (!$___recursive) { // Fail silently on recursive calls.
              $this->plugin->enqueueMainNotice(
                  sprintf(__('<strong>%1$s says...</strong> The Auto-Cache Engine is currently configured with an XML Sitemap location that could not be found. We suggest that you install the <a href="http://zencache.com/r/google-xml-sitemaps-plugin/" target="_blank">Google XML Sitemaps</a> plugin. Or, empty the XML Sitemap field and only use the list of URLs instead. See: <strong>Dashboard → %1$s → Auto-Cache Engine → XML Sitemap URL</strong> ', SLUG_TD), esc_html(NAME)),
                  array('class' => 'error', 'persistent_key' => 'xml_sitemap_missing')
              );
          }
          goto finale; // Nothing more we can do in this case.
  }
  ```
- Submit PR.

**Comment by jaswrks** [comment]
@kristineds While working on this issue you can learn more about `is_wp_error()` and the `WP_Error` class here: https://codex.wordpress.org/Function_Reference/is_wp_error

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: The Auto-Cache Engine now detects when the configured XML Sitemap is not valid or is unreachable and displays an appropriate notice. Props @kristineds and @jaswsinc. See [Issue #555](https://github.com/websharks/zencache/issues/555).

**Comment by KTS915** [comment]
@raamdev, @kristineds, @jaswsinc,

This is a great new addition. (I am just trying out the new RC.) Thank you! I had enabled this before without realizing that I need to use a plugin to create an xml sitemap.

I have now installed Simple Wp Sitemap (https://wordpress.org/support/plugin/simple-wp-sitemap) and it seems to be doing the job (without pinging Google, which other sitemap plugins do, and which I don't want). 

But now I have a question. This plugin allows me to add other pages outside WordPress (e.g. static html files) to the sitemap. If I do this, does it mean that ZenCache Pro will then be able to cache them too?

**Comment by jaswrks** [comment]
> I have now installed Simple Wp Sitemap (https://wordpress.org/support/plugin/simple-wp-sitemap) and it seems to be doing the job (without pinging Google, which other sitemap plugins do, and which I don't want).

Nice! Thanks for the link. I'll bookmark that one.

> But now I have a question. This plugin allows me to add other pages outside WordPress (e.g. static html files) to the sitemap. If I do this, does it mean that ZenCache Pro will then be able to cache them too?

I'm afraid not. If it's in the sitemap, ZenCache may attempt to load that page and cache it, but that attempt will fail gracefully since WordPress and ZenCache are not actually loaded in static HTML files.

**Comment by KTS915** [comment]
@jaswsinc,

That's what I suspected. Thanks for the explanation!

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#555).
