### ISSUE TITLE
HTML Compression breaks Portfolio Slideshow Pro

### ISSUE THREAD

**Issue by karenratte** [wpsharks/comet-cache#558]
Setting these settings to YES, breaks Portfolio Slideshow. I presume it is from combining the javascript. 
I am using MAXCDN as well and have it enabled, if that makes a difference. If there is anything you require of me please ask.

**Comment by jaswrks** [comment]
Thanks for the report. This issue was resolved in a recent update. It's coming soon in a new release of ZenCache Pro. Referencing: https://github.com/websharks/zencache-pro/pull/129
