### ISSUE TITLE
Bug :: Chart.js Rounding Issue (Chart Slicing)

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#559]
@raamdev writes...

Regarding the current development branch:

> I've noticed consistently is with the pie charts getting cut off.

![2015-08-29_14-53-38_720](https://cloud.githubusercontent.com/assets/1563559/9568390/6e73f4cc-4ef4-11e5-8746-c15201345071.png)

**Comment by raamdev** [comment]
@jaswsinc I've been testing the bug fix for the charts on my personal raam.org site and things look great so far:

![2015-09-03_19-51-52](https://cloud.githubusercontent.com/assets/53005/9673717/4bac57a2-5275-11e5-86a3-6bdeecf1acc3.png)

I'm marking this as closed by https://github.com/websharks/zencache-pro/issues/137

**Comment by jaswrks** [comment]
Cool!
