### ISSUE TITLE
Latest version conflicting with another external script

### ISSUE THREAD

**Issue by sarangandk** [wpsharks/comet-cache#560]
I have an external script which uploads Wordpress galleries from images in ftp server. Latest version of ZenCache is giving some problems that prevent my script not working anymore.

I'm willing to share my script with the developers, not in public.
Please tell me how to share it with you by email or private.

When I load my script, I get the following error message:

```
#4 [internal function]: WebSharks\ZenCache\Pro\AbsBaseAp->WebSharks\ZenCache\Pro\{closure}('/^\\/category\\/a...')
#5 /home/domain.tld/public_html/wp- in /home/domain.tld/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php on line 264

Fatal error: Uncaught exception 'Exception' with message 'Invalid argument; host token empty!' in /home/domain.tld/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php:264
Stack trace:
#0 [internal function]: WebSharks\ZenCache\Pro\AbsBaseAp->WebSharks\ZenCache\Pro\{closure}('/^\\/category\\/a...')
#1 /home/domain.tld/public_html/wp-content/plugins/zencache-pro/src/includes/classes/AbsBaseAp.php(55): call_user_func_array(Object(Closure), Array)
#2 /home/domain.tld/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php(54): WebSharks\ZenCache\Pro\AbsBaseAp->__call('deleteFilesFrom...', Array)
#3 /home/domain.tld/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php(54): WebSharks\ZenCache\Pro\Plugin->deleteFilesFromHostCacheDir('/^\\/category\\/a...')
#4 [internal function]: WebSharks\ZenCache\Pro\AbsBaseAp->WebSharks\ZenCache\Pro\{closure}('/^\\/category\\/a...')
#5 /home/domain.tld/public_html/wp- in /home/domain.tld/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php on line 264      
```

**Comment by raamdev** [comment]
@sarangandk You can share privately by opening a ticket here: http://wsharks.com/1fRVz6b (link expires in 48 hours)

**Comment by sarangandk** [comment]
I have uploaded the script.

## 

Sarangan T.

**Comment by raamdev** [comment]
@sarangandk It looks like ZenCache is not finding your hostname in `$_SERVER['HTTP_HOST']` when your script runs, which seems odd to me. Can you try adding `echo $_SERVER['HTTP_HOST']` to your script (or otherwise the value of `$_SERVER['HTTP_HOST']` while your script is running) to see if there's something odd being returned? It should contain the hostname for your site.\

---

Referencing internal ticket with script you submitted: https://websharks.zendesk.com/agent/tickets/8106

**Comment by sarangandk** [comment]
Hello,
I just did that as you requested and echo $_SERVER['HTTP_HOST'] echo'ing my
domain correctly. The following error displaying only when I run the PHP
script via cron. When I load the script via browser like
http://domain/script.php it works fine.

PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid

> argument; host token empty!' in
> /home/tamil.gallery/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php:264
> Stack trace:
> #0 [internal function]:
> WebSharks\ZenCache\Pro\AbsBaseAp->WebSharks\ZenCache\Pro{closure}('/^\/category\/a...')
> #1
> /home/tamil.gallery/public_html/wp-content/plugins/zencache-pro/src/includes/classes/AbsBaseAp.php(55):
> call_user_func_array(Object(Closure), Array)
> #2
> /home/tamil.gallery/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php(54):
> WebSharks\ZenCache\Pro\AbsBaseAp->__call('deleteFilesFrom...', Array)
> #3
> /home/tamil.gallery/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php(54):
> WebSharks\ZenCache\Pro\Plugin->deleteFilesFromHostCacheDir('/^\/category\/a...')
> #4 [internal function]:
> WebSharks\ZenCache\Pro\AbsBaseAp->WebSharks\ZenCache\Pro{closure}('/^\/category\/a...')
> #5 /home/tamil.gallery/public_html/wp- in
> /home/tamil.gallery/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php
> on line 264
> 
> Fatal error: Uncaught exception 'Exception' with message 'Invalid
> argument; host token empty!' in
> /home/tamil.gallery/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php:264
> Stack trace:
> #0 [internal function]:
> WebSharks\ZenCache\Pro\AbsBaseAp->WebSharks\ZenCache\Pro{closure}('/^\/category\/a...')
> #1
> /home/tamil.gallery/public_html/wp-content/plugins/zencache-pro/src/includes/classes/AbsBaseAp.php(55):
> call_user_func_array(Object(Closure), Array)
> #2
> /home/tamil.gallery/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php(54):
> WebSharks\ZenCache\Pro\AbsBaseAp->__call('deleteFilesFrom...', Array)
> #3
> /home/tamil.gallery/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php(54):
> WebSharks\ZenCache\Pro\Plugin->deleteFilesFromHostCacheDir('/^\/category\/a...')
> #4 [internal function]:
> WebSharks\ZenCache\Pro\AbsBaseAp->WebSharks\ZenCache\Pro{closure}('/^\/category\/a...')
> #5 /home/tamil.gallery/public_html/wp- in
> /home/tamil.gallery/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php
> on line 264

## 

Sarangan T.

**Comment by jaswrks** [comment]
> The following error displaying only when I run the PHP
> script via cron. When I load the script via browser like
> http://domain/script.php it works fine.

So this is the problem. Running the script via CRON is a much different thing in terms of which environment variables are set. WordPress is not a command-line application, it is a web-based application. If you have a CRON job, use something like cURL to call the CRON job via `http://` instead of as a command-line application. That way all of the expected environment variables will exist.

**Comment by sarangandk** [comment]
Hmm, anyway my script worked without any problems until you released the
latest version of ZenCache.

## 

Sarangan T.

**Comment by jaswrks** [comment]
> Hmm, anyway my script worked without any problems until you released the
> latest version of ZenCache.

If you look at the configuration of your CRON job (perhaps configured in cPanel), see if there's an option to load the full URL instead of entering an absolute file path location. They may resolve the issue for you here as a short-term fix.

Related issue: https://github.com/websharks/zencache/issues/563

**Comment by sarangandk** [comment]
Yes, but the reason for why I load the script using absolute file path is
because of calling from http will give some timeout problems. Anyway thanks
for your suggestion. I have downgraded ZenCache to older version as a
short-term fix.

## 

Sarangan T.

**Comment by raamdev** [comment]
@sarangandk This issue should be resolved in the next Pro release as part of the work that was completed here: https://github.com/websharks/zencache/issues/563#issuecomment-146996879

If after the next update you're still having issues, please let us know and I'll reopen this issue.
