### ISSUE TITLE
Bug :: NGINX Compat. :: `$_GET['q']`

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#561]
## Overview

Referencing: http://wiki.nginx.org/Pitfalls#Front_Controller_Pattern_based_packages

``` text
try_files $uri $uri/ /index.php?q=$uri&$args;
```

_This is a popular configuration for Nginx servers._

The `$_GET['q']` variable being passed to WordPress & ZenCache though; it can prevent an entire site from being cached. This is because ZenCache, by default, will not cache URLs that contain a query string. With this Nginx config, all requests include the `?q=` variable.
## Steps to Reproduce
- Fire up Nginx
- Use a configuration [like this](https://github.com/jaswsinc/vagrant-ubuntu-lemp/blob/master/assets/nginx/.conf#L32-L34).
  
  ``` text
  try_files $uri $uri/ /index.php?q=$uri&$args;
  ```
- Enable pretty permalinks in WordPress.
- Visit any page on the site.
## Expected Behavior

That fancy permalinks would be cached.
## Observed Behavior

``` html
<!-- ZenCache is NOT caching this page, because `$_GET` contains query string data. The current configuration says NOT to cache GET requests with a query string. -->
```
## Possible Solution

ZenCache already has a [check for special query vars](https://github.com/websharks/zencache-pro/blob/150821/src/includes/closures/Shared/ConditionalUtils.php#L26-L45). We could add `q` to the list of special query vars whenever we can detect that a site is running Nginx. That way the `$_GET['q']` and `$_SERVER['QUERY_STRING']` environment vars will not prevent caching.

**Comment by jaswrks** [comment]
## Short-Term Fix

Change: 

``` text
try_files $uri $uri/ /index.php?q=$uri&$args;
```

To:

``` text
try_files $uri $uri/ /index.php?$args;
```

**Comment by jaswrks** [comment]
I should note that the `?q=$uri` is not there for WordPress. WordPress doesn't need this. It's there (i.e., suggested by Nginx) for cross-compatibility with Drupal and Joomla also. I'm not sure which of those relies on this, but WordPress itself does not. Thus, the short-term fix I posted could also be a long-term fix if you're only running WordPress.

**Comment by raamdev** [comment]
Closed by https://github.com/websharks/zencache-pro/pull/137.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed an issue related to a popular NGINX server configuration (`try_files $uri $uri/ /index.php?q=$uri&$args;`) that was preventing the entire site from being cached. ZenCache disables caching by default for all requests that include a query string (see _Dashboard → ZenCache → Plugin Options → GET Requests_) and this particular NGINX configuration passes _all_ requests to WordPress with a `?q=` query variable, which was resulting in ZenCache disabling caching on all pages. This release implements better detection for NGINX and works around this scenario. Props @jaswsinc. See [Issue #561](https://github.com/websharks/zencache/issues/561).

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [ZenCache Pro v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#561).
