### ISSUE TITLE
Bug: Dev Branch : SHORT_NAME

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#562]
I introduced a bug in [this PR](https://github.com/websharks/zencache-pro/pull/137). The use of `SHORT_NAME`, which I tried to tidy-up as part of this PR, should be forced to lowercase via `strtolower()`. The default value of `SHORT_NAME` is `ZC`, so it needs to be forced to lowercase when used to formulate strings like: `zcABC`.

**Comment by jaswrks** [comment]
Looks perfect to me. Thank you!

**Comment by raamdev** [comment]
Closed by https://github.com/websharks/zencache-pro/issues/142.
