### ISSUE TITLE
Updating plugin via WP-CLI yields ZenCache Pro errors

### ISSUE THREAD

**Issue by MarioKnight** [wpsharks/comet-cache#563]
While I know that ZenCache (Pro) has yet to support WP-CLI directly, an issue has come up that I believe started after updating sites to the latest ZenCache Pro version.  When I run plugin updates, sites with ZenCache Pro activated output the following errors:

```
Fatal error: Uncaught exception 'Exception' with message 'Invalid argument; host token empty!' in /home/xxxx/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php:264
Stack trace:
#0 [internal function]: WebSharks\ZenCache\Pro\AbsBaseAp->WebSharks\ZenCache\Pro\{closure}('/^.+/i')
#1 /home/xxxx/public_html/wp-content/plugins/zencache-pro/src/includes/classes/AbsBaseAp.php(55): call_user_func_array(Object(Closure), Array)
#2 /home/xxxx/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php(54): WebSharks\ZenCache\Pro\AbsBaseAp->__call('deleteFilesFrom...', Array)
#3 /home/xxxx/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php(54): WebSharks\ZenCache\Pro\Plugin->deleteFilesFromHostCacheDir('/^.+/i')
#4 [internal function]: WebSharks\ZenCache\Pro\AbsBaseAp->WebSharks\ZenCache\Pro\{closure}('/^.+/i')
#5 /home/xxxx/public_html/wp-content/plugins/zencache-pro/src/includes/classes/AbsBaseAp.php(55) in /home/xxxx/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php on line 264
```

The plugins still update and the cache still appears to clear and work normally afterward, so thankfully this is currently just an inconvenience.  I just wanted to let you know in case something can be done, and in hopes that this could potentially help with https://github.com/websharks/zencache/issues/464 .  Please let me know if you need anything else on my end.  Thank you!

**Comment by raamdev** [comment]
@MarioKnight Thanks so much for the additional information!

@jaswsinc I noticed `'Invalid argument; host token empty!'` is the same error reported in https://github.com/websharks/zencache/issues/560; it sounds like these could be related.

**Comment by jaswrks** [comment]
> I noticed 'Invalid argument; host token empty!' is the same error reported in #560; it sounds like these could be related.

Yeah. I suspect this is a bug. ZenCache needs to consider that it might run as part of a CLI process where `$_SERVER['HTTP_HOST']` is empty. We had this consideration covered in a previous release, but it looks like something is slipping through in the latest copy.

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch: `feature/563` in the `websharks/zencache-pro` repo.
- Replace [this line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/Plugin.php#L406) with the following:
  
  ``` php
  if (!$this->enable_hooks || strcasecmp(PHP_SAPI, 'cli') === 0) {
  ```
- Submit PR.

**Comment by jaswrks** [comment]
Should also resolve: https://github.com/websharks/zencache/issues/560

**Comment by MarioKnight** [comment]
I tested this on a site, and the behavior is back to normal.  I'm looking forward to seeing this in the next release, though since it's just a one line change, I will likely roll out that change to all our client sites in the meantime.  Thank you!

**Comment by raamdev** [comment]
@MarioKnight Thanks so much for the confirmation that @jaswsinc's fix works. :-) I'll make sure this fix makes it into the next Pro release.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed a bug related to updating plugins with WP-CLI on a site that was running ZenCache Pro. While ZenCache Pro updates must still be done through the ZenCache Pro Updater inside the Dashboard, updating other plugins via WP-CLI was generating a harmless ZenCache exception: "Invalid argument; host token empty!". With this fix, ZenCache will properly detect when WP-CLI is running to avoid these errors. Props @MarioKnight @renzms. See [Issue #563](https://github.com/websharks/zencache/issues/563).

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#563).
