### ISSUE TITLE
html compressor not compressing javascript comment lines that start with // 

### ISSUE THREAD

**Issue by kNmnPyGGCwxk4zQoDD** [wpsharks/comet-cache#564]
html compressor not compressing javascript comment lines that start with // 
For example,

// This is a comment
This is some code

Would turn into

// This is a commentThis is some code

which comments out everything after it up until there is a closing bracket

**Comment by raamdev** [comment]
@kNmnPyGGCwxk4zQoDD Can you provide us with an example snippet of code where this is happening (or better yet, the website where this is happening)?

**Comment by raamdev** [comment]
I have not heard back from @kNmnPyGGCwxk4zQoDD with additional details; closing this issue.
