### ISSUE TITLE
Impossible to activate Pro v150919 (release candidate)

### ISSUE THREAD

**Issue by Kalfer** [wpsharks/comet-cache#566]
When I install and activate the plugin, Wordpress returns an error:

Catchable fatal error: Argument 1 passed to WebSharks\ZenCache\Pro\Plugin::WebSharks\ZenCache\Pro{closure}() must be of the type array, string given in /home/XXXXX/public_html/wp-content/plugins/zencache-pro/src/includes/closures/Plugin/NoticeUtils.php on line 255

**Comment by jaswrks** [comment]
Thanks for reporting! @raamdev Looks like we need a `break;` after this line:
https://github.com/websharks/zencache-pro/blob/150919-RC/src/includes/closures/Plugin/NoticeUtils.php#L204

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch: `feature/566` in the `websharks/zencache-pro` repo.
- After [this line of code](https://github.com/websharks/zencache-pro/blob/150919-RC/src/includes/closures/Plugin/NoticeUtils.php#L204) add the following:
  
  ``` php
  continue; // Bypass; i.e., do not normalize.
  ```
- Submit PR.

**Comment by raamdev** [comment]
@Kalfer Thanks so much for reporting this issue with the RC! We've fixed the bug and will be releasing a second RC in a few hours. If you could test this second RC once it's released to confirm that you don't get any error message, that would be very helpful. :-)

**Comment by raamdev** [comment]
@Kalfer ZenCache Pro v150924 RC2 has been released, which includes the fix for this issue. If you're able to test RC2 to confirm this issue has been fixed, that would be great! :-) See http://zencache.com/zencache-pro-v150924-release-candidate-2/

**Comment by Kalfer** [comment]
Yes, the bug has been fixed. Now I was able to install and activate it perfectly. Thanks.

**Comment by raamdev** [comment]
@Kalfer Awesome! Thanks so much for testing and confirming. :-)
