### ISSUE TITLE
Delete details into the post page

### ISSUE THREAD

**Issue by TOMER628** [wpsharks/comet-cache#567]
hi !
i have score rating in my website and after using Zencache ...
it deleate the score in the post page
i attach some pictures to explain that..
THIS GOOD :
![1](https://cloud.githubusercontent.com/assets/6731295/9988811/5d367972-605c-11e5-8c9b-85184c53c2ca.png)
AND if i enter to page this what i see : (not good)
![2](https://cloud.githubusercontent.com/assets/6731295/9988829/897af7c4-605c-11e5-9345-732cd5319db1.png)
 can you fix it ?

**Comment by raamdev** [comment]
We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [WordPress.org Support Forum](https://wordpress.org/support/plugin/zencache) (for ZenCache Lite) or open a [Trouble Ticket](https://www.websharks-inc.com/support/?product=zencache&request_type=trouble_ticket) (ZenCache Pro). Thank you! :)
