### ISSUE TITLE
Bug using img src=data:image/png;base64

### ISSUE THREAD

**Issue by xgiovio** [wpsharks/comet-cache#568]
Hello, once enabled cloudfront, images like this one ---> img alt="Embedded Image" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIA..."  disapper from the page. How can i blacklist this tag or better, could zencache replace this object with a cloudfront one ? Thank you

**Comment by raamdev** [comment]
@xgiovio Can you tell me which version of ZenCache Pro you're running? Also, do you have the HTML Compressor also enabled?

@jaswsinc Any thoughts on this one?

**Comment by jaswrks** [comment]
@xgiovio writes...

> could zencache replace this object with a cloudfront one ?

No, I'm afraid not. It's better not to do so, actually. Images that are embedded like this with a `data:` URI do not require another connection, and that is a common reason for developers to write markup like this; i.e., to prevent the image from being loaded from another HTTP connection, via a CDN or otherwise.

@raamdev writes...

> @jaswsinc Any thoughts on this one?

I'm not aware of there being a problem like this in ZenCache or in the HTML Compressor. The HTML Compressor intentionally bypasses these. Maybe once @xgiovio writes back we can learn more about this particular case.

**Comment by xgiovio** [comment]
@raamdev i'm using the latest public one. The 150821. I tried also the new rc 150919 but the problem remains. yes html compressor activated but the problem arises only when i enable cloudfront. the img tag disappers completely from the source code.
@jaswsinc I agree with you on the embedded image created in this way to prevent another http creation but i think there should be a method, workaround, to exclude some objects. The actuale static files cdn implementation only exclude/include directories and file extensions but with problems like mine i don't know how display the images with cdn activated. I think the cdn rewrite alghorithm should ignore img tags with embedded base64 images. thank you for your attention

ps. i found out also that the latest rc is bugged on html compressor. it was enabled but the source code wasn't compressed. I tried to reset cache,disable and reenable compressor, disable and reenable the plugin. Nothing. I resolved the html compression activation bug reinstalling the latest public. 150821

ps2 should i open a support ticket here?: https://www.websharks-inc.com/support/?product=zencache

**Comment by raamdev** [comment]
> ps. i found out also that the latest rc is bugged on html compressor. it was enabled but the source code wasn't compressed. I tried to reset cache,disable and reenable compressor, disable and reenable the plugin. Nothing. I resolved the html compression activation bug reinstalling the latest public. 150821

@xgiovio I have the v150919 RC running on three sites and the HTML Compressor is working fine. If it would be possible to create a temporary WordPress Dashboard Admin account for me to confirm there's a bug in v150919 RC, that would be very helpful! You can submit details privately here: http://wsharks.com/1itxyUr

**Comment by xgiovio** [comment]
@raamdev It isn't possible. I'm sorry for denying you the request. However it works fine on 150821. If you could assist me with the base64 image problem, it would be fantastic. Thank you for your time.

**Comment by raamdev** [comment]
@xgiovio As @jaswsinc mentioned [above](https://github.com/websharks/zencache/issues/568#issuecomment-142096477), this is not something ZenCache can (or should) do, so I'm afraid it's not going to be possible to rewrite those.

**Comment by xgiovio** [comment]
@raamdev ok but the plugin completely remove the html tag with the content. at least it should ignore ignore it. i upgraded to pro for html compressor and cdn. I'm considering a refund.

**Comment by raamdev** [comment]
@xgiovio You did not mention that the HTML element is being removed completely from the content.

Could you please provide a link to a page where this is happening so that I can observe it? Unless I can reproduce this problem, I cannot troubleshoot it to determine if it's a problem with the ZenCache software.

**Comment by jaswrks** [comment]
> ok but the plugin completely remove the html tag with the content

I was unable to reproduce this given what we know thus far.

> Hello, once enabled cloudfront, images like this one ---> img alt="Embedded Image" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIA..." disapper from the page.

@xgiovio I was unable to reproduce this either. Are you testing in a clean installation?

See: [Testing ZenCache in a Clean WordPress Installation](http://zencache.com/kb-article/testing-zencache-in-a-clean-wordpress-installation/)

**Comment by xgiovio** [comment]
@jaswsinc of course i'm on a production site. no new installation, a paid plugin should work in a production envirovment!

@raamdev i did mention in my first and second post. You should read carefully. However the page is this one: http://www.xgiovio.com. the only method to bypass the problem is adding the whole uri to cdn filter exclusions. In that page check img class="peLazyLoading"

**Comment by raamdev** [comment]
@xgiovio I am using CloudFront with ZenCache Pro on my personal site, https://raam.org. I have created a page that uses `src="data:image/jpg;base64,...."` and you can see that it works just fine with ZenCache Pro + HTML Compressor + CloudFront:

https://raam.org/568-2/ (view source on this page to see)

---

As we are not able to reproduce this issue at all, and you are unwilling to give us access to your site to attempt to debug this further, I'm going to close this issue.

If you'd like to set up a separate test installation of WordPress on your server and create a temporary WordPress Admin account for us to login there and see this issue occurring, we'd be happy to take a closer look.
