### ISSUE TITLE
Bug or feature request. Not all images cached to CDN

### ISSUE THREAD

**Issue by xgiovio** [wpsharks/comet-cache#569]
Hello, if you visit this page http://www.xgiovio.com/data/dslr/ and view the source, there are some links not cached to cdn. For example all a tags with custom attribute data-rsBigImg from royalslider plugin aren't cached. Other examples:

img alt="logo" src="http://www.xgiovio.com/wp-content/uploads/2013/07/footer.png"

link rel="shortcut icon" href="http://www.xgiovio.com/wp-content/uploads/2013/07/favicon.png"

<img alt="logo" src="http://www.xgiovio.com/wp-content/uploads/2013/07/logo_web_smal_2l.png"

etc
Do you have any ideas?

**Comment by jaswrks** [comment]
@raamdev This is related to: https://github.com/websharks/zencache/issues/535

**Comment by raamdev** [comment]
@jaswsinc Thanks! 

@xgiovio It sounds like the RoyalSlider plugin is using a non-standard way of injecting content into WordPress Posts/Pages, which means that ZenCache is not getting a chance to filter those URLs. We have a Feature Request open to improve the way we filter WordPress Posts/Pages using an output buffer (see #535). I'm going to close this GitHub issue in favor of that one and I recommend leaving a comment over there to show your vote for this feature.
