### ISSUE TITLE
Feature Request - Allow editors to clear cache

### ISSUE THREAD

**Issue by MarioKnight** [wpsharks/comet-cache#571]
We manage our clients sites, and have had it set up where we have an admin account, and they have editor accounts, so they only ever have to focus on the content.  We would like to be able to give these accounts access to the "Clear Cache" function on the top admin menu, however there does not appear to be an option for this, nor does there seem to be a way to grant this through a user role plugin.  Thank you for your time and consideration.

**Comment by raamdev** [comment]
@MarioKnight We have a feature request open for this already (see https://github.com/websharks/zencache/issues/68) and this feature was recently worked on and will be released with the next version of ZenCache Pro:

Next Pro Release Changelog:
- **New Feature:** It's now possible to specify which WordPress Roles/Capabilities are allowed to clear the cache from the WordPress Admin bar. A new option inside _Dashboard → ZenCache → Plugin Options → Manual Cache Clearing_ allows specifying a comma-delimited list of Roles and/or Capabilities under, "Also allow others to clear the cache from their Admin Bar?". If a user has an allowed Role/Capability, they will see the "Clear Cache" button in their Admin Bar. This feature is also compatible with WordPress Multisite Networks, allowing a Network Administrator to define which Child Site roles should allow a Child Site user to see the "Clear Cache" button for their Child Site. Props @danielmt2k @jaswsinc. See [Issue #68](https://github.com/websharks/zencache/issues/68).

If you'd like to help with testing a release candidate, please see: http://zencache.com/zencache-pro-v150919-release-candidate/ (And if you're not already on our beta testers list, you can sign-up to be a beta tester [here](http://zencache.com/r/zencache-beta-testers-list/).)
