### ISSUE TITLE
RC Bug :: Cache Stats :: Editor/Author/Contributor

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#572]
## Overview

First reported by @renzms. This bug can result in the error, _"You do not have sufficient permissions to access this page."_ when attempting to view the full-page stats.
## Steps to Reproduce
- Enable ZenCache RC
- Type: `editor` into the list of additional roles allowed to see stats.
- Create a new user with the Editor role.
- Log in as the Editor role.
- Notice that you can see stats in the admin bar (no problem).
- Click the "More Info" button in the admin bar for stats (bug occurs here).
## Expected Behavior

That "More Info" would be shown.
## Observed Behavior

![2015-09-23_12-39-53](https://cloud.githubusercontent.com/assets/1563559/10058106/37c4a534-61f0-11e5-8425-20f3fbc25f78.png)

**Comment by raamdev** [comment]
Closed by https://github.com/websharks/zencache-pro/issues/147.
