### ISSUE TITLE
v150924-RC: More Info button missing in Cache Stats

### ISSUE THREAD

**Issue by kristineds** [wpsharks/comet-cache#573]
## Overview

First reported here: websharks/zencache/issues/572

When logged in as Editor/Author/Contributor,  the cache stats displayed in the Admin bar is missing the "More Info" blue button which can be seen when logged in as Admin
## Steps to Reproduce
- Enable ZenCache v150924-RC
- Type: `editor` or `author` or `editor,author` or `publish_posts` into the list of additional roles allowed to see stats.
- Create a new user with either the Editor or Author role.
- Log in as the Editor/Author role.
- Click the "Cache Stats" in the admin bar
- Information displayed is missing the blue "More Info" button
## Expected Behavior

Blue "More Info" button will be displayed and will redirect to the "More Info" page when clicked. 
## Observed Behavior

![screen shot 2015-09-24 at 6 57 24 pm](https://cloud.githubusercontent.com/assets/7514953/10071997/b283cb64-62f0-11e5-8a79-0fa355dcc8d1.png)

**Comment by jaswrks** [comment]
@raamdev Although I didn't document the fix, this is now the intended behavior. Bug fixed in: https://github.com/websharks/zencache/issues/572.

So I don't consider this to be a bug, because whenever an Administrator grants others access to stats, they are granting them access to stats "in the admin bar", and not to "More Info". I resolved this issue by removing the "More Info" button for those who are being given access to stats "in the admin bar".

**Comment by raamdev** [comment]
@kristineds Thanks for the report. @jaswsinc Thanks for the clarification.

Reviewing the inline docs inside the plugin itself where you set permissions for other roles to view the stats, I see that it is clearly described that this is enabling stats _in the Admin Bar_, and not enabling access to the entire Stats / Charts page, so it makes sense to me that the blue "More Info" button would not be there. 

![2015-09-24_14-52-23](https://cloud.githubusercontent.com/assets/53005/10083405/56203692-62cc-11e5-83de-4a0761afd86d.png)

I'll go ahead and close this issue.

**Comment by jaswrks** [comment]
> When logged in as Editor/Author/Contributor, the cache stats displayed in the Admin bar is missing the "More Info" blue button which can be seen when logged in as Admin

I just want to add that I can completely understand why Kristine opened this issue, as the fix that I suggested at first was more along the lines of exposing "More Info". It wasn't until I actually went to work on this that I changed the approach. So thanks for reporting this. Always better to be safe.
