### ISSUE TITLE
RC Bug :: Cache Stats :: Refresh Broken

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#574]
## Overview

https://github.com/websharks/zencache-pro/pull/148 introduced a very minor issue related to the "Refresh" button for stats. Once the `$chartA` and `$chartB` divs are filled with an `<img />` tag the nested elements are erased, making a refresh not possible; i.e., you need to refresh the entire page instead of being able to click the refresh button.
## Steps to Reproduce
- Enable ZenCache Pro RC.
- Visit the "More Info" page for stats.
- Test with a fresh install; i.e., no stats available at all.
- Notice that placeholder images exist.
- Hit the front page of the site and let it cache you.
- Without refreshing the entire stats page, click the refresh button.
## Expected Behavior

That it would refresh and show you stats, seeing as how stats now exist after you were cached on the front page of the site.
## Observed Behavior

Refresh fails due to the `$chartA` and `$chartB` div children no longer existing. A JavaScript error occurs, which leads to a blank page and failure to refresh the stats.

![2015-09-24_10-55-27](https://cloud.githubusercontent.com/assets/1563559/10083410/db0f1886-62aa-11e5-9e67-f973581d45f8.png)

**Comment by raamdev** [comment]
@jaswsinc Ah, good catch! All we need to do is update the Refresh Stats/Charts button JS to take into account that there might be placeholders there, correct? If you want to outline this for me, I'll get it fixed.

**Comment by jaswrks** [comment]
## Next Actions
- After [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/classes/MenuPageStats.php#L92) add a new empty div placeholder.
  
  ``` php
  echo '<div class="-empty"></div>'."\n";
  ```
  
  _Repeat for chart B in the same file._

---
- Before [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/client-s/js/menu-pages.js#L449) add the following:
  
  ``` js
  $chartA.find('.-heading, .-canvas').hide(), $chartA.find('.-empty').show();
  ```
  
  _Repeat for chart B in the same file._

---
- Change [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/client-s/js/menu-pages.js#L449) to the following:
  
  ``` js
  $chartA.find('.-empty').html('<img style="width:100%;" src="' + plugin.escHtml(plugin.vars.emptyStatsCountsImageUrl) + '" />');
  ```
  
  _Repeat for chart B in the same file._

---
- After [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/client-s/js/menu-pages.js#L442) add the following:
  
  ``` js
  $chartA.find('.-heading, .-canvas').show(), $chartA.find('.-empty').hide();
  ```
  
  _Repeat for chart B in the same file._

---
- **Tip:** While working on this issue you could review the docs for `.find()` here: https://api.jquery.com/find/
- **Tip:** While working on this issue you could review the docs for `.hide()` and `.show()` here:
  - http://api.jquery.com/hide/
  - http://api.jquery.com/show/

**Comment by raamdev** [comment]
@jaswsinc Thank you!

**Comment by jaswrks** [comment]
Sure :-) These little outlines seem to be really helping us a team.

**Comment by raamdev** [comment]
> Sure :-) These little outlines seem to be really helping us a team.

Absolutely! They are SO helpful. They seem to help bridge the various gaps in skill level and keep us productive while at the same time giving us a way to learn by doing (assuming we don't just copy/paste like robots--I was already familiar with `.show()`, `.hide()`, and `.find()`, but I read through all the links you attached anyway!).

**Comment by raamdev** [comment]
Closed by https://github.com/websharks/zencache-pro/issues/149
