### ISSUE TITLE
Lateset Release Candidate - Removes All Body Content From Admin On Every Page

### ISSUE THREAD

**Issue by theperfectwill** [wpsharks/comet-cache#575]
Hi, 

I just downloaded and installed the latest release candidate and when activated (with no other plugins active) the entire Wordpress admin body content area disappears. 

See screenshots 
@ http://take.ms/OBFpf
@ http://take.ms/adEtR

I'm using the latest version of Wordpress.

Is anyone else having this issue? Let me know how I can help if needed.

**Comment by raamdev** [comment]
@NoahjChampion Thanks so much for the report! I haven't been able to reproduce that issue. If you enable debugging (see [WordPress Debugging](https://codex.wordpress.org/Debugging_in_WordPress)) do you get any errors generated when you see that blank page?

**Comment by theperfectwill** [comment]
@raamdev Welcome! I didn't think to even turn debug on. I will try that momentarily and reply back.

**Comment by theperfectwill** [comment]
@raamdev I tried this again with the same set up and everything is fine now. Well, I mean I downloaded the plugin again, so maybe it was something wrong with how my download came the first time. 

Not sure, but I couldn't reproduce this issue again.

**Comment by raamdev** [comment]
@NoahjChampion Thanks for the update. Yeah, I think it was most likely the result of a corrupt download in that case, or something became corrupt somehow during installation.

I appreciate the help testing! :-)

**Comment by theperfectwill** [comment]
@raamdev You're welcome! 

Everything works well for me in the RC.
