### ISSUE TITLE
Exclude .sass and .map files from distributable zip

### ISSUE THREAD

**Issue by bridgeport** [wpsharks/comet-cache#579]
The latest ZenCache pro v151002 looks great. The stats section and admin bar are very slick and informative.

However, it looks like it was packaged with the .sass and .map files. An oversight perhaps?

Location of the .sass files and directories:

```
zencache-pro/src/client-s/css/admin-bar.scss
zencache-pro/src/client-s/css/menu-pages.scss

zencache-pro/src/client-s/css/admin-bar/*
zencache-pro/src/client-s/css/menu-pages/*
zencache-pro/src/vendor/package/bourbon/*
zencache-pro/src/vendor/package/*
```

Location of the .map files:

```
zencache-pro/src/client-s/css/admin-bar.min.css.map
zencache-pro/src/client-s/css/menu-pages.min.css.map
zencache-pro/src/vendor/websharks/sharkicons/src/long-classes.min.css.map
zencache-pro/src/vendor/websharks/sharkicons/src/short-classes.min.css.map
```

**Comment by raamdev** [comment]
@bridgeport Thanks for the reminder. :-) We'll work towards updating our build script to exclude those files. You're right that they're not needed in the distributable zip.

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch: `feature/579` in the `websharks/phings` repo.
- After [this line](https://github.com/websharks/phings/blob/151002/src/psr4/targets/config.xml#L129) add the following.
  
  ``` xml
  <exclude name="vendor/**.scss" />
  <exclude name="**/vendor/**.scss" />
  
  <exclude name="vendor/**.css.map" />
  <exclude name="**/vendor/**.css.map" />
  
  <exclude name="vendor/package/bourbon/**" />
  <exclude name="**/vendor/package/bourbon/**" />
  ```
- After [this line](https://github.com/websharks/phings/blob/151002/src/psr4/targets/config.xml#L38) repeat the same exclusions.
- Submit PR.

**Comment by jaswrks** [comment]
@raamdev While working on this issue you can take note of the FileSet tag provided by Phing and learn more about how `**` is interpreted by Phing: https://www.phing.info/docs/guide/trunk/FileSet.html

**Comment by raamdev** [comment]
Noting that this GitHub Issue should not be closed until the ZenCache Pro repo has been updated to include the latest build script changes (namely everything from https://github.com/websharks/phings/pull/15, but also the changes from https://github.com/websharks/phings/issues/17 which addresses this particular GitHub Issue). 

GitHub Issue to track updating ZenCache Pro with latest Phing build script is here: https://github.com/websharks/zencache.com/issues/72

**Comment by raamdev** [comment]
Build script has been updated and I've confirmed that the `.sass` and `.map` files (along with some other unnecessary files) are excluded from the distributable zip. The next release will have these files excluded. :-)

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: Excluded several unnecessary files from the plugin zip file that were being used during the build process but were not necessary to run the plugin. Props @bridgeport. See [Issue #579](https://github.com/websharks/zencache/issues/579).

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#579).
