### ISSUE TITLE
Cache dir change leaves old files

### ISSUE THREAD

**Issue by clavaque** [wpsharks/comet-cache#580]
Improvement idea:

I just noticed that if I change the cache directory for ZC, the files in the previous one are left there and not removed. I had to remove them via FTP. 

I think it's something ZC should notice and clear it automatically as it does when other big changes happen. Or move it so it doesn't have to generate all the files again.

**Comment by raamdev** [comment]
@clavaque Thanks for the report! I agree, it makes sense for that to be more intelligent.

**Comment by clavaque** [comment]
:+1:

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch: `feature/580` in the `websharks/zencache-pro` repo.
- Replace [this class member](https://github.com/websharks/zencache-pro/blob/151004/src/includes/closures/Plugin/OptionUtils.php#L45-L55) with the following:
  
  ``` php
  $self->updateOptions = function (array $options) use ($self) {
      if (!IS_PRO) { // Do not save lite option keys.
          $options = array_diff_key($options, $self->pro_only_option_keys);
      }
      if (!empty($options['base_dir']) && $options['base_dir'] !== $self->options['base_dir']) {
          $self->tryErasingAllFilesDirsIn($self->wpContentBaseDirTo(''));
      }
      $self->options = array_merge($self->default_options, $self->options, $options);
      $self->options = array_intersect_key($self->options, $self->default_options);
      update_site_option(GLOBAL_NS.'_options', $self->options);
  
      return $self->getOptions();
  };
  ```
- Submit PR.

**Comment by jaswsinc** [comment]
Assigning this to @renzms

**Comment by jaswrks** [comment]
@renzms While working on this issue you can take note of the `array $options` in the function delcaration above, and learn more about PHP type hinting here: http://www.sitepoint.com/type-hinting-in-php/

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: When the Cache Directory location is changed, ZenCache now cleans up the old Cache Directory and any old cache files instead of leaving them behind. Props @clavaque @renzms. See [Issue #580](https://github.com/websharks/zencache/issues/580).

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#580).
