### ISSUE TITLE
Bug: $this Not in Object Context

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#581]
## Overview

These lines, see: https://github.com/websharks/zencache-pro/blob/151002/src/includes/closures/Plugin/WcpUtils.php#L89-L91

And these lines, see: https://github.com/websharks/zencache-pro/blob/151002/src/includes/closures/Plugin/WcpUtils.php#L44-L46

`$this` should be `$self` due to the PHP 5.3 compat. framework and closures. We use `$self` as a workaround in this context, and therefore, `$this` is not valid as expected.

_First reported here in a private ticket: https://websharks.zendesk.com/agent/tickets/8697_

**Comment by jaswrks** [comment]
I should note also that instead of `$this->plugin->` it should just be `$self->`. So we need to change `$this` to `$self` and remove the `->plugin` reference also.

**Comment by raamdev** [comment]
Example of error related to this issue:

> Fatal error: Using $this when not in object context in /home/example/www/wp-content/plugins/zencache-pro/src/includes/closures/Plugin/WcpUtils.php on line 89

**Comment by jaswrks** [comment]
> Fatal error: Using $this when not in object context

I am able to reproduce this, but only on PHP 5.3. It seems the most recent versions of PHP are magically allowing `$this` to work outside of object context; i.e., via an include. That's definitely an unexpected behavior, and yet I am happy that it works to reduce the impact this bug is having.

So this issue is currently PHP 5.3-specific.

**Comment by raamdev** [comment]
Closed by https://github.com/websharks/zencache-pro/issues/150

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed a bug introduced in the previous release that was resulting in a "Fatal error: Using $this when not in object context" for sites running PHP 5.3. (PHP 5.4+ sites were unaffected.) Props @jaswsinc. See [Issue #581](https://github.com/websharks/zencache/issues/581).
