### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bigjake36** [wpsharks/comet-cache#582]
Since the previous update, I have been getting the following error every time I go to save something in WP. In order for me to be able to save anything I need to disable Zencache and once saved I have to re-inable it. The following is the error I have and I don't know how to fix it....

Fatal error: Using $this when not in object context in /home3/bigjake3/public_html/royalnugget/wp-content/plugins/zencache-pro/src/includes/closures/Plugin/WcpUtils.php on line 44

**Comment by raamdev** [comment]
@bigjake36 We're aware of this bug. It only affects servers running PHP 5.3. With PHP 5.4+ the error does not occur. Please see this GitHub issue: https://github.com/websharks/zencache/issues/581

We'll be releasing a patch shortly to fix this for PHP 5.3. Thank you for the report!

**Comment by bigjake36** [comment]
Thank you for the update and I did fix the issue based on what you posted. So far so good and thank you again.
