### ISSUE TITLE
Disable caching for previews

### ISSUE THREAD

**Issue by clavaque** [wpsharks/comet-cache#583]
While editing a page I noticed that the changes I was making were not shown in the preview, until I cleared the cache. 

I think that not caching the preview is the logical thing, you'll always be expecting it to change with your new edits.

I added `preview=true` as a URI exclusion, but I think this should be there by default because it'll confuse other site owners that'll need to figure this out too.

**Comment by raamdev** [comment]
Are you referring to when Logged-In User Caching is enabled?

**Comment by clavaque** [comment]
I have it enabled, yes.

**Comment by raamdev** [comment]
@clavaque Thanks! I'm marking this as a bug.

**Comment by clavaque** [comment]
ok

**Comment by jaswrks** [comment]
@clavaque And you have GET Request caching enabled also, right?

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch: `feature/583` in the `websharks/zencache-pro` repo.
- After [this line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/closures/Ac/ObUtils.php#L152) add the following:
  
  ``` php
    if (!empty($_REQUEST['preview'])) {
      return $self->maybeSetDebugInfo(NC_DEBUG_PREVIEW);
  }
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/closures/Ac/NcDebugConsts.php#L167) add the following:
  
  ``` php
  /**
  * No-cache because it's a preview.
  *
  * @since 15xxxx Adding support for preview detection.
  *
  * @type string A unique string identifier in the set of `NC_DEBUG_` constants.
  */
  const NC_DEBUG_PREVIEW = 'nc_debug_preview';
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/closures/Ac/NcDebugUtils.php#L141) add the following:
  
  ``` php
  case NC_DEBUG_PREVIEW:
      $reason = __('because `$_REQUEST` indicates this is simply a preview of something to come.', SLUG_TD);
      break; // Break switch handler.
  ```
- Submit PR.

**Comment by jaswrks** [comment]
@kristineds While working on this issue you can learn more about the `switch(){}` and `case:` control structure here: http://php.net/manual/en/control-structures.switch.php

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed a bug where post previews were being cached when Logged-In User Caching and GET Request caching were both enabled (both are disabled by default). This release now detects previews in this scenario and excludes those requests from being cached. Props @clavaque @kristineds. See [Issue #583](https://github.com/websharks/zencache/issues/583).

**Comment by clavaque** [comment]
@jaswsinc 

> you have GET Request caching enabled also, right?

That's correct.

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#583).
