### ISSUE TITLE
PHP 7.0 RC1

### ISSUE THREAD

**Issue by HandyGadget** [wpsharks/comet-cache#585]
I am sure you guys know already but ZenCache Pro and PHP 7.0 RC1 don't play nice.

Immediately it loaded it crashed ~ big time.

However, after running the site/cache a short while on PHP 5.6, I switched it back to 7.0 RC1, and this time it seems to be running just fine.

The browser page also crashed, so I didn't keep the error messages.

**Comment by HandyGadget** [comment]
I take that back. I am seeing this now ~ Fatal error: require_once(): Failed opening required '/srv/users/serverpilot/apps/wpexpert/public/wp-admin/admin.phphZ' (include_path='.:/opt/sp/php7.0/lib/php') in /srv/users/serverpilot/apps/wpexpert/public/wp-admin/post.php on line 12 ~ so I am going back to 5.6.

**Comment by raamdev** [comment]
@QloudPress Looking at that error, it doesn't appear that this is related to ZenCache. @jaswsinc Has tested ZenCache Pro on PHP 7 RC1 and had no issues.

That said, we can't certify ZenCache Pro as working with PHP 7 until PHP 7 is actually has an official public release. :-)

**Comment by VR51** [comment]
I'm using ZenCache Pro v.151004 with PHP 7. Works well for me. Neither my Apache logs nor site error logs show errors.

A earlier version of Zen Cache Pro used to crash my home server running, which Apache 2.4.x, PHP 7 and MariaDB, but worked well in a different host environment running PHP 7 that was provided by a popular host company.

**Comment by HandyGadget** [comment]
I am guessing its a combination of core/plugins/theme here rather than just Zen Cache or PHP 7.0

**Comment by jaswrks** [comment]
> I am guessing its a combination of core/plugins/theme here rather than just Zen Cache or PHP 7.0

That is my take also, for the moment. I have tested ZenCache against PHP 7.0 RC1, RC2, and RC3 and I haven't seen any issues thus far. That was testing in a clean installation of WordPress running only ZenCache Pro.

**Comment by luckybhumkar** [comment]
@WPExpert, The solution for your "Fatal error: require_once():..."
Just change the file permission of **wp-config.php** to **644**. That's it. Nothing else.
Source:http://doubtsolver.com/ask/9/permission-denied-in-public_html-wp-load-php-line-wordpress
