### ISSUE TITLE
PHP Notice: Undefined property: Automatic_Upgrader_Skin::$plugin_active

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#589]
A user reported (via [internal ticket](https://websharks.zendesk.com/agent/tickets/8862)) the following PHP Notice in their error log:

> [09-Oct-2015 11:46:33 UTC] PHP Notice: Undefined property: Automatic_Upgrader_Skin::$plugin_active in /home/example/public_html/testing/wp-content/plugins/zencache-pro/src/includes/closures/Plugin/WcpUpdaterUtils.php on line 46

Here's that line in the source code: https://github.com/websharks/zencache-pro/blob/151004/src/includes/closures/Plugin/WcpUpdaterUtils.php#L46

It looks like we need to check if `isset($skin->plugin_active)` before referencing it on that line. Agreed @jaswsinc?

**Comment by jaswrks** [comment]
It looks like we could also change `$skin->plugin_active === true` to:

``` php
is_plugin_active($data['plugin'])
```

**Comment by raamdev** [comment]
@jaswsinc I agree. That's even better. Thanks!

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed an issue where a PHP Notice was generated when an inactive WordPress component was being upgraded. This issue did not have any adverse affect on the site, but this fix resolves the issue so that the notice won't appear in PHP logs. See [Issue #589](https://github.com/websharks/zencache/issues/589).

**Comment by raamdev** [comment]
@jaswsinc Can you confirm that https://github.com/websharks/zencache-pro/commit/542a6f8333fb647e44ed29dab67f05b3713204a0 is correct before I close this issue? I didn't see any use of `$skin` in the code once I replaced `$skin->plugin_active`, but I want to double-check that I'm not missing something. 

Also, I assume that we **do** need to keep the `\WP_Upgrader $upgrader_instance` function parameter for the `upgrader_process_complete` hook, correct?

**Comment by jaswrks** [comment]
>  Can you confirm that websharks/zencache-pro@542a6f8 is correct before I close this issue? 

Yep, https://github.com/websharks/zencache-pro/commit/542a6f8333fb647e44ed29dab67f05b3713204a0 looks like a good choice to me also.

> Also, I assume that we do need to keep the \WP_Upgrader $upgrader_instance function parameter for the upgrader_process_complete hook, correct?

It looks like we aren't using it any longer. However, we are using the second parameter `$data`, so I'd say just leave it. The type hint for `\WP_Upgrader $upgrader_instance` is a sort of built-in sanity check for us. If that happens to change for some reason it will start throwing an exception and we can get it fixed.

**Comment by raamdev** [comment]
@jaswsinc Cool. Thanks for confirming! :smiley:

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#589).
