### ISSUE TITLE
Feature Request: New API Function

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#590]
I'd like to request a new API Function in ZenCache that would allow a site owner to clear the cache for a specific URL. We recently added one that allows you to [clear a specific post ID](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/ApiBase.php#L86), but it would be easier for most people if this could be extended to allow for a specific URL that they provide.
## API Functions That Exist Already

``` php
<?php
require_once dirname(__FILE__).'/wp-load.php';

zencache::version();
zencache::options();
zencache::clear();
zencache::wipe();
zencache::purge();
zencache::clearPost($post_id);
zencache::clearUser($user_id);
zencache::clearCurrentUser();
```
## What I'd like to add...

``` php
zencache::clearUrl($url);
```
## Next Actions
- New feature branch in the `websharks/zencache-pro` repo.
- After [this line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/ApiBase.php#L89) add a new method:
  
  ``` php
  /**
  * This clears the cache for a specific URL.
  *
  * @since 15xxxx Adding support for custom URLs.
  *
  * @param string $url Input URL to clear.
  *
  * @return int Total files cleared (if any).
  */
  public static function clearUrl($url)
  {
      $regex = $GLOBALS[GLOBAL_NS]->buildHostCachePathRegex($url);
      return $GLOBALS[GLOBAL_NS]->clearFilesFromHostCacheDir($regex);
  }
  ```
- Submit PR.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: Added a new API Function that allows a site owner to clear the cache for a specific URL via `zencache::clearUrl($url);`. See [this article](http://zencache.com/kb-article/clearing-the-cache-dynamically/#toc-988085ad) for further details. Props @kristineds. See [Issue #590](https://github.com/websharks/zencache/issues/590).

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#590).
