### ISSUE TITLE
Commented out WP_CACHE definition in wp-config.php being incorrectly ignored 

### ISSUE THREAD

**Issue by davidfavor** [wpsharks/comet-cache#591]
:::: Summary

This relates specifically when moving from WP Super Cache to ZenCache. Likely also effects other caching plugins besides WP Super Cache.

A slight code modification should fix this problem. See details below.

The bottom line is this bug prohibits ZenCache from ever really being enabled, as WP_CACHE remains commented out.

This means ZenCache appears to be slow, as it's code never really executes.

:::: Detailed Explanation

ZenCache appears to sometimes missing updating wp-config.php with the WP_CACHE directive.

Here's how to reproduce this on WP-4.3.1 with all updates installed.

1) Starting point is clean wp-config.php - no caching plugins installed + no wp-config.php directives. Site speed is 45 reqs/sec

2) Install + Activate WP Super Cache. Site speed increases to 2500 reqs/sec with wp-config.php of...
define('WP_CACHE', true); //Added by WP-Cache Manager
define( 'WPCACHEHOME', '/sites/drf/fastseohosting.com/wordpress/wp-content/plugins/wp-super-cache/' ); //Added by WP-Cache Manager

3) Deactivate WP Super Cache + wp-config.php changes to...
//define('WP_CACHE', true); //Added by WP-Cache Manager
define( 'WPCACHEHOME', '/sites/drf/fastseohosting.com/wordpress/wp-content/plugins/wp-super-cache/' ); //Added by WP-Cache Manager

4) Install + Activate ZenCache + wp-config.php no changes (as expected)

5) In ZenCache settings enable + save config + wp-config.php does not change.
//define('WP_CACHE', true); //Added by WP-Cache Manager

WP_CACHE still appears to be commented out.

:::: Suggested Fix

In zencache.inc.php it appears tests for WP_CACHE require being anchored to left, rather than unanchored (floating).

Test likely should be - ^define... - rather than - define... - which will match the commented out define cruft left over from WP Super Cache.

**Comment by raamdev** [comment]
@davidfavor Thanks for the report. This should have been addressed in v150821 (ZenCache Pro) and v150930 (ZenCache Lite). See https://github.com/websharks/zencache/issues/509

I'm going to run a few tests to see if I can reproduce this issue. 

Can you tell me which version of ZenCache you are running?

**Comment by raamdev** [comment]
I have confirmed this bug following @davidfavor's steps above with both ZenCache Lite v150930 and ZenCache Pro (dev branch). 

If the `wp-config.php` file contains the following line, Enabling ZenCache (**ZenCache → Plugin Options → Enable/Disable**) _does not_ uncomment or otherwise set `WP_CACHE` to true in `wp-config.php`, so despite ZenCache being enabled, nothing on the site is actually being cached.

```
//define('WP_CACHE', true); //Added by WP-Cache Manager
```

@jaswsinc It looks like [this regex](https://github.com/websharks/zencache-pro/blob/443256abdbce31e56a8768700104ba5807eaa8d5/src/includes/closures/Plugin/InstallUtils.php#L140) is not taking into consideration that `define('WP_CACHE', true);` may actually be commented out in `wp-config.php`.

**Comment by raamdev** [comment]
The above comment only referenced the ZenCache Pro codebase. Noting here that this should also be fixed in ZenCache Lite (via [this line](https://github.com/websharks/zencache/blob/000000-dev/zencache/zencache.inc.php#L2069)).

**Comment by jaswrks** [comment]
> @jaswsinc It looks like this regex is not taking into consideration that define('WP_CACHE', true); may actually be commented out in wp-config.php.

Good catch guys! I agree, there is room for improvement here.

@raamdev You could try playing with a [negative lookbehind](http://www.regular-expressions.info/lookaround.html) in that line you referenced.

i.e., `(?<!\/\/\s*)`

``` php
if (preg_match('/(?<!\/\/\s*)define\s*\(\s*([\'"])WP_CACHE ...
```

Looks like there is at least one instance of this in the removal routine also that needs to be updated.

**Comment by raamdev** [comment]
@jaswsinc Thanks! I started playing with negative lookbehinds but `preg_match()` (and regex101.com) complains that it must be zero-width:

> Warning: preg_match(): Compilation failed: lookbehind assertion is not fixed length at offset

https://regex101.com/r/aA0yT1/2 

> Error: Lookbehinds need to be zero-width, thus quantifiers are not allowed

Which throws a wrench into the mix. It seems like we can check for one particular scenario (`//define`...) but that won't account for variations such as `// define`. Ideas?

**Comment by jaswrks** [comment]
Nice! I see what you mean. Well, I think it's fine to pull the `\s*` out of the lookbehind.

```
(?<!\/\/)\s*
```

See: https://regex101.com/r/tD0hK0/2

**Comment by jaswrks** [comment]
Ah. Nevermind. Tricky! That doesn't work either.

**Comment by raamdev** [comment]
Yep, I tried that too!

**Comment by raamdev** [comment]
Why don't we just remove `define('WP_CACHE', true);` if we find it in `wp-config.php` and then re-add it? I realize there's a slight performance hit there by doing work unnecessarily in the event that it's _not_ commented out, but this routine is only running once when ZenCache is activated... it's not like it's running on every page load or something.

**Comment by raamdev** [comment]
In other words, just remove [this entire conditional](https://github.com/websharks/zencache-pro/blob/443256abdbce31e56a8768700104ba5807eaa8d5/src/includes/closures/Plugin/InstallUtils.php#L140-L142) and just let the next line (`removeWpCacheFromWpConfig()`) remove it.

**Comment by jaswrks** [comment]
That's a decent idea. However, the reason it's like that right now, is to cover a scenario where the `wp-config.php` is not writable (I do that myself). So for instance, if you have this already defined in your `wp-config.php` file, and ZenCache finds it in there, there is no reason for us to do anything more; i.e., no reason for failure or any notice about us not being able to write to the file.

Here is a modified version of the regex that seems to work. If you can take a closer look I'd appreciate it. See: https://regex101.com/r/fD4wK5/2

```
(?:\n|\<\?(?:php)?|;)\s* ...
```

Instead of doing a lookbehind, we can be more specific about what we want to find. The `define(` fragment should be found right after `<?` or `<?php`, or on a new line by itself, or right after a previous statement that ends with `;` ... and then followed by any amount of whitespace; i.e., `\s*`

**Comment by jaswrks** [comment]
Or, this might be even better. We could strip all comments from the syntax before we check. See: http://php.net/manual/en/function.php-strip-whitespace.php

**Comment by raamdev** [comment]
> it's like that right now, is to cover a scenario where the `wp-config.php` is not writable

Ah, that makes sense. Yeah, that's an important scenario to consider.

> a modified version of the regex

Yep, that seems to work. I ran it through a few tests (including directly in ZenCache) and it's working as expected.

> We could strip all comments from the syntax before we check.

Hmm, that would work too. Any preference?

**Comment by jaswrks** [comment]
My preference would be to strip the comments before we do a check. That seems bulletproof in terms of us being able to accurately detect whether it's really in there or not.

You could then leave the regex as-is. However, while you're in there it's probably a good idea to change:

this:

```
if (preg_match('/define
```

to:

```
if (preg_match('/\bdefine
```

That avoids a false match on something wild like: `my_define('WP_CACHE' ...` by requiring that `define` be preceded by a word boundary.

**Comment by raamdev** [comment]
Next Pro Release Changelog: 
- **Bug Fix**: Fixed a bug where a commented-out `WP_CACHE` definition in `wp-config.php` (such as what WP Super Cache leaves behind) was being incorrectly ignored and resulted in caching being silently disabled. Props @davidfavor. See [Issue #591](https://github.com/websharks/zencache/issues/591).

**Comment by raamdev** [comment]
Next Lite Release Changelog: 
- **Bug Fix**: Fixed a bug where a commented-out `WP_CACHE` definition in `wp-config.php` (such as what WP Super Cache leaves behind) was being incorrectly ignored and resulted in caching being silently disabled. Props @davidfavor. See [Issue #591](https://github.com/websharks/zencache/issues/591).

**Comment by davidfavor** [comment]
Thanks for fixing this so fast!

BTW, the only reason I figured this bug out instantly is I've done the same thing in my code several times.

**Comment by raamdev** [comment]
> the only reason I figured this bug out instantly is I've done the same thing in my code several times.

@davidfavor Ha! Always better to have more eyes on the bugs. :bug: :beetle: Thanks again. :smile:

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#591).
