### ISSUE TITLE
Bug: Unnecessary Cookie Checks

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#592]
## Overview

While working on some `.htaccess` tweaks in other parts of ZenCache, I noticed that we have two unnecessary cookie checks in ZenCache. [This line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/closures/Shared/ConditionalUtils.php#L118) in particular is causing several pages not to be cached whenever there are stray cookies, even when the user is not logged in.
## Next Actions
- New feature branch in the `websharks/zencache-pro` repo.
- Comment [these two lines](https://github.com/websharks/zencache-pro/blob/151004/src/includes/closures/Shared/ConditionalUtils.php#L118-L119) out; i.e., leave them there, but comment them out please.
- Submit PR.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed a bug where in some scenarios a page might not be cached due to a stray `AUTH_COOKIE` or `SECURE_AUTH_COOKIE` cookie, even when the user is not logged in. Props @jaswsinc @renzms. See [Issue #592](https://github.com/websharks/zencache/issues/592).

**Comment by lkraav** [comment]
I can confirm, I have seen caching being incorrectly disabled with the "user is logged in" message. In our case it happened on staging sites, where admin bar is always visible and https://github.com/Rarst/toolbar-theme-switcher is used for hopping between themes.

**Comment by raamdev** [comment]
@lkraav Thanks for the update. :-) If you still experience this issue after the next Pro release, please let us know and we can reopen this GitHub issue.

**Comment by jaswrks** [comment]
It looks like we can also optimize this routine a bit further, now that we no longer have to consider cookie names that begin with `wordpress_`. I haven't looked carefully at this, but at first glance it looks like there is still room for some improvement in [these lines](https://github.com/websharks/zencache-pro/blob/151004/src/includes/closures/Shared/ConditionalUtils.php#L127-L132).

i.e., that perhaps we can remove those and simplify this routine overall now. That would help, because that routine is called at least once on every page load.

**Comment by raamdev** [comment]
@jaswsinc I assume this can be closed now that https://github.com/websharks/zencache-pro/pull/168 has been merged, correct?

**Comment by jaswrks** [comment]
Yes. Thanks!

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#592).
