### ISSUE TITLE
Possible PHP7 Compatibility Issue

### ISSUE THREAD

**Issue by distinctperspective** [wpsharks/comet-cache#598]
So I am running on Ubuntu Trusty 14.01 on digitalocean and using ServerPilot's PHP7 stack....  crashes every time

Fatal error: require(): Failed opening required '/srv/users/serverpilot/apps/aeriographerdev/public/wp-blog-header.phpALT' (include_path='.:/opt/sp/php7.0/lib/php') in /srv/users/serverpilot/apps/aeriographerdev/public/index.php on line 17 (adding the ALT) to the urls for some reason.   if I swtich the runtime back to php 5.6 its fine.  i really need this to run on 7

**Comment by raamdev** [comment]
@dthreatt I'm not seeing any mention of ZenCache in that error message. How are you determining that ZenCache is the problem here? Can you tell me which RC of PHP7 you're running? We've ran a few tests against PHP7 and have not seen any issues so far.

**Comment by distinctperspective** [comment]
if I turn on your plugin I get the error.... if I turn it off I dont.....

http://dev.aeriographer.com

PHP 7.0.0RC5 (cli) (built: Oct 16 2015 17:41:28) ( NTS )

Copyright (c) 1997-2015 The PHP Group

Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies

```
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend
```

Technologies

**Comment by distinctperspective** [comment]
PHP 7.0.0RC5 (cli) (built: Oct 16 2015 17:41:28) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

if I turn on your plugin I get the error.... if I turn it off I dont.....

this is the ONLY plugin installed on the fresh dev site
4.3.1 WP
http://dev.aeriographer.com

![screen shot 2015-10-31 at 8 46 47 pm](https://cloud.githubusercontent.com/assets/8387791/10867143/99a08d0c-8010-11e5-9b59-6fccf45f16da.jpg)
![screen shot 2015-10-31 at 8 44 39 pm](https://cloud.githubusercontent.com/assets/8387791/10867144/99a0da6e-8010-11e5-9c60-0550143764c2.jpg)
![screen shot 2015-10-31 at 8 44 28 pm](https://cloud.githubusercontent.com/assets/8387791/10867142/999e2e18-8010-11e5-8ab2-7ffb6a609438.jpg)
![screen shot 2015-10-31 at 8 44 04 pm](https://cloud.githubusercontent.com/assets/8387791/10867145/99a11614-8010-11e5-98ea-549964c6552f.jpg)

![screen shot 2015-10-31 at 8 48 39 pm](https://cloud.githubusercontent.com/assets/8387791/10867154/d2ec0afa-8010-11e5-9d2b-8dafc6caf07c.jpg)
![screen shot 2015-10-31 at 8 48 01 pm](https://cloud.githubusercontent.com/assets/8387791/10867155/d2ec887c-8010-11e5-8aad-3f83ceac0fea.jpg)

![screen shot 2015-10-31 at 8 49 37 pm](https://cloud.githubusercontent.com/assets/8387791/10867157/f386509a-8010-11e5-95b8-49bb34f12e0c.jpg)

**Comment by distinctperspective** [comment]
I just did a few more test....the LITE version works fine on PHP7 seems the issue is with the PRO version... I really need this to work because I am using domain sharding.

**Comment by raamdev** [comment]
@dthreatt Thank you for the report and the additional information. We'll take a closer look at this.

Keep in mind that PHP7 has not been publicly released yet. It's still in the Release Candidate period. Until there is a public release, we cannot make any promises about the stability of ZenCache with PHP7.

**Comment by jaswrks** [comment]
@dthreatt What you reported in your last screenshot...

> `file_exists` expects parameter 1 ...

This could be an encoding problem in your `/wp-config.php` file. I would suggest that you try to reproduce this again, and this time if you get the same error, open `/wp-config.php` and inspect the file carefully. In particular, look to see if there are any strange characters or a problem with the `ABSPATH` definition. If you can't find a problem, please remove any sensitive information and post the contents of that file here for us to review with you.

Do you edit your `/wp-config.php` file with an editor that is powered by your hosting provider? Or what editor are you using to make changes to that file?

**Comment by distinctperspective** [comment]
lol, no, I only edit using VI or nano from thessh shell.  I am an advanced user.... not a newbie.

**Comment by jaswrks** [comment]
Copy. Do you have either of these configured to include a BOM marker in UTF-8 files?

**Comment by jaswrks** [comment]
What I'd look for are any differences between the encoding of `/wp-config.php` as it exists after you edit it, and what PHP is configured to work in. By default, PHP 7 should be working in UTF-8 (depending on what your `.ini` file specifies). If there is an encoding conflict, whenever ZenCache adds the `define('WP_CACHE', true);` line to your `/wp-config.php` file, some corruption could occur in that file, which might lead to strange problems like the one you reported above.

**Comment by jaswrks** [comment]
I have tested ZenCache against PHP 7 RC1, RC2, RC3, RC4, RC5, RC6, and RC7. I have not seen this issue yet myself.

**Comment by jaswrks** [comment]
To clarify, in this screenshot you posted earlier, the only way that I'm seeing this could occur is if the `ABSPATH` constant (defined in `/wp-config.php`) contains invalid characters. The only way that I'm seeing that is possible (in response you to enabling ZenCache), is if the `wp-config.php` file is getting corrupted due to an encoding issue.

> ![screen shot 2015-10-31 at 8 46 47 pm](https://cloud.githubusercontent.com/assets/8387791/10867143/99a08d0c-8010-11e5-9b59-6fccf45f16da.jpg)

**Comment by distinctperspective** [comment]
I acutally dont edit the file...the server edits its.  i tore down that environment...but ill put it back up and send you the SSH information.  how do I send that to you?

**Comment by jaswrks** [comment]
What I'd prefer is to see the contents of your `/wp-config.php` file whenever the bug is reproduced. If you can help us out by saving the `/wp-config.php` file when this occurs, we can inspect the file and learn more about any corruption that might be occurring.

Please remove any sensitive information from the file, and then use a service like CloudUp to share the file with us here. See: https://cloudup.com/

In addition, please share a screenshot and/or a URL which points to a `phpinfo()` page that we can review as a part of this bug report. For instance, a PHP file that contains:

``` php
<?php
phpinfo();
```

**Comment by jaswrks** [comment]
@dthreatt Any more insight you can offer on this? Thanks in advance! :-)

**Comment by distinctperspective** [comment]
I havent had time to setup anything.  Ill get it up this weekend for you to
look at.

**Comment by luckybhumkar** [comment]
@dthreatt , The solution for your "Fatal error: require_once():..."
Just change the file permission of **wp-config.php** to **644**. That's it. Nothing else.
Source:http://doubtsolver.com/ask/9/permission-denied-in-public_html-wp-load-php-line-wordpress

**Comment by raamdev** [comment]
Closing; cannot reproduce any adverse behavior with the latest version of PHP 7 at this time.
