### ISSUE TITLE
HTML Compression: Some inline script tags not closed.

### ISSUE THREAD

**Issue by teichfeld** [wpsharks/comet-cache#599]
I am running the White Label Login plugin, which itself is kinda buggy, but it looks liek the admins section is getting an end tag missing when HTML + Inline JS compression is enabled.
Take a look at the first '<script>jQuery(document.ready(function($){ call' .  on line 11 of the attached.  The tag is not closed after load_registered_licenses(); So it looks liek an off by one error in the handling of the end tags fro some reason...  Also looks like it mised some whitespace?

Please let me know if this is known, adn if there is somethign I can do to fix, (other than disabling the HTML Minification)
Here is a snippet:

...
</script> <script>jQuery(document).ready(function($){</script><script type='text/javascript'>jQuery(document).ready(function($){    $('#submit_license').unbind('click').click(function(e){ $('#add-license-msg').html('Adding license').addClass('add-license-message').removeClass('add-license-error').fadeIn(); var url = 'dev.lawley.com'; var args = {    'action':'add-license-spl', 'license_key':$('#add_license_key').val()   };  $.post(ajaxurl,args,function(data){ if(data.R=='OK'){   $('#add-license-msg').html('Done, reloading license keys').show().addClass('add-license-message').removeClass('add-license-error').fadeOut('slow'); load_registered_licenses(); }else if(data.R=='ERR'){    $('#add-license-msg').html(data.MSG).removeClass('add-license-message').addClass('add-license-error').show();   }else{  $('#add-license-msg').html('Service not available.').removeClass('add-license-message').addClass('add-license-error').show();   }   },'json');  }); load_registered_licenses();
});
...

HTML Compression, Inline JS Compression

**Comment by raamdev** [comment]
@teichfeld It looks like part of your message was cut off there.

It's strange to me that ZenCache would be affecting anything on the Admin side of things, because it's designed to only touch things on the front-end of the site.

How are you determining that ZenCache is at fault there? If you're simply disabling ZenCache, then keep in mind the problem may actually be a conflict with the White Label Login plugin and perhaps not an issue with ZenCache itself.

**Comment by teichfeld** [comment]
Hi rram. I am certain you are correct. White Label Login has some issues with JS conflicts. I will continue looking at it in the White Label Login code.  Thanks much :)
