### ISSUE TITLE
Autocache clearing clears entire cache

### ISSUE THREAD

**Issue by mastermikeywwt** [wpsharks/comet-cache#602]
Despite having completely disabled autocache clearing. Every time any change is made the entire sites cache is cleared. Anyway to avoid this happening?

**Comment by raamdev** [comment]
@mastermikeywwt Can you explain what you mean by "autocache clearing"? Which setting, specifically, did you disable?

Could you also give an example of a change on the site that clears the entire cache?

**Comment by mastermikeywwt** [comment]
I'm referring to 'Automatic Cache Clearing'. I have completely disabled every setting here. Now whenever I update a product or a page. Every single page on the site has its cached cleared.

**Comment by raamdev** [comment]
It sounds like you're using a plugin or theme that is hooking into various WordPress hooks that are inadvertently triggering the site-wide cache clearing routines that are supposed to only fire when doing things like upgrading WordPress or changing a core WordPress setting.

If you want to completely disable the automatic clearing routines, you can do so as described in this article:
-  [Disabling Automatic Clear / Wipe Cache Routines](http://zencache.com/kb-article/disabling-automatic-clear-wipe-cache-routines/)

Can you try that and let me know if that works for you?

**Comment by raamdev** [comment]
@mastermikeywwt Are you still having an issue here, or can I close this issue?

**Comment by mastermikeywwt** [comment]
Sorry I forgot to respond. You resolved the problem for me. Thankyou very much, you can close the issue :)
