### ISSUE TITLE
Deactivating ZenCache Pro from Plugins Panel Removes Autocache from WP-Cron

### ISSUE THREAD

**Issue by patdumond** [wpsharks/comet-cache#603]
Reference: https://websharks.zendesk.com/agent/tickets/9223

If ZenCache Pro is deactivated from the WordPress Plugins panel `autocache` job is removed from WP-Cron, disabling Auto-Cache. 

Steps to reproduce: 
1. Install WP-Crontrol plugin.
   1.Wait about 5 minutes to be sure you see the cron job for the Auto-cache **WordPress Dashboard → Tools → Cron Events**.
2. Deactivate ZenCache Pro from the Plugins panel.
3. Wait to verify that Autocache entry did not reappear in the Cron Events panel.

I waited an hour and it didn't reappear. So I went back into **ZenCache Options**, checked that the Auto-Cache was enabled and "Saved All Settings" just to be sure. Waited another 15 minutes and nothing. It only took 5 minutes for it to disappear so 5 minutes should have been enough for it to reappear.

**\* Temporary Workaround

From **WordPress Dashboard → ZenCache → ZenCache Options** click the _Restore_ button at the top of the screen to force the CRON to be reactivated properly.

![ZenCache Options Page - Restore Button Location](https://cloud.githubusercontent.com/assets/9320495/10978075/fb0b358c-83c2-11e5-9d2c-2d78be2d7a8e.jpg)

**Comment by raamdev** [comment]
@patdumond I'm moving this to https://github.com/websharks/zencache/issues/613#issuecomment-158513720 (that issue reports the same issue and has more updates).
