### ISSUE TITLE
CloudFlare Issue

### ISSUE THREAD

**Issue by bigjake36** [wpsharks/comet-cache#604]
I switch hosting service from HostGator to A2 Hosting, which was the best thing I ever did !! The service offered CDN support via CloudFlare for free. The other day I tried to activate the CloudFlare option and started noticing that the main page of my site was getting trashed. In other words, some images were missing other plugins didn't work and script files were getting screwed up. For almost 2 days the tech's and I tried to figure out the issue and had no idea as to why the problems. Then today, just for the fun of it I turned CloudFlare off and left Zencache on and guess what the problems went away and things were back to normal. I informed A2 Hosting to let them know I fixed the problem by turning CloudFlare off. Their support responded quickly and made the following comment.

"Some caching plugins, like W3 Total Cache, offer ways to control Cloudflare from within the plugin. I didn't see this as an option in ZenCache, but if something like that does exist in the plugin, it could explain why rocketoptimized kept getting added to scripts."

I don't know if this can be fixed or adjusments made, but I thought I'd drop you a note to let you know of a possiable problem.

Thank you and I do like ZendCache much more than W3 as it seems more stable.

**Comment by lkraav** [comment]
RocketScript is also a standalone toggle in your CloudFlare control panel. Might not have to turn the whole thing off.

**Comment by raamdev** [comment]
@bigjake36 Thank you very much for the information. :-) ZenCache does not yet have any CloudFlare options integration, however we do have a feature request open for that here: https://github.com/websharks/zencache/issues/418 (I recommend leaving a comment on that GitHub issue to show your vote for this feature.)

You probably need to disable RocketScript inside your CloudFlare control panel, as @lkraav suggested. However, it sounds to me like this might be a conflict specifically between CloudFlare's RocketScript and the ZenCache HTML Compressor feature, which both do a similar thing. 

If you don't want to turn off RocketScript, you could try disabling the HTML Compressor and see if that solves the problem.
