### ISSUE TITLE
Bug :: Pagination Var Translation Breaks Cache Clearing

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#607]
A user writes...

> I've run into a bug with my setup. The Auto Clear feature fails to clear "paged pages" (e.g. the second page of the Home Page). I have identified the problem and am looking for a solution which doesn't involve editing core files.
> 
> Usually wordpress is set up like this (and everything works fine): 
> http://domain.com 
> http://domain.com/page/2
> 
> However I have translated the pagination_base into german, so it looks like this: 
> http://domain.com 
> http://domain.com/seite/2
> 
> Now in this case the second page fails to auto-clear.
> 
> I solved this issue by editing line 131 of "CachePathConsts.php" in /src/includes/closures/Shared
> 
> from
> 
> `const CACHE_PATH_REGEX_DEFAULT_SUFFIX_FRAG = '(?:\/index)?(?:\.|\/(?:page\/[0-9]+|comment\-page\-[0-9]+)[.\/])';`
> 
> to
> 
> `const CACHE_PATH_REGEX_DEFAULT_SUFFIX_FRAG = '(?:\/index)?(?:\.|\/(?:seite\/[0-9]+|comment\-seite\-[0-9]+)[.\/])';`
> 
> Is there a setting or filter I can use to change this constant instead?

**Comment by jaswrks** [comment]
Referencing: http://wordpress.stackexchange.com/a/57090/81760

**Comment by jaswrks** [comment]
Referencing:
- [`pagination_base`](https://github.com/WordPress/WordPress/blob/77e365efbf2e499e2ed11d29c101ea466cf1ceed/wp-includes/class-wp-rewrite.php#L111)
- [`comments_pagination_base`](https://github.com/WordPress/WordPress/blob/77e365efbf2e499e2ed11d29c101ea466cf1ceed/wp-includes/class-wp-rewrite.php#L120)
- [`feed_base`](https://github.com/WordPress/WordPress/blob/77e365efbf2e499e2ed11d29c101ea466cf1ceed/wp-includes/class-wp-rewrite.php#L129)
- [`comments_base`](https://github.com/WordPress/WordPress/blob/77e365efbf2e499e2ed11d29c101ea466cf1ceed/wp-includes/class-wp-rewrite.php#L103)

**Comment by jaswrks** [comment]
## Next Actions (Step 1 of 2)
- New feature branch in the `websharks/zencache-pro` repo.
- After [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/closures/Shared/CachePathUtils.php#L3) add the following:
  
  ``` php
  /*
  * Cache-path suffix frag (regex).
  *
  * @since 15xxxx Enhancing translation support.
  *
  * @param string $regex_suffix_frag Existing regex suffix frag?
  *
  * @return string Cache-path suffix frag (regex).
  */
  $self->cachePathRegexSuffixFrag = function ($regex_suffix_frag = CACHE_PATH_REGEX_DEFAULT_SUFFIX_FRAG) use ($self) {
      if ($regex_suffix_frag === CACHE_PATH_REGEX_DEFAULT_SUFFIX_FRAG) {
          return $self->cachePathRegexDefaultSuffixFrag();
      }
      return (string) $regex_suffix_frag;
  };
  
  /*
  * Default cache-path suffix frag (regex).
  *
  * @since 15xxxx Enhancing translation support.
  *
  * @return string Default cache-path suffix frag (regex).
  */
  $self->cachePathRegexDefaultSuffixFrag = function () use ($self) {
      if ($self->isPlugin() && !empty($GLOBALS['wp_rewrite'])){
          $pagination_base          = $GLOBALS['wp_rewrite']->pagination_base;
          $comments_pagination_base = $GLOBALS['wp_rewrite']->comments_pagination_base;
          return '(?:\/index)?(?:\.|\/(?:'.preg_quote($pagination_base, '/').'\/[0-9]+|'.preg_quote($comments_pagination_base, '/').'\-[0-9]+)[.\/])';
      } else {
          return '(?:\/index)?(?:\.|\/(?:page\/[0-9]+|comment\-page\-[0-9]+)[.\/])';
      }
  };
  ```
- Submit PR.

**Comment by jaswrks** [comment]
## Next Actions (Step 2 of 2)
- New feature branch in the `websharks/zencache-pro` repo.
- Replace [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/closures/Shared/CachePathConsts.php#L140) with the following:
  
  ``` php
  const CACHE_PATH_REGEX_DEFAULT_SUFFIX_FRAG = null;
  ```
- In [this file](https://github.com/websharks/zencache-pro/blob/443256abdbce31e56a8768700104ba5807eaa8d5/src/includes/closures/Shared/CachePathUtils.php) find all occurrences of:
  
  ``` php
  $regex_suffix_frag = (string) $regex_suffix_frag;
  ```
  
  _Find occurrences where the function that you find it in accepts the parameter `$regex_suffix_frag = CACHE_PATH_REGEX_DEFAULT_SUFFIX_FRAG`. One such case is found [here](https://github.com/websharks/zencache-pro/blob/443256abdbce31e56a8768700104ba5807eaa8d5/src/includes/closures/Shared/CachePathUtils.php#L161)._
  
  Change:
  
  ``` php
  $regex_suffix_frag = (string) $regex_suffix_frag;
  ```
  
  to:
  
  ``` php
  $regex_suffix_frag = $self->cachePathRegexSuffixFrag($regex_suffix_frag);
  ```
- Submit PR.

**Comment by jaswrks** [comment]
Assigning this to @renzms :-)

**Comment by shazzygh** [comment]
Hey,
user who sent the original request here. Thanks for working on this!

Just wanted to note that I'm using `$GLOBALS['wp_rewrite']->pagination_base = 'seite';` to do the translation job as well (not sure if it's the only way, but the most popular for sure).

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed a bug with clearing cache files for paginated pages where the `pagination_base` had been changed from the default `page` to something else (e.g., a translated string). The WP Rewrite API is now used to include `pagination_base` and `comments_pagination_base` when building paths to cache files to determine which cache files should be cleared. Props @renzms. See [Issue #607](https://github.com/websharks/zencache/issues/607).

**Comment by raamdev** [comment]
**ZenCache Pro v151220** has been released and includes changes worked on as part of this GitHub Issue. See the [release announcement](http://zencache.com/zencache-pro-v151220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#607).
