### ISSUE TITLE
Error page and server http crash when we save changes

### ISSUE THREAD

**Issue by iaoweb** [wpsharks/comet-cache#609]
Hi, we are getting error blank page and http server crash each time we Save Changes in admin. We have a licensed version. I will have to restart httpd at server to revive the site. Does not happen in free version.

/wp-admin/admin.php?page=zencache&zencache_updated=1

**Comment by raamdev** [comment]
@rafflesiao We reserve GitHub for filing bug reports and making feature requests. Please open a [Trouble Ticket](https://www.websharks-inc.com/support/?product=zencache&request_type=trouble_ticket) and we'll do what we can to help you with this issue. Thank you! :)
