### ISSUE TITLE
Make Trouble Ticket Easy to Submit at Plugin Page

### ISSUE THREAD

**Issue by iaoweb** [wpsharks/comet-cache#610]
We weren't aware how we should submit trouble ticket until you have provided the direct link. Would be good if submitting trouble ticket link is available at Plugin page itself on the top right.

**Comment by jaswrks** [comment]
@iaoweb Thank you for the feedback :-)

**Comment by raamdev** [comment]
@iaoweb Thanks for the feedback! I created a GitHub issue to track this here: https://github.com/websharks/zencache/issues/612
