### ISSUE TITLE
Bug :: Watered-Down Regex Syntax

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#611]
- Here is [the updated routine](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/closures/Shared/CachePathUtils.php#L267) that converts a line-delimited list of URIs into regex patterns.
- And, [the updated routine](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/closures/Shared/CachePathUtils.php#L238) that converts a single URL that you enter into a regex pattern.

_There is still room for improvement in these routines. I am already seeing the potential for minor conflicts between the [intended functionality](http://zencache.com/kb-article/watered-down-regex-syntax/) (i.e., what we have in the article) vs. what actually takes place._

**Comment by raamdev** [comment]
@jaswsinc Could you clarify for me what the bug is here?

**Comment by jaswrks** [comment]
The `^` and `$` characters are not supported in:
- **Dashboard → ZenCache → Automatic Cache Clearing → XML Sitemap Patterns**
  The `^` and `$` characters are not supported there. The KB article says they are, but in truth that is not the case.
- The same is true for Custom URLs that you list and/or for a Specific URL that you give ZC.

_Referencing: [this line](https://github.com/websharks/zencache-pro/blob/151216-RC/src/includes/closures/Shared/CachePathUtils.php#L272) and [this line](https://github.com/websharks/zencache-pro/blob/151216-RC/src/includes/closures/Shared/CachePathUtils.php#L314)_.

The reality is that in these use cases, the `^` and `$` are always applied, no matter what you enter.

---

So that's why I opened this issue, because I remember reading over the KB article and reviewing the new descriptions that we gave in the ZC UI. I was concerned that suggesting the use of `^` and `$` in those areas would lead to unexpected results internally.

---

~~However, now that I'm taking a closer look, I think it's fine.~~

Scratch that. It's not fine. Ugh, this is a confusing issue, because _most of the time_ it's fine. However, there are some example use cases I can think of where a site owner (e.g., one who thinks that `^` and `$` are supported in these areas), might write their patterns _without_ them; i.e., expecting that `/something/` implies `**/something/**`, when it in fact in is handled internally as `^/something/$`

For instance, what if a site owner wants to clear this specific URL?

```
/a/path/to/something/
```

Internally, that is translated into:

```
^/path/to/cache/directory/.../a/path/to/something/$
```

So for that reason, in the areas that I listed above, that pattern would need to be written as:

```
**/a/path/to/something/**
```

Why? Because we have a couple of routines in ZenCache where `^` and `$` are stripped from your pattern, and then forced into play whenever a directory scan is done.

---

## What needs to change?

I'm not entirely sure yet.
- A quick fix might be to update the article and the dashboard panels for those areas.
- A better fix would be to update the codebase so that these patterns are applied as they should be. However, there might be some hoops we need to jump through in order to pull that off; i.e., it appears to me that implementing this could take some work. It's not going to be a quick fix.

**Comment by raamdev** [comment]
@jaswsinc Got it. Thanks so much for clarifying the issue. Perfectly clear now. :-)

**Comment by raamdev** [comment]
@jaswsinc writes...

> A better fix would be to update the codebase so that these patterns are applied as they should be. However, there might be some hoops we need to jump through in order to pull that off; i.e., it appears to me that implementing this could take some work. It's not going to be a quick fix.

Could I get an estimate on that?

**Comment by jaswrks** [comment]
Approx. 1 day of refactoring.

**Comment by jaswrks** [comment]
I updated the inline docs to make note of the exceptions; i.e., I improved the instructions provided to a user for each field where `^` and `$` are tricky and should not be used. I also updated this KBA: https://cometcache.com/kb-article/watered-down-regex-syntax/

**Comment by renzms** [comment]
@raamdev 

### Multibyte support Confirmed as working


**Front End Cache notes and Post**
Cache has been generated.
![screen shot 2016-12-15 at 8 55 00 pm](https://cloud.githubusercontent.com/assets/13220018/21224957/8bc77a5a-c309-11e6-9005-8ddc70d0abb1.png)


**Updating Post with Emoji in URL**
Cache is automatic cleared when post is updated.

![screen shot 2016-12-15 at 8 56 19 pm](https://cloud.githubusercontent.com/assets/13220018/21224956/8bc4d5e8-c309-11e6-9a1a-5ef5b6ff070e.png)

**Front End Cache notes**
Cache has been updated.

![screen shot 2016-12-15 at 8 57 49 pm](https://cloud.githubusercontent.com/assets/13220018/21224955/8bc114a8-c309-11e6-8f52-9c3069c047e5.png)

**Comment by raamdev** [comment]
**Comet Cache v161221** has been released and includes changes from this GitHub Issue. See the [v161221 announcement](https://cometcache.com/blog/comet-cache-v161221-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#611).
