### ISSUE TITLE
Add support-related links to plugin options page

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#612]
As mentioned in https://github.com/websharks/zencache/issues/610, it would be nice to include several support-related links at the top of the plugin options page:

![2015-11-13_12-24-11](https://cloud.githubusercontent.com/assets/53005/11152598/8c8bfb4c-8a01-11e5-9a5f-04de6cea9af8.png)

I would add [Knowledge Base](http://zencache.com/kb/), [Support](http://zencache.com/support/), and [Blog](http://zencache/blog/) to the Pro version, and [Knowledge Base](http://zencache.com/kb/), [Community Forum](http://wordpress.org/support/plugin/zencache), and [Blog](http://zencache/blog/) to the Lite version.

**Comment by jaswrks** [comment]
@renzms This might be a good one for you to tackle, since you have already worked with this specific area of the code in ZenCache before. Would you like to give this a shot? If so, let us know so that we can assign this to you. Thanks man! :-)

**Comment by renzms** [comment]
@jaswsinc @raamdev 

Sure, I'll take this one!

> I would add Knowledge Base, Support, and Blog to the Pro version, and Knowledge Base, Community Forum, and Blog to the Lite version.

These should all open in new tab/window correct?

**Comment by jaswrks** [comment]
:-) Cool!

**Comment by renzms** [comment]
@raamdev 

On your link for the blog I think you meant: http://zencache.com/blog/

Your link up there currently goes to: **zencache/blog/**

**Comment by renzms** [comment]
@raamdev @jaswsinc Tested, submitting PR

![screen shot 2016-01-28 at 10 45 31 pm](https://cloud.githubusercontent.com/assets/13220018/12647609/e2f9ce96-c610-11e5-8095-04e05abce86c.png)

**Comment by jaswrks** [comment]
ha. It would be cool if we owned `http://zencache`

**Comment by jaswrks** [comment]
Better: `zencache://blog`

**Comment by raamdev** [comment]
@renzms I made a few tweaks (see https://github.com/websharks/zencache-pro/commit/38806c7479985fdb77bb93e497adced72df6b782 and https://github.com/websharks/zencache-pro/commit/f2da851e6db1aae6f9abcc479cd5044e8a015499) and I'm attaching screenshots below.

### Lite version

![2016-02-21_08-53-25](https://cloud.githubusercontent.com/assets/53005/13202951/dea2a9d8-d878-11e5-8eb9-31c70919d771.png)

### Pro version

In the Pro version, the mailing list links are moved up to make use of the space vacated by the Pro Preview and Pro Upgrade links, which are not shown in the Pro version.

![2016-02-21_08-52-35](https://cloud.githubusercontent.com/assets/53005/13202953/e7ebab7a-d878-11e5-9f3b-674abcb7c093.png)

The Plugin Updater and the Stats/Charts page has also been updated:

![2016-02-21_08-55-13](https://cloud.githubusercontent.com/assets/53005/13202966/29de966e-d879-11e5-96b1-c4d59a48a90f.png)

![2016-02-21_08-57-59](https://cloud.githubusercontent.com/assets/53005/13202969/396d098a-d879-11e5-858f-2d88f3024471.png)

**Comment by raamdev** [comment]
Next Lite Release Changelog:
- **Enhancement**: Added support-related links to the plugin options page.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: Added support-related links to the plugin options page.

**Comment by raamdev** [comment]
**ZenCache v160222** has been released and includes changes from this GitHub Issue. See the [v160222 announcement](http://zencache.com/zencache-v160222-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#612).
