### ISSUE TITLE
3rd Party Plugin Compatibility: Slider Revolution

### ISSUE THREAD

**Issue by moretarman** [wpsharks/comet-cache#614]
I installed the pro version of Zencache, and enabled the HTML Compression option. All of the pages are properly minimized and compressed on the site, including those making use of Visual Composer. 

However, the one page that has the Slider Revolution plugin active refused to compress (HTML/JS/CSS). The unminified page still caches, though.

**Comment by jaswrks** [comment]
@moretarman Thanks for the report! :-)

You're talking about this plugin right? http://codecanyon.net/item/slider-revolution-responsive-wordpress-plugin/2751380 ~ Is there a free version that we can test against?

**Comment by moretarman** [comment]
Yes, that's the one. Let me know if there's anything I can do to help you track down the issue

**Comment by raamdev** [comment]
@moretarman Is there a free version of the plugin that we can test with?

**Comment by moretarman** [comment]
I checked if there was a free version, but I couldn't find one.

**Comment by raamdev** [comment]
@moretarman Thank you. Unfortunately that makes this difficult to test. I'll leave this GitHub issue open so that we can look into acquiring a copy of that plugin to test against.

**Comment by moretarman** [comment]
I've asked the developers of I can temporarily transfer my license to you, I'll keep you posted

**Comment by moretarman** [comment]
All right, the developers have confirmed that I can send you guys a copy to test locally. Do you have an email address where I can send it?

**Comment by raamdev** [comment]
@moretarman You can use the following link: http://bit.ly/1OQOJO9 (expires in 24 hours). Please let me know when you've submitted it.

**Comment by moretarman** [comment]
I tried to attach the plugin on that page, but I received a "FILE IS TOO BIG" error message. (it's a 5 MB zip)

**Comment by jaswrks** [comment]
> ILE IS TOO BIG" error message. (it's a 5 MB zip)

Very sorry about this. I bumped this limit up to 7MB max so you should be able to do this now. Please try this again when you get a moment. Here is a new link in case the old one expired. http://bit.ly/1PChOwJ

---

_Noting that we can now accept up to 7MB uploads; same as Zendesk limit._

**Comment by moretarman** [comment]
All right, got it through!

**Comment by raamdev** [comment]
@moretarman Can you tell me the ticket number?

**Comment by moretarman** [comment]
9590 I think

**Comment by raamdev** [comment]
@moretarman I spent the past hour reviewing the Revslider plugin and testing it against the ZenCache HTML Compressor. I'm not seeing any immediate fix on our end and it's not entirely clear to me why Revslider is breaking the HTML Compressor. 

I did find that if I disable the HTML Compressor option to "combine CSS/JS from remote resources" (**ZenCache → Plugin Options → HTML Compression → HTML Compression Options → No, do not combine CSS/JS from remote resources**), that the page with Revslider compresses just fine,  however the browser then reports two JavaScript errors related to the Revslider code. From what I can tell, those errors don't affect the slider itself, as it still appears just fine. 

I do see that Revslider fixed an issue with W3TC's Minifying engine back in Version 4.6.5 SkyWood (2nd December 2014):
- Fixed Compatibility issues with W3C Total Cache Minifying engine

I suspect a similar fix may be necessary for ZenCache's HTML Compression engine. If the developers for Revslider need a copy of ZenCache Pro to get the plugin working with ZenCache, we'd be happy to help them out.

**Comment by moretarman** [comment]
I reached out to the Revslider people, and here's what they said: 

Thanks for the update. The best thing to do would be to have the ZenCache team contact us directly, and then we can work with them to solve the issue.

So, there you go. It's funny how that one slider breaks the compression, whereas all the others are fine. I bet it has something to do with the strangish XML data that's included on the page.

**Comment by raamdev** [comment]
@moretarman Do you have an email address or link to a contact page where I can contact the Revslider developers? I did a Google search but didn't find anything. It seems like the only way to reach their support is by purchasing.

**Comment by moretarman** [comment]
Their support told me you could email: info@themepunch.com

**Comment by raamdev** [comment]
> Their support told me you could email: info@themepunch.com

I sent them an email and will update here again when I hear back.

**Comment by raamdev** [comment]
See also: https://github.com/websharks/comet-cache/issues/742

**Comment by SkyViewPros** [comment]
Please keep on this issue!  I just experienced it with the home page of a site I did for a Marina on Long Island - [http://eastshoremarineny.com](http://eastshoremarineny.com)

The video and entire slider disappears randomly, and re-appears after I clear the cache.  What's strange is that it doesn't seem to happen at regular intervals.

**Comment by ThePopularizer** [comment]
I'm experiencing an issue with styling with Revolution Slider as well. It seems the inline element styling changes when the body HTML compression is turned on.

**Comment by raamdev** [comment]
@ThePopularizer Thanks for the extra info! I'm bumping this up a priority and adding this to the milestone that is up for work during the next development cycle (starting later this week).

**Comment by jaswrks** [comment]
Referencing internal/private ticket:
https://websharks.zendesk.com/agent/tickets/9590

**Comment by jaswrks** [comment]
Estimating at .25 days for testing. Unknown problem, unknown fix at this time. So estimate on that will need to wait until the underlying problem is identified.

**Comment by jaswrks** [comment]
Next Release Changelog:
- **HTML Compressor:** Updating to the latest release of the [HTML Compressor](https://github.com/websharks/html-compressor) library. Comet Cache now comes with the new improved v161108 (latest release).
- **RevSlider Compat.:** This release includes a built-in exclusion rule for the HTML Compressor to allow for improved compatibility with the popular RevSlider plugin for WordPress. The new built-in exclusion rule looks for and automatically bypasses an important style tag that must be preserved for the RevSlider plugin to work in all scenarios; i.e., `<style id='rs-plugin-settings-inline-css'`.

**Comment by renzms** [comment]
@raamdev @jaswsinc 

## Confirmed Working

Pages/Posts with Sliders made with Slider Revolution Plugin are cached and compressed properly.

The Sliders also work properly even if CSS/JS is minified with the use of the exclusion rule.

![screen shot 2016-11-18 at 8 46 27 pm](https://cloud.githubusercontent.com/assets/13220018/20431408/cb0f600a-add4-11e6-81a8-d7216802902e.png)

---

However, I did notice that during my testing, the cache file that is served to logged out visitors does not update when editing settings of the slider and/or updating the slides in the Slider on the backend. An old version of the page is served even with Automatic Cache clearing enabled until the cache of the page with the Slider is manually cleared.

**Comment by raamdev** [comment]
@renzms writes...

> However, I did notice that during my testing, the cache file that is served to logged out visitors does not update when editing settings of the slider and/or updating the slides in the Slider on the backend. An old version of the page is served even with Automatic Cache clearing enabled until the cache of the page with the Slider is manually cleared.

Thanks for catching that. It sounds like we need to see if there's something else we can hook into to watch for changes to Slider Revolution. Can you please open a separate GitHub issue for that with steps to reproduce?

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#614).
