### ISSUE TITLE
Auto-Cache Engine XML Sitemap Error Notice Only Shows Once Every 15 Minutes

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#616]
The Auto-Cache Engine currently displays a Dashboard notice whenever the configured XML Sitemap location is not accessible; see [src/includes/classes/AutoCache.php#L246-L258](https://github.com/websharks/zencache-pro/blob/151105/src/includes/classes/AutoCache.php#L246-L258)

![2015-11-17_20-12-45](https://cloud.githubusercontent.com/assets/53005/11229891/200c61d6-8d68-11e5-96f5-f5fe86ac9c81.png)

However, the notice is not intelligent: If the site owner empties the XML Sitemap field as described in the notice, ZenCache does not detect that this has been done and clear the error notice as would be expected. It also takes a full 15 minutes (until the Auto-Cache Engine runs again) for a dismissed error to reappear, which temporarily misleads the site owner into thinking the problem might be fixed.

What needs to happen to improve this:
- Don't make this error notice dismissable--the only way to get rid of the notice should be:
  - Disable the Auto-Cache Engine
  - Fix the issue with the sitemap being unreachable (e.g., install an XML Sitemap plugin, or correct the name of the XML Sitemap)
  - Clear the XML Sitemap field altogether
- Detect when the problem has been fixed; **note that right now this problem is only checked when the Auto-Cache Engine runs, i.e., once every 15 minutes**. This error should be checked on every `admin_init` and cleared as soon as the problem goes away (see previous point).

**Comment by raamdev** [comment]
Related issues: #615 #555

**Comment by jaswrks** [comment]
> However, if a site owner dismisses that message, they will never see it again! That sort of defeats the purpose of that entire feature as there's no way to tell if the problem has been fixed or if the problem returns

Why do you say that they will never see it again? Unless I am missing something, if you dismiss the notice, but the error occurs again, the notice comes back each time. You must dismiss the notice each time the error occurs.

> Detect when the problem has been fixed; note that right now this problem is only checked when the Auto-Cache Engine runs, i.e., once every 15 minutes. This error should be checked on every admin_init

Agree.

**Comment by raamdev** [comment]
> Why do you say that they will never see it again? Unless I am missing something, if you dismiss the notice, but the error occurs again, the notice comes back each time. You must dismiss the notice each time the error occurs.

Hmm, you're right. When I initially tested this, dismissing the notice did not seem to remove the notice from the database, however I just tested it again and this time I see that dismissing the notice removes it from the database and therefore the next time this error occurs, the notice reappears.

I've updated the GitHub issue above to reflect only the changes necessary to improve this notice and make it more intelligent.

**Comment by jaswrks** [comment]
Cool. Copy that.

**Comment by raamdev** [comment]
Related: https://github.com/websharks/zencache/issues/618

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: Auto-Cache Engine XML Sitemap error checking is now more intelligent. When configured, the XML Sitemap URL is now checked upon every `admin_init` to verify that the XML Sitemap is accessible and valid. If a previous error has been fixed, the error message will disappear immediately instead of taking 15 minutes (the Auto-Cache Engine run cycle). See [Issue #616](https://github.com/websharks/zencache/issues/616).

**Comment by raamdev** [comment]
**ZenCache Pro v151220** has been released and includes changes worked on as part of this GitHub Issue. See the [release announcement](http://zencache.com/zencache-pro-v151220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#616).
