### ISSUE TITLE
HTML Compressor- No page compressed

### ISSUE THREAD

**Issue by xgiovio** [wpsharks/comet-cache#619]
Upgraded to pro some months ago. After the last update the html compressor is completely broken. All enabled but no page compressed. http://www.xgiovio.com

**Comment by raamdev** [comment]
@xgiovio This sounds related to your theme and/or a plugin that you have installed. We need more details about the issue to begin troubleshooting. If you could try disabling plugins one-by-one, and temporarily switching to the default Twenty Fifteen theme, that would help narrow down the issue. 

You could also try tweaking the HTML Compressor options to see if enabling/disabling certain features fixes the issue.

**Comment by xgiovio** [comment]
I enabled the pro 2 months ago. I didn't have any problem. The last updates broken the functionality

**Comment by raamdev** [comment]
@xgiovio We have been unable to reproduce the issue you describe above. Please [Test ZenCache in a Clean WordPress Installation](http://zencache.com/kb-article/testing-zencache-in-a-clean-wordpress-installation/) and provide us with a list of steps to reproduce the issue. Until we can reproduce the issue, we have no way of debugging it.

**Comment by xgiovio** [comment]
I can't understand this type of logic. If the software is bugged and i test it on a clean wordpress env , we wouldn't resolve the issue. The html compressor worked with a previous version. I have no time to disable and test your plugin for my cause. I've paid a software and i would have a working plugin. I shouldn't lose time debugging the issue. Am i wrong? I can list my installed plugin but you should make the right tests.

**Comment by raamdev** [comment]
@xgiovio Have you read [Testing ZenCache in a Clean WordPress Installation](http://zencache.com/kb-article/testing-zencache-in-a-clean-wordpress-installation/)? Let me quote you the first part of that article, which addresses your questions:

> Here in the WebSharks support department, we receive many bug reports that are difficult and/or impossible to reproduce on our side of things. A site owner will write to us and say, "feature X is not working as expected". One of our support reps will follow-up by testing that specific feature, but the problem doesn't exist on our side. Hmmm... what gives? **How can that be?**
> 
> **Reason:** WordPress offers you lots of options! As a site owner you have the ability to mix ZenCache with other plugins and a theme you like best. So the reason we are unable to reproduce the issue on our side? Your environment is slightly different than ours. Your WordPress installation has different plugins, it's had a different history, and it's probably running with a different theme too. ZenCache also writes cache files to the server and interacts with other server software quite frequently and your server-side configuration is likely different from ours.
> 
> As you can imagine, testing every feature of ZenCache with every possible combination of plugins, and with each and every theme and server configuration that exists for WordPress — is simply not realistic. **We need common ground! In fact, [our policy](https://www.websharks-inc.com/support/) is that we require it :-)**

**Comment by jaswrks** [comment]
I was also unable to reproduce this in a clean installation.

@xgiovio What are the _exact_ steps to reproduce in a clean install?

**Comment by raamdev** [comment]
I have not heard back from @xgiovio regarding this issue; closing.
