### ISSUE TITLE
ZenCache + PHP 5.6 FASTCGI = Internal Server Error

### ISSUE THREAD

**Issue by patdumond** [wpsharks/comet-cache#624]
Reference: https://websharks.zendesk.com/agent/tickets/9600

User reported an `Internal Server Error` when running ZenCache with PHP 5.6 FASTCGI. User determined the issue was ZenCache and PHP 5.6 FASTCGI using sound troubleshooting techniques (see referenced ticket). Error logs summarized below:

```
[Mon Nov 23 23:27:57 2015] [error] [client 111.243.22.117] Premature end of script headers: plugins.php, referer: http://www.url4.biz/wp-admin/update.php?action=upload-plugin

[Mon Nov 23 23:31:41 2015] [error] [client 208.113.153.204] Premature end of script headers: wp-cron.php

[Mon Nov 23 23:31:41 2015] [error] [client 111.243.22.117] Premature end of script headers: plugins.php, referer: http://www.url4.biz/wp-admin/update.php?action=upload-plugin

[Mon Nov 23 23:33:33 2015] [error] [client 111.243.22.117] Premature end of script headers: plugins.php, referer: http://www.url4.biz/wp-admin/update.php?action=upload-plugin

[Mon Nov 23 23:33:40 2015] [error] [client 111.243.22.117] Premature end of script headers: index.php

[Mon Nov 23 23:39:00 2015] [error] [client 111.243.22.117] zend_mm_heap corrupted, referer: http://www.url4.biz/wp-admin/update.php?action=upload-plugin

[Mon Nov 23 23:39:01 2015] [error] [client 111.243.22.117] zend_mm_heap corrupted, referer: http://www.url4.biz/wp-admin/update.php?action=upload-plugin

[Mon Nov 23 23:41:47 2015] [error] [client 111.243.22.117] zend_mm_heap corrupted, referer: http://www.url4.biz/wp-admin/plugins.php?plugin_status=all&paged=1&s

[Mon Nov 23 23:43:18 2015] [error] [client 111.243.22.117] zend_mm_heap corrupted, referer: http://www.url4.biz/wp-admin/plugins.php?plugin_status=all&paged=1&s

[Mon Nov 23 23:43:22 2015] [error] [client 111.243.22.117] zend_mm_heap corrupted, referer: http://www.url4.biz/wp-admin/update.php?action=upload-plugin

[Mon Nov 23 23:43:26 2015] [error] [client 220.181.108.100] zend_mm_heap corrupted

[Mon Nov 23 23:43:27 2015] [error] [client 220.181.108.119] zend_mm_heap corrupted

[Mon Nov 23 23:44:27 2015] [error] [client 111.243.22.117] zend_mm_heap corrupted, referer: http://www.url4.biz/wp-admin/plugins.php?plugin_status=all&paged=1&s

[Mon Nov 23 23:46:10 2015] [error] [client 111.243.22.117] zend_mm_heap corrupted, referer: http://www.url4.biz/wp-admin/plugins.php?plugin_status=all&paged=1&s

[Mon Nov 23 23:46:11 2015] [error] [client 111.243.22.117] zend_mm_heap corrupted, referer: http://www.url4.biz/wp-admin/plugins.php?plugin_status=all&paged=1&s

[Mon Nov 23 23:47:14 2015] [error] [client 111.243.22.117] zend_mm_heap corrupted, referer: http://www.url4.biz/wp-admin/plugins.php

[Mon Nov 23 23:49:15 2015] [error] [client 111.243.22.117] Premature end of script headers: admin-ajax.php, referer: http://www.url4.biz/wp-admin/plugins.php

[Mon Nov 23 23:50:11 2015] [error] [client 111.243.22.117] Premature end of script headers: plugins.php, referer: http://www.url4.biz/wp-admin/plugins.php
```

**Comment by jaswrks** [comment]
ZenCache uses output buffering which can exacerbate problems in some buggy versions of PHP. I'd suggest a review of [this thread](http://stackoverflow.com/questions/2247977/what-does-zend-mm-heap-corrupted-mean), followed by attempts to alter the PHP configuration in subtle ways. Or, perhaps upgrading to a slightly newer (or slightly older) version of PHP to see if that resolves this.

_Note: I'm not seeing anything in the log that points to a bug in ZenCache, but it does sound like ZenCache being active is increasing the odds of a memory leak in what may already be a problematic PHP configuration._

**Comment by raamdev** [comment]
Also reported here (internal ticket): https://websharks.zendesk.com/agent/tickets/9635

**Comment by raamdev** [comment]
Also reported here (internal ticket): https://websharks.zendesk.com/agent/tickets/9774 (**note that this was with ZenCache Lite v151107**)

**Comment by jaswrks** [comment]
Related: https://wordpress.org/support/topic/cgi-script-zend_mm_heap-corrupted

**Comment by jaswrks** [comment]
Related PHP bug reports that could be the underlying cause of this:

---
- https://bugs.php.net/bug.php?id=69251
  
  Suggested fixes:
  - Upgrade to latest build of PHP v5.6.
  - Or, set `opcache.enable_cli=0` in your php.ini file.

---
- https://bugs.php.net/bug.php?id=68365
  
  Suggested fixes:
  - Upgrade to latest build of PHP v5.6.
  - Or, increase WP memory. See [this article](https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP).

---
- https://bugs.php.net/bug.php?id=69713
  
  Suggested fixes:
  - Upgrade to latest build of PHP v5.6.
  - And/or adjust `opcache.optimization_level` in your php.ini file. See [comment here](https://bugs.php.net/bug.php?id=69713).

---

_See also: https://bugs.php.net/search.php?cmd=display&search_for=zend_mm_heap&x=0&y=0_

**Comment by jaswrks** [comment]
Another possible PHP bug that could cause this:
https://bugs.php.net/bug.php?id=66799&edit=1

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement:** The new default value for "Clear the PHP OPcache Too?" when clearing the cache manually is now disabled. Instead of having this option enabled by default, we automatically invalidate only the `advanced-cache.php` file in PHP's opcode cache whenever you update your configuration options, which allows ZenCache to function as expected. That was the most important reason for needing to clear the opcode cache in previous versions. Props @jaswsinc. Also props to @MarioKnight and @CotswoldPhoto for helping us narrow this down. See [Issue #624](https://github.com/websharks/zencache/issues/624).
- **Bug Fix**: This release attempts to resolve reports of Error 500 and Internal Server Error issues when running with PHP 5.6 + OPcache. Instead of clearing the entire Opcode cache whenever the plugin options are saved, we only invalidate the `advanced-cache.php` file, which is rebuilt each time you update your configuration options. Props @jaswsinc. Also props to @MarioKnight and @CotswoldPhoto for helping us narrow this down. See [Issue #624](https://github.com/websharks/zencache/issues/624).

**Comment by raamdev** [comment]
**ZenCache Pro v151220** has been released and includes changes worked on as part of this GitHub Issue. See the [release announcement](http://zencache.com/zencache-pro-v151220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#624).
