### ISSUE TITLE
Possible Bugs :: Dev Branch :: WcpPluginUtils

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#631]
-  Missing argument 2 for WebSharks\ZenCache\Pro\Plugin::WebSharks\ZenCache\Pro{closure}() in /websharks-wordpress/plugins/zencache-pro/src/includes/closures/Plugin/WcpPluginUtils.php on line 17
- Undefined variable: network_wide in /websharks-wordpress/plugins/zencache-pro/src/includes/closures/Plugin/WcpPluginUtils.php on line 21

**Comment by raamdev** [comment]
Related to work completed in https://github.com/websharks/zencache/issues/424.

**Comment by raamdev** [comment]
@jaswsinc Thanks for catching this! :smile: Fixed by https://github.com/websharks/zencache-pro/pull/196.
