### ISSUE TITLE
WP-PostRatings

### ISSUE THREAD

**Issue by tetradion** [wpsharks/comet-cache#632]
WP-PostRatings

**Comment by raamdev** [comment]
@tetradion What about WP-PostRatings?

**Comment by tetradion** [comment]
При кэшировании, отображается только картинка от PostRatings. Как исправить? Как запретить кэширование?

**Comment by raamdev** [comment]
@tetradion Please see this article:
- [Why isn’t my dynamic content updating?](http://zencache.com/kb-article/why-isnt-my-dynamic-content-updating/)
