### ISSUE TITLE
Filter to disable `_wpnonce` exclusion

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#637]
In v151220, we prevented pages that include `_wpnonce` in their HTML from being cached (see https://github.com/websharks/zencache/issues/601). I have seen several requests now for the ability to disable this functionality and allow `_wpnonce` in the HTML source.

We should add a filter to make this possible, and write a KB Article that explains how to use the filter and the risks of doing so.

**Comment by kristineds** [comment]
Also requested here (referencing internal, private ticket): https://websharks.zendesk.com/agent/tickets/10280

**Comment by kristineds** [comment]
Requested here as well (internal, private ticket): https://websharks.zendesk.com/agent/tickets/10204

**Comment by raamdev** [comment]
Also requested here (internal ticket): https://websharks.zendesk.com/agent/tickets/10258

**Comment by viriis** [comment]
Hi, How can I access to the link because I have this message 
"You do not have access to request #10258. It may have been solved or deleted."
Thanks

**Comment by raamdev** [comment]
> Hi, How can I access to the link because I have this message 
> "You do not have access to request #10258. It may have been solved or deleted."

@viriis Those are private, internal tickets, not publicly accessible.

**Comment by raamdev** [comment]
Also requested here (internal, private ticket): https://websharks.zendesk.com/agent/tickets/10283

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: It's now possible to override the ZenCache Nonce exclusion globally (dangerous) or only for Logged-In Users (safer). Please see [this article](http://zencache.com/r/kb-article-what-are-wordpress-nonces-and-why-are-they-not-cache-compatible/) for full details. [Issue #637](https://github.com/websharks/zencache/issues/637).

**Comment by raamdev** [comment]
**ZenCache Pro v160103** has been released and includes changes from this GitHub Issue. See the [v160103 announcement](http://zencache.com/zencache-pro-v160103-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#637).
