### ISSUE TITLE
Bug: Error In HTML Compression using Special Characters

### ISSUE THREAD

**Issue by renzms** [wpsharks/comet-cache#640]
User reported ZenCache is removing some Russian uppercase letters. Example `Р` in the word `Русский`. 

Issue with code in **zencache-pro\src\vendor\websharks\html-compressor\src\includes\classes/Core.php** on row 2000. ZenCache uses `preg_replase`, but `preg_replase` reportedly has a problem with **UTF-8**.

---

According to customer, this can be fixed using:

```
mb_internal_encoding('utf8');

$html = mb_ereg_replace('<\!\-{2}.*?\-{2}\>is', '', $html); 
$html = mb_ereg_replace('\s+', ' ', $html); 
$html = mb_ereg_replace('\s+\>', '/>', $html);
```

---

Referencing example - http://stackoverflow.com/questions/2063192/preg-replace-and-utf8
Referencing internal ticket - https://websharks.zendesk.com/agent/tickets/10240

**Comment by raamdev** [comment]
@renzms Thanks for the report!

@jaswsinc Any thoughts on this?

**Comment by jaswrks** [comment]
This issue (i.e., full UTF-8 support) can be addressed in https://github.com/websharks/zencache/issues/635 whenever we pass the `/u` flag for all string manipulation. The solution presented above, which uses `mb_ereg_replace()` will work as a short-term solution, but passing the `/u` flag to `preg_replace()` is far better. The ereg_\* family of functions is deprecated. Perl already supports UTF-8, we just need to take full advantage of that.

**Comment by jaswrks** [comment]
@raamdev Just wanted to note that this can probably be closed now. I feel pretty certain that this was resolved by our use of the `/u` flag and of the `mbstring` extension in PHP.

**Comment by raamdev** [comment]
@jaswsinc Thanks! You're right, this should be resolved as of v160706:
- **Enhancement:** Added full support for UTF-8 (multibyte strings). This release adds full support for UTF-8 throughout the Comet Cache codebase, greatly enhancing Comet Cache's ability to deal with file paths and URLs that may contain UTF-8 characters. Props @jaswsinc. [Issue #703](https://github.com/websharks/comet-cache/issues/703).
