### ISSUE TITLE
Failed to update your /.htaccess file automatically.

### ISSUE THREAD

**Issue by BreursICT** [wpsharks/comet-cache#641]
When i try to safe the settings i get the following error "Failed to update your /.htaccess file automatically. Most likely a permissions error. Please make sure it has permissions 644 or higher (perhaps 666). Once you've done this, please try saving the ZenCache options again."

I allready checked my htaccess but nothing strange. Also checked the permissions on the htaccess file but that fine aswell.

Do you have any suggestion ?

**Comment by raamdev** [comment]
@BreursICT Could you show us a copy of your `.htaccess` file? I'd like to test it against my local installation of ZenCache to see if anything strange is going on.

**Comment by raamdev** [comment]
After some research, I discovered a few issues with the htaccess utilities in ZenCache Pro v151220:
- Every time the plugin options are saved when ZenCache is enabled, ZenCache [calls `addWpHtaccess()`](https://github.com/websharks/zencache-pro/blob/151220/src/includes/classes/Actions.php#L570-L572), regardless of whether or not it actually needs to (i.e., whether or not any options are enabled that require adding something to the htaccess file).
- ZenCache does not intelligently keep track of which options are currently enabled that require htaccess rules, and as a result [more code than necessary](https://github.com/websharks/zencache-pro/blob/151220/src/includes/closures/Plugin/HtaccessUtils.php#L21-L42) is being run each time the site owner saves the plugin options and `addWpHtaccess()` is called.

As a result of all this unnecessary work, I believe we're increasing the chances that the site owner might see an error message when the error message isn't even applicable (i.e., ZenCache has no reason to add/remove anything from the htaccess file).

I've submitted a PR (https://github.com/websharks/zencache-pro/issues/204) that resolves these issues.

**Comment by raamdev** [comment]
Also reported here (internal ticket): https://websharks.zendesk.com/agent/tickets/10212

**Comment by BreursICT** [comment]
Hi Raam,

Thank you for your support!

So If I understand correct the error messages are not applicable, and for now I can just ignore them. 

With kind regards,

Wesley de Graaf

Email:  mailto:wesley@breursict.com wesley@breursict.com

Website:  http://www.breursict.com http://www.breursict.com 

BreursICT | Kvk 63788004 | Bunschoten | Nederland 

Van: Raam Dev [mailto:notifications@github.com] 
Verzonden: Monday, December 28, 2015 22:17
Aan: websharks/zencache zencache@noreply.github.com
CC: BreursICT Wesley@breursict.com
Onderwerp: Re: [zencache] Failed to update your /.htaccess file automatically. (#641)

Also reported here (internal ticket): https://websharks.zendesk.com/agent/tickets/10212

**Comment by raamdev** [comment]
@BreursICT That is correct. If you don't have Static CDN Filters enabled (**ZenCache → Plugin Options → Static CDN Filters**), then any messages about being unable to write to the `.htaccess` file can be ignored.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed an issue that was unexpectedly producing "Failed to update your /.htaccess file" error messages. The `.htaccess` routines are now more intelligent and take into consideration which plugin options are enabled and which options require updating the `.htaccess` file. This also improves performance by avoiding unnecessary read/writes to the `.htaccess` file. Props @patdumond. See [Issue #641](https://github.com/websharks/zencache/issues/641).

**Comment by raamdev** [comment]
**ZenCache Pro v160103** has been released and includes changes from this GitHub Issue. See the [v160103 announcement](http://zencache.com/zencache-pro-v160103-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#641).
