### ISSUE TITLE
Crashed my site

### ISSUE THREAD

**Issue by RP-Joe** [wpsharks/comet-cache#647]
I have several websites. All same theme. I installed zencache and now have a white screen of death. 
This is the second time. The first time it crashed one of my websites, I thought I did something wrong. It was no big deal. It was a small website and I rebuilt it.

I have WordPress 4.3 or 4.4, I can't remember. I renamed plug-in folder. I renamed the theme folder. The only thing left in there is 2014.
I changed the htacess to php 5.6

Same pattern as before.
I strongly suspect there is a conflict between this plug-in and rss-multi-importer. 
I have Set these two variables in the wp-settings.php:
define( 'WP_DEBUG', true );
define( 'SCRIPT_DEBUG', true );

What to do now?
the site is:
http://ofwtravel.org/

**Comment by raamdev** [comment]
@RP-Joe Try following the manual uninstallation instructions here: [How do I uninstall ZenCache?](http://zencache.com/kb-article/how-do-i-uninstall-zencache/)

Your `wp-content/advanced-cache.php` file may have become corrupt. You can delete that file and ZenCache will recreate it the next time it is activated and enabled.

If deleting the ZenCache plugin folder _and_ the `wp-content/advanced-cache.php` file does not resolve the white screen issue, then you probably have something going on in your `.htaccess` file. You can try making a backup of it and then deleting it, or checking your web server log files to see what error is being thrown.

Generally the white screen means an error is occurring but your server has been configured to hide errors. See also https://codex.wordpress.org/Debugging_in_WordPress.

**Comment by RP-Joe** [comment]
WOW
I did not expect such a fast response and you solved my problem. 
Amazing. Thank you. 
Its up and running. I am going to use 2014 theme. Not taking any chances now. 
Thanks again.
