### ISSUE TITLE
Bug after saving page

### ISSUE THREAD

**Issue by mennobouma** [wpsharks/comet-cache#649]
Hi Zencache support,

When i save a page i get this error:

Warning: rename(/home/users/*****_.nl/wp-content/cache/zencache/cache/https/www-**_**-nl-568d1affd89a6848447998-tmp,/home/users/weddrftp/****_.nl/wp-content/cache/zencache/cache/https/www-**_**-nl): Directory not empty in /home/users/****_/**_**.nl/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php on line 384

Fatal error: Uncaught exception 'Exception' with message 'Unable to delete files. Rename failure on tmp directory: `/home/users/weddrftp/*****.nl/wp-content/cache/zencache/cache/https/www-*****-nl-568d1affd89a6848447998-tmp`.' in /home/users/****_/**_**.nl/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php:386 Stack trace: #0 [internal function]: WebSharks\ZenCache\Pro\AbsBaseAp->WebSharks\ZenCache\Pro{closure}('/^\/trouwjurk\-...') #1 /home/users/****_/**_**.nl/wp-content/plugins/zencache-pro/src/includes/classes/AbsBaseAp.php(55): call_user_func_array(Object(Closure), Array) #2 /home/users/****_/**_**.nl/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php(54): WebSharks\ZenCache\Pro\AbsBaseAp->__call('deleteFilesFrom...', Array) #3 /home/users/****_/**_**.nl/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php(54): WebSharks\ZenCache\Pro\Plugin->deleteFil in /home/users/****_/**_**.nl/wp-content/plugins/zencache-pro/src/includes/closures/Shared/CacheDirUtils.php on line 386

Any idea how to solve this? Thanks!
- Menno

**Comment by raamdev** [comment]
@mennobouma A few questions:
- What version of PHP are you running?
- What version of ZenCache Pro are you running?
- How often does this error occur? Is it all the time or only occasionally?
- Does your web hosting company used cloud-based or network-based storage (NFS)? Those sorts of filesystems are more prone to issues with file locking.

**Comment by mennobouma** [comment]
Hi Raamdev,
- 5.4.45 
- Zencache Pro 160103
- it happens occasionally but especially on major changes like menu updates where all pages need to be flushed
- running Apache, on network-based storage (cluster hosting @ Byte.nl)

**Comment by raamdev** [comment]
@mennobouma writes...

> it happens occasionally but especially on major changes like menu updates where all pages need to be flushed
> [...] on network-based storage (cluster hosting @ Byte.nl)

This is almost certainly related to the network-based storage system your hosting company is using. Please see this article and consult with them regarding the best technique for locking:
- [What is Cache Locking?](http://zencache.com/kb-article/what-is-cache-locking/)

**Comment by jaswrks** [comment]
> running Apache, on network-based storage

Agree. I suggest _not_ using NFS for a cache.
