### ISSUE TITLE
Feature Request: Option to disable HTML Compression for Logged-In Users

### ISSUE THREAD

**Issue by renzms** [wpsharks/comet-cache#650]
HTML compression allows for cached pages to load a lot faster compared to the initial visit to the page. Logged in users may have a much slower first time visit of loading of a page because of the HTML Compression. Compared to regular visitors or users who are not logged in, those visitors/users may have a faster experience because of the Auto-Cache Engine and the way it can pre-cache.

There should be an option for site owners who don't want to use HTML Compression for logged in users: `Do NOT use Html Compression for logged in users?` 

Additionally, some site owners may choose not to use HTML Compression for certain URLs.

There should be a filter to list down specific URLs to exclude from HTML Compression.

---

Referencing Internal Ticket: https://websharks.zendesk.com/agent/tickets/10412

**Comment by raamdev** [comment]
> There should be an option for site owners who don't want to use HTML Compression for logged in users: Do NOT use Html Compression for logged in users?

Love that idea! Thank you.

> Additionally, some site owners may choose not to use HTML Compression for certain URLs. There should be a filter to list down specific URLs to exclude from HTML Compression.

That sounds like a good idea too. I forked that to a separate GitHub issue: https://github.com/websharks/zencache/issues/651

**Comment by renzms** [comment]
@raamdev 

Cool, thanks for separating the two as I wasn't sure if I should make a **Feature Request Issue** for each feature. I'd love to work on both once an outline is made!

**Comment by jaswrks** [comment]
Another +1 for this here. Private/internal ticket ↓
https://websharks.zendesk.com/agent/tickets/10506

**Comment by renzms** [comment]
## Next Actions (Step 1 of 2)
- New feature branch in the `websharks/zencache-pro` repo.
- After [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/classes/Plugin.php#L216) add the following:
  
  ``` php
  'htmlc_when_logged_in',
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/160103/src/includes/classes/Plugin.php#L347) add the following:
  
  ``` php
  'htmlc_when_logged_in' => '0', // `0|1`; enable when logged in?
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/160103/src/includes/templates/advanced-cache.txt#L407) add the following:
  
  ``` php
  /**
  * @since 15xxxx Adding logged-in check.
  *
  * @type bool HTMLC when logged in?
  */
  protected $htmlc_when_logged_in;
  $this->htmlc_when_logged_in = (boolean) $this->plugin->options['htmlc_when_logged_in'];
  if (!$this->htmlc_when_logged_in && $this->plugin->isLikeUserLoggedIn()) {
      return; // Disable in this case.
  }
  ```

## Step 2

Add UI option for:

`'htmlc_when_logged_in'`

After [this line](https://github.com/websharks/zencache-pro/blob/160103/src/includes/classes/MenuPageOptions.php#L842) here
- Submit PR.

**Comment by raamdev** [comment]
@renzms Nice work getting us started on this! Thank you. :smile: 

This one looks wrong; I don't think that code belongs in `advanced-cache.txt`:

---
- After [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/templates/advanced-cache.txt#L407) add the following:
  
  ``` php
  /**
  * @since 15xxxx Adding logged-in check.
  *
  * @type bool HTMLC when logged in?
  */
  protected $htmlc_when_logged_in;
  $this->htmlc_when_logged_in = (boolean) $this->plugin->options['htmlc_when_logged_in'];
  if (!$this->htmlc_when_logged_in && $this->plugin->isLikeUserLoggedIn()) {
      return; // Disable in this case.
  }
  ```

---

There also appears to be something missing here:

---

Add UI option for:

`'htmlc_when_logged_in'`

After [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/classes/MenuPageOptions.php#L842) here
- Submit PR.

---

**Comment by renzms** [comment]
Updated links to use the `160103` branch

**Comment by renzms** [comment]
~~###Attempt for Step 2~~

### Attempt for Step 2

Add UI option for:

`htmlc_when_logged_in`

~~After this line here~~

After [this line](https://github.com/websharks/zencache-pro/blob/160103/src/includes/classes/MenuPageOptions.php#L842) here

Submit PR.

``` php
echo '      <h3>'.__('Do NOT use Html Compression for logged in users?', SLUG_TD).'</h3>'."\n";
echo '      <p>'.__('HTML compression allows for cached pages to load a lot faster compared to the initial visit to the page. Logged in users may have a much slower first time visit of loading of a page because of the HTML Compression. Compared to regular visitors or users who are not logged in, those visitors/users may have a faster experience because of the Auto-Cache Engine and the way it can pre-cache. In short, do NOT turn this off unless you know what you\'re doing.', SLUG_TD).'</p>'."\n";
echo '      <p><select name="'.esc_attr(GLOBAL_NS).'[saveOptions][cdn_when_logged_in]">'."\n";
echo '            <option value="0"'.selected($this->plugin->options['htmlc_when_logged_in'], '0', false).'>'.__('Yes, disable HTML Compression for logged in users.', SLUG_TD).'</option>'."\n";
echo '            <option value="postload"'.selected($this->plugin->options['htmlc_when_logged_in'], 'postload', false).'>'.__('No, enable HTML Compression for logged in users.', SLUG_TD).'</option>'."\n";
echo '         </select></p>'."\n";
```

**Comment by raamdev** [comment]
@renzms Something still looks wrong with that. ↑

**Comment by renzms** [comment]
@raamdev 

I see, I think its this line:

``` php
echo '      <p><select name="'.esc_attr(GLOBAL_NS).'[saveOptions][cdn_when_logged_in]">'."\n";
```

Should be:

``` php
echo '      <p><select name="'.esc_attr(GLOBAL_NS).'[saveOptions][htmlc_when_logged_in]">'."\n";
```

**Comment by raamdev** [comment]
@renzms Good catch! But I was actually referring your formatting and missing link in your GitHub comment:

![2016-01-21_11-05-00](https://cloud.githubusercontent.com/assets/53005/12486077/0186c6f8-c02f-11e5-8504-10d165c8c17f.png)

---

Nice work on putting together the outline! Please go ahead and open a PR for the above work so that we can start reviewing code. :-)

**Comment by renzms** [comment]
@raamdev 

Oh yeah, thanks! Edited the above. Funny, in my previous posts I actually included the link! I'll get started  on the PR.

**Comment by KTS915** [comment]
@renzms, @jaswsinc, @raamdev: I'm curious. What would be the benefit to logged-in users of disabling HTML compression?

**Comment by raamdev** [comment]
@KTS915 If a site has CSS/JS that gets loaded for logged-in users that is not compatible with the HTML Compressor, it would be nice to have an option for disabling it.

**Comment by jaswrks** [comment]
The issue is that cached pages for logged-in users have a much shorter TTL. For instance, if you're logged into the site and you submit a form, that triggers a cache clearing. Lots of little actions you take can result in a clearing of the cache. This shorter TTL is not ideal when running the HTML Compressor, because the HTML Compressor does a deep analysis of the page content and resources in order to compress things for you. For logged-in users, it is better to skip that and just cache the HTML source as-is, avoiding the extra overhead.

**Comment by KTS915** [comment]
I see! Thank you both, @raamdev and @jaswsinc!

**Comment by KTS915** [comment]
@jaswsinc wrote: "For logged-in users, it is better to skip that and just cache the HTML source as-is, avoiding the extra overhead."

That was particularly enlightening. I have been trying this out and, on every site I tried, it was indeed better to turn off the compressor for logged-in users. I would never have guessed.

So another big thanks for the explanation, and a +1 for this feature request!

**Comment by raamdev** [comment]
@jaswsinc writes...

> For logged-in users, it is better to skip that and just cache the HTML source as-is, avoiding the extra overhead.

That's a good reason to make the default for this new option "Enabled" (so that the HTML Compressor is disabled for Logged-In Users by default). The above should also be explained in the description for this option, i.e., that leaving the HTML Compressor disabled for Logged-In Users will improve performance in most cases.

**Comment by jaswrks** [comment]
Agree.

**Comment by raamdev** [comment]
@renzms I updated https://github.com/websharks/zencache-pro/issues/208 with a few notes. Any chance you could get that PR finished by Monday evening so that this feature can be included in the next ZenCache Pro release (RC is targeted for Monday night, February 15th).

**Comment by renzms** [comment]
@raamdev 
Updated according to your notes, thanks!

**Comment by raamdev** [comment]
![2016-02-26_09-02-43](https://cloud.githubusercontent.com/assets/53005/13373879/3f79a622-dd41-11e5-984f-5ab464697ab2.png)

**Comment by raamdev** [comment]
Next Release Changelog:
- **Enhancement** (Pro): A new HTML Compression options allows you to define whether or not HTML Compression should be enabled for Logged-In users (when Logged-In User caching is enabled). See **Comet Cache → Plugin Options → HTML Compression → Enable HTML Compression for Logged-In Users?**. Props @renzms. See [Issue #650](https://github.com/websharks/comet-cache/issues/650).

**Comment by raamdev** [comment]
**Comet Cache v160227** has been released and includes changes from this GitHub Issue. See the [v160227 announcement](https://cometcache.com/blog/comet-cache-v160227-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#650).
