### ISSUE TITLE
preg_split() expects parameter 3 to be integer

### ISSUE THREAD

**Issue by Zwilla** [wpsharks/comet-cache#652]
\nWarning: preg_split() expects parameter 3 to be integer, null given in /var/www/html/mydomain.com/wp-content/plugins/zencache/zencache.inc.php on line 2237
\

**Comment by raamdev** [comment]
This is line 2237 of `zencache.inc.php`:

``` php
if(($_values = preg_split('/['."\r\n".']+/', $_value, NULL, PREG_SPLIT_NO_EMPTY)))
```

The [`preg_split()` docs](http://php.net/manual/en/function.preg-split.php) say the 3rd parameter can be set to `NULL` (as ZenCache is doing here):

> **limit**
> If specified, then only substrings up to limit are returned with the rest of the string being placed in the last substring. A limit of `-1`, `0` or `NULL` means "no limit" and, as is standard across PHP, you can use `NULL` to skip to the flags parameter.

@jaswsinc We could just change that 3rd parameter to `-1` throughout the codebase to avoid these warnings, sound good?

**Comment by jaswrks** [comment]
@raamdev Yes, that sounds good to me.

I have seen this myself recently. I was forced to update this in a few places in another project. The `NULL` value works fine until you turn on strict types in PHP 7, and then it requires that it be set to an integer value; e.g., `-1`.

**Comment by Zwilla** [comment]
Apache - Mariadb - PHP7 - HHVM (hhvm.php7.all = 1) - Wordpress

I changed the value now to "-1"

thx

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch in the `websharks/zencache-pro` repo.
- Search the entire codebase (excluding `includes/share.php`) and look for: `preg_split`
- In calls to `preg_split()`, if the third argument is currently being set to a value of `null` (or `NULL`), please change it to `-1` instead for PHP v7 + strict types compatibility.
- Submit PR for review.

---

e.g., 

``` php
preg_split('/['."\r\n".']+/', $_value, NULL, PREG_SPLIT_NO_EMPTY)
```

becomes:

``` php
preg_split('/['."\r\n".']+/', $_value, -1, PREG_SPLIT_NO_EMPTY)
```

**Comment by renzms** [comment]
@jaswsinc 

PR submitted, ready for check. Thanks!

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: Fixed several PHP "Warning: preg_split() expects parameter 3 to be integer, null given". Props @Zwilla @renzms. See [Issue #652](https://github.com/websharks/zencache/issues/652).

**Comment by raamdev** [comment]
**ZenCache v160222** has been released and includes changes from this GitHub Issue. See the [v160222 announcement](http://zencache.com/zencache-v160222-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#652).
