### ISSUE TITLE
PHP Rename Error when hosting on Pantheon.io

### ISSUE THREAD

**Issue by rdanamcd** [wpsharks/comet-cache#654]
I've recently moved to Pantheon.io for their Dev, Stage, Live servers and GIT version control. Not sure if Zencache will be able to be compatible with Pantheon.io or not. It works fine caching ( have to put the cache folder in a writable directory wp-content/uploads/cache folder ) but it is unable to delete the cache files. Getting an Exception error at all "Renames" in the src/includes/closures/Shared/CacheDirUtils.php file. Lines 148, 217, 316, 386, 467, and 515.

Pantheon.io docs at https://pantheon.io/docs/articles/sites/platform-considerations/ around the middle does state their platform can not handle "Renaming Files or Directories" have to create New Directory and move the files into the new directory and delete the old.

My site will not work with their Varnish Servers so Zencache is my option for full page caching.

Is this a fixable issue?

Thanks!
Dana

**Comment by jaswrks** [comment]
@rdanamcd To my knowledge, Pantheon is not compatible with _any_ WP cache plugin, due to the nature of their platform. It might be possible to run something that takes further advantage of Redis within their infrastructure, but generally speaking it appears their take is that "_you don't need a WP cache plugin_" when running on their platform. ZenCache does not support Redis (yet).

Referencing: https://pantheon.io/docs/articles/wordpress/wordpress-faq/

> You don't need to! Pantheon provides a web-scale infrastructure, which includes a super-tuned PHP environment, horizontal scalability, and caching. You don’t need to worry about messing with buggy or frustrating cache plugins (supercache, batcache, etc).

**Comment by rdanamcd** [comment]
I contacted them and they gave me the information on how to set it up. They were fine with it. Had to put advanced-cache.php under GIT control and put the cache directory in the wp-content/uploads/cache folder. It does work and cache is fast but does not delete.
I've tried using their Varnish Servers and been in contact with tech support about. Since it's mainly for logged in users and some php sessions are involved, their Varnish Servers will not work ( they don't allow any changes to their cache configuration ). Since not using their caching structure, they were fine with Zencache.

I'm hoping for ZenCache for full page caching and Redis for Object Caching.

Thanks

**Comment by jaswrks** [comment]
> Had to put advanced-cache.php under GIT control and put the cache directory in the wp-content/uploads/cache folder. It does work and cache is fast but does not delete.

Ah. Cool! Thanks for sharing that information with us.

> I'm hoping for ZenCache for full page caching and Redis for Object Caching.

Cool. Thanks for the +1 on Redis. https://github.com/websharks/zencache/issues/47

**Comment by raamdev** [comment]
> Pantheon.io docs at https://pantheon.io/docs/articles/sites/platform-considerations/ around the middle does state their platform can not handle "Renaming Files or Directories" have to create New Directory and move the files into the new directory and delete the old.

ZenCache uses the PHP `rename()` function in several places, so unless you modify the ZenCache codebase to change its behavior, it doesn't sound like there's going to be an easy solution for you with Pantheon.io.

**Comment by rdanamcd** [comment]
That's what I'm thinking. I did notice a TODO parameter to optimize the deleteFilesFromCacheDir for extremely large sites. ( Mine does not fit in the category though :-) ) Don't know if the rename() is the fastest solution to delete files... it might be, have no idea. Just wanted you to be aware of the rename issue and Pantheon.io.

Thanks

**Comment by raamdev** [comment]
@rdanamcd Thanks for the heads up. Much appreciated. :-)
