### ISSUE TITLE
Feature Request/Question: Allowing Developers to Communicate an Asset Priority to Zencache

### ISSUE THREAD

**Issue by theperfectwill** [wpsharks/comet-cache#658]
Hi, 

<strong>For Theme Developers: </strong>
Can you add an option for us to communicate with Zencache, giving Zencache a priority in which to compress an asset? 

I've been working on a theme to tightly optimize it with Zencache, but I need some help as nothing else is working so far. So I had this idea. 

<strong>In Short: </strong>
I need Zencache to compress my theme's css file after my theme's user generated styles. Currently it is grabbing my echoed user generated styles and placing them before my theme's css file. That means the theme's default css is overriding the user's generated styles. 

I've made my Above the Fold Css inlined in the header. 
Then I have made the other styles in a wp_enqueue_style request. 

Here is a screenshot to visualize/explain 
@ http://take.ms/er0Dd

So this is an idea, I think is good in general, for authors to communicate to Zencache, but perhaps my issue can be solved without that? Please let me know your thoughts or what I can do. 

Thanks champs!

**Comment by raamdev** [comment]
@NoahjChampion You need to handle this with `wp_enqueue_style()`. You can create a dynamic PHP file [like this](https://github.com/raamdev/independent-publisher/blob/master/css/customizer.css.php) that generates your user-generated styles.

You can then [make sure the user-generated styles are called after the main theme CSS](https://github.com/raamdev/independent-publisher/blob/master/functions.php#L236-L260).

**Comment by theperfectwill** [comment]
@raamdev Thanks for your genius. 

A little new to php, but I can wrap my head well around that. I've never seen that done, so never knew it could be done that way. 

Thanks!
