### ISSUE TITLE
Theme Support to force a Zencache setting

### ISSUE THREAD

**Issue by theperfectwill** [wpsharks/comet-cache#659]
In <em>HTML Compression</em> > <em>CSS Exclusion Patterns </em>
- I would like my theme tell Zencache to not cache my above the fold styles. 
- I've given my above the fold styles a unique pattern id to be able to do this. But currently this has to be entered manually in Zencache to respect that. 
- Is there away I can make sure my exclusion pattern is considered by Zencache? 

I was looking for an <code>update_option();</code> in the database, but there is only the <code>zencache_options</code> and the <code>zencache_notices</code>. 

Is there anyway I can achieve theme integration to set some Zencache settings? 
- I didn't see anything in the KB.

**Comment by raamdev** [comment]
@NoahjChampion Setting that sort of thing from a theme is not ideal. It would be better to make your above-the-fold styles compatible with compression, or to provide some documentation for your theme users who might be using ZenCache, explaining how to exclude those specific styles.

You might be able to use a technique [like this](http://zencache.com/kb-article/how-do-i-disable-static-cdn-filters-via-php/) to achieve what you're asking, but I wouldn't recommend doing it that way.

cc @jaswsinc Anything to add here?

**Comment by jaswrks** [comment]
Something like this perhaps, as Raam was suggesting.

``` php
<?php
add_filter('zencache_options', function($options) {
    $options['htmlc_css_exclusions'] .= "\n".'/my/file-pattern.css';
    return $options;
});
```

**Comment by theperfectwill** [comment]
Hey, apologies for the delay. I have to figure out why my Github notifications are not making it to my inbox. 

@raamdev I see what you're saying and I agree, but maybe I should be more clear. 

I have a default database setting import, that loops through the database to find if the database option_name is created or not. If it find that it is created then the import runs nothing. If it finds the option_name doesn't exist then my import will create that option_name and add the settings I give it. 

That is basically what I want to do with Zencache. So I shouldn't have said use an `update_option` as that would always force the setting for the user. I just want the setting to be set for the Zencache user when they first install and activate Zencache. 

I will add documentation of course, because I'm also going to showcase why Zencache is better and much farther ahead than any caching plugin available. I'm also going to include the json export, so if users need reset to the recommending settings by my theme they will have that. Even though that would work, I would like to make the first time Zencache experience a little more intuitive. 

@jaswsinc Could you provide a way with that code to run based on the database loop or only to run if user hasn't saved their own Zencache settings?

**Comment by theperfectwill** [comment]
@raamdev @jaswsinc Thanks for the help. I'm closing this. 

I just imported all the Zencache settings when active for the first time. The user afterward can opt to change it.

**Comment by raamdev** [comment]
@NoahjChampion Thanks for the update!
