### ISSUE TITLE
Feature Request: Support for srcset attribute in Static CDN Filters

### ISSUE THREAD

**Issue by omriamos** [wpsharks/comet-cache#660]
Hi,

ZenCache's Static CDN Filters works great within my site, beside one issue - I'm using the 'srcset' parameter in the <img> tags in order to set a different image src for each screen size, and the filter changed only the first "src=" parameter but none of the "srcset=" parameters...

For example:
`<img class="alignnone wp-image-86011" src="//cdn.hwzone.co.il/wp-content/uploads/2016/01/1-1.jpg?iv=1" alt="" width="1920" height="1157" srcset="//hwzone.co.il/wp-content/uploads/2016/01/1-1-300x181.jpg 300w, //hwzone.co.il/wp-content/uploads/2016/01/1-1-768x463.jpg 768w, //hwzone.co.il/wp-content/uploads/2016/01/1-1-1024x617.jpg 1024w, //hwzone.co.il/wp-content/uploads/2016/01/1-1-600x362.jpg 600w, //hwzone.co.il/wp-content/uploads/2016/01/1-1-696x420.jpg 696w, //hwzone.co.il/wp-content/uploads/2016/01/1-1-1068x644.jpg 1068w, //hwzone.co.il/wp-content/uploads/2016/01/1-1-697x420.jpg 697w, //hwzone.co.il/wp-content/uploads/2016/01/1-1.jpg 3882w" sizes="(max-width: 1920px) 100vw, 1920px">`

Note how the "src=" has turned into the cdn subdomain, while the "srcset=" hasn't.

This is not a critical issue since obviously it still works - but nevertheless if there is a possible fix for this - it'll great :)

thanks

**Comment by raamdev** [comment]
@omriamos Thank you for the feature request. :-) 

---

This article provides an overview of the how and why of the `srcset` attribute: 

http://www.sitepoint.com/responsive-images-part-1-using-srcset/

And here's some official docs: 

https://www.w3.org/html/wg/drafts/html/master/semantics.html#introduction-3:device-pixel-ratio-2

Note that this is for HTML 5.1 and the above link is to the W3C Working Draft 08 October 2015.

cc @jaswsinc

**Comment by jaswrks** [comment]
Also requested here. Referencing internal/private ticket.
https://websharks.zendesk.com/agent/tickets/13167

**Comment by YearOfBenj** [comment]
+1, this is preventing almost all my site's images from being served via CDN.  The only ones that _are_ being served by CDN are bugs where I wasn't properly offering high-dpi image srcsets.  ;)

**Comment by raamdev** [comment]
@jaswsinc Could I please get a time estimate on this when you get a chance?

**Comment by jaswrks** [comment]
Referencing filters in this function:
https://developer.wordpress.org/reference/functions/wp_calculate_image_srcset/

Estimate at 1 day of work to add support for this new feature in WP core.

**Comment by YearOfBenj** [comment]
Seems this is the future-looking direction of the web, and these high-density (i.e. bigger) images would benefit from CDN caching more than any!

**Comment by renzms** [comment]
@raamdev @jaswsinc 

### Confirmed Working

`srcset=` also includes CDN Host Name configured in **Comet Cache Pro → Plugin Options →Static CDN Filters**

`src="https://js9dgjsl4llqpp.cloudfront.net/wp-content/uploads/2016/12/troopers-en-Scarif.png?iv=2"`

`srcset="https://js9dgjsl4llqpp.cloudfront.net/wp-content/uploads/2016/12/troopers-en-Scarif.png?iv=2 1600w`

Full HTML:

```html
<img class="alignnone wp-image-38 size-full" src="https://js9dgjsl4llqpp.cloudfront.net/wp-content/uploads/2016/12/troopers-en-Scarif.png?iv=2" width="1600" height="666" srcset="https://js9dgjsl4llqpp.cloudfront.net/wp-content/uploads/2016/12/troopers-en-Scarif.png?iv=2 1600w, https://js9dgjsl4llqpp.cloudfront.net/wp-content/uploads/2016/12/troopers-en-Scarif-300x125.png?iv=2 300w, https://js9dgjsl4llqpp.cloudfront.net/wp-content/uploads/2016/12/troopers-en-Scarif-768x320.png?iv=2 768w, https://js9dgjsl4llqpp.cloudfront.net/wp-content/uploads/2016/12/troopers-en-Scarif-1024x426.png?iv=2 1024w, https://js9dgjsl4llqpp.cloudfront.net/wp-content/uploads/2016/12/troopers-en-Scarif-1200x500.png?iv=2 1200w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 1362px) 62vw, 840px">
```

**Comment by raamdev** [comment]
**Comet Cache v161221** has been released and includes changes from this GitHub Issue. See the [v161221 announcement](https://cometcache.com/blog/comet-cache-v161221-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#660).
