### ISSUE TITLE
Stats Log Endpoint

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#661]
Endpoint URL should be updated to:
`https://stats.wpsharks.io/log`

https://github.com/websharks/zencache-pro/blob/160103/src/includes/closures/Plugin/StatsUtils.php#L24

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- Updated WebSharks stats log endpoint URL. Props @kristineds. See [Issue #661](https://github.com/websharks/zencache/issues/661).

**Comment by raamdev** [comment]
**ZenCache v160222** has been released and includes changes from this GitHub Issue. See the [v160222 announcement](http://zencache.com/zencache-v160222-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#661).
