### ISSUE TITLE
Feature Request: preloading a list of attachments links

### ISSUE THREAD

**Issue by GermontZ** [wpsharks/comet-cache#663]
Hello!

I am using Cloudflare. I just noticed that if my origin server is unfortunately offline, the pages already preloaded can't load all the images, pdf's or whatever.
Is there a way to generate an attachments list? I prefer preloading with a download manager. 
Site owners should have the possibility to choose between automatic preloading and custom solutions.
Thank you!

**Comment by raamdev** [comment]
@GermontZ Just to make sure I understand correctly: Are you saying that if you're using ZenCache Static CDN Filters, your HTML contains links to a CDN, and ZenCache then generates cache files that contain those CDN links, that when the CDN goes down and ZenCache loads a cached file (which contains the links pointing to the CDN), the static resource links end up appearing as broken?

**Comment by GermontZ** [comment]
I never said I use a CDN, at least not one like MaxCDN or other, so I don't need ZenCache settings enabled for it. Just Cloudflare! And the 'origin server' is my shared server with cheap subscription.
Therefore, sometimes it goes offline, and even if the visitors load the html page from Cloudflare servers, the images and other attachments are not, ore I must wait a few seconds for it.

That's why I prefer to preload also all images, pdf's and so on to Cloudflare.

**Comment by raamdev** [comment]
@GermontZ So what is the feature request for ZenCache? I don't understand how ZenCache fits into the picture here.

**Comment by GermontZ** [comment]
It could pick all attachment links, generate a list, and preload it.

**Comment by raamdev** [comment]
Preload it where?

**Comment by GermontZ** [comment]
The same how it's working for .html? On Cloudflare.

**Comment by raamdev** [comment]
So you're asking if ZenCache can visit your attachment URLs so that they get cached by CloudFlare on their servers? The the ZenCache Auto-Cache Engine (**ZenCache → Plugin Options → Auto-Cache Engine**) should already be capable of doing that. The Auto-Cache Engine visits each page in the Sitemap file, which if you're using CloudFlare, should result in any static content stored on each page to be cached by CloudFlare.

**Comment by jaswrks** [comment]
@raamdev He's talking about the static resources that a pre-cached page would ordinarily load had it been viewed by a browser. The ACE is not a browser, so all it preloads is the HTML source, and not the static assets such as JS/CSS, images, or other media, etc.

**Comment by jaswrks** [comment]
@GermontZ Have you tried this yet?
https://support.cloudflare.com/hc/en-us/articles/206776707-Does-CloudFlare-do-prefetching-

**Comment by GermontZ** [comment]
> Prefetching is available for all Enterprise customers. To upgrade to Enterprise, contact the CloudFlare team.

Thx anyway, worth reading.
Other than that, it could be taken into account that not everyone includes attachments, or archive subpages into sitemap. The ACE engine could be improved and preload some predefined pages:
- every blog pages
- attachments

I must create a list with those links and add it to the ACE list.

**Comment by jaswrks** [comment]
I see. Enterprise only.

Well, to me, this feature request seems like it would be rarely-used; i.e., prefetching content for the purpose of being able to serve it in offline mode whenever an under-provisioned server goes offline frequently.

It sounds like CloudFlare already has you covered for this, but it is reserved for Enterprise customers.

**Comment by GermontZ** [comment]
Well, than I will create myself a list for the ACE or download manager...
Thanks both of you for the patience to answer :-)
