### ISSUE TITLE
Option to Cache by Browser Brand (to Fix an Oversight)

### ISSUE THREAD

**Issue by VR51** [wpsharks/comet-cache#668]
Made an observation a few minutes ago while trying to figure out why CSS rules that target specific web browsers would work then not work then work then not.... Surprised I didn't spot this before.

**The Scenario**
- The body element of my pages contains a CSS class for the web browser brand e.g. Firefox, IE, Chrome.
- I often use CSS rules that are specific to web browser brands.
- When a cached page is displayed, the body element contains only the CSS classes that were delivered to the web browser than prompted the creation of the page cache.
- This means my precision crafted browser targeting CSS fails to deliver results.

**Feature Request**

Can we add an option to serve cache pages filtered by browser brand.

Or

Can we use a little regex rule to insert the browser related CSS classes into the opening body as pages are served.

**Short-term Workaround**

CSS classes can be inserted with Javascript or jQuery.

Kicking myself right now for not noticing this oversight earlier.

**Comment by jaswrks** [comment]
> Can we add an option to serve cache pages filtered by browser brand.

You can already do this with a Version Salt.
See: http://zencache.com/kb-article/introduction-to-dynamic-version-salts/

**Comment by VR51** [comment]
Hadn't thought of using version salts. Thanks for this advice.
