### ISSUE TITLE
Blank page on first load

### ISSUE THREAD

**Issue by Bobchev** [wpsharks/comet-cache#669]
Hello, when I activate the plugin, the website become blank on first load. I have similar problem with other cache plugins.

**Comment by raamdev** [comment]
We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [WordPress.org Support Forum](https://wordpress.org/support/plugin/zencache) (for ZenCache Lite) or open a [Trouble Ticket](https://www.websharks-inc.com/support/?product=zencache&request_type=trouble_ticket) (ZenCache Pro). Thank you! :)
