### ISSUE TITLE
HTML compression works except on homepage

### ISSUE THREAD

**Issue by marcselman** [wpsharks/comet-cache#672]
Hi,

On my website nomadandvillager.com the HTML compression seems to work fine, except on the homepage.
Any ideas what could cause this?

Thanks

**Comment by raamdev** [comment]
@marcselman We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [WordPress.org Support Forum](https://wordpress.org/support/plugin/zencache) (for ZenCache Lite) or open a [Trouble Ticket](https://www.websharks-inc.com/support/?product=zencache&request_type=trouble_ticket) (ZenCache Pro). Thank you! :)
