### ISSUE TITLE
Bug: Settings Link in Multisite Network

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#675]
![2016-02-21_06-07-11](https://cloud.githubusercontent.com/assets/1563559/13203302/9d7de2ae-d861-11e5-926e-1b6837d442a8.png)

The settings link leads to an error when viewing the list of active plugins on the Main Site in a Network installation. I actually was not expecting to find ZenCache listed there at all, so a solution to this problem might be to simply exclude those additional links whenever `is_multisite() && !is_network_admin()`
## Steps to Reproduce
- Install on a MS Network installation and network activate.
- Visit the Dashboard for the Main Site (not the Network Admin).
- View the list of active plugins from the Main Site.
- Click the [Settings] link.
## Expected Behavior

That it would take me to the Network admin panel.
## Observed Behavior

Permission denied, as a result of trying to load Settings on the Main Site instead of via the Network Admin panel.

**Comment by raamdev** [comment]
Confirmed fixed via https://github.com/websharks/zencache-pro/commit/d640106f580025013c8c66807f5907a673a46d45.

![2016-02-21_10-37-10](https://cloud.githubusercontent.com/assets/53005/13203471/19137044-d887-11e5-83a6-966417df8855.png)

Also, it appears that the Multisite behavior changed in a recent WordPress update, as one of my Multisite test sites was running an older version of WordPress and ZenCache simply did not show up in the Main Site plugins list at all. Once I updated to the latest version of WordPress, all of the plugins that were Network Activated appeared in the Main Site plugins list.

**Comment by raamdev** [comment]
Next Lite Release Changelog:
- **Bug Fix (Multisite)**: Fixed a bug where when ZenCache was Network Activated the plugin settings link would show up in the plugins list for the Main Site and would lead to a 404 error. The settings link is now only shown when viewing the plugins list from the Network Admin. Props @jaswsinc. See [Issue #675](https://github.com/websharks/zencache/issues/675).

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix (Multisite)**: Fixed a bug where when ZenCache was Network Activated the plugin settings link would show up in the plugins list for the Main Site and would lead to a 404 error. The settings link is now only shown when viewing the plugins list from the Network Admin. Props @jaswsinc. See [Issue #675](https://github.com/websharks/zencache/issues/675).

**Comment by raamdev** [comment]
**ZenCache v160222** has been released and includes changes from this GitHub Issue. See the [v160222 announcement](http://zencache.com/zencache-v160222-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#675).
