### ISSUE TITLE
Backwards compatibility for ZENCACHE_ALLOWED is missing

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#683]
There should be backwards compatibility in Comet Cache for the `ZENCACHE_ALLOWED` constant, so that if a site owner had been using `define('ZENCACHE_ALLOWED', FALSE);`, Comet Cache should pick that up and treat it the same way it would `COMET_CACHE_ALLOWED` (i.e., caching should be disabled if that constant is set to `FALSE`). 

However, I confirmed that `ZENCACHE_ALLOWED` is not working in Comet Cache v160223.1.

---

Reported in (private ticket): https://websharks.zendesk.com/agent/tickets/11379

**Comment by jaswrks** [comment]
It looks like the `12` here needs to change to the number of characters in `ZENCACHE_`. https://github.com/websharks/comet-cache-pro/blob/160223.1/src/includes/classes/AdvCacheBackCompat.php#L54

**Comment by raamdev** [comment]
@jaswsinc Ah! Thanks for pointing that out. That would've taken me some digging to discover. :smile:

**Comment by raamdev** [comment]
@jaswsinc Correct me if I'm wrong, but it looks like `GLOBAL_NS` is not available in the scope of where this runs: https://github.com/websharks/comet-cache-pro/blob/160223.1/src/includes/classes/AdvCacheBackCompat.php#L54

**Comment by raamdev** [comment]
Hmm, nope, that's wrong. I see that `src/includes/stub.php`, where `GLOBAL_NS` is defined, gets included before the compat. routines: https://github.com/websharks/comet-cache-pro/blob/160223.1/src/includes/templates/advanced-cache.txt#L22-L28

I'm trying to figure out why despite [this line](https://github.com/websharks/comet-cache-pro/blob/160223.1/src/includes/classes/AdvCacheBackCompat.php#L58) being run (now that I've fixed the number of characters being looked for), the `COMET_CACHE_ALLOWED` constant is not being set.

**Comment by raamdev** [comment]
Ah, it's because `GLOBAL_NS` is set to a lowercase `comet_cache`, which results in the constant being set to `comet_cache_ALLOWED`, instead of `COMET_CACHE_ALLOWED`.

**Comment by raamdev** [comment]
Next Release Changelog:
- **Bug Fix**: Fixed a ZenCache Backwards Compatibility bug that was preventing `ZENCACHE_ALLOWED` from working properly with Comet Cache. See [Issue #683](https://github.com/websharks/comet-cache/issues/683).

**Comment by raamdev** [comment]
**Comet Cache v160227** has been released and includes changes from this GitHub Issue. See the [v160227 announcement](https://cometcache.com/blog/comet-cache-v160227-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#683).
