### ISSUE TITLE
Settings are not saving anymore

### ISSUE THREAD

**Issue by zaproo-support** [wpsharks/comet-cache#684]
We have bought the Pro version and now we can enable and disable the cache, other settings are not saving anymore.

**Comment by raamdev** [comment]
@indrekpihor I've tested saving other settings and it works fine for me. Which settings specifically are not working? 

Also, have you tried clicking the Restore button to reset the Comet Cache configuration to the defaults?

![2016-02-24_22-12-22](https://cloud.githubusercontent.com/assets/53005/13308714/d1e64e98-db43-11e5-9e1b-29643288955b.png)

**Comment by zaproo-support** [comment]
yes, this didnt help.

**Comment by jaswrks** [comment]
@raamdev writes...

> Which settings specifically are not working?

@indrekpihor Which settings are not changing for you? Is there anything in particular that you can point to which might shed light? i.e., Do you have any thoughts about what could have led to this scenario?

 Also, can you take a screenshot of the top of your Comet Cache Pro Dashboard for us, just so we can see which version is installed, and confirm that you do in fact have the pro version recognized.

Also, if problems persist, try clearing your OPcache also, as this can sometimes contain old PHP code in memory; i.e., you can update to the latest version, but if the old version is still cached in PHP memory by PHP itself, the old version is actually still running. Comet Cache Pro comes with a tool in the admin bar that allows you to reset the OPcache.

**Comment by zaproo-support** [comment]
As I wrote before, please look first comment. Anyway, its seems like they all return to default when we hit save. All dropdowns are in default position. It didnt happen on ZenCache, I will probably go back to free version if that works better.

**Comment by jaswrks** [comment]
I see. So it's _all_ of the options then? Is that correct?

What about OPcache. What did you find there?

**Comment by zaproo-support** [comment]
Right.
Where is the OP tool?

**Comment by jaswrks** [comment]
If you don't see it in your Admin Bar already, and if you cannot save the options, you won't be able to turn that on. Instead, you can try running it through a script like this:

``` php
<?php
opcache_reset();
```

http://php.net/manual/en/function.opcache-reset.php

**Comment by zaproo-support** [comment]
i did that.. on CLI. So thats not the case. Still same thing.

**Comment by jaswrks** [comment]
Hmm. How strange! Have you tried testing in a clean installation also? Raam reported success, and I haven't been able to reproduce this yet either. https://cometcache.com/kb-article/testing-comet-cache-in-a-clean-wordpress-installation/
