### ISSUE TITLE
Time out switching to Comet Cache, can't file ticket through site

### ISSUE THREAD

**Issue by noodlz** [wpsharks/comet-cache#685]
Trying to switch from Zen Cache Pro to Comet Cache Pro, and my website is timing out after clicking on the Activate button and waiting 30 seconds. I'm on Rackspace.

You also have a problem with your site, I tried to file a ticket through the paid customers link but it's saying my email address doesn't exist as a customer, even though I'm copying/pasting straight from my profile page.

**Comment by raamdev** [comment]
@noodlz Thanks for the heads up on the support center issue; we're aware of the problem and we're working on it. :-) 

Regarding the ZenCache → Comet Cache migration: Can you try manually uninstalling ZenCache and Comet Cache following these [manual uninstall instructions](https://cometcache.com/kb-article/how-do-i-uninstall-comet-cache/#toc-86754ab8)? Once that's done, try installing Comet Cache again and see if you have any issues.

**Comment by jaswrks** [comment]
This issue with the support center has now been resolved. Thanks for the heads up.

---

@noodlz writes...

> Trying to switch from Zen Cache Pro to Comet Cache Pro, and my website is timing out after clicking on the Activate button and waiting 30 seconds. I'm on Rackspace.

Are you still having this trouble? I have been unable to reproduce thus far. Any additional details that you can provide? e.g., maybe a step-by-step on how to reproduce that error.

**Comment by noodlz** [comment]
Whatever was happening seems to be fixed now, it activated instantly. Thanks.
