### ISSUE TITLE
3rd Party Plugin Compatibility: AMP

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#688]
The [AMP plugin](https://wordpress.org/plugins/amp/) adds support for the [Accelerated Mobile Pages (AMP) Project](https://www.ampproject.org/). AMP is already used by Google and is becoming a big thing. The AMP WordPress plugin (developed by Automattic) already has 10k+ active installs.

Initial testing with Comet Cache v160223.1 indicates that AMP pages (which are generated by appending `/amp/` to the URL, e.g., for `/example-post/` you simply access `/example-post/amp/` to get the AMP version) are cached fine by Comet Cache, resulting in a cache file stored in `[...]/example-post/amp.html`.

However, what is not working is the automatic clearing of the AMP cache file when the post changes. So if we edit the Example Post, Comet Cache clears the cache file for `/example-post/` but _does not_ clear the cache file for `/example-post/amp/`. We need to update Comet Cache to add support for the AMP plugin.

**Comment by theperfectwill** [comment]
+5

**Comment by jaswrks** [comment]
This is an easy fix. We can change [this line](https://github.com/websharks/comet-cache-pro/blob/160223.1/src/includes/closures/Shared/CachePathUtils.php#L33) to the following:

```
return '(?:\/index|\/amp)?(?:\.|\/(?:page\/[0-9]+|comment\-page\-[0-9]+)[.\/])';
```

The same thing in [this line](https://github.com/websharks/comet-cache-pro/blob/160223.1/src/includes/closures/Shared/CachePathUtils.php#L31) also.

**Comment by jaswrks** [comment]
We may also need to look at how permalinks are structured when this plugin is running, because we need to know if pagination occurs like `/amp/page-2` or `/page-2/amp` for instance.

**Comment by raamdev** [comment]
It appears that Comments, Pages, and Archives are not supported at all yet by the AMP plugin. The comments section and any links to comments do not appear on posts that are loaded via AMP. 

The only other thing to note is that you can also load the AMP version of a post by appending `?amp=1`, so we should be sure to consider that.

**Comment by raamdev** [comment]
@jaswsinc FYI, I tested and confirmed the fix you noted above. It works great! Cache files for AMP versions of posts are now automatically cleared when a post cache needs to be cleared. :-) I've submitted a PR that I will be merging soon.

**Comment by jaswrks** [comment]
Cool. That's awesome!

**Comment by raamdev** [comment]
Next Release Changelog:
- **Accelerated Mobile Pages (AMP) Compatibility**: Added full support for Accelerated Mobile Pages via the [AMP plugin](https://wordpress.org/plugins/amp/). Comet Cache now works great alongside the AMP plugin. AMP-generated pages will be cached and those cache files will be intelligently cleared when necessary to keep things up-to-date. See [Issue #688](https://github.com/websharks/comet-cache/issues/688).

**Comment by raamdev** [comment]
**Comet Cache v160227** has been released and includes changes from this GitHub Issue. See the [v160227 announcement](https://cometcache.com/blog/comet-cache-v160227-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#688).
