### ISSUE TITLE
Backwards Compatibility for $GLOBALS['quick_cache'] is missing 

### ISSUE THREAD

**Issue by Kedakai** [wpsharks/comet-cache#691]
Good evening everyone,
i have a very annoying Issue.
Environment:
Wordpress Site, that has used Zencache before (Which worked fine!).

One of my friends told me this evening that changes made in the Plugins:
"Pretty simple progress meter" or
"tablepress" are not visible for not logged-in users.

I knew immediately that this was a Comet Cache Issue, but i thought about other points before, because of the fact, that Zencache worked perfectly.
I've checked the File permissions, checked if Comet Cache is on the newest Version.

If i try to change a site or a post, Comet Cache clears the cache just fine and the contect if visible for everyone. 

Any Idea how to fix this?

Faithfully,
Alexander

**Comment by raamdev** [comment]
@Kedakai If you reinstall ZenCache, does the problem go away? 

The Comet Cache codebase is exactly the same as the ZenCache codebase--the only thing we changed was the name of the plugin. So if it was working fine with ZenCache, it should work just fine with Comet Cache. If you can reinstall ZenCache and verify that it actually does work with ZenCache but not with Comet Cache, I'll see if I can take a closer look.

One other thing comes to mind: Do you have any custom code in place (an MU-Plugin, perhaps) that is using the ZenCache API? The current version of Comet Cache is supposed to include full backwards compatibility for ZenCache, but that compatibility is currently broken in Comet Cache v160223.1. We'll be doing a maintenance release this weekend to fix the backwards compatibility with ZenCache.

**Comment by Kedakai** [comment]
With Zencache the changes in tablepress worked fine.
Comet Cache does not recognize this changes, i think.

I have recorded the Issue so i can prove what i'm saying.
https://www.youtube.com/watch?v=_iH43m9AOcc (Available soon in 1080P60FPS)

I have no Costum Plugins installed and i haven't modified a Plugin ever.

**Comment by raamdev** [comment]
@Kedakai Thank you very much for the video. I just watched it and I see the problem you are demonstrating. I will look into this issue a bit more and update here when I have more info.

**Comment by raamdev** [comment]
@Kedakai I have confirmed the bug. The issue is that TablePress is using `$GLOBALS['quick_cache']->clear_cache()` to integrate with our caching plugin. That's the old API call (it should now be `comet_cache::clear()`;  see [Is there an API call that clears the cache?](https://cometcache.com/kb-article/is-there-an-api-call-that-clears-the-cache/)). ZenCache had backwards compatibility for Quick Cache, but Comet Cache dropped support for Quick Cache backwards compatibility.

We're going to add Quick Cache backwards compatibility back into Comet Cache so that plugins like TablePress continue to work as expected. This fix will go out with the next release, later today. :-)

Thanks so much for reporting this!

**Comment by Kedakai** [comment]
@raamdev, great!
Thanks for the great support :-)

**Comment by raamdev** [comment]
Next Release Changelog:
- **Bug Fix**: Fixed a Quick Cache Backwards Compatibility bug that was preventing calls to `$GLOBALS['quick_cache']` from working properly with Comet Cache. Props to @Kedakai for reporting. See [Issue #691](https://github.com/websharks/comet-cache/issues/691).

**Comment by raamdev** [comment]
**Comet Cache v160227** has been released and includes changes from this GitHub Issue. See the [v160227 announcement](https://cometcache.com/blog/comet-cache-v160227-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#691).
