### ISSUE TITLE
Accelerated Mobile Pages (AMP) + HTML Compressor

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#695]
The Comet Cache HTML Compressor currently causes several validation errors when applied to AMP pages (which are loaded by appending `/amp/` to the URL of a page). 

AMP has very specific rules for the markup of a page, as the whole point of the AMP project is to create somewhat of a standard for maximizing the speed and simplicity of displaying pages on mobile devices.

The following two sections particularly relevant to the HTML Compressor are copied from the [AMP HTML Format Spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md):

---
### Required markup

AMP HTML documents MUST
- <a name="dctp"></a>start with the doctype `<!doctype html>`. 
- <a name="ampd"></a>contain a top-level `<html ⚡>` tag (`<html amp>` is accepted as well).
- <a name="crps"></a>contain `<head>` and `<body>` tags (They are optional in HTML).
- <a name="canon"></a>contain a `<link rel="canonical" href="$SOME_URL" />` tag inside their head that points to the regular HTML version of the AMP HTML document or to itself if no such HTML version exists.
- <a name="chrs"></a>contain a `<meta charset="utf-8">` tag as the first child of their head tag.
- <a name="vprt"></a>contain a `<meta name="viewport" content="width=device-width,minimum-scale=1">` tag inside their head tag. It's also recommend to include `initial-scale=1` (1).
- <a name="scrpt"></a>contain a `<script async src="https://cdn.ampproject.org/v0.js"></script>` tag inside their head tag.
- <a name="boilerplate"></a>contain the [AMP boilerplate code](amp-boilerplate.md) in their head tag.

(1) `width=device-width,minimum-scale=1` is required to ensure [GPU rasterization](https://www.chromium.org/developers/design-documents/chromium-graphics/how-to-get-gpu-rasterization) is enabled.
### Custom fonts

Authors may include stylesheets for custom fonts. The 2 supported methods are link tags pointing to whitelisted font providers and `@font-face` inclusion.

Example:

``` html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
```

Font providers can be whitelisted if they support CSS-only integrations and serve over HTTPS. The following origins are currently allowed for font serving via link tags:
- https://fast.fonts.net
- https://fonts.googleapis.com

IMPLEMENTERS NOTE: Adding to this list requires a change to the Google AMP Cache CSP rule.

Authors are free to include all custom fonts via a `@font-face` CSS instruction via their custom CSS. Fonts included via `@font-face` must be fetched via the HTTP or HTTPS scheme.

---
## Validation Errors Caused by the HTML Compressor

Given all these requirements, it doesn't look like the HTML Compressor will be able to do any combining of resources into smaller files, as that violates several of these rules and throws validations errors.

Here's an example of those validation errors when the HTML Compressor is enabled (the blurred out errors are not related to the HTML Compressor or Comet Cache):

![2016-02-28_15-05-04](https://cloud.githubusercontent.com/assets/53005/13381554/e9585c06-de2c-11e5-8157-93aef8beea5c.png)

---
## How to Improve Compatibility

The easiest way to improve compatibility with AMP would be to always disable specific HTML Compressor options when compressing `/amp/` pages. That way AMP pages can still benefit from things like HTML Compression. 

In my testing, the following HTML Compressor configuration works fine with AMP pages. If we can turn off the highlighted options below whenever compressing an `/amp/` page, that will be a great way to improve compatibility:

![2016-02-28_15-01-11](https://cloud.githubusercontent.com/assets/53005/13381559/2472d690-de2d-11e5-8c3f-acef72d26710.png)

**Comment by jaswrks** [comment]
Referencing: https://github.com/websharks/comet-cache-pro/blob/160227/src/includes/closures/Ac/HtmlCUtils.php#L42-L66

**Comment by Li-An** [comment]
I confirm the problem with AMP and last version of Comet Cache. I do not use HTML compression on my sites and I've got a bunch of 404 errors. ![See here](https://framapic.org/1avHTcvG3BbE/Je4h2tBLeX9C)

**Comment by raamdev** [comment]
@Li-An This GitHub issue is specifically related to Comet Cache + HTML Compressor and the AMP plugin. If you're not using the HTML Compressor and you're seeing an issue, please provide us with some additional details about the problem so that we can investigate more closely.

Also, the URLs in your screenshot indicate the 404 errors were for `blog/11/`, etc. However, the WordPress AMP plugin specifically loads pages only when `/amp/` is appended to the URL, so it doesn't even look like those URLs (`blog/11/`, etc.) are using AMP.

**Comment by Li-An** [comment]
OK, sorry. After reflexion I may be wrong but cannot understant where the problem comes from.

**Comment by e11productions** [comment]
After trying the suggestions for HTML compression setting, the page speed dropped significantly. Will a future update correct the issue? If not, are there any other suggestions you may have?

**Comment by raamdev** [comment]
@e11productions As described above under "Validation Errors Caused by the HTML Compressor", the markup required by AMP (see "Required markup" above) does not support compression. If you try to compress AMP markup, you will get validation errors. There's nothing Comet Cache can do about that, as we have no control over what AMP requires.

**Comment by raamdev** [comment]
@e11productions writes...

> Will a future update correct the issue?

As described earlier in this issue, a future update will selectively disable the appropriate HTML Compressor features only when an AMP page is being loaded, yes. Right now, disabling some of the HTML Compressor features as described above (so that you don't get AMP validation errors) also disables those HTML Compressor features for non-AMP pages, which is of course not ideal.

The fix we'll be implementing will selectively disable those HTML Compressor features for AMP pages, but there's no way to make all of the HTML Compressor features work with AMP pages due to the requirements set forth in the [AMP HTML Format Spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md).

**Comment by jaswrks** [comment]
Noting that a follow-up release of the HTML Compressor was needed here as well, due to the bug mentioned in the release notes: https://github.com/websharks/html-compressor/releases/tag/161208

**Comment by renzms** [comment]
@raamdev @jaswsinc 

### Confirmed Working

This is confirmed working for `<html ⚡>`, `<html amp>` and URLS ending in `/amp`.

Page loads normally without console errors while the HTML Compressor is active with the option to detect AMP + disable incompatible features. 

![screen shot 2016-12-16 at 8 06 49 am](https://cloud.githubusercontent.com/assets/13220018/21247139/32f7501c-c368-11e6-9c06-374bd3cc79d6.png)


I aslo tested this using the [AMP Plugin](https://wordpress.org/plugins/amp/faq/)

Please note that the AMP Plugin hasn't been updated for at least 2 months and has not been tested with WP 4.7 so there are some features that were incompatible with this version of WordPress.

![screen shot 2016-12-16 at 8 09 12 am](https://cloud.githubusercontent.com/assets/13220018/21247160/59384d6c-c368-11e6-93d4-60afa7edb97a.png)


```
Deprecated: Non-static method AMP_Customizer_Design_Settings::register_customizer_ui() should not be called statically in /app/src/wp-includes/class-wp-hook.php on line 298 

Call Stack: 0.0009 388392 
1. {main}() /app/src/index.php:0 0.0017 388736 
2. require('/app/src/wp-blog-header.php') /app/src/index.php:17 0.2673 3986248 
3. require_once('/app/src/wp-includes/template-loader.php') /app/src/wp-blog-header.php:19 0.2674 3986248 
4. do_action() /app/src/wp-includes/template-loader.php:12 0.2674 3986624 
5. WP_Hook->do_action() /app/src/wp-includes/plugin.php:453 0.2674 3986624 
6. WP_Hook->apply_filters() /app/src/wp-includes/class-wp-hook.php:323 0.2699 3987800 
7. amp_render() /app/src/wp-includes/class-wp-hook.php:298 0.3015 4080504 
8. do_action() /app/src/wp-content/plugins/amp/amp.php:127 0.3015 4080880 
9. WP_Hook->do_action() /app/src/wp-includes/plugin.php:453 0.3015 4080880 
10. WP_Hook->apply_filters() /app/src/wp-includes/class-wp-hook.php:323 0.3015 4082008 
11. AMP_Template_Customizer->init_preview() /app/src/wp-includes/class-wp-hook.php:298 0.3015 4082008 
12. AMP_Template_Customizer->register_ui() /app/src/wp-content/plugins/amp/includes/admin/class-amp-customizer.php:99 0.3018 4086360 
13. do_action() /app/src/wp-content/plugins/amp/includes/admin/class-amp-customizer.php:117 0.3018 4086736 
14. WP_Hook->do_action() /app/src/wp-includes/plugin.php:453 0.3018 4086736 
15. WP_Hook->apply_filters() /app/src/wp-includes/class-wp-hook.php:323

```

**Comment by raamdev** [comment]
**Comet Cache v161221** has been released and includes changes from this GitHub Issue. See the [v161221 announcement](https://cometcache.com/blog/comet-cache-v161221-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#695).
