### ISSUE TITLE
How to use a Cookie Free Domain?

### ISSUE THREAD

**Issue by theperfectwill** [wpsharks/comet-cache#697]
I am trying out the [Cookie Free Domain](https://codex.wordpress.org/Editing_wp-config.php#Set_Cookie_Domain) wp-config.php feature locally because I am new to using it. 

I have this in wp-config.php...

```
define("WP_CONTENT_URL", "http://test.dev.com"); 
define("COOKIE_DOMAIN", "test.dev.com");
```

All things (theme, plugins, etc.) are working fine for me, but Comet Cache is not doing it's job correctly, to my fault or not. I'm not sure, so let me know. 

Comet Cache is working partly... 

I end up with the following url... 

```
http://test.dev.com/cache/comet-cache/htmlc/public/customtheme-baby/9/b/5/f/6/780e4cba1b040571485f496798657337-compressor-part.css
```

But nothing is created from Comet Cache. The cache directory, folder paths and static files are not created in the cookie free domain. 

I tried running the CDN filter specifying my cookie free domain, but that doesn't work either. I watched the video tutorial and nothing helped for this issue. I'm not sure if the CDN filter is needed in this case, because the WP_CONTENT_URL is done through Wordpress in the wp-config.php? 

So, how can I use a Cookie Free Domain with Comet Cache?

And as a side note, that may come up for another user to be mindful of. I get the following console error when using a cookie free domain in Comet Cache setting pages (ie: for the font files)...

```
Cross-Origin Request Blocked: 
The Same Origin Policy disallows reading the remote resource at 
http://test.dev.com/plugins/comet-cache-pro/src/vendor/websharks/sharkicons/src/fonts/sharkicons.ttf?v160221. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

So I had to add the following to my .htaccess file to fix that console error...

```
Header set Access-Control-Allow-Origin: http://test.dev.com
```

**Comment by raamdev** [comment]
@NoahjChampion Are you saying here that your `WP_CONTENT_URL` and `WP_CONTENT_DIR` are located somewhere outside the WordPress directory? It would help to see a complete breakdown of the various locations, e.g., the path to your WordPress directory, the WordPress Site URL (see **Settings → General**), etc.

**Comment by raamdev** [comment]
Closing due to lack of feedback.
