### ISSUE TITLE
How to change the wp-content path as the top level path used?

### ISSUE THREAD

**Issue by theperfectwill** [wpsharks/comet-cache#698]
I asked this some time ago, when Comet Cache was QuickCache :) 

Back then I didn't understand as much as I do now, but I still don't see an easy way of doing this, when I looked in ZenCache or maybe I missed it. 

I'm of course using Comet Cache now... :) 

<strong>But, how can I change the wp-content path to use the [UPLOADS](https://developer.wordpress.org/reference/functions/wp_upload_dir/) directory instead? </strong>

The reason for this (for me) is because I change my uploads path so that it helps hide that face I am using Wordpress, since I can pretty much put that uploads directory anywhere. But, since Comet Cache builds and serves all it's static resources from the wp-content/$cache folder, static resources still reveal I'm using Wordpress because of the "wp" (wp-content) path. 

As a feature request it would be really nice to either choose from the settings page to use the wp-content directory or the uploads directory. The wp-content directory outside of the wp-includes and wp-admin are the most revealing of any vulnerability a Wordpress install has, if discovered. It has all the files that aren't directly related to serving a visitor their content (plugin files, theme files, etc.). Moving the uploads directory easily allows me to get rid of mostly all of that by a source code point of view because the mostly the only things in the uploads directory are user uploaded content (images, documents, etc.) no actually php execution (at least hopefully not or shouldn't be). 

So, I would like to spend some time getting this off my to-do list now. 

Would you help me out/point me in the right direction?

**Comment by jaswrks** [comment]
@NoahjChampion Take a look at the `WP_CONTENT_DIR` constant mentioned in this article. https://premium.wpmudev.org/blog/10-wp-config-tweaks-to-improve-your-wordpress-site/
