### ISSUE TITLE
Plugin Settings Page not Usable on Mobile Devices

### ISSUE THREAD

**Issue by ricsmo** [wpsharks/comet-cache#699]
The plugin settings page does not resize small enough on some mobile browsers and the "Clear Cache" button is off screen and not scrollable. Tried on iPhone 6 using Safari and Chrome in both portrait and landscape.

**Comment by raamdev** [comment]
@ricsmo Thank you for opening an issue for this. I'm aware of the problem with using the Comet Cache options pages on mobile devices, but I kept forgetting to open a GitHub issue so that I'd remember to get that fixed. :-)

We have another GitHub issue open to simplify the plugin options page itself (see https://github.com/websharks/comet-cache/issues/96) and working on this (improving mobile compatibility) would definitely be part of that work.

However, I'll leave this GitHub issue open and see if there are a few simple tweaks we can make to improve mobile layout for the next release.

**Comment by renzms** [comment]
@raamdev 

**Before Using Media Queries**:

![screen shot 2016-04-07 at 5 47 25 pm](https://cloud.githubusercontent.com/assets/13220018/14347455/bf87ea3c-fce9-11e5-8452-2725c29a07cd.png)
![screen shot 2016-04-07 at 5 47 51 pm](https://cloud.githubusercontent.com/assets/13220018/14347461/c26dad9a-fce9-11e5-95a9-c103446c35fe.png)

**Mock up using Responsive Design - Media Queries**:

```
@media (min-width: 480px) and (max-width: 1023px)
```

![screen shot 2016-04-07 at 5 45 09 pm](https://cloud.githubusercontent.com/assets/13220018/14347428/aa4a6352-fce9-11e5-8291-ec9df0895f96.png)

**Changes made**
- Images auto adjust depending on width of screen. Mock set at 90% of screen width (480px) Noting that we would need to make different parameters for Tablet (768px) and mobile(480px), horizontal/vertical (480/1024px), and retina media query. 
- Header menu items/links/buttons adjusted and centered. 

![screen shot 2016-04-07 at 5 46 52 pm](https://cloud.githubusercontent.com/assets/13220018/14347445/b5af5d6a-fce9-11e5-91a7-12f6b5f7e6f5.png)

Plugin options for drop downs are visible, but fields are smaller.

![screen shot 2016-04-07 at 6 07 02 pm](https://cloud.githubusercontent.com/assets/13220018/14347823/928a75e8-fceb-11e5-8542-8dd94e306a90.png)

Though its still possible to scroll left and right within field, this could be solved with media query for font size if needed.

**Comment by jaswrks** [comment]
@renzms That looks like a fantastic start on this. Do you have that work (seen in the screenshots above) in a separate branch that you can push for a review?

**Comment by renzms** [comment]
> That looks like a fantastic start on this. Do you have that work (seen in the screenshots above) in a separate branch that you can push for a review?

@jaswsinc 

Looks like I missed this comment from way back, I'll find some time this week to create a new branch for the work I did in the mock up. Thanks!

**Comment by raamdev** [comment]
@renzms Any update on this?

**Comment by jaswrks** [comment]
Next Release Changelog:
- **UI Enhancement:** The Comet Cache UI is now fully Responsive with an improved UI on laptops and other mobile devices. Props @renzms. See also: [issue #699](https://github.com/websharks/comet-cache/issues/699) if you'd like additional details.

**Comment by renzms** [comment]
@raamdev 

Looks good to me and adjusts properly + smoothly to browser/device size. @jaswsinc has improved upon my original PR and changed some things. 👍 

Just two things, in my opinion, I would've kept for the mobile version:

### 1) The menu panel open/close toggler

> > Original Size:
> > ![screen shot 2016-11-11 at 9 47 40 pm](https://cloud.githubusercontent.com/assets/13220018/20217172/93953166-a859-11e6-8448-8dfa044549f5.png)
> > 
> > Mobile:
> > ![screen shot 2016-11-11 at 9 48 02 pm](https://cloud.githubusercontent.com/assets/13220018/20217174/95aadac8-a859-11e6-86d9-ea71b34412da.png)

**with Wipe Button:**

> > Original Size:
> > ![screen shot 2016-11-11 at 9 56 10 pm](https://cloud.githubusercontent.com/assets/13220018/20217408/c287bc18-a85a-11e6-957c-a193d02a8e47.png)
> > 
> > Mobile:
> > ![screen shot 2016-11-11 at 9 56 49 pm](https://cloud.githubusercontent.com/assets/13220018/20217412/c5dca036-a85a-11e6-925b-c4809e3dd84c.png)

---

## 2) The `Comet Cache = Speed` image

> > Original Size:
> > ![screen shot 2016-11-11 at 9 46 22 pm](https://cloud.githubusercontent.com/assets/13220018/20217192/a01ef980-a859-11e6-80e3-60583322a97a.png)
> > 
> > Mobile:
> > ![screen shot 2016-11-11 at 9 46 37 pm](https://cloud.githubusercontent.com/assets/13220018/20217188/9de94ff8-a859-11e6-95fa-d27b8b90a620.png)

Other than that, works fine on Ipad and Android mobile! :)

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#699).
