### ISSUE TITLE
BUG: Comet Cache v160227 running Nginx / MariaDB server on Ubuntu causes PHP Fatal error: Uncaught exception 'RuntimeException' 

### ISSUE THREAD

**Issue by renzms** [wpsharks/comet-cache#700]
Using Comet Cache v160227 on Nginx / MariaDB server on Ubuntu causes PHP Fatal error

```
PHP Fatal error: Uncaught exception 'RuntimeException' with message 'SplFileInfo::getType(): Lstat failed for /websites/supersite-31/public_html/wp-content/cache/zencache/cache/http/chronicle-northcoastnow-com/2015/11/01/girl-scouts-get-hands-on-experience.html' in /websites/supersite-31/public_html/wp-content/plugins/comet-cache-pro/src/includes/closures/Shared/FsUtils.php:275
```

(full error message with stack trace here: http://pastebin.com/2Yfq71yZ)

---

Referencing Internal ticket: https://websharks.zendesk.com/agent/tickets/11528

**Comment by raamdev** [comment]
Referencing line mentioned in error message: https://github.com/websharks/comet-cache-pro/blob/160227/src/includes/closures/Shared/FsUtils.php#L275

**Comment by jaswrks** [comment]
Hmm. I replied to that ticket to inquire about the type of filesystem they have.

**Comment by jaswrks** [comment]
The user writes...

> EXT4 partition on a ubuntu 14.04.02 that is virtualized through Vsphere.

**Comment by jaswrks** [comment]
User has been invited to collaborate with us here, and I requested that they run the following command so that we can hopefully learn more about the condition of this particular file.

``` bash
$ stat /websites/supersite-31/public_html/wp-content/cache/zencache/cache/http/chronicle-northcoastnow-com/2015/11/01/girl-scouts-get-hands-on-experience.html
```

**Comment by gossipninja** [comment]
File: ‘/websites/supersite-31/public_html/wp-content/cache/zencache/cache/http/chronicle-northcoastnow-com/2011/08/17/high-school-football-2011-running-game-young-clippers-e2-80-99-biggest-asset.html’
  Size: 63090           Blocks: 128        IO Block: 4096   regular file
Device: 811h/2065d      Inode: 15089170    Links: 1
Access: (0644/-rw-r--r--)  Uid: (   33/www-data)   Gid: (   33/www-data)
Access: 2016-03-04 13:37:30.526644962 -0500
Modify: 2016-03-04 13:37:30.526644962 -0500
Change: 2016-03-04 13:37:30.526644962 -0500
 Birth: -

**Comment by gossipninja** [comment]
is there any other information I can provide?

**Comment by jaswrks** [comment]
@gossipninja Thank you for those details. I apologize for the delayed response, I was on vacation over the past few days.

I see from the `stat` output that the file looks like it is a condition that we would expect; i.e., nothing jumping right out at me yet I'm afraid. You mentioned this was an ext4 filesystem. Do you know if that drive is an NFS mount powered by something like GlusterFS or any other NFS-based drive? i.e., is that drive on a dedicated server or is it located in the cloud elsewhere?

**Comment by gossipninja** [comment]
as far as I know it is a set as a drive in a dedicated server, the server
itself is a VM on vsphere

**Comment by jaswrks** [comment]
> as far as I know it is a set as a drive in a dedicated server, the server
> itself is a VM on vsphere

I see, thank you. As a next step in debugging this, if you can try to learn more about the underlying drive where the cache files are stored and report back, it may shed light.

Cloud and network-based filesystems tend to have more trouble with file locking, which is required for Comet Cache as it needs to lock the cache whenever it writes to or updates it. If the drive is network-based, it may explain the problem that you reported here. If not, I'd like to have a closer look.

**Comment by gossipninja** [comment]
is there a command I can run to take a look? Or do I need to check with our
contractors to see how they have it provisioned in vcenter?

**Comment by jaswrks** [comment]
Not that I'm aware of, sorry. I think contacting the host would be easiest.

**Comment by gossipninja** [comment]
I asked if the /websites was set as an NFS share or glusterFS and they
said no.
"It is just a separate virtual disk than the rest of the OS.  All hard
drives are connected to a SAN via iSCSI at the VMWare layer and not at the
OS layer."

So hopefully that gives you some info.

Sorry this is a pain.

**Comment by jaswrks** [comment]
@gossipninja Thank you for checking. That does help.

> SAN via iSCS

So it sounds like that could be problematic in this case, because this type of drive, while not classified as a network-based file system, usually does not have it's own set of network-based file systems that effectively make this a _virtual_ shared drive; i.e., normal file locking techniques may fail on a drive of this type, because the underlying drive space it provides may come from one or more sources that are being accessed by other machines at the same time.

My suggestion is that you try to tell Comet Cache to use a different file locking mechanism on that server. For instance, using a Semaphore is something that Comet Cache is already equipped with, it just needs to be enabled for cases like this. Please see: https://cometcache.com/kb-article/how-do-i-change-the-cache-locking-type-flock-vs-sem_get/

**Comment by gossipninja** [comment]
Thanks for this.

luckily our server appears to have semaphore already installed (so no
recompile)

I followed the instructions you sent and added that file to the mu-plugins
directory. And fingers crossed it gets rid of the errors.

Thanks again.
