### ISSUE TITLE
inconsistent HTTP headers

### ISSUE THREAD

**Issue by jessuppi** [wpsharks/comet-cache#701]
I've spent the last several days researching this across several websites, and though I'm not 100% sure, it seems like the HTTP headers being sent by CC are inconsistent.

_Quick background:_ it seems generally agreed upon that HTTP headers sent by modern web servers should include both one "strong" cache header and one "weak" cache header, that is one of either `Expires` or `Cache-Control` and one of either `Etags` or `Last Modified` ... furthermore my research has concluded that `Etags` are best used only for static resources due to MD5 hashing, and that `Expires` is becoming less preferred than `Cache-Control` for various reasons.

On your "recommended Nginx configuration" you recommend `Etags` and `If Modified Since` to be set on the server block, but since Nginx doesn't serve WordPress (PHP) pages directly these don't seem to have any bearing on your plugin's configuration (only on static files). Also keep in mind that newer Nginx versions enable `Etags` by default anyway.

For a dynamic environment like WordPress this would probably mean that a single `Cache-Control` HTTP header and a single `Last Modified` header would be most appropriate. In addition, `If Modified Since` a.k.a. 304 HTTP headers would best be avoided, at least in a user-friendly cache plugin, with mind to potential conflicts with shopping carts, comments, and so forth.

But in the case of CC it seems that your plugin uses both `Expires` AND `Cache-Control` AND also the rather outdated `Pragma` header which isn't really used anymore.

The issues that I've seen are all on sites behind CloudFlare, however, keep in mind that CloudFlare claims to not alter any HTTP headers sent from an origin server, besides dropping any redundant headers, for example they will honor only the first `Cache-Control` header found. But my testing was with their "dev mode" enabled so it seems to be irrelevant in any regard.

Anyway here's a simpler breakdown:

**A.** CC has a setting _Client Side Cache_ which would seem to imply that the plugin is setting HTTP cache headers on behalf of WordPress, however, even with this setting enabled it seems that the `no-cache` directive still shows in both `Cache-Control` and `Pragma` HTTP headers. In addition, the `Expires` header is set to a date in 1981 which is its way of disabling itself.

**B.** Even when CC is in _Inactive_ mode, it still adds the three HTTP headers mentioned above.

**C.** Even when using a third-party plugin (Add Headers) to generate missing HTTP headers, it seems that CC strips these out perhaps, for example `Last Modified` generated by Add Headers disappears after enabling the CC plugin, although this only seems occasional (not sure).

Ultimately, there are a few solutions here I believe:
1. Ensure your _Client Side Cache_ is indeed responsible for HTTP headers and perhaps mention it briefly on the control panel under that feature. If that option is disabled, then `max-age=0` should be set within the `Cache-Control` header site-wide. If the CC plugin is in _Inactive_ mode, absolutely no HTTP headers should be sent by the plugin whatsoever.
2. Ensure only a single `Cache-Control` and single `Last Modified` header are being sent, or, allow webmasters to choose which HTTP headers they wish to send. Moreover, perhaps explore the "order" of WP header hooks (etc) because a plugin like CC should probably be able to forcefully over-write any conflicting HTTP headers that may exist already.
3. When website URIs are entered for exclusion to CC they should also have `max-age=0` set within the `Cache-Control` header for those excluded pages.
4. Don't recommend any Nginx server-level cache configuration besides for static files, otherwise it gets confusing fast; WordPress (PHP) should be generating such HTTP headers.

I may have missed a few points here but hopefully this gets a discussion going in the right direction and anyway the free Add Headers plugin is a nice place to start. Cheers!

**Comment by raamdev** [comment]
@jessuppi Thanks so much for the detailed feedback! :-)

I just reviewed the codebase to remind myself how all of this works and I'm sharing that below. This will require more research and discussion (hoping that @jaswsinc will chime in here soon). 

Also, referencing two related issues: https://github.com/websharks/comet-cache/issues/255 and https://github.com/websharks/comet-cache/issues/134.

---

The method that removes `Last-Modified` and adds `Expires`, `Cache-Control`, and `Pragma` is [`sendNoCacheHeaders()`](https://github.com/websharks/comet-cache-pro/blob/160227/src/includes/closures/Shared/HttpUtils.php#L156-L166). 

The method that determines when `sendNoCacheHeaders()` should be called is [`maybeStopBrowserCaching()`](https://github.com/websharks/comet-cache-pro/blob/160227/src/includes/closures/Ac/BrowserUtils.php#L4-L34). 

Here are the scenarios where `sendNoCacheHeaders()` is called from `maybeStopBrowserCaching()`:
- **Comet Cache → Plugin Options → Client-Side Cache** is enabled
- **Comet Cache → Plugin Options → Client-Side Cache** is disabled but the page is called with the `?ccABC=1` query parameter (or `?zcABC=1` or `?qcABC=1`, for ZenCache and Quick Cache backwards compatibility). 

Note that when Client-Side Caching is disabled (the default), Comet Cache simply does not call `sendNoCacheHeaders()`, which means it leaves those headers untouched. If another plugin or the server adds/removes those headers, Comet Cache should not get in the way.

Also worth noting here is that Comet Cache stores many HTTP Headers inside the cache file itself when it caches a page, and then [resends those headers](https://github.com/websharks/comet-cache-pro/blob/160227/src/includes/closures/Ac/ObUtils.php#L207) when the cached page is presented to a future visitor. See [`cacheableHeadersList()`](https://github.com/websharks/comet-cache-pro/blob/160227/src/includes/closures/Shared/HttpUtils.php#L45-L120) for a list of headers that Comet Cache allows to be cached.

**Comment by jaswrks** [comment]
@jessuppi Thank you for the feedback and willingness to discuss this topic.

You wrote...

> I've spent the last several days researching this across several websites, and though I'm not 100% sure, it seems like the HTTP headers being sent by CC are inconsistent.

They are not inconsistent, but I will try to comment on some of your notes.

---

> On your "recommended Nginx configuration" you recommend Etags and If Modified Since to be set on the server block, but since Nginx doesn't serve WordPress (PHP) pages directly these don't seem to have any bearing on your plugin's configuration (only on static files). Also keep in mind that newer Nginx versions enable Etags by default anyway.

That is correct, and it is only suggested for the purpose of speeding up the delivery of static files; i.e., as an additional suggestion that we make. It has no bearing on the cache functionality itself.

---

> For a dynamic environment like WordPress this would probably mean that a single Cache-Control HTTP header and a single Last Modified header would be most appropriate. In addition, If Modified Since a.k.a. 304 HTTP headers would best be avoided, at least in a user-friendly cache plugin, with mind to potential conflicts with shopping carts, comments, and so forth.

We follow the WordPress standard established by the `nocache_headers()` function available in core. See: https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/functions.php#L1133

This particular core function is not available in the early phase where Comet Cache runs, so we have a polyfill that does the exact same thing; i.e., in the exact same way as WordPress core would, had the core `nocache_headers()` function been called.

With respect to multiple headers being sent, the idea is to cover as many browsers as possible. All three of [these headers found in WP core](https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/functions.php#L1095-L1097) tell the browser the same thing, just in slightly different ways. In each case, the point is to make it clear that the HTML markup should _not_ be cached in the browser. I am not aware of there being any negative impact from setting all three; i.e., it only reiterates the point that is being made. Do _not_ cache the markup for the page.

---

> A. CC has a setting Client Side Cache which would seem to imply that the plugin is setting HTTP cache headers on behalf of WordPress, however, even with this setting enabled it seems that the no-cache directive still shows in both Cache-Control and Pragma HTTP headers. In addition, the Expires header is set to a date in 1981 which is its way of disabling itself.

If that's the case in your tests then I would start looking at other plugins or at WP core itself.

For instance, in WP core, all admin areas call the core `nocache_headers()` function, so it would be normal to see those headers even with Comet Cache disabled, if you are in the admin area. 

Otherwise, with Comet Cache disabled (or with Client Side Caching allowed in your Comet Cache config), those headers will not be sent by Comet Cache itself.

However, it might _appear_ that they are, given the parity between Comet Cache and the core `nocache_headers()` function that other themes/plugins call upon. So seeing those headers could mean they were set elsewhere by another plugin, not necessarily by Comet Cache.

---

> Ensure your Client Side Cache is indeed responsible for HTTP headers and perhaps mention it briefly on the control panel under that feature. If that option is disabled, then max-age=0 should be set within the Cache-Control header site-wide. If the CC plugin is in Inactive mode, absolutely no HTTP headers should be sent by the plugin whatsoever.

This is already the case. If Client-Side caching is not allowed (default behavior), no-cache headers are sent, and those include the `max-age=0` directive in the `Cache-Control:` header, along with others standardized by WP core according to `nocache_headers()`.

As @raamdev noted, the method that removes `Last-Modified` and adds `Expires`, `Cache-Control`, and `Pragma` is [`sendNoCacheHeaders()`](https://github.com/websharks/comet-cache-pro/blob/160227/src/includes/closures/Shared/HttpUtils.php#L156-L166).

---

> When website URIs are entered for exclusion to CC they should also have max-age=0 set within the Cache-Control header for those excluded pages.

This is already the case.

---

> Don't recommend any Nginx server-level cache configuration besides for static files, otherwise it gets confusing fast; WordPress (PHP) should be generating such HTTP headers.

We make recommendations on ways to enhance speed, and I feel that our Nginx recommendations are all aimed at that goal. Whether they are specifically focused on the caching functionality or not, our main goal (with caching) is to speed up a site. So any suggestions we can make that will help our users achieve that goal have value in my view.

---

> C. Even when using a third-party plugin (Add Headers) to generate missing HTTP headers, it seems that CC strips these out perhaps, for example Last Modified generated by Add Headers disappears after enabling the CC plugin, although this only seems occasional (not sure).

The removal of `Last-Modified:` was a decision on the part of WordPress core, and we follow their lead on this in an effort to remain consistent with the core `nocache_headers()` function. See discussion here: https://core.trac.wordpress.org/ticket/22258

**Comment by jaswrks** [comment]
@jessuppi Just curious. Does https://www.littlebizzy.com/ support PHP 7 yet?

**Comment by jessuppi** [comment]
Thanks for your response. I suppose this topic runs the risk of getting too deep in criticism of WordPress core (and Nginx, Google, Chrome/Webkit, etc) and when (if) it's appropriate to ignore/over-write WP core functionality. I'm not really a programmer so I can't pretend to speak authoritatively, however, there are some further points that I believe need to be made.

> That is correct, and it is only suggested for the purpose of speeding up the delivery of static files; i.e., as an additional suggestion that we make. It has no bearing on the cache functionality itself.

Fair enough, however, your recommended config is on the top of the server block. For clarity it would perhaps be best to use an example more like below, and no default `If Modified Since` as many devs do not know how to configure that correctly and it can lead to serious issues. It's really not necessary to send 304 HTTP headers for static resources in my opinion although I guess it's debatable, in any regard for the purposes of a cache plugin like CC it is perhaps confusing that your team makes this recommendation since it has no bearing on your plugin. And as mentioned there is no need to set `Etags` in Nginx as those are enabled by default (for static served files). Also, when setting `Expires` in Nginx (up to 1.9.11) the server will automatically generate the relevant `Cache-Control` header too, which further confuses things, esp. as it does not contain the `public` directive >_<

We've played around with CloudFlare-friendly (with cache plugins) Nginx configs i.e:

https://www.littlebizzy.com/blog/nginx-configuration
https://www.littlebizzy.com/blog/nginx-server-block-ssl

```
## set appropriate HTTP headers for static resources
location ~* \.(js|css|png|jpg|jpeg|gif|ico|mp4|svg|svgz|ogg|ogv|webm|htc)$ {
    ## no Expires header to avoid redundant Cache-Control headers from Nginx
    add_header Cache-Control "public, max-age=604800";
    ## enable If Modified Since for 304 headers if you understand them
    # if_modified_since before;
    log_not_found off;
    access_log off;
    }
```

What you say here is rather interesting:

> We follow the WordPress standard established by the nocache_headers() function available in core. See: https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/functions.php#L1133 This particular core function is not available in the early phase where Comet Cache runs, so we have a polyfill that does the exact same thing; i.e., in the exact same way as WordPress core would, had the core nocache_headers() function been called. With respect to multiple headers being sent, the idea is to cover as many browsers as possible. All three of these headers found in WP core tell the browser the same thing, just in slightly different ways. In each case, the point is to make it clear that the HTML markup should not be cached in the browser. I am not aware of there being any negative impact from setting all three; i.e., it only reiterates the point that is being made. Do not cache the markup for the page.
> 
> The removal of Last-Modified: was a decision on the part of WordPress core, and we follow their lead on this in an effort to remain consistent with the core nocache_headers() function. See discussion here: https://core.trac.wordpress.org/ticket/22258

Thanks for pointing that out, I wasn't aware that WP core was against `Last Modified` esp. as its still used by default by servers for static resources, etc. It does seem that Google has recently updated their recommendations, however, to include `Etags` and `Cache-Control` only:

https://developers.google.com/speed/docs/insights/LeverageBrowserCaching
vs: http://stackoverflow.com/questions/10314174/difference-between-pragma-and-cache-control-headers

The issue being that MD5 hashing of `Etags` for dynamic content is expensive. Perhaps a single HTTP header for `Cache-Control` on dynamic pages will emerge as the future. In any regard it seems bizarre that WP core is concerned with deprecating `Last Modified` yet still retains `Pragma` which is from way back in HTTP 1.0 and severely out of date at this point. Moreover, it sounds like the only reason WP core removed `Last Modified` is because of Webkit's aggressive caching, which doesn't seem like a good reason to permanently purge a popular HTTP header.

If the other inconsistencies I noticed were mistaken, I apologize. It seems that WP core is to blame perhaps; I didn't know that `no-cache` directives were sent on the frontend by default. However, I'm still seeing several cases where frontend `no-cache` exists on my client sites even when CC is fully activated so I'm not really sure what is causing that at this point.

> @jessuppi Just curious. Does https://www.littlebizzy.com/ support PHP 7 yet?

Not yet but playing around a bit, from what I've heard too many WP plugins don't support PHP7 yet and with CloudFlare it is less of an immediate priority for us too :)

**Comment by szepeviktor** [comment]
Clear your cache and use https://redbot.org/
It'll tell you all kinds of problems.

**Comment by raamdev** [comment]
Closing; I don't see anything actionable here for Comet Cache.

**Comment by petertenhoor** [comment]
It would have been nice to have a filter to add / remove headers in the $cacheable_headers array in method cacheableHeadersList(). Comet cache removes some of my http security headers which I would like to keep (Feature-Policy and Referrer-Policy).
