### ISSUE TITLE
Possible Memory Leak?

### ISSUE THREAD

**Issue by afbmb** [wpsharks/comet-cache#702]
We're operating a massive multi-site WP network. Everything has been running basically flawless since our migration to Microsoft Azure in November, up until the last week or so. Apache is continuously crashing and there appears to be a memory leak. Free memory isn't being allocated to services.

The only correlation we can see at this moment is Comet Cache. Feb. 23rd we purchased an unlimited license for Comet Cache and switched the network from ZenCache to CometCache. The time frame matches when problems started to begin.

We're still digging through log files and everything so we're still not sure what may be the cause, figured we would see if anyone else is experiencing anything similar to this?

**Comment by afbmb** [comment]
Discovered the issue.

The Comet Cache plugin by default has "Enable WebSharks™ HTML Compression" enabled. And after a few days we discovered this was interfering with certain JavaScript files of ours so we disabled it. It appears all of the compressed asset files were left behind in the /cache/comet-cache/htmlc/public/ directory but access to them was forbidden. 

Coincidentally both Googlebot & Bingbot started pounding these asset files creating a insane loop of "Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary." in our error logs. To fix this I wiped out the /htmlc/ directory and created a rewrite rule in the htaccess to redirect the bots to the homepage if they hit these forbidden files.

RedirectMatch 301 ^/wp-content/cache/comet-cache/htmlc/public/.*$ /

No more memory leaks...

**Comment by raamdev** [comment]
> The Comet Cache plugin by default has "Enable WebSharks™ HTML Compression" enabled.

Actually, the HTML Compressor is disabled by default (you can click the "Restore" button on the plugin options page to reset to plugin defaults to see that this is the case). The only reason it would be enabled when you migrated from ZenCache to Comet Cache is if the HTML Compressor was enabled in ZenCache, as Comet Cache imports the ZenCache settings the first time it is installed.

---

> Coincidentally both Googlebot & Bingbot started pounding these asset files creating a insane loop

Hmm, you should be able to use `robots.txt` to tell those bots not to touch anything inside `wp-content/cache/*`.
