### ISSUE TITLE
Support for Multibyte Strings

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#703]
_Forked from https://github.com/websharks/comet-cache/issues/635._

@jaswsinc writes...

We should do a better job (even better than WP itself) in dealing with UTF-8. Given the amount of string manipulation that occurs in Comet Cache, we should:
- [x] Adopt the use of all `mb_*()` functions where applicable. 
- [x] Always pass the `/u` flag to any `preg_*()` functions that we use.
- [x] Ensure that WP PHP RV requires the `mbstring` extension to prevent issues with sites that don't have it installed.

_This work can probably be moved to a separate issue though; i.e., we should have a separate issue that will be for UTF-8 enhancements. See [this article](http://www.phpwact.org/php/i18n/utf-8#str_replace)._

_Related GitHub issue: https://github.com/websharks/zencache/issues/640#issuecomment-167721023_

---

_Also noting here at an announcement was made in Comet Cache v160222 to any site owner that did not have the `mbstring` extension installed that the PHP `mbstring` extension would be required by Comet Cache after March 1st._

**Comment by jaswrks** [comment]
- [x] 

A first and very easy step here would be to search for all calls to:
- `preg_match`
- `preg_replace`
- `preg_replace_callback`

and on the end of the regex pattern add a `u` modifier.

e.g., `/pattern/` becomes `/pattern/u`
e.g., `/pattern/i` becomes `/pattern/ui`

**Comment by jaswrks** [comment]
- [x] 

Next, we need to search for instances of:
- `strpos`
- `stripos`

and a decision needs to be made that is based on the following.
- If `strpos` is being used to detect the number of _bytes_, leave it as-is.
- If `strpos` is being used to detect the number of _characters_ (or to search for another string, most prevalent in Comet Cache), change it to `mb_strpos` or `mb_stripos` respectively.

**Comment by jaswrks** [comment]
- [x] 

Next, search for:
- `strtolower`
- `strtoupper`

And change all of those to `mb_strtolower()` or `mb_strtoupper()` respectively.

**Comment by jaswrks** [comment]
- [x] 

Same thing for `substr`; i.e., should become `mb_substr`.

**Comment by jaswrks** [comment]
- [x] 

Next, we will need to see which other UTF-8-incompatible functions we are using in Comet Cache; i.e., see which functions we use in PHP core for which there is no UTF-8 `mb_*` variation available. In those cases, we will need to build a replacement of our own as a polyfill.

e.g., There is no `mb_str_ireplace`, and there is no `mb_str_pad()` either. PHP is also missing `mb_substr_replace()`. I'm not sure if Comet Cache needs any of these (or others), but we need to dig through and see which might need polyfills.

Examples of a UTF-8 compatible polyfills:
- https://github.com/websharks/core/blob/000000-dev/src/includes/classes/Core/Utils/SubstrReplace.php
- https://github.com/websharks/core/blob/000000-dev/src/includes/classes/Core/Utils/StrCaseCmp.php
- https://github.com/websharks/core/blob/000000-dev/src/includes/classes/Core/Utils/StrPad.php
- https://github.com/websharks/core/blob/000000-dev/src/includes/classes/Core/Utils/StrRev.php
- https://github.com/websharks/core/blob/000000-dev/src/includes/classes/Core/Utils/StrSplit.php
- https://github.com/websharks/core/blob/000000-dev/src/includes/classes/Core/Utils/Trim.php
- https://github.com/websharks/core/blob/000000-dev/src/includes/classes/Core/Utils/UcFirst.php
- https://github.com/websharks/core/blob/000000-dev/src/includes/classes/Core/Utils/UcWords.php
- https://github.com/websharks/core/blob/000000-dev/src/includes/classes/Core/Utils/MbLcFirst.php
- https://github.com/websharks/core/blob/000000-dev/src/includes/classes/Core/Utils/ReplaceOnce.php

**Comment by jaswrks** [comment]
Referencing full list of existing `mb_` functions provided by the `mbstring` extension.
http://php.net/manual/en/ref.mbstring.php

**Comment by jaswrks** [comment]
- [x] Noting that the `trim()`, `rtrim()` and `ltrim()` PHP functions are generally safe to use on multibyte data. However, if we find instances of these functions where we are attempting to trim characters outside of the ASCII range, we will need to use `preg_replace()` with the `/u` modifier instead.

**Comment by raamdev** [comment]
> If strpos is being used to detect the number of bytes, leave it as-is.
> If strpos is being used to detect the number of characters (or to search for another string, most prevalent in Comet Cache), change it to mb_strpos or mb_stripos respectively.

Can you give an example of those two? I'm not seeing anything that looks like `strpos()` is being used to detect the number of bytes...

**Comment by jaswrks** [comment]
- [x] 

Sorry, I stated that incorrectly. What I should have been talking about there was `strlen()` instead of `strpos()`. All instances of `strpos()` and `stripos()` should be updated to their `mb_` counterparts.

---

Examples of `strlen()` looking for (or testing) the number of bytes:

``` php
if(!strlen($variable)) {
   // Empty.
}
```

``` php
header('Content-Length: '.strlen($export));
```

Examples of `strlen()` looking for the total number of characters.

``` php
if (strlen($string) > $max_length) {
```

``` php
$hook = GLOBAL_NS.substr($hook, strlen('zencache'));
```

**Comment by raamdev** [comment]
@jaswsinc writes...

> Noting that the trim(), rtrim() and ltrim() PHP functions are generally safe to use on multibyte data. However, if we find instances of these functions where we are attempting to trim characters outside of the ASCII range, we will need to use preg_replace() with the /u modifier instead.

Can you give me an example of where we're "attempting to trim characters outside of the ASCII range"? Trim functions are usually used on variables that have hard-to-predict (dynamic) values, so this seems like a case of challenging best-guess work.

**Comment by jaswrks** [comment]
Example where it should be updated:

``` php
$string = trim($string, '®');
```

Should become:

``` php
$string = preg_replace('/^®+|®+$/u', '', $string);
```

_I'm not sure if there are any cases like this in Comet Cache, so there might be nothing to do._

---

Examples that are fine like they are:

``` php
$string = trim($string);
$string = rtrim($string, '/');
$string = ltrim($string, '/');
$string = trim($string, '-');
```

**Comment by raamdev** [comment]
Reviewed all instances of `trim()`, `rtrim()` and `ltrim()`; not seeing anything that needs to be changed.

**Comment by raamdev** [comment]
@jaswsinc writes in https://github.com/websharks/comet-cache/issues/703#issuecomment-192048622...

> There is no `mb_str_ireplace`, and there is no `mb_str_pad()` either. PHP is also missing `mb_substr_replace()`. I'm not sure if Comet Cache needs any of these (or others), but we need to dig through and see which might need polyfills.

I reviewed occurrences of `str_ireplace()` and `substr_replace()` in the codebase and none seemed to require Multibyte replacements. 

I think the work to add support for multibyte strings is complete except for the analysis of any other areas where we might need polyfills. Would you mind taking a look when you get a chance and let me know if I missed anything here? 

Once you're done, I think https://github.com/websharks/comet-cache-pro/pull/225 is ready to merge if you agree (all that's left is to add the check to WP PHP RV).

**Comment by jaswrks** [comment]
Outstanding! I just reviewed the changes that you introduced and those all look great to me. In particular, I think that [this line](https://github.com/websharks/comet-cache-pro/pull/225/files#diff-eefc7d67c4b583b13d432c9dd467d40fR205) is going to be a _very_ important fix that will prevent corruption of the `wp-config.php` file in certain cases where it contains UTF-8 chars. I've seen that reported now and again in both CC and in s2Member, and I think this will fix that.

I'm taking a closer look now and the rest of the codebase, so I will post another update shortly. [This file](https://github.com/websharks/comet-cache-pro/blob/b88b656de09154d4d2382a379261ccef4f32f2a2/src/includes/traits/Shared/ReplaceUtils.php#L31) in particular needs some work; i.e., `substr_replace()` there is problematic. As you mentioned, a polyfill will be needed, or an alternate approach maybe.

**Comment by raamdev** [comment]
@jaswsinc writes...

> I'm taking a closer look now and the rest of the codebase, so I will post another update shortly

Ping. ↑ 😄

**Comment by jaswrks** [comment]
> I reviewed occurrences of str_ireplace() and substr_replace() in the codebase and none seemed to require Multibyte replacements.

Anything which currently uses `str_ireplace()` can be updated to use `preg_replace('//ui', ...)` instead, for unicode compatibility. So for instance: https://github.com/websharks/comet-cache-pro/search?utf8=%E2%9C%93&q=str_ireplace

``` php
$wp_path_rel_to_home = str_ireplace($home, '', $siteurl); /* $siteurl - $home */
```

Becomes:

``` php
$wp_path_rel_to_home = preg_replace('/'.preg_quote($home, '/').'/ui', '', $siteurl); /* $siteurl - $home */
```

That way if the URL contains a multibyte character it won't get mangled when doing string replacements.

In WordPress (as it stands), this is not going to do anything super useful at the moment, because WordPress is not perfect in the way it deals with UTF-8 yet, which means that `$home` containing unicode may break, regardless, in various areas of the WP core.

However, from my perspective it's the difference between wrong and right in the way this is handled. As WordPress improves its support for unicode throughout, it will make it possible for WordPress home/blog URLs to contain unicode characters (e.g., emojis) and when that happens we want Comet Cache to be prepared for it.

---

_I have some other comments I'll post shortly._

**Comment by jaswrks** [comment]
[This line](https://github.com/websharks/comet-cache-pro/blob/866bbf7011f42c2ebe0441156384486a465a6f59/src/includes/traits/Shared/CacheDirUtils.php#L145) can become:

``` php
$cache_dir_tmp_regex = preg_replace('/'.preg_quote(preg_quote($cache_dir.'/', '/'), '/').'/ui', '', $cache_dir_tmp_regex, 1);
```

[This line](https://github.com/websharks/comet-cache-pro/blob/866bbf7011f42c2ebe0441156384486a465a6f59/src/includes/traits/Shared/CacheDirUtils.php#L310) can become:

``` php
$_host_cache_dir_tmp_regex = preg_replace('/'.preg_quote(preg_quote($_host_cache_path.'/', '/'), '/').'/ui', '', $_host_cache_dir_tmp_regex, 1);
```

[This line](https://github.com/websharks/comet-cache-pro/blob/866bbf7011f42c2ebe0441156384486a465a6f59/src/includes/traits/Shared/CacheDirUtils.php#L311) can become:

``` php
$_host_cache_dir_tmp_regex = preg_replace('/'.preg_quote(preg_quote($_host_cache_dir.'/', '/'), '/').'/ui', '', $_host_cache_dir_tmp_regex, 1);
```

---

And then, [this file](https://github.com/websharks/comet-cache-pro/blob/866bbf7011f42c2ebe0441156384486a465a6f59/src/includes/traits/Shared/ReplaceUtils.php#L45) could be removed and/or deprecated, because those methods are no longer used by anything.

**Comment by jaswrks** [comment]
The `stripos()` examples in this file could be updated to show `mb_stripos()`.
https://github.com/websharks/comet-cache-pro/blob/feature/703/src/includes/templates/ac-plugin.txt

**Comment by jaswrks** [comment]
[These lines](https://github.com/websharks/comet-cache-pro/blob/feature/703/src/includes/traits/Plugin/InstallUtils.php#L346-L354) can be replaced with:

``` php
$advanced_cache_contents = preg_replace(
    [
        '/'.preg_quote("'%%".GLOBAL_NS.'_'.$_option."%%'", '/').'/ui',
        '/'.preq_quote("'%%".GLOBAL_NS.'_'.preg_replace('/^cache_/ui', '', $_option)."%%'", '/').'/ui',
    ],
    $_value,
    $advanced_cache_contents
);
```

**Comment by jaswrks** [comment]
[This line](https://github.com/websharks/comet-cache-pro/blob/feature/703/src/includes/traits/Plugin/InstallUtils.php#L364) can be replaced with:

``` php
$advanced_cache_contents = preg_replace('/'.preg_quote("'%%".GLOBAL_NS."_PLUGIN_FILE%%'", '/').'/ui', $plugin_file, $advanced_cache_contents);
```

**Comment by jaswrks** [comment]
In [this file](https://github.com/websharks/comet-cache-pro/blob/feature/703/src/includes/classes/MenuPageOptions.php) there are a few instances of `strtolower()` that still should be changed to `mb_strtolower()`.

**Comment by jaswrks** [comment]
In [this file](https://github.com/websharks/comet-cache-pro/blob/feature/703/src/includes/traits/Shared/CacheDirUtils.php) also. Convert all instances of `strtolower()` into `mb_strtolower()`.

**Comment by jaswrks** [comment]
Everything else looks great. I'd like to do another round of testing once the above changes are implemented though.

**Comment by raamdev** [comment]
@jaswsinc This is ready for another round of tests. Your latest suggestions have been committed in https://github.com/websharks/comet-cache-pro/pull/225/commits/edadf24ad6d0d30c6cc2ec3c70da8226ed4e3b46.

**Comment by jaswrks** [comment]
@raamdev The code sample I gave [here](https://github.com/websharks/comet-cache/issues/703#issuecomment-223723562) has a misspelled word `preq` instead of `preg`.

**Comment by raamdev** [comment]
> a misspelled word preq instead of preg.

Ha, glad somebody caught that. 😳

**Comment by raamdev** [comment]
@jaswsinc writes...

> Everything else looks great. I'd like to do another round of testing once the above changes are implemented though.

Were you able to run those tests? Can I merge now, or would you like to do some more testing?

**Comment by jaswrks** [comment]
I'm running some additional tests now...

**Comment by jaswrks** [comment]
I ran some tests on this branch and I haven't seen any problems thus far. Looks good-to-go.

**Comment by raamdev** [comment]
Next Release Changelog:
- **Enhancement:** Added full support for UTF-8 (multibyte strings). This release adds full support for UTF-8 throughout the Comet Cache codebase, greatly enhancing Comet Cache's ability to deal with file paths and URLs that may contain UTF-8 characters. Props @jaswsinc. [Issue #703](https://github.com/websharks/comet-cache/issues/703).

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#703).
