### ISSUE TITLE
HTML Compression work? - Comet Cache Pro v160227

### ISSUE THREAD

**Issue by Kalfer** [wpsharks/comet-cache#704]
I have it on, but I do not see any files in subfolders: .../wp-content/cache/comet-cache/htmlc

**Comment by raamdev** [comment]
@Kalfer We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://www.websharks-inc.com/support/?product=comet-cache&request_type=trouble_ticket) (Comet Cache Pro). Thank you! :)
