### ISSUE TITLE
Undefined property: WP_Rewrite::$comments_pagination_base

### ISSUE THREAD

**Issue by mati8** [wpsharks/comet-cache#706]
Since I upgraded from ZenCache to Comet Cache, in another plugin I am using on Wordpress I am receiving this error:

Notice: Undefined property: WP_Rewrite::$comments_pagination_base in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/comet-cache-pro/src/includes/closures/Shared/CachePathUtils.php on line 32

**Comment by raamdev** [comment]
@mati8 Can you tell us what this other plugin is where you're receiving this notice?

**Comment by raamdev** [comment]
I'm thinking we just need to check if `$GLOBALS['wp_rewrite']->comments_pagination_base;` is set (via `isset()`) before assigning it to a variable on this line: https://github.com/websharks/comet-cache-pro/blob/160227/src/includes/closures/Shared/CachePathUtils.php#L32.

@jaswsinc Do you concur?

**Comment by mati8** [comment]
Hi, sorry for the late reply.
I am using this: https://it.wordpress.org/plugins/flickr-pick-a-picture/
Of course it's an old plugin, but maybe the error I am receiving it's on other plugins too, that's why I wrote it here. :-)

**Comment by jaswrks** [comment]
> @jaswsinc Do you concur?

I don't see a problem with doing that, but I don't think that should be necessary either. That is a property that is hard-coded into WordPress core. So if it doesn't exist, there is a bigger problem.

@mati8 What version of WordPress are you running please?

**Comment by jaswrks** [comment]
I see that `->comments_pagination_base` has existed since WP v4.2.0.

**Comment by jaswrks** [comment]
> I am using this: https://it.wordpress.org/plugins/flickr-pick-a-picture/

Thanks! :-) I reviewed the code in this plugin and there is nothing in it that would alter the `WP_Rewrite` class or any properties in it. So my best guess at this point is that you might be running an older version of WordPress that doesn't have the `comments_pagination_base` property.

**Comment by raamdev** [comment]
> I see that ->comments_pagination_base has existed since WP v4.2.0.

Ah, that's most likely the issue We currently indicate WP 4.1+ as a minimum requirement.

Given that we'll need to increase the minimum version at some point anyway, I'd say this is probably a good opportunity to bump the minimum requirement to WP 4.2+. WP 4.2 was released almost a full year ago (see [versions](https://codex.wordpress.org/WordPress_Versions))

**Comment by raamdev** [comment]
Next Release Changelog:
- **Required WordPress Version is now v4.2.** The minimum required WordPress version has been bumped from v4.1 to v4.2. See [Issue #706](https://github.com/websharks/comet-cache/issues/706).

**Comment by raamdev** [comment]
**Comet Cache v160416** has been released and includes changes from this GitHub Issue. See the [v160416 announcement](https://cometcache.com/blog/comet-cache-v160416-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#706).
