### ISSUE TITLE
Pro Preview "Manual Cache Clearing" panel has the wrong color

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#711]
It should be using the Preview blue color like the other Pro Preview panels:

![2016-03-06_13-19-20](https://cloud.githubusercontent.com/assets/53005/13556030/3a16326e-e39e-11e5-8656-1e58d8a1bae8.png)

**Comment by renzms** [comment]
@raamdev 
Submitted a PR, ready for review. Thanks!

**Comment by raamdev** [comment]
Next Release Changelog:
- **Bug Fix**: Fixed a UI bug in the Pro Preview that was causing the Manual Cache Clearing panel to not appear as part of the Pro Preview. Props @renzms. See [Issue #711](https://github.com/websharks/comet-cache/issues/711).

**Comment by raamdev** [comment]
**Comet Cache v160416** has been released and includes changes from this GitHub Issue. See the [v160416 announcement](https://cometcache.com/blog/comet-cache-v160416-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#711).
