### ISSUE TITLE
Main user role capability to use Comet Cache Lite

### ISSUE THREAD

**Issue by lomars** [wpsharks/comet-cache#712]
Hello!
The main user role capability in Comet Cache Lite is defined in 
comet-cache -> src -> includes -> classes -> Plugin.php at line 54:
`
public $cap = 'activate_plugins';`
However having access to Comet Cache Lite settings page has nothing to do with 'activate_plugins' user role capability.
Normaly this kind of capability is set in most plugins (that grant access to admin user role) as:
`
public $cap = 'manage_options';`

After that, as the "clearing cache" button is on the settings page, Authors, Contributors and Editors roles need to have access, for clearing cache in some cases. 
**So may be the best capability to set on could be:**
`
public $cap = 'edit_posts';`

Why? 
For example using plugins like **User Role Editor** and **Adminimize** to create special admin rôles with some kind of restricted access, are problematic with 'activate_plugins' as main capability in Comet Cache Lite, because if you don't want this special admin role to have access to plugins page (add new, activate, deactivate and delete), they also will not have access to Comet cache settings.

> **Last thing:** Why there is not **a purge cache button on top admin bar** like in Pro version, considering that settings page in Comet Cache has to be accessed only by admin user role.

For info and reference: [With Adminimize plugin, C.cache still hidden for authorized roles](https://wordpress.org/support/topic/with-adminimize-plugin-ccache-still-hidden-for-authorized-roles?)

Hope you will change this in next update.

Thanks

**Comment by raamdev** [comment]
@lomars Thank you for submitting a GitHub issue. I gave this some thought and filed a separate feature request using your feedback. See https://github.com/websharks/comet-cache/issues/713

I'm going to close this issue in favor of https://github.com/websharks/comet-cache/issues/713.
