### ISSUE TITLE
Run setup() on plugins_loaded instead of after_setup_theme

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#716]
Comet Cache currently [hooks its setup routine](https://github.com/websharks/comet-cache/blob/160227/src/includes/classes/Plugin.php#L127) into [`after_theme_setup`](https://github.com/WordPress/WordPress/blob/4.4.2/wp-settings.php#L376), which runs _after_ [`plugins_loaded`](https://github.com/WordPress/WordPress/blob/4.4.2/wp-settings.php#L276).

Other plugins that integrate with Comet Cache might hook into `plugins_loaded` to make API calls like `comet_cache::clear()`, which would currently fail with a fatal error because the setup routine hasn't been run yet:

> **PHP Fatal error: Uncaught exception 'Exception' with message 'Missing base_dir option value.'**

We should take a closer look at this and use the `plugins_loaded` hook instead if possible. 

---

Referencing: https://wordpress.org/support/topic/clearing-cache-from-autoptimize-base_dir-option

**Comment by raamdev** [comment]
@jaswsinc Is there any reason we're hooking into `after_setup_theme` here and not `plugins_loaded`? I reviewed the `setup()` function and I'm not seeing anything in there that would require waiting until `after_theme_setup`.

**Comment by jaswrks** [comment]
No, that sounds fine to me also.

**Comment by raamdev** [comment]
Next Release Changelog:
- **Hooks/Filters**: Comet Cache now hooks into `plugins_loaded` instead of `after_setup_theme` when calling its own setup routine. This improves integration with other plugins that may be expecting the Comet Cache API functions to be available after `plugins_loaded`. Props to Frank Goossens (@futtta) from Autoptimize for helping with this. See [Issue #716](https://github.com/websharks/comet-cache/issues/716).

**Comment by raamdev** [comment]
**Comet Cache v160416** has been released and includes changes from this GitHub Issue. See the [v160416 announcement](https://cometcache.com/blog/comet-cache-v160416-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#716).
