### ISSUE TITLE
AMP error validation

### ISSUE THREAD

**Issue by Li-An** [wpsharks/comet-cache#718]
I've got some errors:
Incorrect attribute value in english ?
Valeurs d'attribut incorrectes:  href=http://www.li-an.fr/blog/wp-content/cache/comet-cache/htmlc/public/www-li-an-fr/5/b/6/6/6/1c9917bfecc0f24c037ba2a8917ea5bc-compressor-part.css
for this page: http://www.li-an.fr/blog/zolies-images/swallow-n5/amp/ (8 errors for the moment).

**Comment by raamdev** [comment]
@Li-An Have you seen https://github.com/websharks/comet-cache/issues/695? Are you getting a validation error even when you disable the specific HTML Compressor options that are listed in https://github.com/websharks/comet-cache/issues/695?

**Comment by Li-An** [comment]
Oh, I thought I was solved. Well, I don't know what is the best. Desactivate AMP or compressor :-) ? I will desactivate AMP until Comet Cache is compatible with it.

**Comment by raamdev** [comment]
@Li-An You don't have to deactivate the HTML Compressor... you should be able to just deactivate a few of the options to make it compatible with AMP; see near the bottom here under **How to Improve Compatibility**: https://github.com/websharks/comet-cache/issues/695

**Comment by Li-An** [comment]
Well, it won't be so good on GMetrix :-) OK, I will make a test.

**Comment by raamdev** [comment]
@Li-An Any update here? Did the disabling the HTML Compressor options described in #695 work for you?

**Comment by Li-An** [comment]
I do not use HTML Compressor anymore. So, I don’t have the problem - well, as you saw on wp.org forum, other problems with AMP but not relative to Comet Cache Pro.

**Comment by raamdev** [comment]
@Li-An Thanks for the update. I'll close this issue in that case in favor of #695.
