### ISSUE TITLE
problem with Autoptimize

### ISSUE THREAD

**Issue by Li-An** [wpsharks/comet-cache#720]
Hello - again -
I have a problem with Autoptimize - https://wordpress.org/plugins/autoptimize/ - and Comet Cache. When trying to "save and clean the cache" generated by Autoptimize, I've got this error:

**Fatal error: Uncaught Exception: Missing `base_dir` option value. in /home/xxx00/www/echodesplugins/wp-content/plugins/comet-cache-pro/src/includes/closures/Plugin/DirUtils.php:21 Stack trace: #0 [internal function]: WebSharks\CometCache\Pro\Plugin->WebSharks\CometCache\Pro{closure}('cache') #1 /home/xxx00/www/echodesplugins/wp-content/plugins/comet-cache-pro/src/includes/classes/AbsBaseAp.php(55): call_user_func_array(Object(Closure), Array) #2 /home/xxx00/www/echodesplugins/wp-content/plugins/comet-cache-pro/src/includes/closures/Shared/CacheDirUtils.php(21): WebSharks\CometCache\Pro\AbsBaseAp->__call('wpContentBaseDi...', Array) #3 [internal function]: WebSharks\CometCache\Pro\AbsBaseAp->WebSharks\CometCache\Pro{closure}() #4 /home/xxx00/www/echodesplugins/wp-content/plugins/comet-cache-pro/src/includes/classes/AbsBaseAp.php(55): call_user_func_array(Object(Closure), Array) #5 /home/xxx00/www/echodesplugins/wp-content/plugins/comet-cache-pro/src/includes/closures/Plugin/WcpUtils.php(79): WebSharks in /home/xxx00/www/echodesplugins/wp-content/plugins/comet-cache-pro/src/includes/closures/Plugin/DirUtils.php on line 21**

**Comment by raamdev** [comment]
@Li-An See https://github.com/websharks/comet-cache/issues/716.

**Comment by Li-An** [comment]
OK, thanks - I should have made a research.
