### ISSUE TITLE
HTML Compression not including all CSS

### ISSUE THREAD

**Issue by ronnieg303** [wpsharks/comet-cache#723]
For the most part, HTML compression is working great. However, I just discovered that not all CSS files are being included. And as noted at the end, I eventually found out why. 

My site uses Weaver Xtreme theme. It has a main theme CSS, child theme CSS, and CSS overrides. All of those appear to be always correctly included. My own plugin includes up to three additional CSS files. Of those, the main plugin css file is always properly included. But two very small css files, about 15-30 lines each, which have to be separated from the main css because they apply a small sub-set of rules depending on the pages they are on and other plugin options, are not being included in the consolidated/compressed css generated by CC.

Here is how I determined that: 
- I duplicated one key css rule from one of the files not being included during compression, into the main plugin css file that was always correctly included.
- Looked at html source of pages with CC deactivated. All css files are there. Looking at the code for the rule that was duplicated, using Firebug, I could see that the copied rule appeared once from the main css file, and again from the small css file that Comet Cache, when activated, was not including. The 2nd occurrence was overriding the 1st one, as expected. 
- Looked at page source with CC activated and html compression enabled, including for css, again with Firebug. This time, the rule from the main css file was in place, but the rules from the two smaller css files were not. There was only one rule in effect for the one I duplicated, and it was not being overriden by the duplicate rule from the other file as it should have been.

On digging into this, I discovered that there was a bad rule close to the end of the primary plugin css file. So when html/css compression was not in effect, the only rules that were affected were those following the bad rule in the main file, and because the following css files were independently loaded, their rules were working just fine. But when everything was consolidated and compressed, the one bad rule caused all later css files and all of their rules to be omitted and/or ignored.  Other than being extra careful to have no broken rules anywhere in any file, I don't know how this could be addressed.

**Comment by jaswrks** [comment]
@ronnieg303 writes...

> On digging into this, I discovered that there was a bad rule close to the end of the primary plugin css file. So when html/css compression was not in effect, the only rules that were affected were those following the bad rule in the main file, and because the following css files were independently loaded, their rules were working just fine. But when everything was consolidated and compressed, the one bad rule caused all later css files and all of their rules to be omitted and/or ignored. Other than being extra careful to have no broken rules anywhere in any file, I don't know how this could be addressed.

Thanks so much for the very detailed report! :-)

So can I assume from your last comment there that you resolved this already? It sounds like you did. Actually, it sounds like there was a bad rule in the CSS, and once it was compressed (all one line of code in compressed form) that caused some other rules following the bad one to be ignored. Do I have that right?

**Comment by raamdev** [comment]
@ronnieg303 Thank you for the detailed report. 

HTML/CSS/JS Compression requires abiding by specific rules set forth by the various standards. That's how we're able to strip out white space and combine the content to speed things up. However, it's true that if a plugin or theme adds some CSS/JS that is broken, it has a high probability of causing problems with the HTML Compressor. There's just no way around that. That's one reason we provide features for excluding specific CSS/JS files within the HTML Compressor: if you find a file that causes problems when compressed, you can exclude it.
