### ISSUE TITLE
Cache for date-based archive views not cleared when post is updated

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#724]
### Steps to reproduce
- Install Comet Cache Lite v160227, activate, enable.
- Set **Settings → Permalinks** to Custom Structure: `/%year%/%monthnum%/%postname%/`
- Publish a new post, then logout and visit that post to generate a cache file.
- Visit the date-based archive view for the post, e.g., `/2016/03/` to generate a cache file that includes that post.
- Now login and edit the published post, change it in some way; click 'Update' to update the post.
### Expected behavior

All cache files associated with the post are cleared, e.g., the post cache itself, and the date-based archive view that includes the post (`/2016/03/`).
### Observed behavior

The post cache, category archive cache, and tag archive cache files all get cleared as expected, but the date-base archive cache does not. Visiting `/2016/03/` shows an archive view that includes an old copy of the post (because that cache file was never cleared when the post was updated).

**Comment by raamdev** [comment]
@jaswsinc I was looking through the Comet Cache Automatic Cache Clearing options and I realized that we don't even have anything for date-based archive views. Am I missing something or have we never had support for this? This seems like a pretty important thing to support, given that date-based archive views are on-par with category and tag archive views in terms of how often they're used.

**Comment by jaswrks** [comment]
> Am I missing something or have we never had support for this?

Great catch. I'm not seeing anything either.

> This seems like a pretty important thing to support, given that date-based archive views are on-par with category and tag archive views in terms of how often they're used.

Agreed.

**Comment by jaswrks** [comment]
I was just taking a closer look at this issue. The permalink structure should not matter, should it? If a Post is updated in some way (regardless of permalink) the date-based archive view should be cleared as well, when that functionality is enabled. Does that sound right?

So it seems like what we need is a routine that can look at the original publication date and then clear the date-based archive views for that publication date, regardless of permalink.

**Comment by raamdev** [comment]
> So it seems like what we need is a routine that can look at the original publication date and then clear the date-based archive views for that publication date, regardless of permalink.

Yes, that sounds right.

All we need to consider is that the date-based archive views may be paginated, and the post that's being updated might be somewhere other than page 1. 

I just did some testing and it appears that for a post published on April 9th, 2016, we would need to clear all of the following:

```
/2016/*
/2016/page/*
/2016/04/*
/2016/04/page/*
/2016/04/09/*
/2016/04/09/page/*
```

It's unfortunate that the cache for a whole years' worth of archives will get cleared each time a post is published/updated, but I'm not seeing any way around this.

Also noting that we should use `$GLOBALS['wp_rewrite']->pagination_base` instead of `page`, as the slug may be different on some sites (e.g., sites that have translated it into their own language).

---

We should add a new option to **Automatic Cache Clearing** that allows a site owner to control this behavior:

**Auto-Clear "Date Archives" Too?**
- Yes, if any single Post is cleared/reset, also clear the associated Date archive views. (default)
- Yes, but only clear the associated Day and Month Date archive views.
- Yes, but only clear the associated Day Date archive view.
- No, don't clear any associated Date archive views.

**Comment by jaswrks** [comment]
Copy that. Sounds like a plan then.

> Also noting that we should use $GLOBALS['wp_rewrite']->pagination_base instead of page, as the slug may be different on some sites (e.g., sites that have translated it into their own language).

Agreed. Our existing code for regex formulation should already handle this properly. Once we implement a new method to clear the date-based archive views for dated variations as you outlined above, the pagination will be taken into account by some of our existing regex handlers.

**Comment by renzms** [comment]
### Not working


Tested using 

WordPress Version: 4.7.2
Current WordPress Theme: Twenty Seventeen version 1.1
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentyseventeen/
Active Plugins: Comet Cache™ Pro v170201-RC
PHP Version: 7.0.10-2+deb.sury.org~xenial+1
MySQL Version: 10.0.29-MariaDB-0ubuntu0.16.04.1

Set `Settings → Permalinks to Custom Structure: /%year%/%monthnum%/%postname%/`

### Steps to reproduce

Published a new post, and visited that post as a logged out visitor to generate a new cache file.

**Create New Test Post** 
>![screen shot 2017-02-06 at 9 15 58 pm](https://cloud.githubusercontent.com/assets/13220018/22648618/7acda120-ecb2-11e6-8331-92fc32eeffaf.png)

Visited the date-based archive view for the post, `/2017/02/` to generate a cache file that includes that post.

**Archive**
>![screen shot 2017-02-06 at 9 13 53 pm](https://cloud.githubusercontent.com/assets/13220018/22648617/7acb5492-ecb2-11e6-9120-30b457f42072.png)


Updated the published post, and cache files are cleared, the post cache itself, and Home Page cache.

**Cache Cleared upon updating Post**
>![screen shot 2017-02-06 at 9 16 18 pm](https://cloud.githubusercontent.com/assets/13220018/22648616/7ac7c4d0-ecb2-11e6-84de-0d25af755323.png)

**Front End Post Update and Cache Update**
>![screen shot 2017-02-06 at 9 17 35 pm](https://cloud.githubusercontent.com/assets/13220018/22648615/7ac10d7a-ecb2-11e6-92d1-f6bc340b6e24.png)



Observed behavior

The post cache file all get cleared as expected, but the date-base archive cache does not.

**Archive**
>![screen shot 2017-02-06 at 9 19 20 pm](https://cloud.githubusercontent.com/assets/13220018/22648614/7ac014a6-ecb2-11e6-8c9a-2b4376192fa1.png)




Manually clearing the cache will clear the Archive and generate a new cache upon visit:




>![screen shot 2017-02-06 at 9 20 12 pm](https://cloud.githubusercontent.com/assets/13220018/22648613/7abb71a8-ecb2-11e6-893b-b788f3ed9da6.png)

**Comment by jaswrks** [comment]
Recording incorrect link formulation found during follow-up tests.

```
Array
(
    [1473911820 Date Archive] => https://jason.wpsharks.net/1473911820/
    [1473911820/1473825420 Date Archive] => https://jason.wpsharks.net/1473911820/1473825420/
    [1473911820/1473825420/ Date Archive] => https://jason.wpsharks.net/1473911820/1473825420/09/
)
```

**Comment by jaswrks** [comment]
Recording correct link formulation after bug fix:

```
Array
(
    [2016 Date Archive] => https://jason.wpsharks.net/2016/
    [2016/09 Date Archive] => https://jason.wpsharks.net/2016/09/
    [2016/09/14 Date Archive] => https://jason.wpsharks.net/2016/09/14/
)
```

**Comment by jaswrks** [comment]
@renzms Another great catch! Thank you.

This, along with the other issue in Apache Optimizations, have both been resolved now — in the release/170201-RC branch. ~ cc @raamdev

**Comment by renzms** [comment]
### Fix Confirmed Working for Comet Cache Pro v170209-RC 

**Original Archive Cache**
>![screen shot 2017-02-10 at 5 05 30 pm](https://cloud.githubusercontent.com/assets/13220018/22820861/8c4dcaf2-efb3-11e6-9d32-a5b27941e1e7.png)


**After updating post, cache is cleared for post as well as archive cache.**
>![screen shot 2017-02-10 at 5 04 56 pm](https://cloud.githubusercontent.com/assets/13220018/22820862/8c514d62-efb3-11e6-8d08-8a07f96c57f6.png)

**Updated Archive Cache**
>![screen shot 2017-02-10 at 5 06 08 pm](https://cloud.githubusercontent.com/assets/13220018/22820860/8c4a8568-efb3-11e6-8af0-a392ef243ec3.png)

**Comment by raamdev** [comment]
**Comet Cache v170220** has been released and includes changes from this GitHub Issue. See the [v170220 announcement](https://cometcache.com/blog/comet-cache-v170220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#724).
