### ISSUE TITLE
3rd Party Plugin Compatibility: WooCommerce + Product Tags

### ISSUE THREAD

**Issue by kristineds** [wpsharks/comet-cache#725]
Referencing: [internal private ticket](https://websharks.zendesk.com/agent/tickets/11885)

---

Customer reports..

> I try to use Comet Cache on my website with Woocommerce but I have a problem with products tags. If I add an existing tag to a product, then the cached page for this product tags is (are) not refreshed. Is there's any solution, to make it works as "normal" WP tags (regenerate the cached page for this tag) without the URI Exclusion Patterns ?

A decent short term solution for this is by [clearing the cache dynamically with PHP](https://cometcache.com/kb-article/clearing-the-cache-dynamically/).

It would be nice if we could improve the compatibility between the two and run some tests to see if it requires special attention.

**Comment by raamdev** [comment]
@kristineds Were you able to reproduce this? If WooCommerce is using Custom Post Types, this should already work when "Auto-Clear Custom Post Type Archives" is enabled in Automatic Cache Clearing:

![2016-04-04_09-34-56](https://cloud.githubusercontent.com/assets/53005/14249602/8b37d5ec-fa48-11e5-8eb4-ffba1f755997.png)

It sounds like this might be related to the issue with that option being **disabled** by default; see related issue: https://github.com/websharks/comet-cache/issues/693#issuecomment-198439091

**Comment by kristineds** [comment]
@raamdev I'm afraid I'm not able to reproduce this issue in a clean install of WordPress.

Also, "Auto-Clear "Custom Post Type Archives" Too?" is _enabled_ by default, which is the one that I used when I tested this out.

**Comment by kristineds** [comment]
@raamdev Please close this issue. I'm tagging it as **cannot reproduce**.  "Auto-Clear Custom Post Type Archives" fixed this. Thank you! :)

**Comment by raamdev** [comment]
@kristineds Thank you for the update and for retesting. :-)
