### ISSUE TITLE
Fatal error: Unknown: Cannot use output buffering in output

### ISSUE THREAD

**Issue by rashkoff** [wpsharks/comet-cache#726]
Hello,
when I pass from ZEN to Comet I take often this error:
Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0
Any suggestions?

**Comment by jaswrks** [comment]
Thanks for the report. What are the steps needed to reproduce this error please?

**Comment by rashkoff** [comment]
Sorry, 
I hopping to  understand if you have a solution.
I think is connect to the minify options.
the php_limit is 256M on the server

**Comment by jaswrks** [comment]
> Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0

I can't seem to reproduce that bug in a test installation of WordPress. If you have a list of steps that we can use to reproduce the issue, then I'm happy to take a closer look.

**Comment by jaswrks** [comment]
@rashkoff I'm waiting for a list of steps we can use to reproduce this issue; e.g., install, set this option, enable, do this, do that, observe the problem here, etc.

**Comment by rashkoff** [comment]
I can’t understand why this error persist…

For sure when the plugin is off or Zen cache is restore, the problem is gone…

**Comment by raamdev** [comment]
@rashkoff See [Testing Comet Cache in a Clean WordPress Installation](https://cometcache.com/kb-article/testing-comet-cache-in-a-clean-wordpress-installation/).
