### ISSUE TITLE
Bug: Comet Cache prompting users to upgrade to v160316.

### ISSUE THREAD

**Issue by renzms** [wpsharks/comet-cache#727]
Related to: https://github.com/websharks/comet-cache/issues/678 

Customers have been reporting an issue where Comet Cache is prompting them to update to ​**Comet Cache v160316**​ however, only ​**ZenCache** has a **v160316**​. Latest installed version of Comet Cache and the available file you get from [cometcache.com](https://cometcache.com/) is ​**v160227**​.

![ccv160316](https://cloud.githubusercontent.com/assets/13220018/14094519/9a9acb16-f589-11e5-9ed9-90bb7713c47a.png)

Findings from @jaswsinc 

> The problem will impact users who upgraded to the latest release of ZenCache, or who had ZenCache installed long enough for it to do a recent update check, where their configured options include that ZenCache version number. Whenever they update to Comet Cache, that version is carried over into their new Comet Cache options, resulting in this unexpected behavior. 
> 
> Referencing: https://github.com/websharks/comet-cache-pro/blob/160227/src/includes/closures/Plugin/OptionUtils.php#L17 where we should be deleting that option after importing the old ZenCache options.
### Workaround

In Comet Cache please click `Restore Default Options.`

**Note** if this does not work either, then it could be that you haven't completely deleted ZenCache from your installation yet. Please see the following steps to remove ZenCache: 
- Install ZenCache and turn off Deletion Safeguards in your ZenCache config options.
- Deactivate and delete ZenCache entirely.
- Install Comet Cache. 

Or, another way to resolve this....
- In PHP, run `delete_site_option('zencache_options');`
- In Comet Cache click `Restore Default Options.`

---

Referencing internal ticket(s):
https://websharks.zendesk.com/agent/tickets/11884
https://websharks.zendesk.com/agent/tickets/11841

**Comment by jaswrks** [comment]
@renzms Thanks for opening this report! :-)

## Next Steps for a PR
- After [this line](https://github.com/websharks/comet-cache-pro/blob/000000-dev/src/includes/traits/Plugin/OptionUtils.php#L23) please add the following:
  
  ``` php
  $options['latest_lite_version'] = $this->default_options['latest_lite_version'];
  $options['latest_pro_version'] = $this->default_options['latest_pro_version'];
  ```

**Comment by jaswrks** [comment]
_For the benefit of others coming to this issue..._

Noting that we have a release archive available here where you can acquire older versions of ZenCache.
Please see: https://cometcache.com/release-archive/

**Comment by raamdev** [comment]
Next Release Changelog:
- **Bug Fix** (Pro): Fixed a bug related to the Pro Updater where some users who had migrated from ZenCache Pro to Comet Cache Pro were seeing an invalid new version message. Props @renzms @jaswsinc. See [Issue #727](https://github.com/websharks/comet-cache/issues/727)

**Comment by raamdev** [comment]
**Comet Cache v160416** has been released and includes changes from this GitHub Issue. See the [v160416 announcement](https://cometcache.com/blog/comet-cache-v160416-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#727).
