### ISSUE TITLE
Deactivating plugin via WP-CLI yields errors

### ISSUE THREAD

**Issue by MarioKnight** [wpsharks/comet-cache#728]
This seems to match #563 from what I can see.  In trying to determine an error (confirmed now to not have been caused by Comet Cache), I attempted to disable Comet Cache Pro through the command line and received the following errors:

```
Fatal error: Uncaught exception 'Exception' with message 'Invalid argument; host token empty!' in /xxxxx/wp-content/plugins/comet-cache-pro/src/includes/closures/Shared/CacheDirUtils.php:274
Stack trace:
#0 [internal function]: WebSharks\CometCache\Pro\AbsBaseAp->WebSharks\CometCache\Pro\{closure}('/^.+/i')
#1 /xxxxx/wp-content/plugins/comet-cache-pro/src/includes/classes/AbsBaseAp.php(55): call_user_func_array(Object(Closure), Array)
#2 /xxxxx/wp-content/plugins/comet-cache-pro/src/includes/closures/Shared/CacheDirUtils.php(54): WebSharks\CometCache\Pro\AbsBaseAp->__call('deleteFilesFrom...', Array)
#3 /xxxxx/wp-content/plugins/comet-cache-pro/src/includes/closures/Shared/CacheDirUtils.php(54): WebSharks\CometCache\Pro\Plugin->deleteFilesFromHostCacheDir('/^.+/i')
#4 [internal function]: WebSharks\CometCache\Pro\AbsBaseAp->WebSharks\CometCache\Pro\{closure}('/^.+/i')
#5 /xxxxx/wp-content/plugins/comet-cache-pro/src/include in /xxxxx/wp-content/plugins/comet-cache-pro/src/includes/closures/Shared/CacheDirUtils.php on line 274
```

I don't think is something that would be done often (I only did it this way since I didn't want to login to WordPress if I didn't have to), but I figured y'all would want to know.  Please let me know if you need anything else from my end.

**Comment by raamdev** [comment]
Thanks for the report, @MarioKnight. It sounds like this is related to https://github.com/websharks/comet-cache/issues/464

**Comment by raamdev** [comment]
Noting that adding `--url=` to the WP-CLI command and specifying your WordPress Site Address allows Comet Cache to be disabled properly without the "host token empty" error. 

```
  --url=<url>
      Pretend request came from given URL. In multisite, this argument is how the target
  site is specified.
```

**Comment by jaswrks** [comment]
Referencing the following areas of the CC codebase where we could try to use a default value matching the current site's host name; i.,e, `parse_url(home_url('/'), PHP_URL_HOST)` (or similar).
- https://github.com/websharks/comet-cache-pro/search?utf8=%E2%9C%93&q=HTTP_HOST

The same would be true in the case of `$_SERVER['REQUEST_URI']`, which could default to just `/`.
- https://github.com/websharks/comet-cache-pro/search?utf8=%E2%9C%93&q=REQUEST_URI

**Comment by raamdev** [comment]
@jaswsinc I assume you're suggesting that we apply those defaults only `if (defined('WP_CLI') && WP_CLI && empty($_SERVER['HTTP_HOST']))`, correct?

**Comment by jaswrks** [comment]
@raamdev Yes, correct. Maybe it would help if we create a new method somewhere in the Shared Traits folder called `envVar()` that would capable of returning `$_SERVER` environment variables from a central location. That method could be responsible for working out a default value whenever we can detect (in this case) that WP CLI is running without them, which leads to this problem.

Doing it that way would also allow us to read the information we need from those variables without contaminating the global environment at large; i.e., without writing to `$_SERVER` directly, which may have an undesirable impact on plugins that do not expect them to exist in CLI processes.

**Comment by jaswrks** [comment]
## Next Actions
- Change [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Shared/TokenUtils.php#L41) to the following:
  
  ``` php
  $token = !empty($_SERVER['HTTP_HOST']) ? (string) $_SERVER['HTTP_HOST'] : '';
  ```
- Same thing on [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Shared/TokenUtils.php#L46).
- Same thing on [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Shared/TokenUtils.php#L53).
- Replace [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Shared/UrlUtils.php#L138) with the following:
  
  ``` php
  if (empty($_SERVER['HTTP_HOST']) || empty($_SERVER['REQUEST_URI'])) {
      return ''; // Not possible.
  }
  return ($this->isSsl() ? 'https://' : 'http://').$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
  ```
- Change [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Plugin/DirUtils.php#L77) to the following:
  
  ``` php
  if (!empty($home) && 0 !== strcasecmp($home, $siteurl) && !empty($_SERVER['SCRIPT_FILENAME'])) {
  ```
- Change [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Ac/BrowserUtils.php#L24) to the following:
  
  ``` php
  } elseif (COMET_CACHE_EXCLUDE_CLIENT_SIDE_URIS && (empty($_SERVER['REQUEST_URI']) || preg_match(COMET_CACHE_EXCLUDE_CLIENT_SIDE_URIS, $_SERVER['REQUEST_URI']))) {
  ```
- Change [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Plugin/NoticeUtils.php#L154) to the following:
  
  ``` php
  if ($_notice['only_on_uris'] && (empty($_SERVER['REQUEST_URI']) || !@preg_match($_notice['only_on_uris'], $_SERVER['REQUEST_URI']))) {
  ```
- Submit PR for review.

**Comment by raamdev** [comment]
Next Release Changelog:
- **WP-CLI Compatibility**: Fixed a bug with deactivating Comet Cache using WP-CLI. Doing so was producing a "Invalid argument; host token empty!" error message. This has been resolved. Props @MarioKnight @jaswsinc @renzms. See [Issue #728](https://github.com/websharks/comet-cache/issues/728).

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#728).
