### ISSUE TITLE
HTML Compression interferes with Text in Slider Revolution Plugin

### ISSUE THREAD

**Issue by ReachWest** [wpsharks/comet-cache#729]
Using Comet Cache Pro v160227

If HTML Compression option "Yes Combine CSS from Head and Body into fewer files" is activated, then text used in the Slider Revolution plugin becomes miniaturized. Disable the HTML compression option "Yes Combine CSS from Head and Body into fewer files" and the text size in Slider Revolution returns to normal.

Note: We have all other HTML Compression options in Comet Cache turned to ON.

The attached screenshots show the issue. With HTML Compression option for "Yes Combine CSS.." turned on and turned off.

![screen shot 2016-03-31 at 12 36 10 pm](https://cloud.githubusercontent.com/assets/684456/14186893/d4491f60-f73d-11e5-8e4d-c942c18e4846.png)
![screen shot 2016-03-31 at 12 40 22 pm](https://cloud.githubusercontent.com/assets/684456/14186894/d44b96aa-f73d-11e5-8df6-a829001aa4d6.png)

**Comment by raamdev** [comment]
@ReachWest Thank you for the report. We have another GitHub issue open for compatibility with Slider Revolution here: https://github.com/websharks/comet-cache/issues/614 

I'm going to close this issue in favor of that one, but your note about disabling "Yes Combine CSS from Head and Body into fewer files" is definitely helpful! :-)
