### ISSUE TITLE
Plugin Compatibility: Facebook Comments

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#731]
We've had a report ([internal ticket)](https://websharks.zendesk.com/agent/tickets/11850)) of Comet Cache Pro not clearing the Home Page cache when a new post is published when the [Facebook Comments](https://wordpress.org/plugins/facebook-comments-plugin/) plugin is active. The same report also mentioned that this API call no longer worked:

``` php
add_action( 'save_post', 'my_custom_clear_cache', 10, 1 );
function my_custom_clear_cache( ) { 
     comet_cache::clear(); 
}
```

The Facebook Comments plugin has 100k active installs, so we should review Comet Cache compatibility with it.

**Comment by renzms** [comment]
@raamdev 

### Unable to reproduce issue

WordPress Version: 4.7
Current WordPress Theme: Twenty Seventeen version 1.0
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentyseventeen/
Active Plugins: Comet Cache Pro Version 161227 + Facebook Comments Plugin Version 2.3.6
PHP Version: 7.0.10-2+deb.sury.org~xenial+1
MySQL Version: 10.0.28-MariaDB-0ubuntu0.16.04.1

**Checking cache file for home page**
>![fb test 2](https://cloud.githubusercontent.com/assets/13220018/21548611/4bd97b6c-ce28-11e6-840c-2c07d4a71dd9.png)

**Dashboard prompt for cache clearing after adding new post**
>![screen shot 2016-12-30 at 12 33 38 am](https://cloud.githubusercontent.com/assets/13220018/21548614/4f0e5de8-ce28-11e6-8ead-23a2bd7fbe09.png)


**Home page cache after new post**
>![fb test](https://cloud.githubusercontent.com/assets/13220018/21548610/4bccc2d2-ce28-11e6-88bf-be931df2f4d8.png)

**Comment by raamdev** [comment]
Thanks, Renz. I'll go ahead and close this as `cannot reproduce`.
