### ISSUE TITLE
Problem after upgrading to WP 4.5

### ISSUE THREAD

**Issue by ghost** [wpsharks/comet-cache#734]
One of my sites just upgraded to WP 4.5.  I run Comet Cache version "Comet Cache™ Pro v160227".  Since the upgrade, I can no longer click on the blue menu options in Comet Cache to configure details.

Please advise

Torsten Dreier

**Comment by raamdev** [comment]
@GulfToBayWeb I'm not able to reproduce this problem with WP 4.5 + Comet Cache Pro v160227. 

It sounds to me like you might have a browser caching issues, where some of the older WP JavaScript files were cached by your browser. Can you try clearing your browser cache and testing again?

**Comment by ghost** [comment]
Raam,

you were right,  clearing cache helped, everything is back to normal

Thanks
Torsten Dreier
