### ISSUE TITLE
Difficulty enabling CDN URL Replacement (Static CDN Filters) on large domain-based multisite

### ISSUE THREAD

**Issue by dbaritchi** [wpsharks/comet-cache#735]
Hi there!

Trying to enable CDN URL Replacement (via Static CDN Filters) for a large domain-based multisite and having some difficulty turning it on. 

Our config is 1 main site (i.e. mainsite.com) with thousands of sub-sites (i.e. blog1.mainsite.com, blog2.mainsite.com, etc.). we also have hundreds of domain-mapped sites (i.e. differentsite.com, anotherdifferentsite.com, etc.). 

The goal is to enable domain mapping for ALL sites on the network EXCEPT the top-levels site with the exact same MaxCDN URL replacement setup. The main site is already well optimized with HTTP/2 on CloudFlare so no need for URL Replacement as with the others. 

Running into 2 challenges:

1.)  Can't seem to enable the Static CDN Filters function - I choose the enable option ("Yes, I want CDN filters applied w/ my configuration below") and Save. page reloads and comes back with the setting disabled again. Screenshot Below.

2.) Using MaxCDN for URL Replacement so need to specify a HTTP URL (i.e. cdn.mydomain.com) and separately a HTTPS URL.

MaxCDN does not by default support HTTPS on regular URLs with their SSL Cert, so they provide you something like cdn-mymaxcdnaccount.netdna-ssl.com as the SSL replacement URL.

How can I specify the separate HTTP and HTTPS replacement URLs?

Thanks!

![image](https://cloud.githubusercontent.com/assets/7244858/14513446/84109274-01ad-11e6-885d-41b7a964334a.png)

**Comment by raamdev** [comment]
> 1.) Can't seem to enable the Static CDN Filters function - I choose the enable option ("Yes, I want CDN filters applied w/ my configuration below") and Save. page reloads and comes back with the setting disabled again. Screenshot Below.

That sounds to me like you have another plugin on your site that is conflicting with Comet Cache in some way. Unfortunately the advice we recommend when that happens is to [Test Comet Cache in a Clean WordPress Installation](https://cometcache.com/kb-article/testing-comet-cache-in-a-clean-wordpress-installation/), however that's probably not practical in your situation with so many sub-sites.

Changing that CDN option and hitting save just runs the WordPress [`update_site_option()`](https://developer.wordpress.org/reference/functions/update_site_option/) function, the same thing that gets run for updating any other Comet Cache options. So if you're only having trouble updating the CDN option in Comet Cache, that would tell me something is off with your WordPress database and/or something (e.g., another plugin or some custom code somewhere) is interfering with updating that specific option.

With so many sites running in that multisite environment, the easiest thing to do might be to backup the Comet Cache options (**Comet Cache → Plugin Options → Import/Export Options**), then disable Plugin Deletion Safeguards (**Comet Cache → Plugin Options → Plugin Deletion Safeguards**) and Deactivate and Delete Comet Cache Pro. Then reinstall Comet Cache Pro and try enabling the Static CDN Filters _before_ importing your backed-up options.

If enabling Static CDN Filters works, then try importing your backed-up options and enabling Static CDN Filters again. (If it _doesn't_ work at that point, then we'd be interested in getting a copy of those exported options to see if we can reproduce this.)

> 2.) Using MaxCDN for URL Replacement so need to specify a HTTP URL (i.e. cdn.mydomain.com) and separately a HTTPS URL.
> 
> MaxCDN does not by default support HTTPS on regular URLs with their SSL Cert, so they provide you something like cdn-mymaxcdnaccount.netdna-ssl.com as the SSL replacement URL.
> 
> How can I specify the separate HTTP and HTTPS replacement URLs?

@jaswsinc Any thoughts on how this might be possible? I'm thinking we might need a new option, or to build in some new functionality, to address this scenario.

**Comment by jaswrks** [comment]
> @jaswsinc Any thoughts on how this might be possible?

I think @dbaritchi is seeing this after having implemented the filter I suggested [here](https://github.com/websharks/comet-cache/issues/657#issuecomment-207528277) for a specific use case. That filter impacts the Main Site, and so it impacts the config options panel too.

See: https://github.com/websharks/comet-cache/issues/657#issuecomment-207528277

I suggest the following modification to avoid this confusion.

``` php
<?php
add_filter('comet_cache_options', function($options) {
    if(is_main_site() && !is_admin()) {
        $options['cdn_enable'] = '0';
    }
    return $options;
});
```

_Note the addition of `&& !is_admin()` above._

**Comment by dbaritchi** [comment]
@jaswsinc Yes, sorry i had indeed added that filter. Your new version above fixes the issue - It's now possible to Enable Static CDN Filters in the plugin settings and the setting stays on. :)

I've removed the filters altogether form functions.php now to debug the other items. 

@raamdev thanks for the helpful advice. 

OK - with the filter completely removed, the CDN URL Replacement happens perfectly on the main site - but still not happening on any of the sub-sites. 

It's odd because the page caching works perfectly across the network - both here on our Dev server and in Production. 

We're running the latest Comet Cache (160227).
And I DID enable Static CDN FIlters for "Logged in Users" too just in case - tho i'm testing in a Chrome incognito window too just in case. 

I actually tried to Reset settings but that didn't fix it. 

So I network deactivated and completely uninstalled the plugin (after disabling the Plugin Detection Safeguards). 

Then re-installed and network activated again... and enabled Static CDN Filters again. 

Still no go.

This is on our Dev server and we're about to re-build it from production anyway in the coming days, so I can test this again after the rebuild. 

Have you guys seen something like this before? Ideas? 

Separately, I still need to figure out the HTTP vs HTTPS issue with MaxCDN URL replacement... pasting it again here just in case:

> 2.) Using MaxCDN for URL Replacement so need to specify a HTTP URL (i.e. cdn.mydomain.com) and separately a HTTPS URL.
> 
> MaxCDN does not by default support HTTPS on regular URLs with their SSL Cert, so they provide you something like cdn-mymaxcdnaccount.netdna-ssl.com as the SSL replacement URL.
> 
> How can I specify the separate HTTP and HTTPS replacement URLs?

Thanks!
Dan

**Comment by raamdev** [comment]
> Have you guys seen something like this before? Ideas?

Unfortunately no, I have not seen anything like that. Static CDN Filters are working as expected in the tests in our multisite environments. 

> the CDN URL Replacement happens perfectly on the main site - but still not happening on any of the sub-sites.

Are your sub-sites on a different domain (e.g., a sub-domain or a mapped domain)? If so, keep in mind that you need separate configuration lines for those:

![2016-04-20_14-34-54](https://cloud.githubusercontent.com/assets/53005/14686051/2cf75ae2-0705-11e6-82e1-379f3a9b77a8.png)

---

> I still need to figure out the HTTP vs HTTPS issue with MaxCDN URL replacement...

I'm still waiting for @jaswsinc to reply to this one--I don't believe this is currently possible, but he may have an idea.

**Comment by jaswrks** [comment]
@dbaritchi writes...

> MaxCDN does not by default support HTTPS on regular URLs with their SSL Cert, so they provide you something like cdn-mymaxcdnaccount.netdna-ssl.com as the SSL replacement URL.

Hmm. I didn't realize that. Thanks for the heads up! :-)

Unfortunately, that is not something that Comet Cache supports at the moment. It is expected that you will have one CDN Host Name that can cover both protocols. It seems a little strange to me that MaxCDN wouldn't support this, because without having one CDN Host Name that can support both protocols you can't use cross-protocol compatible links like `//cdn.com/path/to/file.js`.

Are you sure the `.netdna-ssl.com` won't work over `http://` _and_ `https://` too! Sorry, I haven't had the time to run my own tests against that yet. If you can try that and let me know I'd appreciate it.

If not, here are a couple of ideas:
- Use the `.netdna-ssl.com` Host Name only, and then force your entire site to be served over SSL, which is a growing trend anyway. If you do that, you may not need the `http://` variation at all.
- Or, you can implement a filter (for now) while we work this issue.

`wp-content/mu-plugins/cc-hacks.php`

``` php
<?php
add_filter('comet_cache_options', function($options) {
    if(is_ssl()) {
        $options['cdn_host'] = str_ireplace('non-ssl-host.com', 'ssl-enabled-host.com', $options['cdn_host']);
        $options['cdn_hosts'] = str_ireplace('non-ssl-host.com', 'ssl-enabled-host.com', $options['cdn_hosts']);
    } else {
        $options['cdn_host'] = str_ireplace('ssl-enabled-host.com', 'non-ssl-host.com', $options['cdn_host']);
        $options['cdn_hosts'] = str_ireplace('ssl-enabled-host.com', 'non-ssl-host.com', $options['cdn_hosts']);
    }
    return $options;
});
```

Replace `non-ssl-host.com` and `ssl-enabled-host.com` w/ the ones you have.

**Comment by dbaritchi** [comment]
Re: MaxCDN SSL Access, the gotcha is they allow you to use their shared SSL host instead of using your own SSL cert - at no cost. meaning MaxCDN is a good deal at $70 per terabyte. 

BUT if you want to use your own SSL cert for a zone, while possible, it's $99/MONTH per zone. makes it not worth using in almost all cases. 

Here's their Shared SSL Guide: https://www.maxcdn.com/one/tutorial/setup-shared-ssl/

![image 2016-04-23 at 2 38 48 pm](https://cloud.githubusercontent.com/assets/7244858/14763681/3d111ef4-0962-11e6-85d4-9d5380d152c4.png)

![image 2016-04-23 at 2 39 10 pm](https://cloud.githubusercontent.com/assets/7244858/14763682/466fa592-0962-11e6-9858-3fbaba84bb4b.png)

> Are you sure the .netdna-ssl.com won't work over http:// and https:// too! Sorry, I haven't had the time to run my own tests against that yet. If you can try that and let me know I'd appreciate it.

Ah, I see your point... using the SSL-provided host but with HTTP... that "should" work... I'll check with one of our zones and update this ticket. 

Quick side note been meaning to mention, fwiw. W3TC added ability to provide both HTTP and HTTPS host for URL replacement like 5 yrs ago, but it wasn't well documented. Basically in the CDN URL field, you'd enter "HTTP Host,HTTPS Host". so comma separated in that field. 2 clear fields is probably so much cleaner lol. 

> Use the .netdna-ssl.com Host Name only, and then force your entire site to be served over SSL, which is a growing trend anyway. If you do that, you may not need the http:// variation at all.

Unfortunately that won't work for us because there are thousands of sites hosted on our WordPress multisite, some SSL some not, and we can't change them all to SSL, not viable. 

> Or, you can implement a filter (for now) while we work this issue.

Awesome - will try this and update the ticket with results. 

Thanks!
Dan

**Comment by dbaritchi** [comment]
just to be super clear, I'm in no way comparing Comet Cache to W3TC... the difference is night and day lol. :)

**Comment by jaswrks** [comment]
> Basically in the CDN URL field, you'd enter "HTTP Host,HTTPS Host". so comma separated in that field. 2 clear fields is probably so much cleaner lol.

Ah, good to know. Thanks :-)

> SSL-provided host but with HTTP... that "should" work... I'll check with one of our zones and update this ticket.

Cool. That'd be awesome.

In the meantime, I'm opening a new issue to address this feature request here: https://github.com/websharks/comet-cache/issues/749

**Comment by raamdev** [comment]
Closing due to lack of feedback.
