### ISSUE TITLE
Install on subdomain complains comet is already installed

### ISSUE THREAD

**Issue by CInsights** [wpsharks/comet-cache#736]
If comet is installed on an existing subdomain then when installing on a further subdomain of the same site comet complains that the cache directory already exists.
The plugin fails to activate initially.
It can be activated through the plugin admin panel and appears to work normally.

**Comment by raamdev** [comment]
@CInsights Is this on a WP multisite or a standard installation?

**Comment by CInsights** [comment]
Standard installation.

(Sent from iPhone)

On 16 Apr 2016, at 9:06 PM, Raam Dev notifications@github.com wrote:

@CInsights Is this on a WP multisite or a standard installation?

**Comment by raamdev** [comment]
@CInsights Hmm. I'm a bit confused about how the site is set up.

If you install WordPress on subdomain1.example.com, then that WordPress installation should have its own root directory on your web server (e.g., `/home/example/www/subdomain1/`) and Comet Cache would create and write to a directory inside there (e.g., `/home/example/www/subdomain1/wp-content/cache/`).

If you install WordPress on subdomain2.example.com, then that WordPress installation should have its own root directory on your web server (e.g., `/home/example/www/subdomain2/`) and Comet Cache would create and write to a directory inside there (e.g., `/home/example/www/subdomain2/wp-content/cache/`).

I'm not seeing how it's possible for the Comet Cache cache directory to "already exist" if the subdomains have their own separate space on the file system.

The only thing that comes to mind is that your web server is somehow misconfigured and trying to write to the same directory for all subdomains (which would be _really_ misconfigured—I'm not even sure how that would work).

**Comment by CInsights** [comment]
Agreed it doesn't make a lot of sense.
FYI the server is a "reseller" host system.
So not quite a VPS but a little different in that it has WHM.
The primary account domain is not used for hosting "public facing" sites.
I just have multiple utility and other test sites set up as subdomains of the primary account/domain.

All I did was to install using the upload of my Comet Pro zip so that was about as plain vanilla as a plug-in install gets.

I'll jump on to another of the subdomains and run an install of Comet and see if I get the same issue.

Back soon...

**Comment by CInsights** [comment]
Well as you'd expect that install worked without a hitch.
I tried uninstall and re-install also without a hitch.
So lacking any ability to reproduce I'll close this.

**Comment by raamdev** [comment]
@CInsights Got it. Thanks for the update and for closing. :-)
