### ISSUE TITLE
Medias -> Add new Media raises a Fatal error while processing newly uploaded .mp3 media

### ISSUE THREAD

**Issue by emanwebdev** [wpsharks/comet-cache#738]
![comet_cache_fatal_error_feedutils_line232](https://cloud.githubusercontent.com/assets/1505372/14587918/47fb34ee-04bc-11e6-87db-76accfefe308.png)

Medias -> Add new Media -> Fatal error while processing newly uploaded .mp3 media

`Undefined class constant ‘CACHE_PATH_NO_SCHEME’`

in /plugins/comet-cache/src/includes/classes/**FeedUtils.php** on **line 232**

**Comment by emanwebdev** [comment]
Using Comet Cache™ v160416
WP 4.4

all rights ok 

Scenario found with .mp3 and .ogg media files formats

**Comment by raamdev** [comment]
@emanwebdev Thank you for the heads up. I'm aware of this bug and working on a fix now. I'll release a maintenance update shortly that will fix this. See https://github.com/websharks/comet-cache/issues/739

**Comment by raamdev** [comment]
@emanwebdev Just noting here that Comet Cache v160417 has been released and includes the fix for this issue. Please see https://cometcache.com/blog/comet-cache-v160417-maintenance-release/.
