### ISSUE TITLE
Feature Request: Second Pro Updater Button

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#741]
In the latest release whenever I fill-in my Username and License Key, then scroll to the bottom, all I find is the "Save All Changes" button. Clicking that does what it says, but it's not quite clear how I can actually perform the upgrade itself.

![2016-04-18_21-03-28](https://cloud.githubusercontent.com/assets/1563559/14628309/20842f7c-05a9-11e6-8d62-b7c01aae6e55.png)

---

Of course, there is another button at the top that allows me to begin the upgrade, but that seems slightly confusing, because that button is not presented in the same context as my Username/License Key is, which is what I need to enter to complete the upgrade.

_Keep in mind that Comet Cache Pro suggests (through a notice) that a site owner visit this page whenever a new version becomes available. After clicking that link in the notice, my expectation (after clicking the link to complete an upgrade), is that this page will allow me to do the upgrade, not just save upgrade-related options._

I suggest that we add a second button (at the bottom) with the label: **Save All & Upgrade Now**. Clicking that would perform two actions:
- Save the options.
- Perform the upgrade.

**Comment by raamdev** [comment]
I agree it's a problem that needs solving, but I'm not sure yet about the best way to go about solving it from a UX perspective. 

Following are two mockups of a second button at the bottom—both feel slightly wrong to me from a usability perspective (it's confusing: do I Save and Then Update? Or does Update also Save?):

![2016-04-19_20-33-11](https://cloud.githubusercontent.com/assets/53005/14659972/9a76ae02-066e-11e6-8e59-c1c49c0720e5.png)
![2016-04-19_20-33-44](https://cloud.githubusercontent.com/assets/53005/14659974/9c7df304-066e-11e6-9d12-d7c53fd36a1e.png)

One thing that might work is to change the "Update Comet Cache Now" to "Save and Update Comet Cache Now" so that it's clear you can do both with one button:

![2016-04-19_20-37-48](https://cloud.githubusercontent.com/assets/53005/14659990/af632e12-066e-11e6-8fa4-3d27f9024c15.png)

**Comment by jaswrks** [comment]
> One thing that might work is to change the "Update Comet Cache Now" to "Save and Update Comet Cache Now" so that it's clear you can do both with one button:

Cool. That sounds good to me also. I like the "Save _and_ Update" idea. That does make it clearer.

**Comment by jaswrks** [comment]
While working on this issue, it would be awesome if we could find a way to disable Google Chrome Auto-Fill on this page (notice the yellow fields in my screenshot above). That always seems to get in my way on this page. That's not a CC problem, it's a Chrome problem, but if there is a way to turn that off altogether I'd love to know how.

I have never been able to accomplish this myself in any reliable way, so maybe it is just not possible to do it. I just thought I would mention it in case anyone else becomes aware of some way to turn that off for specific forms or specific fields.

**Comment by raamdev** [comment]
## What needs to be done

We need to add a second button to the bottom of the Plugin Updater page, one that goes right next to the "Save All Changes" button and says "Save and Update Comet Cache" (note: the screenshot says "Save and Update Comet Cache Now", but I feel we should take out the "Now").

![2016-04-19_20-37-48](https://cloud.githubusercontent.com/assets/53005/14659990/af632e12-066e-11e6-8fa4-3d27f9024c15.png)

Right now we have a "Save All Changes" button at the bottom and an "Update Comet Cache Now" button at the top right of the page, but a site owner might scroll to the bottom of the page and expect to see a way to "save and update".

The "Update Comet Cache Now" button in the top right actually does a save and update, so this new "Save and Update Comet Cache" button should behave the exact same way. The only new thing here is that we're providing two buttons for saving and updating: One at the top right that says "Update Comet Cache Now" and one at the bottom that says "Save and Update Comet Cache".

**Comment by raamdev** [comment]
@jaswsinc writes...

> it would be awesome if we could find a way to disable Google Chrome Auto-Fill on this page

It seems this is the only workaround (even as recently as March 2016): http://stackoverflow.com/a/15917221/130664 I'm not sure how I feel about adding hidden fields to the page to solve this, but if you think it's worth doing, I'm fine with it.

**Comment by jaswrks** [comment]
Nah, I'm not wild about that idea either.

**Comment by jaswrks** [comment]
Did you give this a go?
http://stackoverflow.com/a/30976223/1219741

**Comment by raamdev** [comment]
@jaswsinc writes...

> Did you give this a go?
> http://stackoverflow.com/a/30976223/1219741

Whoa! I just tried that and it worked! Sweet.

Now I wonder if that's cross-browser compatible though... will Firefox obey `autocomplete="new-password"`?

**Comment by raamdev** [comment]
Nope, `autocomplete="new-password"` is not compatible with Firefox—when you use `new-password`, Firefox ends up auto-filling the fields.

**Comment by jaswrks** [comment]
> Whoa! I just tried that and it worked! Sweet.

Ah. Awesome! Well, at least Chrome can be made to obey. That's progress!

**Comment by raamdev** [comment]
It looks like we can use `autocomplete="off"` in the `<form>` tag and Firefox will obey that. Then we can use `autocomplete="new-password"` in the individual fields, and Chrome will obey that. Woohoo! 

@renzms Please include the above changes in your PR for this issue. :-)

**Comment by raamdev** [comment]
Next Release Changelog:
- **UX Bug Fix** (Pro): If you had your WordPress Dashboard login details saved by your browser, the browser autofill would automatically fill in the Pro Plugin Updater fields with those details, which then needed to be replaced with your actual Pro license details. The browser autofill has been disabled for those fields (tested in Chrome, Firefox, and Safari). Props @renzms. See [Issue #741](https://github.com/websharks/comet-cache/issues/741).
- **UI Enhancement** (Pro): A second button has been added to the bottom of the Pro Plugin Updater page that allows you to "Save and Update Comet Cache Pro" in one step. Props @renzms. See [Issue #741](https://github.com/websharks/comet-cache/issues/741).

**Comment by raamdev** [comment]
@renzms The **Save All Changes** button should not be half-width on the Plugin Options or Stats/Charts pages, only the Plugin Updater page:

![2016-06-15_22-39-33](https://cloud.githubusercontent.com/assets/53005/16103868/4f64aaaa-334a-11e6-8e2f-cdfe5ecb50ee.png)

**Comment by renzms** [comment]
> The Save All Changes button should not be half-width on the Plugin Options or Stats/Charts pages, only the Plugin Updater page:

@raamdev Thanks for catching that, I'll make a new class for the buttons on the Plugin Updater page, so it only affects that page.

**Comment by renzms** [comment]
@raamdev Updated, thanks!

Pro Updater Page:
![screen shot 2016-06-17 at 12 30 41 pm](https://cloud.githubusercontent.com/assets/13220018/16140885/10423128-3488-11e6-8970-5cd5e7304530.png)

Options Page
![screen shot 2016-06-17 at 12 31 07 pm](https://cloud.githubusercontent.com/assets/13220018/16140888/244f9e94-3488-11e6-8f82-63320ed7ed3f.png)

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#741).

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#741).
