### ISSUE TITLE
Comet Cache pro kills styles inside Slider Revolution

### ISSUE THREAD

**Issue by groubee** [wpsharks/comet-cache#742]
Hi

When I activate the Comet Cache pro plugin - some of the style disappears. Here: [http://www.skisme.dk/lejligheder/casa-marietta/](url) in the right side you find an "Open fullsize icon" and a white animated text inside the Slider Revolution slide which disappears if Comet Cache pro plugin is active.? It happens in every slide - also on the homepage (here some text style changes to grey).

What could be the problem?

Cheers
Tonny

![skaermbillede 2016-04-20 kl 13 15 48](https://cloud.githubusercontent.com/assets/8695777/14672751/19256c58-06fa-11e6-91d1-99c7edf44bf3.png)
![skaermbillede 2016-04-20 kl 12 07 59](https://cloud.githubusercontent.com/assets/8695777/14672752/1925f966-06fa-11e6-8697-741082e05c40.png)

**Comment by raamdev** [comment]
@groubee It sounds like you're using the HTML Compressor feature of Comet Cache Pro and the CSS and/or JavaScript that Slider Revolution uses is not compatible with compression. 

I suggest excluding any Slider Revolution scripts in **Comet Cache → Plugin Options → HTML Compression**; see **CSS Exclusion Patterns** and **JavaScript Exclusion Patterns**.

---

Note that we have another GitHub issue open to keep track of compatibility with Slider Revolution; see https://github.com/websharks/comet-cache/issues/614. I'm going to close this GitHub issue in favor of that one and I'll reference this issue over there.
