### ISSUE TITLE
Issue Report: "Unknown error: Please wait 15 minutes and try again" is alive and well

### ISSUE THREAD

**Issue by patdumond** [wpsharks/comet-cache#743]
Reference: https://github.com/websharks/comet-cache/issues/678

I tried to update my WebSharks' test site this morning and got the "Unknown error: Please wait 15 minutes and try again." error. I checked the Developers Console and the only error is about jQuery Migrate being installed (WordPress 4.5 update). 
![jquery-migrate](https://cloud.githubusercontent.com/assets/9320495/14679448/ebf07c58-06e7-11e6-9294-afd3ba88b147.jpg)

I updated manually and the plugin updated, but the error message ("Unknown error...") is still there as well as a notification to update to v160316 (which has been there for a month now even though I updated as soon as v160315 was available.).

![2016-04-20_11-12-46](https://cloud.githubusercontent.com/assets/9320495/14679765/3dfb0918-06e9-11e6-954c-aa0997b71a3b.jpg)

**Comment by raamdev** [comment]
> as well as a notification to update to v160316 (which has been there for a month now even though I updated as soon as v160315 was available.).

That looks related to testing an older version of Comet Cache where that message got left in the database and never cleared out. I suggest turning off Plugin Deletion Safeguards, then Deactivating and Deleting the plugin (that will wipe all Comet Cache related settings from the database). If you then reinstall Comet Cache, you should see the proper messages. 

> I tried to update my WebSharks' test site this morning and got the "Unknown error: Please wait 15 minutes and try again." error. I checked the Developers Console and the only error is about jQuery Migrate being installed (WordPress 4.5 update).

Hmm, the jQuery Migrate message seems unrelated. Also, keep in mind that the "Unknown error" message is certainly still _possible_. 

The thing that was fixed in v160416 was a specific scenario that generated that error (the scenario where your server is running an old version of cURL and/or OpenSSL; see #678). However, there are plenty of other scenarios that could generate that "Unknown error" message, including basic network connectivity issues (hence the suggestion to wait 15 minutes and try again). 

If you see that "Unknown error" indefinitely, then it's something we should look at more closely.

**Comment by jaswrks** [comment]
If that was done on a HostGator test site, it's something I would _expect_ for now. HostGator is running an extremely outdated version of the cURL library that is unable to speak with a large percentage of the web. They are aware of the issue and have done nothing about it yet, but they are supposed to be rolling out an update in mid-April that I'm hoping will resolve this.

So updating from the previous release to the new one that Raam just made available will still generate this error when testing from HostGator. Moving to the next release, Raam has implemented a short-term workaround via a proxy server to avoid this problem at HostGator. So the next time you update (even if it's from HostGator, and even if they haven't upgraded their systems yet) you shouldn't see that message again. This time I had the same issue whenever I upgraded to v160416.

**Comment by patdumond** [comment]
Unless we are hosting websharks-inc.net on a HostGator server, it was not on HostGator. I would not go near HostGator if I had to build my own web server and run fiber-optic cable to my house. ;)

@raamdev: I uninstalled Comet Cache after disabling _Plugin Deletion Safeguards_ last month and it didn't get rid of the false notification. If I have time I'll do it again. Reference the main point of this issue, I didn't say the _jQuery Migrate_ message was related but wanted to offer a complete report of my findings. If you don't feel this is anything we need worry about, no problems here.

**Comment by jaswrks** [comment]
> Unless we are hosting websharks-inc.net on a HostGator server, it was not on HostGator. I would not go near HostGator if I had to build my own web server and run fiber-optic cable to my house. ;)

haha! That's hilarious. I know what you mean.

The test sites that we have _are_ on HostGator, so that may explain this.

**Comment by raamdev** [comment]
> The test sites that we have are on HostGator, so that may explain this.

I just upgraded Comet Cache Pro on my `raam.websharks-inc.net` test site (which is on HostGator). I had a Dashboard message about there being an update available for v160417. I had no problem with the update.

I will note that HostGator is a web host where we had the issue described in #678, and I'll also note that when I updated my test site (which was probably running v160416; I forgot to check beforehand) I noticed that it used thew new proxy server that we set up. (You can tell it uses the proxy server by looking at the URL where it downloads the update; if it says `proxy.websharks-inc.net`, then you know it's using the proxy to get around the issue described in #678).

@patdumond One thing you might want to try is installing v160416 on your test site and then waiting for the update notification. When you see it, see if you can update to v160417 without issue.

**Comment by patdumond** [comment]
@raamdev wrote: 

> One thing you might want to try is installing v160416 on your test site and then waiting for the update notification. When you see it, see if you can update to v160417 without issue.

That worked. Got rid of the erroneous notification as well.

**Comment by raamdev** [comment]
@patdumond Cool. Thank you for the update and for the report here. :-) 

I'll go ahead and close this issue, but let us know if you run into the "Unknown error" again.
