### ISSUE TITLE
Publishing via XMLRPC does not automatically clear the cache

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#744]
As reported [here](https://forums.wpsharks.com/t/no-cache-refresh-after-new-post-from-xmlrpc/240), when publishing a post via [XMLRPC](https://codex.wordpress.org/XML-RPC_WordPress_API/Posts) Comet Cache does not properly detect this and clear the appropriate cache files. If, for example, someone publishes a new post, the home page cache does not get cleared and the new post is not visible. 

This needs to be tested to confirm and researched to figure out what needs to be done to fix it.

**Comment by renzms** [comment]
@raamdev 

### Status

 **Was able to replicate issue.**
Using Test installation: **WP 4.6.1, PHP 7.0, Comet Cache Pro Version 160917, WP CLI**

### Steps to reproduce

_Note, I did not use XMLRPC._

I was informed by @jaswsinc that it would be okay to use XMLRPC, but I could actually use Wordpress Rest API to do this.

@jaswsinc writes...

> The key thing is that XMLRPC is not a new protocol. It's just a fancy name for what is nothing more than an API like any other. XMLRPC is an outdated API for WordPress that is enabled by default now in all WP installs. It used to be enabled by a site owner, but now it is _disabled_ by most system administrators because it is open to attacks and will increase the odds of your site being hit with a DDoS attack.
> 
> Basically, it just comes down to formulating a request that you will send to WordPress that speaks the XML language. Like any other API, you formulate that request, send it to the server over HTTP and get back a response. 
- Install and enable **Comet Cache Pro**. Enable `Automatic Cache Clearing` settings and configurations
- Create some sample post/page(s) and create cache
- Check cache is clearing automatically by adding/updating post/page(s)
- Using **WP RESTful CLI** use command line for posting via `SSH`. (see command lines here:http://wp-cli.org/commands/post/)
- Post using different commands and types of posts/pages. (e.g, public, private, draft, post, page, future, set post date and time, update post/page, delete post/page)
- Check if cache has cleared

### Results

Cache does not clear when posting via WP CLI. Deleting/Editing/Updating those post/page(s) via the WP dashboard _does_ clear the cache. Comet Cache only recognizes and clears the cache when changes are done in the **WP Dashboard**.

**Comment by raamdev** [comment]
@renzms Thanks for testing and for sharing that information.

@jaswsinc Can I get a time estimate on this?

**Comment by jaswrks** [comment]
Testing via WP-CLI (over SSH) is not the same as testing via XMLRPC. The WP-CLI tool operates in a CLI context. Meaning, web server environment variables may not be present, depending on your configuration. For the best WP-CLI compatibility it is suggested that you enable one of these flags when dealing with Comet Cache.

```
--http=<http>
Perform operation against a remote WordPress install over HTTP.

--url=<url>
Pretend request came from given URL. In multisite, this argument is how the target site is specified.
```

We can improve compatibility with WP-CLI though. For example, by refactoring and taking a closer look at `$_SERVER` environment variable access on the part of Comet Cache. We will likely need new functions that can fall back on a DB lookup for things like the current host name, instead of failing when `$_SERVER['HTTP_HOST']` is unavailable; e.g., when running in a CLI context. For this I estimate three days.

For XMLRPC compatibility I'm not sure. That's a web-based HTTP API, which means it doesn't operate in a CLI context like WP-CLI does. If automatic cache clearing is not working when posting via XMLRPC, it could be that we need to take a closer look at hooks we attach to. If someone can find out more about the problem for me, my estimate would be lower, but for now I'll say three additional days to research and fix this.

**Comment by raamdev** [comment]
@jaswsinc Thanks!

---

@renzms writes...

> Using WP RESTful CLI use command line for posting via SSH. (see command lines here:http://wp-cli.org/commands/post/)

That's really a separate issue than this XMLRPC issue. Can you please open another GitHub issue, "WP-CLI Compatibility: Create Post Command" and document your findings there (please also quote Jason's reply above Re: WP-CLI)? We'll have to research that issue separately. 

---

@jaswsinc writes...

> If automatic cache clearing is not working when posting via XMLRPC, it could be that we need to take a closer look at hooks we attach to. If someone can find out more about the problem for me

@renzms Could you do some more research on this? You'll probably need to get a client that connects to a WordPress installation via XMLRPC to publish/edit posts. See https://en.support.wordpress.com/xml-rpc/. Ping me on Slack if you have any additional questions.

**Comment by renzms** [comment]
@raamdev Noted, I'll look into this more.

Created WP CLI issue here: https://github.com/websharks/comet-cache/issues/839

**Comment by renzms** [comment]
@raamdev 

### Status

 **Was not able to replicate issue.**
Using Test installation: **WP 4.6.1, PHP 7.0, Comet Cache Pro Version 160917, WordPress Desktop App for MacOS (App connects via XML-RPC)**

### Steps
- Install and enable **Comet Cache Pro**. Enable `Automatic Cache Clearing` settings and configurations
- Create some sample post/page(s) and create cache
- Check cache is clearing automatically by adding/updating post/page(s)
- Using **WP Desktop APP** created and updated posts. 
- Tried different types of posts/pages. (e.g, public, private, draft, post, page, future, set post date and time, update post/page, delete post/page)
- Check if cache has cleared

### Results

Cache cleared when posting via WP Desktop App. Comet Cache recognizes and clears the cache when changes are done in the **WP Desktop App**.

**Comment by renzms** [comment]
Additional testing done via https://github.com/letrunghieu/wordpress-xmlrpc-client

Using **XML-RPC** client with **WP 4.6.1, PHP 7.0, Comet Cache Pro Version 160917**, was not able to replicate issue. 
- Created PHP file for testing and executed via command line.
- Cache automatically cleared and post was added/updated.

**Comment by raamdev** [comment]
I also just ran a test using the WordPress iOS app on my iPhone (WordPress 4.6.1, Comet Cache Pro v160917, iOS v10.0.2, WordPress iOS App v6.5) and confirmed that updating an existing post clears the cache for that post, so I'm going to close this as resolved. 

Thanks for the testing, @renzms! :-)
