### ISSUE TITLE
Comet Cache does not appear to be working because of wpnonce

### ISSUE THREAD

**Issue by clanooij** [wpsharks/comet-cache#745]
Comet Cache is NOT caching this page, because the current page contains `_wpnonce` or `akismet_comment_nonce`. How can this be solved?

**Comment by raamdev** [comment]
@clanooij See: [What are WordPress nonces and why are they not cache-compatible?](https://cometcache.com/kb-article/what-are-wordpress-nonces-and-why-are-they-not-cache-compatible/)
