### ISSUE TITLE
v160417: PHP Fatal error: Undefined class constant 'CACHE_PATH_NO_PATH_INDEX'

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#752]
Reported in an [private ticket](https://websharks.zendesk.com/agent/tickets/12316), this appears to be a similar problem as [the one that was fixed in v160417](https://github.com/websharks/comet-cache/issues/739):

> [Mon Apr 25 17:31:25.095675 2016] [proxy_fcgi:error] [pid 22938] [client 130.223.32.47:17867] AH01071: Got error 'PHP message: PHP Fatal error: Undefined class constant 'CACHE_PATH_NO_PATH_INDEX' in /var/www/html/example/wordpress/wp-content/plugins/comet-cache-pro/src/includes/classes/DirStats.php on line 574\n', referer: http://example.com/wp-admin/network/admin.php?page=comet_cache-stats

It would appear that we need to add an `implements Interfaces\Shared\CachePathConsts` to the end of [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/classes/DirStats.php#L11).

I have not yet reproduced the issue myself, but reviewing `DirStats.php` and its usage of Cache Path Constants tells me there is a bug there.

**Comment by jaswrks** [comment]
I concur. My suggestion would be to implement those constants at the base class layer.

On [this line](https://github.com/websharks/comet-cache/blob/160417/src/includes/classes/AbsBase.php#L9) add:

``` php
 implements Interfaces\Shared\NcDebugConsts, Interfaces\Shared\CachePathConsts
```

That way those constants are available to all classes that extend the base, which I believe is _all_ of the classes that we have. It looks like we did that [here](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/classes/AbsBaseAp.php#L12) for `AbsBaseApp`, but we should remove them from that class and implement them in the absolute base class, which is `AbsBase`.

**Comment by raamdev** [comment]
Next Release Changelog:
- **Bug Fix**: Fixed a bug that, in some scenarios, resulted in "PHP Fatal error: Undefined class constant 'CACHE_PATH_NO_PATH_INDEX'". This also affected the Cache Statistics feature, resulting in a blank panel when hovering over the Cache Stats button in the menu bar. See [Issue #752](https://github.com/websharks/comet-cache/issues/752).

**Comment by raamdev** [comment]
#### **Comet Cache v160521** has been released and includes changes from this GitHub Issue. See the [v160521 announcement](https://cometcache.com/blog/comet-cache-v160521-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#752).
