### ISSUE TITLE
Last version of comet cache generates an error

### ISSUE THREAD

**Issue by abiere** [wpsharks/comet-cache#755]
The last version of Comet Cache generates the following error:

```
Fatal error: Uncaught exception 'Exception' with message 'Undefined method/closure: `loadAcPlugins`.' in /home/axel/public_html/site/wp-content/plugins/comet-cache-pro/src/includes/classes/AbsBaseAp.php:57 

Stack trace: #0 /home/axel/public_html/site/wp-content/plugins/comet-cache-pro/src/includes/classes/AdvancedCache.php(57): WebSharks\CometCache\Pro\AbsBaseAp->__call('loadAcPlugins', Array) 
#1 /home/axel/public_html/site/wp-content/plugins/comet-cache-pro/src/includes/classes/AdvancedCache.php(57): WebSharks\CometCache\Pro\AdvancedCache->loadAcPlugins() 
#2 /home/axel/public_html/site/wp-content/advanced-cache.php(431): WebSharks\CometCache\Pro\AdvancedCache->__construct() 
#3 /home/axel/public_html/site/wp-settings.php(74): include('/home/axel/publ...') 
#4 /home/axel/public_html/site/wp-config.php(86): require_once('/home/axel/publ...') 
#5 /home/axel/public_html/site/wp-load.php(37): require_once('/home/axel/publ...') 
#6 /home/axel/public_html/site/wp-blog-header.php(13): require_once('/home/axel/publ...') 
#7 /home/axel/ in /home/axel/public_html/site/wp-content/plugins/comet-cache-pro/src/includes/classes/AbsBaseAp.php on line 57
```

I was only able to fix it by renaming the comet cache plugin directory. I have no clue how github etc works. Please let me know how to fix this.

**Comment by abiere** [comment]
After I renamed the comet cache plugin directory back to the original name and refreshed wp-admin I could activate the plugin again. It recompiled and seems to work again.

**Comment by raamdev** [comment]
@abiere Thank you for the report. Do you remember which version of Comet Cache you were upgrading _from_? Was it v160417, v160416, or v160227?

**Comment by abiere** [comment]
I'm sorry, but I don't remember. I updated everything every month or so. Is there some way I can check this for you?

**Comment by raamdev** [comment]
> Is there some way I can check this for you?

Hmm, I'm afraid not. However, do you have an idea roughly how long ago you did the last update? v160417 and v160416 were released within the past 2 weeks, so if the last time you updated was earlier than that, you must've been running v160227.

**Comment by abiere** [comment]
It is a month or more since I've updated, so it must be v160227. There is no harm done. Everything works again. Scared me as hell, but I survived ;)

**Comment by raamdev** [comment]
When it crashed, were you updating using the built-in Pro Plugin Updater, or were you upgrading in some other way?

**Comment by jaswrks** [comment]
> Fatal error: Uncaught exception 'Exception' with message 'Undefined method/closure: `loadAcPlugins`.' in /home/axel/public_html/site/wp-content/plugins/comet-cache-pro/src/includes/classes/AbsBaseAp.php:57

This looks like an issue with the OPcache to me. This exception had to have been thrown by the old version of the software as seen here on line 57 in v160227: https://github.com/websharks/comet-cache/blob/160227/src/includes/classes/AbsBaseAp.php#L57

Now look at [these lines](https://github.com/websharks/comet-cache/blob/160227/src/includes/classes/AbsBaseAp.php#L23-L27) where the closures are loaded in the old version of the software. If those files no longer exist (e.g., if you upgraded to the latest release that doesn't come with those files), you will see the exception about a missing closure.

This can happen as a result of updating the plugin, but with a stale opcode cache; e.g., the old version of files that existed in both versions of the software are still in memory, but with missing dependencies that those old versions had, because the filesystem itself was updated, and no longer contains the `.../closure` files.

**Comment by raamdev** [comment]
Related: https://github.com/websharks/comet-cache/issues/740

**Comment by abiere** [comment]
I was updating with the built in updater.

**Comment by jaswrks** [comment]
> I was updating with the built in updater.

Yeah, this is not your fault. Sorry for any confusion. I'm just seeing how we can avoid this in the future and I think Raam is too. The OPcache is something that works internally in a lot of PHP installations and if not properly flushed after an upgrade it can lead to this problem. Thanks for your patience.

**Comment by abiere** [comment]
No worries guys :) I was glad I was able to fix it with my nub skills ;) I will patiently await your magic to avoid panic with nubs like me ;) Keep up the good work!

**Comment by raamdev** [comment]
@abiere Thanks again for the report. :-) I'm glad things are working now on your end but it's reports like this that help us improve the software for future releases, so I really appreciate it! 

I'm going to close this issue in favor of https://github.com/websharks/comet-cache/issues/740, which should address the issue that you experienced here.
