### ISSUE TITLE
Cache Stats not working on subsites or Multisite network

### ISSUE THREAD

**Issue by gwfc** [wpsharks/comet-cache#760]
Hey folks,

See here http://screencast.com/t/EywzSYzwf65b

Since the last update, the cache stats never load FYI.

In case it matters, I have comet cache on a multisite.

Please let me know how to fix.

:)

https://wordpress.org/plugins/comet-cache/

**Comment by raamdev** [comment]
@gwfc Thank you for the report. This bug has been fixed (see https://github.com/websharks/comet-cache/issues/752) and will go out with the next release (occurring within the next week or so).

_Note: If you're interested in testing a beta release of Comet Cache before the next version comes out, please sign-up to be a beta tester [here](http://cometcache.com/beta-testers/) or see **Comet Cache → Plugin Updater → Beta Testers** to automatically receive Release Candidate updates._
