### ISSUE TITLE
Update WP PHP RV Dependency

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#762]
There have been two new releases of the WP PHP RV module.
https://github.com/websharks/wp-php-rv/releases

We can update Comet Cache to v160504 here:
https://github.com/websharks/comet-cache-pro/blob/160417/composer.json#L33

---

_**WPSC Note:** The upcoming release of the WPSC will attempt to take advantage of the newer features in the latest release of WP PHP RV. If those are not available the WPSC will fail gracefully, but ideally we will make an effort to update the WP PHP RV library in other plugins that use it, so that, should a plugin like Comet Cache load it first (i.e., before the WPSC), all others will have the latest to work with._

**Comment by jaswrks** [comment]
@renzms This is one that could tackle if you'd like, and then submit a PR. We just need to bump the version defined here to the latest release of WP PHP RV and let Raam review.

See: https://github.com/websharks/comet-cache-pro/blob/160417/composer.json#L33

**Comment by raamdev** [comment]
Closed by https://github.com/websharks/comet-cache-pro/issues/249.
