### ISSUE TITLE
`.htaccess` Tweaks: Automatic GZIP Compression

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#764]
## Next Actions
- **1.** New file in [this directory](https://github.com/websharks/comet-cache-pro/tree/160417/src/includes/templates/htaccess) with the name: `gzip-enable.txt`
  
  **Note:** This requires Apache v2.1+
  
  ``` apache
  # GZIP compression.
  
  <IfModule deflate_module>
    <IfModule filter_module>
      AddOutputFilterByType DEFLATE text/plain text/html
      AddOutputFilterByType DEFLATE text/xml application/xml application/xhtml+xml application/xml-dtd
      AddOutputFilterByType DEFLATE application/rdf+xml application/rss+xml application/atom+xml image/svg+xml
      AddOutputFilterByType DEFLATE text/css text/javascript application/javascript application/x-javascript
      AddOutputFilterByType DEFLATE font/opentype application/font-otf application/x-font-otf
      AddOutputFilterByType DEFLATE font/truetype application/font-ttf application/x-font-ttf
      <IfModule headers_module>
        <FilesMatch \.(?:js|css|xml|svg|xhtml|html|txt|ttf|otf|gz)$>
          Header append vary: accept-encoding
        </FilesMatch>
      </IfModule>
    </IfModule>
  </IfModule>
  ```
  
  Referencing: [WUBS config file](https://github.com/websharks/ubuntu-bootstrap/blob/160501/src/apache/.conf#L65-L81).

---
- **2.** After [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Plugin/HtaccessUtils.php#L69) add the following:
  
  ``` php
  case 'gzip-enable.txt':
      if ($this->options['htaccess_gzip_enable']) {
          $template_blocks .= trim(file_get_contents($templates_dir.'/'.$_template_file))."\n";
      } // Only if GZIP is enabled via .htaccess at this time.
      break;
  ```

---
- **3.** New option key [in this list](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/classes/Plugin.php#L266) after a blank link to start a new section.
  
  ``` php
  
  'htaccess_gzip_enable',
  ```

---
- **4.** New option key [in this list](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/classes/Plugin.php#L401) also.
  
  ``` php
  /* Related to .htaccess tweaks. */
  
  'htaccess_gzip_enable' => '1', // `0|1`; enable GZIP via .htaccess?
  ```

---
- **5.** New UI option panel for `.htaccess` Tweaks (pro version only) and it should include details about this option. The option value can be either `0` (off) or `1` (on) with `1` being the default behavior.

---
## Before Beginning Work ...
- Check with @raamdev to see if the above outline is suitable; i.e., if this in fact going to be a pro-only feature. If so, the option panel in step 5 should provide a pro preview. If it's going to be available in both the lite and pro versions, you can skip over step 3 and step 5 can be implemented in a way that exposes this option to users of both the lite and pro version.

**Comment by jaswrks** [comment]
Noting that the UI panel should be titled, **Apache Optimization**. See: https://github.com/websharks/comet-cache/issues/554#issuecomment-150065142

**Comment by raamdev** [comment]
Noting that this feature should be _disabled_ by default. We should not be updating the `.htaccess` unless the site owner tells Comet Cache it should be doing so.

**Apache Optimization** should be a Pro-only feature, yes.

Otherwise the outline looks good to me.

**Comment by jaswrks** [comment]
Noting that we should remove this section as it is unnecessary.
The deflate module does this automatically in a more effective way.

```
<IfModule headers_module>
      <FilesMatch \.(?:js|css|xml|svg|xhtml|html|txt|ttf|otf|gz)$>
        Header append vary: accept-encoding
      </FilesMatch>
    </IfModule>
```

**Comment by raamdev** [comment]
Next Release Changelog:
- **New Feature!** A new "Enable GZIP Compression" option has been added to the new Apache Optimizations panel. This option will automatically add the appropriate configuration to your `.htaccess` file to enable GZIP compression. This option is disabled by default. The old "GZIP Compression" panel has been removed in favor of the new option inside Apache Optimizations. Props @renzms, @jaswsinc. See [Issue #764](https://github.com/websharks/comet-cache/issues/764).

**Comment by GermontZ** [comment]
I have a few huge posts, e.g. 45 A4 pages, or even more. Do you think there will be a problem if these posts will be gzipped on the fly for every page load? I'm thinking about increased load time.
I think I've seen a few plugins that stores already gzipped cache files.
Maybe it would be a good ideea for Comet Cache? Thanks!

**EDIT**: I suppose that gzipping on the fly does matter if the posts become viral on social networks or whatever.

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#764).
