### ISSUE TITLE
`.htaccess` Tweaks: Leverage Browser Caching

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#765]
## Next Actions (referencing https://github.com/websharks/comet-cache/issues/134)
- **1.** New file in [this directory](https://github.com/websharks/comet-cache-pro/tree/160417/src/includes/templates/htaccess) with the name: `client-side-cache-enable.txt`
  
  **Note:** This requires Apache v2.1+
  
  ``` apache
  # Client-side caching.
  
  FileETag mtime size
  
  <IfModule expires_module>
    ExpiresActive on
    ExpiresDefault "access plus 5 days"
  </IfModule>
  ```
  
  Referencing: [WUBS config file](https://github.com/websharks/ubuntu-bootstrap/blob/160501/src/apache/.conf#L56-L63).

---
- **2.** After [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Plugin/HtaccessUtils.php#L69) add the following:
  
  ``` php
  case 'client-side-cache-enable.txt':
      if ($this->options['htaccess_client_side_cache_enable']) {
          $template_blocks .= trim(file_get_contents($templates_dir.'/'.$_template_file))."\n";
      } // Only if client-side caching is enabled via .htaccess at this time.
      break;
  ```

---
- **3.** New option key [in this list](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/classes/Plugin.php#L266) after a blank link to start a new section.
  
  ``` php
  
  'htaccess_client_side_cache_enable',
  ```

---
- **4.** New option key [in this list](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/classes/Plugin.php#L401) also.
  
  ``` php
  /* Related to .htaccess tweaks. */
  
  'htaccess_client_side_cache_enable' => '1', // `0|1`; enable client-side caching via .htaccess?
  ```

---
- **5.** New UI option panel for `.htaccess` Tweaks (pro version only) and it should include details about this option. The option value can be either `0` (off) or `1` (on) with `1` being the default behavior.

---
## Before Beginning Work ...
- Check with @raamdev to see if the above outline is suitable; i.e., if this in fact going to be a pro-only feature. If so, the option panel in step 5 should provide a pro preview. If it's going to be available in both the lite and pro versions, you can skip over step 3 and step 5 can be implemented in a way that exposes this option to users of both the lite and pro version.

**Comment by jaswrks** [comment]
Noting that the UI panel should be titled, **Apache Optimization**. See: https://github.com/websharks/comet-cache/issues/554#issuecomment-150065142

**Comment by jaswrks** [comment]
Noting that I changed my mind about the default value for this option. Raam is here to make the final call, but my suggestion would be to leave this (and other `.htaccess` options like it) off by default. That way we are not writing to the `.htaccess` file without the site owner knowing about it. Currently, these changes are not absolutely required for effective caching. They are highly recommended, but not essential.

**Comment by raamdev** [comment]
> off by default

I agree 100%. I'd rather not write to the `.htaccess` without the site owner knowing that's what's happening.

**Comment by raamdev** [comment]
Noting that this feature should be _disabled_ by default. We should not be updating the `.htaccess` unless the site owner tells Comet Cache it should be doing so.

**Apache Optimization** should be a Pro-only feature, yes.

Otherwise the outline looks good to me.

**Comment by raamdev** [comment]
@jaswsinc writes...

> `client-side-cache-enable.txt`

Would you mind if we changed this (and the `htaccess_client_side_cache_enable` option) to say `browser-caching` instead? My feeling is saying `client_side_cache` adds a _lot_ of confusion because we already have a **Client-Side Cache** feature that is totally unrelated to this new feature (one controls `nocache` headers, the other controls whether or not the browser caches static resources).

**Comment by jaswrks** [comment]
Agreed. No problem.

**Comment by raamdev** [comment]
Next Release Changelog:
- **New Pro Feature!** A new "Leverage Browser Caching" option has been added to the new Apache Optimizations panel. This option will automatically add the appropriate configuration to your `.htaccess` file to enable Browser Caching. This option is disabled by default. Props @renzms, @jaswsinc. See [Issue #764](https://github.com/websharks/comet-cache/issues/764).
- The `COMET_CACHE_ALLOW_BROWSER_CACHE` constant has been renamed to `COMET_CACHE_ALLOW_CLIENT_SIDE_CACHE` to avoid confusion with the new "Apache Optimizations → Leverage Browser Caching" option. Backwards compatibility for the old constant has been maintained.
- The `allow_browser_cache` plugin option has been renamed to `allow_client_side_cache` to avoid confusion with the new "Apache Optimizations → Leverage Browser Caching" option.

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#765).
