### ISSUE TITLE
Improve Logged-In Users panel

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#768]
When Logged-In Users caching is disabled (the default), everything else in that panel (other than the option to enable Logged-In Users caching) should be greyed out, as none of the other options are applicable unless Logged-In Users caching is enabled. (This should work the same way the HTML Compressor panel works.)

![2016-05-14_13-30-34](https://cloud.githubusercontent.com/assets/53005/15269780/397f537e-19d8-11e6-80aa-650c51c875df.png)

While we're at it, the **Enable HTML Compression for Logged-In Users?** option from the HTML Compressor panel should be moved to the Logged-In Users panel, as it seems more appropriate there.

![2016-05-14_13-33-03](https://cloud.githubusercontent.com/assets/53005/15269790/6712251e-19d8-11e6-8c6a-5a31fbeb6d9f.png)

**Comment by raamdev** [comment]
Noting that this is complicated by the `when_logged_in` option having one of three possible values: `0`, `1`, and `postload`. (The ability to choose the value of `1` was dropped a long time ago and only exists for backwards-compatibility.) [The JavaScript](https://github.com/websharks/comet-cache-pro/blob/160417/src/client-s/js/menu-pages.js#L78) that is used by the HTML Compressor panel to fade out additional options currently looks for an integer value of `>= 1`, which does not work with a value of `postload`.

So, we'll either need to change the `when_logged_in` option so that instead of using `postload` it uses, perhaps, `2`, or we'll need to adjust the JavaScript to consider the `postload` value. If we change the `postload` value, we'll need to write a Version Upgrade routine to change the value for existing sites who may have that option enabled.

**Comment by jaswrks** [comment]
> The JavaScript that is used by the HTML Compressor panel to fade out additional options currently looks for an integer value of >= 1, which does not work with a value of postload.

### Working Around This Issue
- In [the select tag](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/classes/MenuPageOptions.php#L597) add `data-enabled-strings="1,postload"`
- Replace [these lines](https://github.com/websharks/comet-cache-pro/blob/160417/src/client-s/js/menu-pages.js#L74-L78) with the following:
  
  ``` js
  plugin.enableDisable = function (event) {
      var $this = $(this),
      thisValue = $this.val(),
      thisName = $this.attr('name'),
      thisEnabledStrings = String($this.data('enabledStrings') || '1,2,3,4,5').split(/,+/);
  
      var enabled = $.inArray(thisValue, thisEnabledStrings) !== -1;
  ```

**Comment by raamdev** [comment]
@jaswsinc Thanks! :-)

You have a couple of bugs in that outline:
- "Replace these lines with the following"; doing that breaks the rest of the JavaScript below that section because [these lines](https://github.com/websharks/comet-cache-pro/blob/160417/src/client-s/js/menu-pages.js#L80-L89) are part of the previous `var` statement.
- The outline does not completely solve the problem, because [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/client-s/js/menu-pages.js#L25) attaches `plugin.EnableDisable` only to select elements whose name ends with `_enable` (`'select[name$="_enable\\]"]'`), and the Logged-In Users option does not end with `_enable` (its value is `when_logged_in`). (I was banging my head against the table trying to figure out why the heck it wasn't working.)

So, do you suggest adding a second line that attaches `when_logged_in` to `plugin.EnableDisable`, or something else?

**Comment by renzms** [comment]
@raamdev 

Hi Raam, are there things that need to be addressed first before I start working on this?

**Comment by jaswrks** [comment]
> because these lines are part of the previous var statement.

Copy. I missed that, sorry :-)

> plugin.EnableDisable only to select elements whose name ends with _enable ('select[name$="_enable\]"]'), ... So, do you suggest adding a second line that attaches when_logged_in to plugin.EnableDisable, or something else?

We could alter the select so that it includes an explicit attempt to include the enable/disable functionality on a given `<select>` tag. So for instance, we can change [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/client-s/js/menu-pages.js#L25) to the following:

``` js
$('select[name$="_enable\\]"], select[data-toggle~="enable-disable"]', plugin.$menuPage).not('.-no-if-enabled').on('change', plugin.enableDisable).trigger('change');
```

and then on the `<select>` tag add the following attributes [here](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/classes/MenuPageOptions.php#L597).

``` html
data-toggle="enable-disable" data-enabled-strings="1,postload"
```

Example:

``` html
echo '      <p><select name="'.esc_attr(GLOBAL_NS).'[saveOptions][when_logged_in]" data-toggle="enable-disable" data-enabled-strings="1,postload">'."\n";
```

**Comment by raamdev** [comment]
@renzms writes...

> Hi Raam, are there things that need to be addressed first before I start working on this?

I've assigned this to myself and already submitted a PR, so I'll take care of this one. :-)

**Comment by raamdev** [comment]
@jaswsinc writes...

> `select[data-toggle~="enable-disable"]`

Ah, brilliant! Nice. I'm loving those data attributes. 

Your suggestions above (see https://github.com/websharks/comet-cache-pro/commit/93d37f7d0c2cb6148759e93ba386408fd63ad2ed) fixed the issue and now toggle works as expected. Woohoo! Thanks. :-)

**Comment by jaswrks** [comment]
Awesome :-) One last thing I just noticed is that we might need to include `2` here also. Not sure about that, but I'm guessing you will know more since you're working closely with that at the moment.

I'm thinking maybe:

``` html
data-enabled-strings="1,2,postload"
```

**Comment by raamdev** [comment]
> I just noticed is that we might need to include 2 here also.

No, the possible values for `when_logged_in` are `0|1|postload`; see [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/classes/Plugin.php#L356).

**Comment by jaswrks** [comment]
Ah, OK.

**Comment by raamdev** [comment]
The following was applied to both the Logged-In Users panel and the Client-Side Caching panel:

![2016-06-03_19-17-49](https://cloud.githubusercontent.com/assets/53005/15795502/07ecb8a4-29c0-11e6-8b1b-967a610bd608.png)
![2016-06-03_19-17-59](https://cloud.githubusercontent.com/assets/53005/15795503/0956f42a-29c0-11e6-81ca-1152898ce52d.png)

Additionally, the "Enable HTML Compression for Logged-In Users?" option has been relocated from the HTML Compressor option panel to the more appropriate Logged-In Users option panel:

![2016-06-03_19-19-25](https://cloud.githubusercontent.com/assets/53005/15795511/249cb1e8-29c0-11e6-9985-161dade68f7b.png)

**Comment by raamdev** [comment]
Next Release Changelog:
- **UI Enhancements**: Improved the Logged-In Users and the Client-Side Caching options panels to dim additional options when the feature is disabled. Additionally, the "Enable HTML Compression for Logged-In Users?" option has been relocated from the HTML Compressor option panel to the more appropriate Logged-In Users option panel. See [Issue #768](https://github.com/websharks/comet-cache/issues/768).

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#768).
