### ISSUE TITLE
Pro Plugin Updater does not reactivate Comet Cache Pro after update

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#772]
While testing the upgrade from Comet Cache Pro v160417 → v160521 via the Pro Plugin Updater, I'm noticing that in some cases the plugin does not reactivate despite having been active before the update, and despite WordPress saying the plugin was reactivated successfully. Manually activating the plugin after the update works fine and the plugin does not produce any errors.

This appears to be just an inconvenience issue, but it might be symptomatic of something else and should be investigated.

I haven't been able to pinpoint exactly what scenarios cause this to happen, but I'm able to reproduce the problem more than 75% of the time.

![2016-05-20_20-43-39](https://cloud.githubusercontent.com/assets/53005/15445473/22514898-1ecd-11e6-8e28-0b9c5d51bfda.png)
![2016-05-20_20-44-14](https://cloud.githubusercontent.com/assets/53005/15445475/23aadd4e-1ecd-11e6-8702-83f3f78d8433.png)

**Comment by Reedyseth** [comment]
@raamdev Did you test this on the WordPress 4.5.2 ?

**Comment by renzms** [comment]
Was unable to reproduce this after multiple reinstallation and uninstalls from **Comet Cache Pro v160417 → v160521 via the Pro Plugin Updater**. 

I also tested three extra scenarios just in case:
- 1 scenario where I had ZenCache installed, uninstalled and installed Comet Cache Pro v160417 then upgraded
- 1 scenario where I cleared the settings from Plugin Deletion Safeguards and installed Comet Cache Pro v160417 then upgraded
- 1 scenario where I removed the username and license saved in the field, tried to update then input the credentials 

The only thing I noticed that was different was when I cleared the settings from Plugin Deletion Safeguards and installed Comet Cache Pro v160417 then upgraded to v160521, it took a bit longer before it said "Plugin Reactivated Successfully"

Is there a significant difference when WordPress downloads from the proxy server rather than cometcache.com itself?

![screen shot 2016-05-21 at 12 28 36 pm](https://cloud.githubusercontent.com/assets/13220018/15446343/67bf7bce-1f50-11e6-8b75-f1713e2b40d7.png)

**Comment by kristineds** [comment]
@raamdev Was unable to reproduce this issue either. Tested using WP 4.5.2. Steps I followed:
- Removed installed Comet Cache v160521 on site with Plugin Deletion Safeguards disabled
- Installed and activated old Comet Cache Pro v160416 from the Release Archive. 
- Used Pro Plugin Updater to update to the latest version `v160521`.
- Returned to Plugins page and check if Comet Cache is activated.

![screen shot 2016-05-21 at 3 46 20 pm](https://cloud.githubusercontent.com/assets/7514953/15447200/ad47e5c6-1f6b-11e6-8e98-c17f6134af4b.png)

![screen shot 2016-05-21 at 3 47 04 pm](https://cloud.githubusercontent.com/assets/7514953/15447201/b0e71f8a-1f6b-11e6-9905-a65f7fdb3651.png)

**Comment by patdumond** [comment]
I was unable to reproduce this issue, but I also unable to update using the Plugin Updater for Comet Cache. Clicking the **Update Comet Cache Now** button takes me to a 404 page at this link: http://s2m.sitegeeks.net/wp-admin/update.php?action=upgrade-plugin&plugin=comet-cache-pro%2Fcomet-cache-pro.php&_wpnonce=561d193fc9&comet_cache_update_pro_version=160521&comet_cache_update_pro_zip=aHR0cHM6Ly9jb21ldGNhY2hlLmNvbS8%2FdHNsPXgyMjBy

The plugin did not update.

I have had this issue before intermittently on various sites with both _Comet Cache_ (also _ZenCache_) and _s2Member_. However, normally the plugin updates even though I reach a 404 page.... I reported it at least once, long ago, but since I can never reproduce it after the patch that has the problem with any specific patch is updated manually I just don't bother anymore. ;)

I was not able to reproduce the problem on my websharks-inc.net site: the plugin updated normally. I didn't have any issues updating an of my other sites either.

**Comment by jaswrks** [comment]
> Clicking the Update Comet Cache Now button takes me to a 404 page at this link: http://s2m.sitegeeks.net/wp-admin/update.php?action=upgrade-plugin&plugin=comet-cache-pro%2Fcomet-cache-pro.php&_wpnonce=561d193fc9&comet_cache_update_pro_version=160521&comet_cache_update_pro_zip=aHR0cHM6Ly9jb21ldGNhY2hlLmNvbS8%2FdHNsPXgyMjBy

Do you know if your server running Mod Security for Apache?

@raamdev I'm guessing the problem reported by @patdumond is related to `&comet_cache_update_pro_zip=aHR0cHM6Ly9jb21ldGNhY2hlLmNvbS8%2FdHNsPXgyMjBy` on the end of the URL. That's probably triggering Mod Security rules.

@patdumond You can check the Apache error log (if you have access to it) and confirm that.

**Comment by raamdev** [comment]
@jaswsinc writes...

> I'm guessing the problem reported by @patdumond is related to &comet_cache_update_pro_zip=aHR0cHM6Ly9jb21ldGNhY2hlLmNvbS8%2FdHNsPXgyMjBy on the end of the URL. That's probably triggering Mod Security rules.

I agree, and we have a separate GitHub issue for that; see https://github.com/websharks/comet-cache/issues/416. 

However, that doesn't explain the issue that I've reproduced across several hosting environments with Comet Cache Pro not reactivating after an update. The environments I reproduced this in included Apache, NGINX, PHP 5.5 and PHP 7. Nothing appears in the PHP error log, however it didn't occur to me to check the Apache error log. Will do that next.

**Comment by raamdev** [comment]
I finally managed to get a PHP error associated with problem:

```
[21-May-2016 20:58:30 UTC] PHP Warning:  include_once(/srv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/stub.php): failed to open stream: No such file or directory in /srv/www/wordpress-default/wp-content/advanced-cache.php on line 25
[21-May-2016 20:58:30 UTC] PHP Stack trace:
[21-May-2016 20:58:30 UTC] PHP   1. {main}() /srv/www/wordpress-default/wp-admin/plugins.php:0
[21-May-2016 20:58:30 UTC] PHP   2. require_once() /srv/www/wordpress-default/wp-admin/plugins.php:10
[21-May-2016 20:58:30 UTC] PHP   3. require_once() /srv/www/wordpress-default/wp-admin/admin.php:31
[21-May-2016 20:58:30 UTC] PHP   4. require_once() /srv/www/wordpress-default/wp-load.php:37
[21-May-2016 20:58:30 UTC] PHP   5. require_once() /srv/www/wordpress-default/wp-config.php:53
[21-May-2016 20:58:30 UTC] PHP   6. include() /srv/www/wordpress-default/wp-settings.php:74
[21-May-2016 20:58:30 UTC] PHP Warning:  include_once(): Failed opening '/srv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/stub.php' for inclusion (include_path='.:/usr/share/php') in /srv/www/wordpress-default/wp-content/advanced-cache.php on line 25
[21-May-2016 20:58:30 UTC] PHP Stack trace:
[21-May-2016 20:58:30 UTC] PHP   1. {main}() /srv/www/wordpress-default/wp-admin/plugins.php:0
[21-May-2016 20:58:30 UTC] PHP   2. require_once() /srv/www/wordpress-default/wp-admin/plugins.php:10
[21-May-2016 20:58:30 UTC] PHP   3. require_once() /srv/www/wordpress-default/wp-admin/admin.php:31
[21-May-2016 20:58:30 UTC] PHP   4. require_once() /srv/www/wordpress-default/wp-load.php:37
[21-May-2016 20:58:30 UTC] PHP   5. require_once() /srv/www/wordpress-default/wp-config.php:53
[21-May-2016 20:58:30 UTC] PHP   6. include() /srv/www/wordpress-default/wp-settings.php:74
```

**Comment by raamdev** [comment]
And looking at the part of `advanced-cache.php` that is producing this error reveals why others may not have been able to reproduce it; if you don't have `WP_DEBUG` enabled, the error is suppressed with `@include_once`:

``` php
if (defined('WP_DEBUG') && WP_DEBUG) {
    if ((include_once(dirname(COMET_CACHE_PLUGIN_FILE).'/src/includes/stub.php')) === false) {
      return; // Unable to find stub. Fail softly w/ PHP warning.
    }
} elseif ((@include_once(dirname(COMET_CACHE_PLUGIN_FILE).'/src/includes/stub.php')) === false) {
    return; // Unable to find stub. Fail softly.
}
```

**Comment by patdumond** [comment]
No Mod Security errors in the error log, but I did find this:

```
[Sat May 21 12:19:54 2016] [warn] [client 99.194.46.170] mod_fcgid: stderr: PHP Fatal error:  Trait 'WebSharks\\CometCache\\Pro\\Traits\\Plugin\\WcpUserUtils' not found in /home/sgnet/public_html/s2m.sitegeeks.net/wp-content/plugins/comet-cache-pro/src/includes/classes/Plugin.php on line 55
[Sat May 21 12:19:34 2016] [warn] [client 99.194.46.170] mod_fcgid: stderr: PHP Fatal error:  Trait 'WebSharks\\CometCache\\Pro\\Traits\\Plugin\\WcpSettingUtils' not found in /home/sgnet/public_html/s2m.sitegeeks.net/wp-content/plugins/comet-cache-pro/src/includes/classes/Plugin.php on line 49
[Sat May 21 12:19:29 2016] [warn] [client 69.162.124.236] mod_fcgid: stderr: PHP Fatal error:  Trait 'WebSharks\\CometCache\\Pro\\Traits\\Plugin\\WcpPostUtils' not found in /home/sgnet/public_html/s2m.sitegeeks.net/wp-content/plugins/comet-cache-pro/src/includes/classes/Plugin.php on line 47
[Sat May 21 12:19:09 2016] [warn] [client 69.162.124.236] mod_fcgid: stderr: PHP Fatal error:  Trait 'WebSharks\\CometCache\\Pro\\Traits\\Plugin\\WcpHomeBlogUtils' not found in /home/sgnet/public_html/s2m.sitegeeks.net/wp-content/plugins/comet-cache-pro/src/includes/classes/Plugin.php on line 41
[Sat May 21 12:18:09 2016] [warn] [client 69.162.124.236] mod_fcgid: stderr: PHP Fatal error:  Trait 'WebSharks\\CometCache\\Pro\\Traits\\Plugin\\AdminBarUtils' not found in /home/sgnet/public_html/s2m.sitegeeks.net/wp-content/plugins/comet-cache-pro/src/includes/classes/Plugin.php on line 16
```

Looks like FastCGI?

**Comment by jaswrks** [comment]
> http://s2m.sitegeeks.net/wp-admin/update.php?action=upgrade-plugin&plugin=comet-cache-pro%2Fcomet-cache-pro.php&_wpnonce=561d193fc9&comet_cache_update_pro_version=160521&comet_cache_update_pro_zip=aHR0cHM6Ly9jb21ldGNhY2hlLmNvbS8%2FdHNsPXgyMjBy

@patdumond Removing `&comet_cache_update_pro_zip=aHR0cHM6Ly9jb21ldGNhY2hlLmNvbS8%2FdHNsPXgyMjBy` from this URL gets rid of the 404 error, so there is something on the web server that doesn't like this series of characters. It's most likely Mod Security or a web application firewall of another name that uses similar heuristic rulesets.

> [Sat May 21 12:19:54 2016] [warn] [client 99.194.46.170] mod_fcgid: stderr: PHP Fatal error:  Trait 'WebSharks\CometCache\Pro\Traits\Plugin\WcpUserUtils' not found in /home/sgnet/public_html/s2m.sitegeeks.net/wp-content/plugins/comet-cache-pro/src/includes/classes/Plugin.php on line 55

Thank you. Have you been able to confirm that those files do in fact exist?

**Comment by jaswrks** [comment]
> PHP Warning:  include_once(/srv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/stub.php): failed to open stream: No such file or directory

I haven't been able to reproduce this yet, but I will take a closer look shortly. That file should exist in that location, so I'm curious to see how this happens.

**Comment by patdumond** [comment]
> Thank you. Have you been able to confirm that those files do in fact exist?

Yes. They all exist.

**Comment by raamdev** [comment]
@jaswsinc writes...

> I haven't been able to reproduce this yet, but I will take a closer look shortly. That file should exist in that location, so I'm curious to see how this happens.

My guess is that it has something to do with the old version of Comet Cache being deleted during the update process, and then something (I'm not sure what) leading to a call to `advanced-cache.php`, which will obviously fail when Comet Cache doesn't exist. However, immediately after the latest version of Comet Cache is unpacked and then `advanced-cache.php` loads just fine.

So far I've been able to consistently reproduce this issue on my local dev site (running NGINX + PHP 7) and raam.websharks-inc.net (Apache + PHP 5.5). Both sites have `WP_DEBUG` enabled.

**Comment by raamdev** [comment]
Here's a screencast I did demonstrating the deactivation after Pro update: http://quick.as/k8j5f5xbv

**Comment by raamdev** [comment]
I should add that this error does not _always_ show up when Comet Cache fails to reactivate after a Pro update:

> PHP Warning: include_once(/srv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/stub.php): failed to open stream: No such file or directory

So it could be that it's unrelated and just a red herring.

**Comment by Reedyseth** [comment]
I was not able to reproduce this as well on my live site, it runs **PHP 5.6.14**,**WordPress 4.5.2** and **Apache 2.2.31**, I did:
- Deactivate Comet Cache.
- Delete my v160514-RC version and then update the v160417 version downloaded from here https://cometcache.com/release-archive/
- Install the the version v160417 through the Plugin Dashboard and upload the zip file.
- Run the autoupdate by clicking the green `Update Now` button on the plugin settings.
- Reload the dashboard. Comet Cache is in the latest version.

**Comment by jaswrks** [comment]
> Here's a screencast I did demonstrating the deactivation after Pro update: http://quick.as/k8j5f5xbv

I ran this same test, moving from CC Pro v160417 to v160521 at HostGator. I was unable to reproduce the issue that you're having. I tried it three times and each time it upgraded as expected.

However, I am seeing another (seemingly unrelated) issue at HostGator. It appears that HostGator is having problems connecting to the WordPress.org update server over SSL. 

```
Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /home4/wsksdev/public_html/jason/wp-includes/update.php on line 306
```

I saw that same error on all three attempts and in various places in my Dashboard. It might be related to the ancient version of cURL they are running over there at HostGator, but I thought I'd mention it. Even with this issue though, the CC Pro upgrade went smoothly.

**Comment by jaswrks** [comment]
↑ My last tests were on PHP v7.0.4 @ HostGator by the way.

**Comment by raamdev** [comment]
> However, I am seeing another (seemingly unrelated) issue at HostGator. It appears that HostGator is having problems connecting to the WordPress.org update server over SSL.

I actually noticed that error a few times while running these tests locally (NGINX + PHP 7), but they were never consistent so I assumed they were just the result of temporary connectivity issues. 

> I was unable to reproduce the issue that you're having.

Bummer. That's so strange. I can (relatively) consistently reproduce the issue across three separate hosting platforms (locally, HostGator, and LiquidWeb).

Hmm, now I'm wondering if I might have a browser issue that's causing this. (I can't remember if I tested with another browser.) I'll test another browser now.

**Comment by raamdev** [comment]
> I'll test another browser now.

Well, I'll be. I can't reproduce the problem using Firefox (I was using Chrome before). So it must be a browser issue on my end. 

@websharks/team Ugh. Sorry for the false alarm, but thank you very much for testing.

**Comment by raamdev** [comment]
FYI, I tracked it down to this [WordPress Theme and Plugins detector](https://chrome.google.com/webstore/detail/wordpress-theme-and-plugi/jdflfokckhmchfpokjmpcoblghjngjja) extension that I installed about a week ago.

**Comment by jaswrks** [comment]
Ah. Thanks for the follow-up. Glad you found the underlying problem.

> Ugh. Sorry for the false alarm, but thank you very much for testing.

No problem. Happy to do it.

**Comment by Reedyseth** [comment]
> Well, I'll be. I can't reproduce the problem using Firefox (I was using Chrome before). So it must be a browser issue on my end.

@raamdev just FYI I tested on Chrome without any issue.

**Comment by raamdev** [comment]
@Reedyseth Thanks. Please see my comment above about the browser extension that caused the problem.

**Comment by Reedyseth** [comment]
> Please see my comment above about the browser extension that caused the problem.

haha :smile_cat: I just saw that, my bad !
