### ISSUE TITLE
Incorrect Directory and File Permissions for C. Cache 650251

### ISSUE THREAD

**Issue by VR51** [wpsharks/comet-cache#773]
The download package for the latest release of Comet Cache Pro (v. 650251) has incorrect directory and file permissions. The directory permissions are set to 777 (should be 755) and files are set to 666 (should be 644). Package downloaded from the Comet Cache website. Just letting you know.

**Comment by raamdev** [comment]
@VR51 Thank you for the heads up! This has been fixed.
