### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by bobo1** [wpsharks/comet-cache#778]
This is becoming a bit of nuisance. We have almost 100 sites now using Comet Cache. Plugin updates on all sites are handled via managewp - allowing us to update all sites at once. Your plugin requires actual going the admin panel and activating an update. This is ridiculous! You need to come up with a compatible method of the standard Wordpress updating...

**Comment by raamdev** [comment]
@bobo1 Are you using Comet Cache Pro or Comet Cache Lite?

**Comment by bobo1** [comment]
Pro

John Phipps
RADX Corporation
972-422-9903
www.roadhog.com http://www.roadhog.com/

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. If the reader of this message is not the intended recipient, you are hereby notified that your access is unauthorized, and any review, dissemination, distribution or copying of this message including any attachments is strictly prohibited. If you are not the intended recipient, please contact the sender and delete the material from any computer or mobile device.

**Comment by raamdev** [comment]
@bobo1 In that case, please see this GitHub issue that is already open to add Pro Updater compatibility for ManageWP: https://github.com/websharks/comet-cache/issues/465

I'll see if we can work that into the current development cycle for the next release.
