### ISSUE TITLE
Excluding inline JS snippets setting not working.

### ISSUE THREAD

**Issue by joeldbirch** [wpsharks/comet-cache#779]
When I select "No, do not compress inline JavaScript snippets" it has no effect. I still need to add exclusion patterns to exclude them one by one. Anyone else seeing this?

**Comment by raamdev** [comment]
@joeldbirch Can you give us an example? Perhaps copy/paste the part of your page source code that you're expecting Comet Cache to exclude? Or if you could provide us with a link to the page, that would work too.

**Comment by ghost** [comment]
Think i might be having the same issue, have opened a separate ticket about mine.

**Comment by raamdev** [comment]
@adster85 You did not mention anything about using the exclusion patterns in https://github.com/websharks/comet-cache/issues/809, so I'm not sure how this issue seems related. Could you elaborate?

**Comment by raamdev** [comment]
Closing due to lack of feedback.
