### ISSUE TITLE
Feature Request: Link "Cache Stats" button in Admin Bar to the Cache Stats page

### ISSUE THREAD

**Issue by Presskopp** [wpsharks/comet-cache#780]
![dashstatslink](https://cloud.githubusercontent.com/assets/18373563/15556157/cb7d065c-22cc-11e6-9a97-0ce41323b9cb.jpg)

It's more an idea than a feature request.. :)

If you click on 'Cache Stats' in Adminbar, why not end up here?
/wp-admin/admin.php?page=comet_cache

After talking to @raamdev  I just drop it here.

**Comment by raamdev** [comment]
@Presskopp Thank you for opening a GitHub issue. :-) 

I think it would make more sense for that to link to the Comet Cache Stats page:
`wp-admin/admin.php?page=comet_cache-stats`

Note that the Cache Stats panel that opens up includes a "More Info" button at the bottom, which _does_ link to the Cache Stats page, however I agree that it makes sense to also link the "Cache Stats" at the top to this page.

![2016-05-26_14-15-27](https://cloud.githubusercontent.com/assets/53005/15585236/68d6b072-234c-11e6-9451-921dd801e685.png)

**Comment by Presskopp** [comment]
First: Sorry, just a typo I have here, always talking about `wp-admin/admin.php?page=comet_cache-stats`

Nothing more to say here but Thank you.

**Comment by raamdev** [comment]
Next Release Changelog:
- **UI Enhancement** (Pro): The "Cache Stats" button in Admin Bar is now linked to the Cache Stats page. Instead of hovering over the button and then clicking "More Info" inside the popup panel, you can now just click the "Cache Stats" button to go directly to the Cache Stats page. Props @Presskopp, @renzms. See [Issue #780](https://github.com/websharks/comet-cache/issues/780).

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#780).
