### ISSUE TITLE
Webserver-only caching

### ISSUE THREAD

**Issue by szepeviktor** [wpsharks/comet-cache#782]
Do you plan to support HTML-only caching (without starting PHP)?

**Comment by jaswrks** [comment]
@szepeviktor Yep. Take a look here: https://github.com/websharks/comet-cache/issues/134

**Comment by jaswrks** [comment]
Closing this in favor of https://github.com/websharks/comet-cache/issues/134

**Comment by raamdev** [comment]
@szepeviktor I think @jaswsinc meant https://github.com/websharks/comet-cache/issues/783.
