### ISSUE TITLE
Installing Comet Cache on site with PHP < 5.3 causes fatal error

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#784]
PHP 5.3 is the version where the `__DIR__` magic constant was introduced. The `comet-cache.php` file, which is the very first thing loaded when you install Comet Cache, loads the `plugin.php`, but it does so using a magic constant to figure out the full path to that file:

``` php
require_once __DIR__.'/plugin.php';
```

While Comet Cache requires PHP 5.4+ and there's [a version check](https://github.com/websharks/comet-cache/blob/160521/plugin.php) that prevents Comet Cache from crashing when you're running something older than PHP 5.4, that version check happens inside `plugin.php`, which is too late to catch the fact that the `__DIR__` magic constant might cause a fatal error if you try installing on something older than PHP 5.3.

A review of [`plugin.php`](https://github.com/websharks/comet-cache/blob/160521/plugin.php) reveals also reveals that it would cause fatal errors on a site running PHP < 5.3, as there are many uses of `__DIR__` in there. 

I suggest that we make `comet-cache.php` and `plugin.php` as backwards compatible as possible. It would be a lot more desirable to show a proper "Requires PHP 5.4+" message than to generate a fatal error. Any uses of `__DIR__` can be replaced with `dirname(__FILE__)`, which should work back to PHP 5.0.

---

Reported here: https://wordpress.org/support/topic/error-when-enabling-plugin-1?replies=5#post-8501791

**Comment by Presskopp** [comment]
Worth mentioning that WP itself requires PHP 5.6 (or higher), so anybody installing it on lower versions is playing with fire anyway.
https://wordpress.org/about/requirements/

**Comment by raamdev** [comment]
@Presskopp WordPress does not _require_ PHP 5.6 or higher, it simply recommends it. WordPress still runs on PHP 5.2.4. See the following from the page you linked to:

> Note: If you are in a legacy environment where you only have older PHP or MySQL versions, WordPress also works with PHP 5.2.4+ and MySQL 5.0+, but these versions have reached official End Of Life and as such may expose your site to security vulnerabilities.

**Comment by Presskopp** [comment]
You're right. It's still riding a dead horse :)

**Comment by raamdev** [comment]
Next Release Changelog:
- **PHP Compatibility:** Improved compatibility back to PHP 5.2 (the lowest version allowed by WordPress). Comet Cache still requires PHP 5.4+, but if you install Comet Cache on a site running PHP 5.2, it will now fail gracefully with a Dashboard notice indicating PHP 5.4+ is required, instead of producing a fatal error. See [Issue #784](https://github.com/websharks/comet-cache/issues/784).

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#784).
