### ISSUE TITLE
Comet Cache Pro Visual Composer Post Grid bug

### ISSUE THREAD

**Issue by mennobouma** [wpsharks/comet-cache#785]
Hi Websharks,

Thanks for this great plugin. Almost everything works fine for me, except one thing. I'm running into a issue with the Visual Composer plugin and elements like the Post Grid where it uses Ajax and nonces with 24 hour lifetime. The problem also mentioned here: http://www.wpfastestcache.com/features/visual-composer-post-grid-problem/.

I need my cache to stay 'alive' for longer than 24 hours and after 1 day the Post Grid from VC disappears because of the cache. Any idea how to solve this, except set the cache lifetime to 24 hours?

Thanks, Menno

**Comment by raamdev** [comment]
@mennobouma Thanks for the report. We have an existing GitHub issue already open for Visual Composer Post Grid compatibility; please see https://github.com/websharks/comet-cache/issues/673. I'm going to close this issue in favor of https://github.com/websharks/comet-cache/issues/673.
