### ISSUE TITLE
Gain Control of `.htaccess` Tweaks Order

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#791]
@raamdev I just wanted to suggest that we alter the iteration of `.htaccess` tweaks just a bit so that we can gain control over the order in which they are applied to the `.htaccess` file.

I worked on this a bit in `feature/sonic-boom` as seen here by example.
https://github.com/websharks/comet-cache-pro/pull/165/files#diff-9c436c451e7c22ab8953f50e98f9b793R36

**Comment by jaswrks** [comment]
Notice that I used a custom array filled with the templates I wanted to iterate (in a specific order), instead of using `scandir()`.

**Comment by raamdev** [comment]
@jaswsinc Ah, nice. I like that idea. I'll work that into the work I'm doing on https://github.com/websharks/comet-cache-pro/pull/260 before the RC later today. Thanks!

**Comment by raamdev** [comment]
@jaswsinc Fixed via https://github.com/websharks/comet-cache-pro/commit/9d076abf36411c3bbb0e7348d172e6cf5e3e684e.
