### ISSUE TITLE
AutoCache: PHP Fatal error

### ISSUE THREAD

**Issue by peter-fb** [wpsharks/comet-cache#795]
After upgrading to Comet Cache Pro v160706 I get this error:

[09-Jul-2016 10:17:32 UTC] PHP Fatal error:  Call to undefined method WebSharks\CometCache\Pro\Classes\AutoCache::applyWpFilters() in /home/user/addon/domain-name.at/wp-content/plugins/comet-cache-pro/src/includes/classes/AutoCache.php on line 265

My PHP version is 
PHP 5.6.23 (cli) (built: Jun 24 2016 07:07:36)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.1.1, Copyright (c) 2002-2016, by ionCube Ltd.

I don't experience the error with v160521.

**Comment by raamdev** [comment]
@Peter-FB Thank you for the report! I have confirmed this is a bug. I'll be merging a patch shortly (see https://github.com/websharks/comet-cache-pro/issues/268) and will do a Comet Cache Pro maintenance release today as well.

**Comment by peter-fb** [comment]
@raamdev Thank you, I applied the changes to my installation and it works! :)

**Comment by raamdev** [comment]
Next Release Changelog:
- **Bug Fix** (Pro): Fixed a bug in the Auto-Cache Engine that was introduced by the previous release (v160706). The bug produced an error whenever the Auto-Cache Engine ran: "PHP Fatal error: Call to undefined method applyWpFilters()". This had no visible affect on the front-end of the site or in the WordPress Dashboard, but it prevented the Auto-Cache Engine from working behind the scenes. Props @Peter-FB for reporting. See [Issue #795](https://github.com/websharks/comet-cache/issues/795).

**Comment by raamdev** [comment]
**Comet Cache v160709** has been released and includes changes from this GitHub Issue. See the [v160709 announcement](https://cometcache.com/blog/comet-cache-pro-v160709-maintenance-release/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#795).
