### ISSUE TITLE
3rd Party Plugin Compatibility: Ultimate Member

### ISSUE THREAD

**Issue by LouiByrdziak** [wpsharks/comet-cache#800]
Hi team comet!

I have been a happy customer for almost 2 years. However, I have recently installed Ultimate Member plugin, and Comet Cache STOPPED working.

Please see my attached screenshot.

Thanks,

Loui
loui.rrokk@gmail.com
![comet cache problem 4](https://cloud.githubusercontent.com/assets/6117222/16715505/bbf694f8-4696-11e6-9363-eb9b433da285.png)

**Comment by raamdev** [comment]
@LouiByrdziak Thank you for the report. I'll label this as something that needs testing and research.

**Comment by LouiByrdziak** [comment]
Raam,

I figure it out! Comet Cache and Ultimate Member work great now. I'll send
you the important configuration details in a few days.

Loui
