### ISSUE TITLE
Code size

### ISSUE THREAD

**Issue by szepeviktor** [wpsharks/comet-cache#801]
Is there a way to _optionally_ avoid loading total of 1 047 296 bytes byte code (opcache)?

/index.php
/wp-blog-header.php
/wp-load.php
/wp-config.php
/wp-settings.php
/wp-includes/load.php
/wp-includes/default-constants.php
/wp-includes/version.php
/wp-content/advanced-cache.php

/wp-content/plugins/comet-cache/src/includes/stub.php
/wp-content/plugins/comet-cache/src/vendor/autoload.php
/wp-content/plugins/comet-cache/src/vendor/composer/autoload_real.php
/wp-content/plugins/comet-cache/src/vendor/composer/ClassLoader.php
/wp-content/plugins/comet-cache/src/vendor/composer/autoload_namespaces.php
/wp-content/plugins/comet-cache/src/vendor/composer/autoload_psr4.php
/wp-content/plugins/comet-cache/src/vendor/composer/autoload_classmap.php
/wp-content/plugins/comet-cache/src/includes/functions/i18n-utils.php
/wp-content/plugins/comet-cache/src/includes/classes/AdvCacheBackCompat.php
/wp-content/plugins/comet-cache/src/includes/classes/AdvancedCache.php
/wp-content/plugins/comet-cache/src/includes/classes/AbsBaseAp.php
/wp-content/plugins/comet-cache/src/includes/classes/AbsBase.php
/wp-content/plugins/comet-cache/src/includes/interfaces/Shared/NcDebugConsts.php
/wp-content/plugins/comet-cache/src/includes/interfaces/Shared/CachePathConsts.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/BlogUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/CacheDirUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/CacheLockUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/CachePathUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/ConditionalUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/DomainMappingUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/EscapeUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/FsUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/HookUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/HttpUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/I18nUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/IpAddrUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/PatternUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/ReplaceUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/ServerUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/StringUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/SysUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/TokenUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/TrimUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Shared/UrlUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Ac/AbortUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Ac/AcPluginUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Ac/ClientSideUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Ac/NcDebugUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Ac/ObUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Ac/PostloadUtils.php
/wp-content/plugins/comet-cache/src/includes/traits/Ac/ShutdownUtils.php
/wp-content/plugins/comet-cache/src/includes/functions/wp-cache-postload.php

**Comment by szepeviktor** [comment]
I must admit it is not slow on my dev box (PHP 5.6)

```
# time wget -q -S -O /dev/null http://subtwo.wp/
  HTTP/1.1 200 OK
  Date: Sun, 10 Jul 2016 19:26:19 GMT
  Server: Apache/2.4.20 (Debian)
  Expires: Wed, 11 Jan 1984 05:00:00 GMT
  Cache-Control: no-cache, must-revalidate, max-age=0
  Pragma: no-cache
  Link: <http://subtwo.wp/wp-json/>; rel="https://api.w.org/"
  Vary: Accept-Encoding
  X-UA-Compatible: IE=edge
  X-Content-Type-Options: nosniff
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
  Transfer-Encoding: chunked
  Content-Type: text/html; charset=UTF-8

real    0m0.013s
user    0m0.004s
sys     0m0.000s
```

**Comment by raamdev** [comment]
@szepeviktor You _want_ things loaded in the opcache to make PHP run faster—that's what the OPCache is for. If you don't want to use the OPCache, I suggest disabling it in your PHP configuration.

**Comment by szepeviktor** [comment]
Ok-Ok.
I am already using opcache. Those bytes above are opcache bytes.
Would it be possible - while using opcache - to execute less code to get an HTML page?

**Comment by raamdev** [comment]
@szepeviktor Comet Cache already handles that by generating a cache file for the page. Once the cache file is generated, future requests to that page do not require loading all of WordPress for each request. Instead, only the (HTML) cache file is loaded.

**Comment by szepeviktor** [comment]
> Instead, only the (HTML) cache file is loaded.

No.

The [above files](https://github.com/websharks/comet-cache/issues/801#issue-164729689) are loaded for each HTTP request. ~ 1 MB of opcache byte code.

**Comment by raamdev** [comment]
@szepeviktor Yes, those are the files required for Comet Cache to load the cache. Keep in mind that the 1MB opcache is not _reloaded_ with each request; once the byte code for those files is cached, the same 1MB opcache is reused by each request. If you want to skip PHP altogether, that will require something like Apache's ModRewrite (see https://github.com/websharks/comet-cache/issues/783).

**Comment by szepeviktor** [comment]
OK-OK.
I am just wondering what percentage is actually executed of that 1 MB byte code.
I don't have anything against PHP but I would consider conditional loading of those traits.

**Comment by jaswrks** [comment]
Very, very little. This is mostly about a loading sequence in WordPress and having all the libraries needed to handle various scenarios in code. In a typical request that is already cached, several files are loaded in sequence, but the PHP routines are brought down to an absolute minimum needed to serve the request, which is why we are able to achieve the speeds that we have.

**Comment by szepeviktor** [comment]
> Very, very little.

I see.
Would it be possible to not include those PHP classes/traits not running?
