### ISSUE TITLE
Pro upgrade notice is not dismissed when upgrading via FTP

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#806]
If you upgrade Comet Cache Pro via FTP, the Dashboard notice that announces a new version is available does not get automatically dismissed. 

![2016-07-12_16-53-07](https://cloud.githubusercontent.com/assets/53005/16783224/2af9e614-4851-11e6-9599-d4f98837a76b.png)

There needs to be a routine that dismisses any upgrade notice if the current version installed is detected as the latest version.

**Comment by jaswrks** [comment]
Estimate .25 days.

**Comment by jaswrks** [comment]
Related comment: https://github.com/websharks/comet-cache/issues/829#issuecomment-252807069

**Comment by jaswrks** [comment]
Next Release Changelog:
- **Bug Fix:** Automatically dismiss any persistent update notifications whenever a new version of the software is recompiled; i.e., don't continue to show an upgrade notice whenever the software has just been updated by a site owner. See also: [issue #806](https://github.com/websharks/comet-cache/issues/806) if you'd like additional details.

**Comment by jaswrks** [comment]
_Noting also that these update notifications that are being cleared no longer exist in the current release of the software. The automatic clearing of these persistent notifications is to clear them on old installations of Comet Cache._

**Comment by renzms** [comment]
@jaswsinc 

![screen shot 2016-11-13 at 7 05 23 pm](https://cloud.githubusercontent.com/assets/13220018/20245124/299ff8cc-a9d5-11e6-9d01-cee244c198d3.png)

Built from the current `dev` branch and ran `phing -D project_version=160701 full-build-all` to backdate, but no `update available` shows in the header. Is this the correct way to test this?

**Comment by jaswrks** [comment]
@renzms You'd need to actually install one of the older builds where that notification was posted to the Dashboard. The newer builds, like those from the `dev` branch, don't do this, even if you backdate the build. It's still from the newer source code that doesn't post that notice.

**Comment by renzms** [comment]
@jaswsinc 

Thanks! 

@raamdev 

## Confirmed working in Comet Cache v161116-RC / Pro

Tested using Comet Cache 160412 / Pro and upgraded via FTP using Comet Cache v161116-RC / Pro. Update notice is removed after uploading via FTP.

![screen shot 2016-11-16 at 10 25 13 pm](https://cloud.githubusercontent.com/assets/13220018/20350999/02f600a8-ac4c-11e6-85e9-4b9ae777ff9b.png)

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#806).
