### ISSUE TITLE
Pro Preview Option Panel labels are not translatable

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#808]
The "Pro Version Only" and "Additional Pro Features" labels that get added to option panels when the Pro Preview is enabled are not translatable: 

![cc-preview](https://cloud.githubusercontent.com/assets/53005/16895451/8e5776ae-4b44-11e6-871f-7c99133e0186.jpg)

That's because those labels are set via CSS:
- https://github.com/websharks/comet-cache-pro/blob/160709/src/client-s/css/menu-pages/_panels.scss#L64
- https://github.com/websharks/comet-cache-pro/blob/160709/src/client-s/css/menu-pages/_panels.scss#L48

We need to move those into [`MenuPageOptions.php`](https://github.com/websharks/comet-cache-pro/blob/160709/src/includes/classes/MenuPageOptions.php) so that they can be translated.

---

Reported by @Presskopp.

**Comment by jaswrks** [comment]
Estimate at .5 days.

**Comment by jaswrks** [comment]
Next Release Changelog:
- **i18n Compat.** This release makes all pro preview labels translatable by moving the labels that were previously defined in CSS only into HTML attribute values. See [issue #808](https://github.com/websharks/comet-cache/issues/808) if you'd like additional details.

**Comment by renzms** [comment]
@raamdev 

## Confirmed Working

The HTML values can now be translated/modified for the Pro Preview Option panels

![screen shot 2016-11-16 at 11 42 11 pm](https://cloud.githubusercontent.com/assets/13220018/20353591/57a7ded2-ac56-11e6-8c6a-f8c85fe53a40.png)

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#808).
