### ISSUE TITLE
JS broken

### ISSUE THREAD

**Issue by ghost** [wpsharks/comet-cache#809]
I use a tooltip,js file, and after the latest update to comet cache pro. The JS overlay doesnt work, and is broken. I have had to disable the plugin to get it back to functionality.

I literally havent changed any of the settings, only enabled comet cache pro and selected yes.

Happy to provide my JS code for tooltip,js

**Comment by raamdev** [comment]
@adster85 Are you using the Comet Cache HTML Compressor? If so, does disabling it fix the issue?

**Comment by ghost** [comment]
No HTML compressor is active, i disabled the plugin and my tooltips loaded fine. Re-enabled it, and they didn't work again.

Its serving my tooltip PHP files as a separate page, instead of an overlay. This was working fine before the recent two updates, since then it has been broken. I have had to disable the plugin, as it is affecting my business and i am loosing sales.

I have previously asked for a refund of this plugin due to a lot of bugs, but no-one would give me one!

**Comment by raamdev** [comment]
> No HTML compressor is active

So you're saying that the HTML Compressor IS active? If it is active, have you tried running Comet Cache with the HTML Compressor **disabled** to see if that fixes the issue with the tooltips?

**Comment by ghost** [comment]
should have said isnt \* Auto correct on mobiles is a pain!

**Comment by raamdev** [comment]
@adster85 Can you send me the JS with instructions for how you're implementing it so that I can attempt to reproduce the problem?
