### ISSUE TITLE
Pages not cached under FlatSOME theme, and there is not such plugin Akismet ON.

### ISSUE THREAD

**Issue by uhlhosting** [wpsharks/comet-cache#813]
`<!-- Comet Cache is NOT caching this page, because the current page contains`_wpnonce`or`akismet_comment_nonce`. Note that`_nonce_`values in the markup are not cache-compatible. See http://wsharks.com/1O1Kudy for further details. -->`

**Comment by uhlhosting** [comment]
page here: https://www.tabaklaedeli.ch/

**Comment by raamdev** [comment]
@highacid Search your page source for `wpnonce`; you'll find that on the page. See [this article](http://wsharks.com/1O1Kudy) for details. 

---

We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://www.websharks-inc.com/support/?product=comet-cache&request_type=trouble_ticket) (Comet Cache Pro). Thank you! :)
