### ISSUE TITLE
Dynamic Woocommerce shopping cart not working

### ISSUE THREAD

**Issue by mennobouma** [wpsharks/comet-cache#819]
Hi @raamdev, 

I'm using a dynamic shopping cart in my Woocommerce shop and i doesn't work well with Comet Cache Pro. I think it's caused by session caching. Can it be solved by something like this: https://sub-q-subqmagazine.netdna-ssl.com/wp-content/uploads/2015/08/woocommerce-w3-total-cache-not-working-database-cache.png

Thanks, Menno

**Comment by raamdev** [comment]
@mennobouma Comet Cache does not do any database caching, so the screenshot you linked to wouldn't apply here.

> I'm using a dynamic shopping cart in my Woocommerce shop and i doesn't work well with Comet Cache Pro

Can you explain in a bit more detail what's not working well? We've tested Comet Cache with WooCommerce and it seems to work well.

**Comment by raamdev** [comment]
Closing due to lack of feedback.
