### ISSUE TITLE
Auto clean on edit a post did not work

### ISSUE THREAD

**Issue by rottmann** [wpsharks/comet-cache#820]
Tested in pro an non-pro with default installation settings (cache enabled).

Default post type, no custom post,  use only CMB2 to extend some fields.

**Comment by raamdev** [comment]
@rottmann I just tested this and it's working as expected:

![2016-08-19_15-50-37](https://cloud.githubusercontent.com/assets/53005/17822359/b498340c-6624-11e6-9808-6c4b075676e6.png)

Please see [Testing Comet Cache in a Clean WordPress Installation](https://cometcache.com/kb-article/testing-comet-cache-in-a-clean-wordpress-installation/).
