### ISSUE TITLE
Enable nonces for logged in user

### ISSUE THREAD

**Issue by uhlhosting** [wpsharks/comet-cache#821]
I did the steps as in documentation site is still reporting the 

`<!-- Comet Cache is NOT caching this page, because the current page contains`_wpnonce`or`akismet_comment_nonce`. Note that`_nonce_`values in the markup are not cache-compatible. See http://wsharks.com/1O1Kudy for further details. -->`

**Comment by raamdev** [comment]
@highacid We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://www.websharks-inc.com/support/?product=comet-cache&request_type=trouble_ticket) (Comet Cache Pro). Thank you! :)
