### ISSUE TITLE
Gzip conflict with TM STORE

### ISSUE THREAD

**Issue by matteoraggi** [wpsharks/comet-cache#822]
If I activate the gzip compression the plugin crash,disable by itself and the app is not working to with TM STORE https://wordpress.org/plugins/tm-store-pure-native-mobile-app-for-free-ios-android/ .
my website is https://spesagodina.it/web/

**Comment by raamdev** [comment]
@matteoraggi This looks like a problem with the TM Store plugin and not Comet Cache. When you enable GZIP Compression in Comet Cache, all that's happening is your `.htaccess` file is being updated with the following configuration:

``` htaccess
# Enable GZIP compression.
<IfModule deflate_module>
  <IfModule filter_module>
    AddOutputFilterByType DEFLATE text/plain text/html
    AddOutputFilterByType DEFLATE text/xml application/xml application/xhtml+xml application/xml-dtd
    AddOutputFilterByType DEFLATE application/rdf+xml application/rss+xml application/atom+xml image/svg+xml
    AddOutputFilterByType DEFLATE text/css text/javascript application/javascript application/x-javascript
    AddOutputFilterByType DEFLATE font/opentype application/font-otf application/x-font-otf
    AddOutputFilterByType DEFLATE font/truetype application/font-ttf application/x-font-ttf
  </IfModule>
</IfModule>
```

There is nothing unusual about this `.htaccess` configuration—it is the configuration recommended by most web hosting companies. The fact that the TM Store breaks only when GZIP Compression is enabled tells me there's a problem with the TM Store plugin. I recommend contacting the plugin developer and letting them know about this.

If you find that Comet Cache is somehow to blame here, please let me know and I'll take a closer look.

**Comment by matteoraggi** [comment]
they just told me that they have problems with every caching system. So I solved the problem exluding them referrers from caching and now it is all right, yeah!
