### ISSUE TITLE
HTML CSS JS minify and others

### ISSUE THREAD

**Issue by MahrUK** [wpsharks/comet-cache#823]
Dear Support 

I have purchased Comet Cache™ pro and enabled Enable WebSharks™ HTML Compression

all the options under this its not working; can you please look into this?
regards 
Humaira

**Comment by raamdev** [comment]
@MahrUK We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://www.websharks-inc.com/support/?product=comet-cache&request_type=trouble_ticket) (Comet Cache Pro). Thank you! :)
