### ISSUE TITLE
Automatic Clear Cache routines are too aggressive for options-general.php

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#825]
Comet Cache automatically [clears the entire cache](https://github.com/websharks/comet-cache-pro/blob/160709/src/includes/traits/Plugin/WcpSettingUtils.php#L27-L29) whenever `options-general.php?settings-updated=true` is detected. This is meant to detect when Settings → General is being saved, since any changes there _should_ result in a full clearing of the cache. 

The problem with this is that other plugins may use `options-general.php`, as demonstrated in [`add_options_page()` on the WordPress Codex](https://codex.wordpress.org/Function_Reference/add_options_page), to create a plugin options page in the Settings section:

![2016-09-02_15-17-17](https://cloud.githubusercontent.com/assets/53005/18215685/667e5a24-7120-11e6-9084-12132f4f08dd.png)

The plugin options page URL would then end up being something like `options-general.php?page=autoptimize`. Whenever the settings for that plugin are saved, **even if the plugin doesn't affect anything on the front-end of the site**, Comet Cache will automatically clear the entire cache because it assumes that a core WP setting is being changed (`options-general.php?page=autoptimize&settings-updated=true` is called, and Comet Cache makes no consideration for the `?page` query var). 

While it might make sense to assume that saving the settings for _any_ plugin that uses `options-general.php` should result in the cache being cleared, my feeling is that it would be better for that to be handled on a case-by-case basis, i.e., if a plugin affects the front-end of the site, it should either integrate with caching plugins, or Comet Cache should have specific support for detecting when the settings are saved (such as has been done with bbPress, BuddyPress, Comment Mail, and WooCommerce).
## How this can be improved

Comet Cache should check if the `?page` query var is present when the settings are being saved via `options-general.php`. If the `?page` query var is NOT present, that indicates that the options for Settings → General are being saved. Otherwise, it indicates that another plugin is utilizing `options-general.php` and we should skip auto-clearing the cache in that scenario.

---

Noting that this was originally reported by Frank Goossens (@futtta) of Autoptimize.

**Comment by raamdev** [comment]
Next Release Changelog:
- **Compatibility / Bug Fix**: The automatic Clear Cache routines that cleared the entire cache automatically whenever _WordPress Dashboard → Settings → General_ was updated, were being too aggressive and not taking into consideration other plugins that might also be using the same `options-general.php` URL. As a result, the entire cache was being unnecessarily cleared when the settings for those other plugins were saved. Props to @futtta from Autoptimize for reporting. See [Issue #825](https://github.com/websharks/comet-cache/issues/825).

**Comment by jaswrks** [comment]
> Comet Cache should check if the ?page query var is present when the settings are being saved via options-general.php. If the ?page query var is NOT present, that indicates that the options for Settings → General are being saved. Otherwise, it indicates that another plugin is utilizing options-general.php and we should skip auto-clearing the cache in that scenario.

Agree.

**Comment by raamdev** [comment]
**Comet Cache v160917** has been released and includes changes from this GitHub Issue. See the [v160917 announcement](https://cometcache.com/blog/comet-cache-v160917-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#825).
