### ISSUE TITLE
Feature Request: Automatic Background Updates

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#827]
In https://github.com/websharks/comet-cache/issues/289 we made Comet Cache Pro compatible with [WordPress Automatic Background Updates](https://codex.wordpress.org/Configuring_Automatic_Background_Updates#Plugin_.26_Theme_Updates_via_Filter). Now we just need an option to enables this by default, and allows a site owner to disable it (instead of requiring a filter). The [WordPress Codex page](https://codex.wordpress.org/Configuring_Automatic_Background_Updates#Plugin_.26_Theme_Updates_via_Filter) explains how `auto_update_plugin` can be filtered to achieve this.

![2016-09-06_23-52-53](https://cloud.githubusercontent.com/assets/53005/18299222/109003cc-748d-11e6-87df-51ec68953aca.png)

```
<h3>Automatic Background Updates</h3>
<input type="radio" name="" value="1" checked="checked" id=""> On&nbsp;&nbsp;
<input type="radio" name="" value="0" id=""> Off <br>
<p>Set this to ON to allow Comet Cache Pro to download and install bug fixes and security updates automatically in the background. Requires a valid license key.</p>
<hr>
```

**Comment by jaswrks** [comment]
Also referencing: https://wordpress.org/plugins/automatic-plugin-updates/screenshots/

**Comment by raamdev** [comment]
Noting that this feature should be _disabled_ by default, so that site owners can then opt-in to automatic updates if they so choose.

**Comment by jaswrks** [comment]
Noting that I went with a dropdown menu for consistency with the rest of Comet Cache.

![2016-12-08_02-38-43](https://cloud.githubusercontent.com/assets/1563559/21009231/fbd024dc-bcf1-11e6-99f2-111c1dd1a053.png)

**Comment by raamdev** [comment]
**Comet Cache v161221** has been released and includes changes from this GitHub Issue. See the [v161221 announcement](https://cometcache.com/blog/comet-cache-v161221-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#827).
