### ISSUE TITLE
"Update Available" shows in header but no update shows in Plugin updater

### ISSUE THREAD

**Issue by renzms** [wpsharks/comet-cache#829]
While testing the new features: ManageWP Compatibility + Automatic Updates (see: [Comet Cache v160908-RC (Release Candidate)](https://cometcache.com/blog/comet-cache-v160908-rc-release-candidate/), I observed an inconsistency with the update notifications. In the Plugin Options of Comet Cache Pro the header would say **update available**, but no update for the plugin would show in the Plugin updater list. By extension, it did not appear in the ManageWP Dashboard for list of Plugins to be updated.
## Steps to reproduce:
- Make sure your existing WP installation does not have Comet Cache Pro 160908-RC settings saved. If so, please disable Plugin Deletion Safeguard Options to wipe settings upon deletion.
- Checkout `release/160908` Comet Cache Pro branch, then run `phing -D project_version=160701 full-build-all`
- Upload and install `Comet Cache Pro v160701`
- Wait a few moments before adding the **Update Credentials** after installing and activating the plugin.
## Observed Behavior:
- In the header for Comet Cache Pro, it will indicate an update is available, (`v160709`).

**"Update Available" in header:**
![screen shot 2016-09-14 at 6 50 17 am](https://cloud.githubusercontent.com/assets/13220018/18495752/f984a40a-7a52-11e6-975c-bae7672cfd06.png)
- In the plugins list, it will not indicate any available update

**No update in Plugins list**
![screen shot 2016-09-14 at 7 56 44 am](https://cloud.githubusercontent.com/assets/13220018/18495758/022cab0c-7a53-11e6-9328-ebf4ba3b027b.png)
- In ManageWP the plugins update list does not show Comet Cache Pro with any available update

**ManageWP Dashboard:**
![screen shot 2016-09-14 at 7 35 38 am](https://cloud.githubusercontent.com/assets/13220018/18495949/4a89f746-7a54-11e6-896e-4f74312c38f9.png)
- Forcing WordPress to `Check Again` via the Updates list would sometimes cause it to trigger the update, other times not
- Waiting exactly **1 hr**, will trigger the update in the Plugins list if it doesn't initially appear after installation.
## Expected behavior:
- Comet Cache should show update available in header, Plugins list, and ManageWP Dashboard.

![2016-09-13_19-38-00](https://cloud.githubusercontent.com/assets/13220018/18495991/9c21fb4e-7a54-11e6-8ed1-6632d9dc71be.png)

![screen shot 2016-09-14 at 8 23 56 am](https://cloud.githubusercontent.com/assets/13220018/18496036/f9d77c82-7a54-11e6-80bc-c3ac7c7c7082.png)

**Comment by raamdev** [comment]
I suggest that we simply remove the "(update available)" from the plugin options menu to resolve this issue. Now that we're integrating with the WordPress Update mechanism, there are already plenty of places that will indicate an update is available. I don't think it's necessary to also show it on the plugin options page.

**Comment by jaswrks** [comment]
Next Release Changelog:
- **UI Enhancement:** Following improvements to the update API in a previous release of Comet Cache that made it possible to update both the lite and pro versions of the software through normal WordPress update mechanisms, this release removes some clutter from the menu pages for Comet Cache. In short, now that we have a tighter integration with WordPress core, it's no longer necessary for Comet Cache to display update notifications in a custom way. See also [issue #829](https://github.com/websharks/comet-cache/issues/829) for further details.

**Comment by renzms** [comment]
@jaswsinc 

Attempted testing this, see comment [here](https://github.com/websharks/comet-cache/issues/806#issuecomment-260179698)

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#829).
