### ISSUE TITLE
Chart.js should not be enqueued in Lite version

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#830]
In Comet Cache v160917 we [included](https://github.com/websharks/comet-cache-pro/pull/273) the Clear Cache button in the Admin Toolbar for the Lite version of Comet Cache (previously this was a Pro-only feature). As part of that work, the `Chart.js` was unnecessarily allowed to be included in the Lite verison [here](https://github.com/websharks/comet-cache-pro/blob/160917/src/includes/traits/Plugin/AdminBarUtils.php#L344) and [here](https://github.com/websharks/comet-cache-pro/blob/160917/src/includes/traits/Plugin/MenuPageUtils.php#L39) — this is unncessary as `Chart.js` is only used by the Comet Cache Stats/Charts feature (still a Pro-only feature).

We should avoid enqueueing `Chart.js` in the Lite version not only because it's not being used but because it can cause problems with other plugins that might be using a different version of `Chart.js`, as seen in the report below.

Pär Thernström, plugin author for the [Simple History](https://wordpress.org/plugins/simple-history/) plugin (30k+ active installs) [says](https://wordpress.org/support/topic/comet-cache-breaks-simple-history/#post-8199757):

> Comet Cache uses an older version of the chart.js-library and there is a conflict because of the newer version included in Simple History. This will be fixed in the next version by putting the script used by Simple History in its own namespace.

Note that this has also been cross-referenced [on the Comet Cache support forum](https://wordpress.org/support/topic/chart-js-error/).

**Comment by jaswrks** [comment]
Next Release Changelog:
- **Bug Fix:** Don't enqueue Chart.js unnecessarily in lite version of the sofware. See also: [issue #830](https://github.com/websharks/comet-cache/issues/830) if you'd like additional details.

**Comment by renzms** [comment]
@raamdev 

## Confirmed Working

Chart.js only loaded in the Pro version. 👍 

**PRO:**

> ![screen shot 2016-11-16 at 11 13 40 pm](https://cloud.githubusercontent.com/assets/13220018/20352686/1e919866-ac53-11e6-8022-39c7abf02f16.png)

**LITE:**

> ![screen shot 2016-11-16 at 11 13 28 pm](https://cloud.githubusercontent.com/assets/13220018/20352688/1f83fba6-ac53-11e6-8510-ffa3e4019f6a.png)

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#830).
