### ISSUE TITLE
translate.wordpress.org missing string from /src/includes/traits/Plugin/NoticeUtils.php#L189

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#831]
The translate.wordpress.org site doesn't seem to be picking up the string translated on this line for Comet Cache Lite:
https://github.com/websharks/comet-cache/blob/160917/src/includes/traits/Plugin/NoticeUtils.php#L189

I suspect this is because that translated string contains JavaScript. There's no good reason for the string to contain JavaScript and that could be moved outside of the translation function (`__()`).

**Comment by jaswrks** [comment]
Next Release Changelog:
- **Minor UI Enhancement:** This release improves the toggle link that allows you to see additional details whenever Comet Cache automatically clears more than one facet of the cache. See also [issue #837](https://github.com/websharks/comet-cache/issues/837) and [issue #831](https://github.com/websharks/comet-cache/issues/831) if you'd like additional details.

**Comment by jaswrks** [comment]
![2016-11-08_09-10-22](https://cloud.githubusercontent.com/assets/1563559/20111299/4b07659e-a594-11e6-9238-16e6b8171436.png)

**Comment by renzms** [comment]
@raamdev 

Confirmed minor change is working. 

![screen shot 2016-11-11 at 10 12 26 pm](https://cloud.githubusercontent.com/assets/13220018/20217796/831c0de8-a85c-11e6-8022-c495e936c10d.png)

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#831).
