### ISSUE TITLE
License Code problem on Chrome Browser

### ISSUE THREAD

**Issue by Metacowboy** [wpsharks/comet-cache#832]
the License Code get replaced by Chrome Browser -Autofill 
if the login name for the blog /any site is the same as the plugin login 
Prevent any update on chrome 
Safari Firefox works fine

**Comment by raamdev** [comment]
@Metacowboy Can you confirm you're running the latest version of Comet Cache Pro (v160917)?

We did resolve this issue [back in v160709](https://github.com/websharks/comet-cache/issues/741#issuecomment-225240377), however the latest release (v160917) changed the location of the Update Credentials field and it looks like the `autocomplete="off"` that should go in the `<form>` tag was mistakenly omitted from the latest version.

**Comment by jaswrks** [comment]
Next Release Changelog:
- **Bug Fix:** Avoid browser autocomplete in configuration fields by adding `autocomplete="off"` to all form tags in Comet Cache menu pages. See also: [issue #832](https://github.com/websharks/comet-cache/issues/832) if you'd like additional details.

**Comment by renzms** [comment]
@raamdev 

I can confirm this is working on Chrome. The license field has `<input type=password autocomplete=new-password>`, which prevents the autocomplete. 👍

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#832).
