### ISSUE TITLE
HTML Compression not saving

### ISSUE THREAD

**Issue by juanmrad** [wpsharks/comet-cache#833]
After enabling HTML compression and adding my options. I hit save. when I check back the options it shows as disable. I have WordPress 4.5.3 Nginx server.

**Comment by raamdev** [comment]
@juanmrad I'm unable to reproduce this issue. Please see [Testing Comet Cache in a Clean WordPress Installation](https://cometcache.com/kb-article/testing-comet-cache-in-a-clean-wordpress-installation/).

**Comment by uhlhosting** [comment]
I have the same issues, running apache with nginx, the css and js compression doesnt work in any ways. I know my site uses wpnonce yet this should not affect compression.

**Comment by raamdev** [comment]
@highacid writes...

> the css and js compression doesnt work in any ways

When you say it "doesn't work", do you mean that you're not able to enable it, as the OP explained at the top? Or are you referring to something else?

**Comment by uhlhosting** [comment]
I refer that they are enabled on plugin, yet the test results from pingdom and gtmetrix say the other way

**Comment by raamdev** [comment]
@highacid That's not the same issue as what's described at the top of this GitHub issue. If you're having trouble getting the HTML Compressor to work, please [open a support ticket](https://cometcache.com/support/).

**Comment by juanmrad** [comment]
I updated wordpress and it worked. please close

**Comment by raamdev** [comment]
@juanmrad Thank you for following up. I'll close this.
