### ISSUE TITLE
HTML compression completely ignored

### ISSUE THREAD

**Issue by Helmi** [wpsharks/comet-cache#834]
Comet cache is installed in a multisite with 2 sites. HTML compression is enabled with everything on yes but although pages are cached by comet cache they don't get compressed at all, no minifcation or whatever.

Footer says "Comet Cache fully functional" (sic!) :)

Ideas?

**Comment by raamdev** [comment]
@Helmi I just tested Comet Cache Pro v160917 with the HTML Compressor on WP Multisite and compression works as expected. Please see [Testing Comet Cache in a Clean WordPress Installation](https://cometcache.com/kb-article/testing-comet-cache-in-a-clean-wordpress-installation/). 

Also, we reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://www.websharks-inc.com/support/?product=comet-cache&request_type=trouble_ticket) (Comet Cache Pro). Thank you! :)
