### ISSUE TITLE
"Show details." should be "See details."

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#837]
In the Dashboard notification that indicates the cache has been cleared, the link to view more details should be "See details" and not "Show details", as that goes better with the wording in the message ('show' sounds like we're telling the site owner to do something, as opposed to inviting the site owner to 'see' more details by clicking the link).

![2016-10-03_19-19-20](https://cloud.githubusercontent.com/assets/53005/19057536/88d7a03a-899e-11e6-946e-91aa9fe443c5.png)

**Comment by jaswrks** [comment]
And the link could be a dashed underline instead of a normal underline to help indicate that you're not going to navigate somewhere else, but just toggle something open.

**Comment by jaswrks** [comment]
Next Release Changelog:
- **Minor UI Enhancement:** This release improves the toggle link that allows you to see additional details whenever Comet Cache automatically clears more than one facet of the cache. See also [issue #837](https://github.com/websharks/comet-cache/issues/837) if you'd like additional details.

**Comment by jaswrks** [comment]
![2016-11-08_09-10-22](https://cloud.githubusercontent.com/assets/1563559/20111101/8088b39a-a593-11e6-8801-260ee094d215.png)

**Comment by renzms** [comment]
@raamdev 

I can confirm changes and is showing properly! 👍 

![screen shot 2016-11-11 at 10 12 26 pm](https://cloud.githubusercontent.com/assets/13220018/20217698/fe59a03e-a85b-11e6-884c-af4fc5834541.png)

![screen shot 2016-11-11 at 10 12 19 pm](https://cloud.githubusercontent.com/assets/13220018/20217697/fb0511fc-a85b-11e6-897b-8735ee4c9c70.png)

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#837).
