### ISSUE TITLE
Comet Cashe Pro Adding Spaces in Boilerplate

### ISSUE THREAD

**Issue by e11productions** [wpsharks/comet-cache#840]
We are getting errors from Google. The plugin is adding spaces/linebreaks in areas of the site that it shouldn't. Is there any way to correct this?

The mandatory tag 'head > style[amp-boilerplate]' is missing or incorrect.

https://episode11productions.com

**Comment by raamdev** [comment]
@e11productions Is this referring to the [Wordpress AMP](https://wordpress.org/plugins/amp/) plugin? Are you using Comet Cache Pro with the HTML Compressor? If so, have you seen issue https://github.com/websharks/comet-cache/issues/695?

**Comment by raamdev** [comment]
Closing due to lack of feedback.
