### ISSUE TITLE
MaxCDN Tutorial Link not redirected properly

### ISSUE THREAD

**Issue by kristineds** [wpsharks/comet-cache#842]
In the Comet Cache Dashboard (see: **WordPress Dashboard → Comet Cache → Plugin Options → Static CDN Filters → CDN Host Name**), clicking on the MaxCDN tutorial link will redirect the site owner to the [CometCache.com homepage](https://cometcache.com/). 

Instead, it should be redirected to this: https://cometcache.com/kb-article/how-do-i-setup-static-cdn-filters-with-maxcdn/.

![screen shot 2016-10-16 at 2 37 08 am](https://cloud.githubusercontent.com/assets/7514953/19412485/fb9dea52-9349-11e6-8fb1-6f0ded19e18a.png)

Using the following setup:
- Comet Cache™ Pro v160917
- WordPress v4.6.1

**Comment by raamdev** [comment]
This has been fixed. Thanks!

**Comment by raamdev** [comment]
Next release changelog:
- Fixed a broken link to the [Static CDN Filters tutorial for MaxCDN integration](http://cometcache.com/r/static-cdn-filters-maxcdn/). Props @kristineds. See [Issue #842](https://github.com/websharks/comet-cache/issues/842).

**Comment by renzms** [comment]
@raamdev 

I can confirm the link now redirects to the KBA: https://cometcache.com/kb-article/how-do-i-setup-static-cdn-filters-with-maxcdn/. 👍

**Comment by raamdev** [comment]
**Comet Cache v161119** has been released and includes changes from this GitHub Issue. See the [v161119 announcement](https://cometcache.com/blog/comet-cache-v161119-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#842).
