### ISSUE TITLE
Bug: Possible Time Calculation Issue

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#853]
Referencing internal/private ticket: http://jas.xyz/2f8st76
This issue may be related to the new HTML notes in the latest release.
Not yet confirmed.

**Comment by raamdev** [comment]
Referencing additional details from the internal ticket:

- Cache Expiration Time was set to 28 days.
- When viewing the HTML source for a cached page, the expiration date has a year of 2063:

See screenshot: 

![2016-11-23 as 11 11 00](https://cloud.githubusercontent.com/assets/53005/20633213/016682cc-b312-11e6-9f12-51a4471ab632.png)

**Comment by renzms** [comment]
@raamdev 

### Unable to reproduce error

WordPress Version: 4.6.1
Current WordPress Theme: Twenty Sixteen version 1.3
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentysixteen/
Active Plugins: Comet Cache Pro Version 161119

- set Cache Expiration time to 28 days

![screen shot 2016-11-26 at 1 53 31 pm](https://cloud.githubusercontent.com/assets/13220018/20638407/fa84f9cc-b3e1-11e6-9989-67b41e411fad.png)

- visited front end for html notes

![screen shot 2016-11-26 at 1 53 04 pm](https://cloud.githubusercontent.com/assets/13220018/20638410/0323fd12-b3e2-11e6-834b-37223a3c54df.png)

**Results**
From and including: **Saturday, 26 November 2016**
To, but **not** including **Saturday, 24 December 2016**
Result: **28 days**


______

**Notes based on information from internal ticket**

Referencing internal/private ticket: http://jas.xyz/2f8st76

Cache Expiration time: `28 Days`

Based on first screenshot:

From: **Tuesday, 22 November 2016, 17:53:00**
To: **Monday, 15 October 2063, 11:47:00**

The duration is **17,127 days, 17 hours, 54 minutes and 0 seconds** or excluding the exact time but not including the day of : **17,128** days

Based on second set of screenshots

Cache Expiration time: `21 Days`

From: **Wednesday, 23 November 2016, 23:12:00**
To: **Wednesday, 17 October 2063, 22:24:00**

The duration is **17,128 days, 23 hours, 12 minutes and 0 seconds** or excluding the exact time but not including the day of : **17,129** days 


Looks like the error on customer's test site is always adding **17,128 days** give or take a couple hours. Could it be a possible error on customer's server host time? Or a conflict with another plugin?

**Comment by raamdev** [comment]
@renzms Thank you for the additional testing.

@jaswsinc Had you done any code review prior to posting this issue? Would you like me to leave this open for further research or do you feel this was most likely user-specific?

**Comment by jaswrks** [comment]
Yes, I'd like to leave this open for further research. My best guess at the moment is that this occurs whenever you also enable the load average check in Comet Cache.

Notice that `cache_max_age` is forced to `0` here, leading to an invalid time calculation later: https://github.com/websharks/comet-cache-pro/blob/161119/src/includes/traits/Ac/ObUtils.php#L215

**Comment by raamdev** [comment]
@renzms Can you try reproducing this with the Load Average Check enabled? See **Comet Cache → Plugin Options → Cache Expiration Time → Disable Cache Expiration If Server Load Average is High?**

**Comment by renzms** [comment]
@raamdev 

### Confirmed able to reproduce Bug

WordPress Version: 4.7
Current WordPress Theme: Twenty Sixteen version 1.3
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentysixteen/
Active Plugins: Comet Cache Pro Version 161221

At lower Server Load Average numbers, it causes the invalid time calculation.


### Correct Calculation at Server Load Average `.70`

Set at `28`Days 

>![screen shot 2016-12-22 at 5 12 15 pm](https://cloud.githubusercontent.com/assets/13220018/21420794/8af96bcc-c86a-11e6-9404-c02423cf50f4.png)

Front end HTML notes
>![screen shot 2016-12-22 at 5 11 55 pm](https://cloud.githubusercontent.com/assets/13220018/21420795/8aff5064-c86a-11e6-8e49-087971fdb4b8.png)


### Incorrect Calculation at Server Load Average `.01`

Set at `28`Days 

>![screen shot 2016-12-22 at 5 14 10 pm](https://cloud.githubusercontent.com/assets/13220018/21420750/575ab334-c86a-11e6-8591-0ab9d32b1bb0.png)

Front end HTML notes

>![screen shot 2016-12-22 at 5 14 55 pm](https://cloud.githubusercontent.com/assets/13220018/21420749/57579e42-c86a-11e6-9a2b-ea6301444ece.png)

**Comment by renzms** [comment]
**Fix Confirmed Working**, see comments [here](https://github.com/websharks/comet-cache/issues/863#issuecomment-269068663)

**Comment by raamdev** [comment]
**Comet Cache Pro v161226** has been released and includes changes from this GitHub Issue. See the [v161226 announcement](https://cometcache.com/blog/comet-cache-pro-v161226-maintenance-release/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#853).
