### ISSUE TITLE
HTML Notes don't indicate "fully functional" when generating cache file

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#860]
When a page is cached for the first time, the HTML Notes don't indicate that Comet Cache is "fully functional":

![2016-12-21_13-09-48](https://cloud.githubusercontent.com/assets/53005/21400628/17d9661a-c77f-11e6-8789-e8a026926663.png)

That message is only shown when actually loading a cached file:

![2016-12-21_13-09-58](https://cloud.githubusercontent.com/assets/53005/21400629/18c8d15a-c77f-11e6-9f29-f4ede9dede86.png)

While Comet Cache _is_ working in both cases, it's a bit confusing to see that "Fully Functional" message missing the first time around. It would be better if the "Fully Functional" message was shown in both cases, with the "Loaded via Cache" lines absent when the request is what triggered the cache file generation. (Even better would to be include a message like, "This request generated the cache file; the cache file will be used on the next request.")

**Comment by renzms** [comment]
### Confirmed as Working


![screen shot 2017-02-03 at 8 24 56 pm](https://cloud.githubusercontent.com/assets/13220018/22591305/dc28e53a-ea4e-11e6-8762-28fc42b38bb1.png)

**Comment by raamdev** [comment]
**Comet Cache v170220** has been released and includes changes from this GitHub Issue. See the [v170220 announcement](https://cometcache.com/blog/comet-cache-v170220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#860).
