### ISSUE TITLE
Problem with updating to 161227

### ISSUE THREAD

**Issue by KTS915** [wpsharks/comet-cache#865]
The Pro update to 161227 (see #864) is not updating properly. In fact, it seems to just be "updating" to 161226. So then (a) the user gets a message to update again, and (b) the issue with the adminbar is not fixed.

**Comment by renzms** [comment]
@KTS915 @raamdev 



Hi KTS, was this during a manual upgrade?

On my test site where Automatic updates were configured, it updated properly to **v161227** and has the admin bar fix.

![screen shot 2016-12-28 at 11 54 30 am](https://cloud.githubusercontent.com/assets/13220018/21513521/8b4b4760-ccf4-11e6-8a64-c139850d6ac7.png)

**Comment by KTS915** [comment]
Yes, it was a manual update. I don't understand why it would make a difference, though.

**Comment by renzms** [comment]
Let me try reproducing that error with a manual installation and manual update.

**Comment by KTS915** [comment]
Just tried on another site and had the same result.

**Comment by renzms** [comment]
Tested using 3 sites, (single site and 2 multisites) all are working fine with manual installation and manual update from the plugins list to Comet Cache Pro v161227

Distributable is from https://cometcache.com/account/

WordPress Version: 4.7
Current WordPress Theme: Twenty Sixteen version 1.3
PHP Version: 7.0.10-2+deb.sury.org~xenial+1
MySQL Version: 10.0.28-MariaDB-0ubuntu0.16.04.1
Server: NGINX

![screen shot 2016-12-28 at 12 05 52 pm](https://cloud.githubusercontent.com/assets/13220018/21513764/8fcdd6c4-ccf7-11e6-8c20-7b2d3fc6f037.png)


WordPress Version: 4.7
Current WordPress Theme: Twenty Sixteen version 1.3
PHP Version: 7.0.10
MySQL Version: 10.0.28-MariaDB-0ubuntu0.16.04.1
Apache Version: Apache/2.4.10 (Debian)

![screen shot 2016-12-28 at 12 09 57 pm](https://cloud.githubusercontent.com/assets/13220018/21513776/b76a9d66-ccf7-11e6-85f0-0925dfbe9798.png)


WordPress Version: 4.7
Current WordPress Theme: Twenty Sixteen version 1.3
PHP Version: 5.4.45
MySQL Version: 10.0.28-MariaDB-0ubuntu0.16.04.1
Apache Version: Apache/2.4.10 (Debian)

![screen shot 2016-12-28 at 12 15 09 pm](https://cloud.githubusercontent.com/assets/13220018/21513780/c546e32c-ccf7-11e6-8082-36d9b0cf3e43.png)

**Comment by KTS915** [comment]
Interesting! I have had one site work now (on localhost), but none of the other three I've tried (two on a live server, one on localhost). Just tried again and still no go (even though it reports success).

What version were you updating from? The unsuccessful updates were all from 161226. The successful one was from an earlier version (I think the November one). Perhaps that makes a difference.

**Comment by renzms** [comment]
Yeah, that is interesting! 😄 

> What version were you updating from?

Two sites I tried upgrading from v161226 and one I tried upgrading from v161223-RC. 

I've also tried deleting the plugin and removing Safeguard settings to clear the database of Comet Cache to start from scratch, and then manually install on all 3.They all seem to work. 

Could you please try one with an older RC and one by removing Safeguard settings of v161226 on those sites that didn't upgrade well?

**Comment by KTS915** [comment]
Just tried upgrading a localhost site from version 160917 and it all went fine.

**Comment by KTS915** [comment]
Hmm, just gone into a site I haven't touched for a while. It's running version 161119. The update message it's getting is for 161226 -- so even the message is wrong on that one.

Something is buggy somewhere!

**Comment by renzms** [comment]
Hmm, that's strange it might be a case with Comet Cache Pro v161226 or the update process.

@raamdev Could there be a bug or a lag in the update process?

**Comment by renzms** [comment]
@KTS915 

> It's running version 161119. The update message it's getting is for 161226 -- so even the message is wrong on that one.

If you go to WordPress updates and ask it to `Check Again`, does it still say to upgrade to v161226?

**Comment by KTS915** [comment]
That's just caused it to hang. 

Actually, cancel that. As I was typing, and after several minutes of apparently getting nowhere, it's now updated the message to 161227.

**Comment by KTS915** [comment]
And that update to 161227 has now gone fine. But, again, it was from an older version.

**Comment by renzms** [comment]
For the sites that are using v161226, does the Update prompt say `Upgrade to Comet Cache Pro v161227`? Could you please try doing the `Check Again` for sites using v161226 to see if it jumpstarts an upgrade properly?

**Comment by KTS915** [comment]
For the sites that are using v161226, the prompt already says 161227.

Just re-tried a localhost site that refused to update properly before, and now it's worked (at about the sixth time of asking)! So maybe whatever the glitch has been is clearing.

**Comment by renzms** [comment]
Awesome! The inconsistency might have just been a problem with a Cron Job/Server Upkeep time which delayed the proper update on your installation. Like an old tv, WordPress sometimes needs a little bump to get it started.

Glad to hear you got it working though! Cheers!

**Comment by KTS915** [comment]
Thanks for responding! Time for bed here -- goodnight!
