### ISSUE TITLE
Bug: Firefox = Broken Textarea

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#866]
- Enable Static CDN Filters
- Attempt to fill-in multiple CDN Hostnames from a Network installation.
- Try to break down to the next line by pressing Enter.

_This is broken in the most recent version of Firefox._

![2016-12-28_03-14-48](https://cloud.githubusercontent.com/assets/1563559/21521704/e5c30582-ccab-11e6-9f69-76f70fbfc861.jpg)

**Comment by jaswrks** [comment]
Referencing internal/private ticket:
https://app.intercom.io/a/apps/zbpo3mkk/inbox/me@jaswsinc.com/conversations/7405306906

**Comment by raamdev** [comment]
This appears to be caused by the `style="white-space:nowrap;"` attribute on that textarea.

**Comment by raamdev** [comment]
Related Mozilla bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1137650

According to [the spec](https://drafts.csswg.org/css-text-3/#valdef-white-space-pre-wrap), we should be using `style="white-space:pre-wrap;"`, which preserves new lines, not `nowrap`, which collapses new lines.

**Comment by raamdev** [comment]
Confirmed that `pre-wrap` works as expected on Firefox Version 50.1.0 (macOS), Chrome Version 55.0.2883.95 (macOS), and Safari Version 10.0.2 (macOS).

**Comment by jaswrks** [comment]
Referencing: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
~ I agree with the above and that was my mistake. However, I think `pre` is even better than `pre-wrap` in this case. We don't ever want breaks to occur because much of Comet Cache is based on line-delimited configuration options.

**Comment by renzms** [comment]
### Confirmed Working

Tested Using:

WordPress Version: 4.7.2
Current WordPress Theme: Twenty Seventeen version 1.1
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentyseventeen/
Active Plugins: Comet Cache Comet Cache™ Pro v170201-RC
PHP Version: 7.0.10-2+deb.sury.org~xenial+1
MySQL Version: 10.0.29-MariaDB-0ubuntu0.16.04.1

FireFox: 51.0.1

Tested by attempting to fill-in multiple CDN Hostnames from a Network installation and going to the next line by pressing Enter.

![screen shot 2017-02-03 at 8 58 32 pm](https://cloud.githubusercontent.com/assets/13220018/22592221/90e45172-ea53-11e6-808b-722aa5396791.png)

**Comment by raamdev** [comment]
**Comet Cache v170220** has been released and includes changes from this GitHub Issue. See the [v170220 announcement](https://cometcache.com/blog/comet-cache-v170220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#866).
