### ISSUE TITLE
Custom expiration cache for given pages

### ISSUE THREAD

**Issue by danielmt2k** [wpsharks/comet-cache#867]
Hi,

It would be nice to be able to set different expiration dates for different sets of content. For example:

- The posts in a blog won't be updated mostly, so it can have a 7 days expiration date.

- The main's calendar page with events will change daily, so it would be necessary to have a 1 day expiration date. In this case, a 7 days expiration date that suits most of the website doesn't have sense for this specific section.

Thanks.

**Comment by jaswrks** [comment]
_Noting another related issue:_ https://github.com/websharks/comet-cache/issues/170

**Comment by raamdev** [comment]
@danielmt2k Thank you for the feature request. I'm going to close this issue in favor of https://github.com/websharks/comet-cache/issues/170, but your request has been noted on that GitHub issue.
