### ISSUE TITLE
Clear Cache not clearing cache directories

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#868]
We have several reports of Comet Cache Lite v161221 not deleting directories in `wp-content/cache/comet-cache/cache/http/example-com/*` when you click the 'Clear Cache' button. Cache _files_ get deleted, but any and all directories remain. Comet Cache Lite v160917 and v160706 are also reported as having this issue.

I have not been able to reproduce this, but there are at least three confirmed reports of this issue:

- https://forums.wpsharks.com/t/cache-folders-not-removed-during-clean-up-process/866/6
- https://wordpress.org/support/topic/empty-folders-2/
- https://wordpress.org/support/topic/empty-folders-2/page/2/#post-8596995

Users have double-checked permissions and even installed other caching plugins to see if those plugins delete directories fine (they do). Please see the above links for the details of each report.

**Comment by renzms** [comment]
@raamdev 

### Unable to reproduce error

Tested using Comet Cache Lite v161221, with single site and multisite.

Using PHP 5.4/7

Comet Cache Lite v161221 clears files and directories properly.

![screen shot 2016-12-29 at 12 58 31 am](https://cloud.githubusercontent.com/assets/13220018/21526998/2fd87028-cd63-11e6-8f8b-f1f17a3f8de3.png)

![screen shot 2016-12-29 at 1 04 23 am](https://cloud.githubusercontent.com/assets/13220018/21527000/3318779c-cd63-11e6-8dde-df62654ab568.png)

**Comment by eurobank** [comment]
Doesn't work for me also. CloudLinux Shared Hosting with PHP 7, using LiteSpeed webserver (if this makes any difference).

Directories remain. 

Tested with other cache plugins and works as expected.

**Comment by raamdev** [comment]
After extensive tests, we discovered the bug that was causing this issue; see https://github.com/websharks/comet-cache-pro/commit/3db638daf2df16e3a4e9da5aa7729bfc1d1b07ac. A fix for this issue will go out with the next release.

**Comment by renzms** [comment]
### Confirmed working in Comet Cache™ Pro v170201-RC

Clear button clears out all empty directories

**Comment by raamdev** [comment]
**Comet Cache v170220** has been released and includes changes from this GitHub Issue. See the [v170220 announcement](https://cometcache.com/blog/comet-cache-v170220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#868).
