### ISSUE TITLE
Download On local plugin error

### ISSUE THREAD

**Issue by freddiehdxd** [wpsharks/comet-cache#872]
Hello when l download the zip file here to put it in the local server l am getting errors and the plugin is not activating any suggesting fix?

**Comment by raamdev** [comment]
@freddiehdxd This repo is for development only and the ZIP file packaged by GitHub is not an installable WordPress plugin. Please download Comet Cache from https://cometcache.com/release-archive/ or https://wordpress.org/plugins/comet-cache/.

**Comment by freddiehdxd** [comment]
yeah l want to do some deep testing with nginx. but l need it to be install
on my local the plugin
