### ISSUE TITLE
Any issues Running On Nginx Server

### ISSUE THREAD

**Issue by freddiehdxd** [wpsharks/comet-cache#873]
hello Any issues Running On Nginx Server. Is the plugin compatible with Nginx. apache is not install on my server all website run on Nginx

**Comment by raamdev** [comment]
No, there are no issues running on NGINX. Comet Cache is fully-compatible with NGINX. See [Recommended Nginx Configuration for Comet Cache](https://cometcache.com/kb-article/recommended-nginx-configuration-for-comet-cache/).
