### ISSUE TITLE
PHP7 Compatibility issues

### ISSUE THREAD

**Issue by freddiehdxd** [wpsharks/comet-cache#875]
PHP7 Compatibility issues when will  comet-cache be full compatible with php 7 my website crash if l activate php 7.

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/vendor/websharks/wp-php-rv/src/includes/functions/checks.php
---------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------
 52 | WARNING | Function name "___wp_php_rv_initialize" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
---------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/vendor/websharks/wp-php-rv/src/includes/functions/notices.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
 175 | WARNING | Function name "___wp_php_rv_notice_brand_name" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/vendor/websharks/html-compressor/src/includes/classes/Core.php
--------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------
 3762 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.
--------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/classes/Plugin.php
------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------
 214 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/functions/i18n-utils.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
------------------------------------------------------------------------------------------------------------------------------------
 14 | WARNING | Function name "__" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
 26 | WARNING | Function name "__" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
 33 | WARNING | Function name "__" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/TokenUtils.php
-------------------------------------------------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 5 LINES
-------------------------------------------------------------------------------------------------------------
  35 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 122 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 170 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 274 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 324 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
-------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/UrlUtils.php
------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------
 108 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/ConditionalUtils.php
-------------------------------------------------------------------------------------------------------------------
FOUND 13 ERRORS AFFECTING 13 LINES
-------------------------------------------------------------------------------------------------------------------
  69 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
  94 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 121 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 146 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 188 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 212 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 235 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 263 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 288 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 319 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 354 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 376 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 379 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
-------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/IpAddrUtils.php
--------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------
 20 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
--------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/SysUtils.php
-----------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
-----------------------------------------------------------------------------------------------------------
 17 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 42 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 86 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
-----------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/DomainMappingUtils.php
---------------------------------------------------------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 5 LINES
---------------------------------------------------------------------------------------------------------------------
  19 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
  41 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 167 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 210 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 261 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
---------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/FsUtils.php
------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
------------------------------------------------------------------------------------------------------------
  54 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 105 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 248 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/HttpUtils.php
------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
------------------------------------------------------------------------------------------------------------
  17 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
  40 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
  62 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 142 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/ServerUtils.php
--------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
--------------------------------------------------------------------------------------------------------------
 17 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 40 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 60 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
--------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/UserUtils.php
------------------------------------------------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 5 LINES
------------------------------------------------------------------------------------------------------------
  17 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
  62 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
  97 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 132 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 167 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpHomeBlogUtils.php
-------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-------------------------------------------------------------------------------------------------------------------
 24 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 65 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
-------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpTermUtils.php
---------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------
 36 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
---------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpAuthorUtils.php
-----------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------
 36 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
-----------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpWooCommerceUtils.php
----------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------
 21 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
----------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpFeedUtils.php
---------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------
 32 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
---------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/BbPressUtils.php
---------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
---------------------------------------------------------------------------------------------------------------
 32 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 55 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
---------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpSettingUtils.php
------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------
 22 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpJetpackUtils.php
------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------
 21 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpCommentUtils.php
------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------
 28 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 83 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpSitemapUtils.php
------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------
 24 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/PostUtils.php
------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------
 17 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 35 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/AutoCacheUtils.php
-----------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------------------------
 45 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 94 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
-----------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpPostUtils.php
---------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
---------------------------------------------------------------------------------------------------------------
  33 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
  42 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 161 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
---------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/AdminBarUtils.php
----------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------
 22 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
----------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpUrlUtils.php
--------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------
 26 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
--------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpUserUtils.php
---------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------
 33 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
---------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpPostTypeUtils.php
-------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------
 29 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
-------------------------------------------------------------------------------------------------------------------

FILE: /home/ultrahor/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpUtils.php
------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
------------------------------------------------------------------------------------------------------------
 218 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 264 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 298 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 332 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
------------------------------------------------------------------------------------------------------------

**Comment by raamdev** [comment]
@freddiehdxd Comet Cache is fully-compatible with PHP 7. We're running Comet Cache on many production sites that are also running PHP 7 and there are no issues. The tool you're using to run your tests is producing false-positives. 

See: https://wordpress.org/support/topic/false-positive-comet-cache/

If you're using the PHP 7 Compatibility Checker plugin, please make sure you're running the latest version.
