### ISSUE TITLE
Unable to deleted the cache directory

### ISSUE THREAD

**Issue by freddiehdxd** [wpsharks/comet-cache#877]
Unable to deleted the cache directory on my server 
any way to deleted the folder

**Comment by raamdev** [comment]
@freddiehdxd We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://www.websharks-inc.com/support/?product=comet-cache&request_type=trouble_ticket) (Comet Cache Pro). Thank you! :)
