### ISSUE TITLE
Cannot activate or configure comet cache in backend

### ISSUE THREAD

**Issue by Richi400** [wpsharks/comet-cache#878]
Hi there,

I installed the comet cache pro plugin right now.
But it is not possible to activate it. (I see no Save Button)! Or to configure it in the plugin options because I cannot navigate the single tabs. All Tabs (like "Update Credentials") are liked to /wp-admin/admin.php?page=comet_cache# which just leads me to the top of my page.

What went wrong? Any suggestions?

thanks! kind regards
Torsten

**Comment by raamdev** [comment]
@Richi400 Please [Test in a Clean WordPress Installation](https://cometcache.com/kb-article/testing-comet-cache-in-a-clean-wordpress-installation/) and see if you can reproduce this issue. You most likely have another plugin, or your theme, introducing a conflict. If you continue to have trouble, please open a support ticket: https://cometcache.com/support/
