### ISSUE TITLE
Fatal Error with loading includes/functions/.load.php

### ISSUE THREAD

**Issue by MikeiLL** [wpsharks/comet-cache#890]
I'm using php7 locally and php5.6 on the server. Locally I get the following error:

```
Fatal error: require_once(): Failed opening required '/var/www/html/wp-content/plugins/comet-cache/src/vendor/websharks/wp-php-rv/src/includes/functions/.load.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/comet-cache/src/vendor/websharks/wp-php-rv/src/includes/check.php on line 14
```

On the server there's a fatal error, but no details provided.

I saw I similar issue here: https://github.com/websharks/comet-cache/issues/585

But wp-config.php has permissions of 644.

Can you possibly offer any insights?

**Comment by raamdev** [comment]
@MikeiLL This is definitely an issue specific to your environment and not a bug in Comet Cache. We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://cometcache.com/support/) (Comet Cache Pro). Thank you! :)
