### ISSUE TITLE
Cacheing not working for logged in users

### ISSUE THREAD

**Issue by timparkin** [wpsharks/comet-cache#897]
Testing website with Comet Cache Pro and setting cache for logged in users and it says that it isn't cacheing. 

e.g. https://www.onlandscape.co.uk/2017/06/alex-bamford-featured-photographer/

I've uploaded the options json (as a txt)

[comet_cache-options.txt](https://github.com/websharks/comet-cache/files/1078868/comet_cache-options.txt)

**Comment by raamdev** [comment]
@timparkin I've thoroughly tested the Logged-In User feature and it's working as expected. Please [Test in a Clean WordPress Installation](https://cometcache.com/kb-article/testing-comet-cache-in-a-clean-wordpress-installation/). 

We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://cometcache.com/support/) (Comet Cache Pro). Thank you! :)
