### ISSUE TITLE
3rd Party Plugin Compatibility: WooCommerce Waitlist

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#910]
We have a report of a possible conflict with the WooCommerce Waitlist plugin: 
https://wordpress.org/support/topic/conflict-with-woocommerce-waitlist/

> We ran into an issue with not being able to delete Users, which got an error pointing to WooCommerce. We had WooCommerce support looking into the issue, and apparently it’s a conflict with the WooCommerce Waitlist plugin somehow.
> 
> If either Comet Cache or WooCommerce Waitlist are deactivated it works fine, but we can’t have them both active. WooCommerce support is still looking into things on their end, but they suggested checking here too in case anyone might know what’s up. This is the PHP error we get when both plugins are active and we try to delete a user:
> 
> PHP Fatal error: Call to undefined function wc_get_chosen_shipping_method_ids() in /home/example/public_html/wp-content/plugins/woocommerce/includes/class-wc-customer.php on line 184

This needs to be tested to see if we can reproduce the issue and to determine if Comet Cache is causing a problem here. It would be most helpful if we can get a stacktrace when the fatal error occurs so that we can see what calls led up to the failure.

**Comment by renzms** [comment]
**Tested Using:**
WordPress Version: 4.8.1
Current WordPress Theme: Twenty Seventeen version 1.3
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentyseventeen/
Active Plugins: Comet Cache Pro v 170220 and v170808 - RC, WooCommerce v 3.1.1, WooCommerce Waitlist v 1.4
 PHP Version: 7.1.3-3+deb.sury.org~xenial+1
MySQL Version: 10.0.31-MariaDB-0ubuntu0.16.04.2

### Unable to Reproduce Issue

**Active Plugins List**

Comet Cache Pro v 170220 , WooCommerce v 3.1.1, WooCommerce Waitlist v 1.4
>![Plugins List](https://user-images.githubusercontent.com/13220018/29168747-dbed982a-7e02-11e7-8e19-bb2291e25cd4.png)

User List

>![User List](https://user-images.githubusercontent.com/13220018/29168755-e4192744-7e02-11e7-8851-998f607ee9fb.png)

User Deleted, no PHP errors encountered.

>![Confirm Deletion](https://user-images.githubusercontent.com/13220018/29168751-e0f08aee-7e02-11e7-9619-9037fa021cd1.png)

>![User Deleted](https://user-images.githubusercontent.com/13220018/29168749-deaf6976-7e02-11e7-85e0-92711f384247.png)


Additional Testing with Comet Cache Pro v 170808-RC also yielded same results. It successfully allowed deletion of users with no issues.

**Comment by raamdev** [comment]
@renzms Thank you. It sounds to me like the original issue might be related to another plugin that the site owner is running. I'm going to mark this as closed until we have further feedback that warrants reopening this.
