### ISSUE TITLE
Cannot write to htaccess even with 777 permissions

### ISSUE THREAD

**Issue by jpSimkins** [wpsharks/comet-cache#919]
Cannot write to htaccess even with 777 permissions. How about you output the changes to be made so I can make these myself? I actually prefer this method.

**Comment by raamdev** [comment]
@jpSimkins All of the `.htaccess` snippets that Comet Cache tries to add are available inside the plugin itself, in the Apache Optimizations panel. 

You'll want to check with your hosting provider to see why the web server cannot write with 777 permissions.
